### ISSUE TITLE
Firefox - Gitlab Integration - Missing button on issues

### ISSUE THREAD

**Issue by traedamatic** [toggl/toggl-button#1000]
### Environment details

* Archlinux
* Firefox: 59
* Toggle Button: 1.10

### Expected behavior

See a toggle button on Gitlab Issues to start a new toggl time 

### Actual behavior
I cannot see the toggl Button on any Gitlab issues.

### Additional details

I added the permissions for the Gitlab url at the permission tab of the add on preferences. 

Does any one has the same behavior?

**Comment by renestalder** [comment]
I also don't see it (not even an idea where it should be)

**Comment by renestalder** [comment]
Oh, wait, wasn't aware that having own hosted GitLab instances need additional permission settings. After I added the domain URL in the addon settings, I see the button.

**Comment by tcrammond** [comment]
Closing as above 🙌
