### ISSUE TITLE
Toggl button and Slack

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggl-button#1002]
Minor bug - When starting a Toggl button timer on a public slack channel, everything works as expected, however when the timer is started for a private channel or direct message channel, the first letter of the channel/direct message is cut off in the Toggl button description.

Tested and replicated with Chrome

**Comment by rudivs** [comment]
I have a couple of broader question about the behaviour of the Toggl button in Slack. 

1. Currently it gets the project from the Team Name and the task description from the channel. Is that how most people use Slack? In my case it would be better to get the project from the channel and leave the task description undefined.
2. Slack requires that channel names should all be lowercase with no spaces. In Toggl, my projects are all in Title Case, using spaces. I would prefer that the Toggl button interprets hyphens (`-`) and underscores (`_`) as spaces and converts the resulting phrase to Title Case.

I already have a fix which implements these changes, but before I submit it as a pull request I'd like to check that I'm not proposing something that clashes with how everyone else uses Slack and Toggl. Also, if anyone has better suggestions for where to get the task description from, I could look into implementing that too.

**Comment by rudivs** [comment]
I added a second Toggl button to the hover action menu. It takes the message as the task description, and gets the project name from the channel. If you'd like to see whether you agree with the changes, I've created a pull request: https://github.com/toggl/toggl-button/pull/1063
