### ISSUE TITLE
Pomodoro: Play a ticking sound

### ISSUE THREAD

**Issue by amrtn** [toggl/toggl-button#1003]
I'd love to have a ticking sound being played while I'm working on a Pomodoro because:

* It's an easy way to be sure I'm in the middle of a task (and not in a rest period) even if the browser window is not focused
* It helps me to maintain my focus

The ticking sound should go away when the Pomodoro ends and come back whenever a Pomodoro is started.

**Comment by LukeFlego** [comment]
The Chrome menu icon has a ring around it of the time left if that's of any immediate help

![image](https://user-images.githubusercontent.com/2726761/38529099-39fd114a-3ca6-11e8-951f-2058fa52a74b.png)

**Comment by amrtn** [comment]
I've been using the icon ring for some time but it doesn't help when there are other windows on top of the browser or I'm using the Full-Screen mode for more focused work. An audible feedback during the Pomodoro would help in those cases.

**Comment by ww7** [comment]
https://pomodoro-tracker.com/ ticking good
It think option for ticking speed adjusting is needed.

**Comment by NoriSte** [comment]
I need it too, it's the only reason why I don't use Toggle yet 😊

**Comment by shantanuraj** [comment]
This is scheduled for development https://github.com/toggl/toggl-button/issues/1568
Should be ready for deployment in the coming week or so
