### ISSUE TITLE
Login issue - Chrome

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggl-button#1004]
Version 65.0.3325.181 (Official Build) (64-bit) on
Windows 10 pro (fully updated).

1.10.3

Users having issues when logging in, explained by users below

case/670238 1st user "Yesterday my Chrome integration became detached from my account (clicking "go" on another site else didn't start the task at toggl), and today I can't sign-in on the Chrome button: "Wrong Email or Password!" Tried resetting PW, restarting Chrome, can log out/in on site. 

Reinstall of extension fixed it"

2nd user case/669879 "I'm able to work around this by uninstalling and reinstalling the plugin
when logged in to the Toggle website which appears to then be utilized by
the plugin, but this isn't overly convenient to need to do each time I
close and reopen the browser."

**Comment by dpsxp** [comment]
Seem to be working on the current version of Chrome and Toggl Button. So I'm closing this, feel free to reopen if the issue happens again.

**Comment by niggeulimann** [comment]
I recently solved this Issue on my new machine - ist been the `Block third-party cookies
Prevent third-party websites from saving and reading cookie data` Setting.

It would be great to show a small info or or something in the case something went wrong (403 in this case)
The behaviour was kind of odd:
Using incorrect credentials triggers a "wrong / email / Passwort" hint. But using the correct combination has been doing nothing...
