### ISSUE TITLE
Time tracker starts automatically whe 2 accounts in 2 Fiferox profiles used

### ISSUE THREAD

**Issue by miro-kodet** [toggl/toggl-button#1005]
### Environment details
* Operation system: LINUX (Kubuntu 16.04)
* Extension version: 1.10.3

### Expected behavior
I use 2 separate Firefox windows with 2 different profiles. In both of them I use the same button. Under each profile I'm logged in to toggle under different account.
When notification regarding "Don't forget to track your time" appears, it should be dismissible (or just left to fade out) without any resultant (automatic) action.

### Actual behavior
When notification regarding "Don't forget to track your time" appears, I dismiss it or let it fade out, it runs time tracker automatically - mostly in the second window (under completely different toggl account).

### Steps to reproduce the behavior
Use 2 profiles in 2 different FF profiles.

### Additional details
This is very probably not a bug, possibly just an annoying design issue. But should be mentioned.

* screenshots or screencapture

**Comment by tcrammond** [comment]
Hi @NORDCOMPCZ, we've since fixed some issues related to timers starting automatically. The latest version from the Firefox store includes these fixes.

I was wondering if you're still experiencing the same problem when using 2 different profiles, or is this fixed now as well?

**Comment by NORDCOMPCZ** [comment]
Hi @tcrammond, I've not experienced same behaviour last couple of weeks, therefore I think this issue was resolved (to be fair, I've moved most of browser-based work to Chrome and there is this issue not at all).
