### ISSUE TITLE
Button missing on Airtable

### ISSUE THREAD

**Issue by langri-sha** [toggl/toggl-button#1007]
User reports that the extension is missing from [Airtable](https://try.airtable.com). 

Case 674657.

**Comment by ricotheque** [comment]
/case/726198 shared a console error:

![image](https://user-images.githubusercontent.com/5687885/41751528-615df4e8-75f4-11e8-8e37-685f852871f7.png)

**Comment by langri-sha** [comment]
Fixed via https://github.com/toggl/toggl-button/pull/1013.
