### ISSUE TITLE
Gitlab integration - move button to the sidebar

### ISSUE THREAD

**Issue by LubosRemplik** [toggl/toggl-button#1009]
Maybe it would be good idea to move button to the sidebar instead of top bar?

There are cases I need to use start button when I read very long gitlab issue (page) so very at the bottom and to do so I need to sroll to the top and then press start.

**Comment by LubosRemplik** [comment]
Let me know if it is good idea and it's worth to try to make PR

**Comment by tcrammond** [comment]
Hey @LubosRemplik, thanks for the suggestion. The Gitlab integration is quite well established, so we probably wouldn't move the button entirely at this stage.

Perhaps there's a chance for this to be configurable some day, so let's keep the issue open for discussion.

**Comment by 23tux** [comment]
@tcrammond would it be possible to place the button in the sidebar when you are in the board view? When I click on an issue in the Gitlab board, the sidebar opens, where I can do some work (like assigning labels). But when I want to start tracking I have to open the issue itself in a completely new page.

**Comment by tcrammond** [comment]
@23tux while we aren't actively developing this integration right now, we would be happy to review a PR adding the button into a new location. I've updated the title of the issue to reflect the latest idea, as it still solves the problem in the original request.

Anyone can please feel free to pick up the idea 👍

**Comment by LubosRemplik** [comment]
@tcrammond not sure if the title update is accurate, @23tux is talking about board view -> sidebar, I was talking about list view > detail

I am not JS guru, so not going to PR since I dont konw how to test, but if anyone here is where the gitlab part JS is located  
https://github.com/toggl/toggl-button/blob/master/src/scripts/content/gitlab.js  
It handles issue detail + MR detail as far as I see

Related / duplicated issue https://github.com/toggl/toggl-button/issues/791

**Comment by tcrammond** [comment]
My bad, changed it back now 👍.

**Comment by LubosRemplik** [comment]
It seems this is implemented now? Can see the start now button with the time tracking section at GL

**Comment by rizerzero** [comment]
Anything new on this ? it seems to be showing for some people and not for some others .
