### ISSUE TITLE
Targetprocess update

### ISSUE THREAD

**Issue by kyllikekimmel** [toggl/toggl-button#1010]
case/675318
> After recent Targetprocess update and slight changes in its UI your Toggl Chrome Extension stopped appearing in Entity Details view in our application.

**Comment by vedr4n** [comment]
I've got another user mentioning the same problem. 

Case 676088.

**Comment by bearoutthere** [comment]
I can confirm this problem.  Toggl button is no longer visible on User Stories and Bugs.  The only workaround is to use right click menu to start time tracking.

**Comment by S3ns3o** [comment]
Hello, I'm also using the button with target process, I'm on a fix, hope to push it quickly.
