### ISSUE TITLE
Intercom update

### ISSUE THREAD

**Issue by maritoggl** [toggl/toggl-button#1015]
User reported that Intercom has recently updated their UI, resulting in a disappearance of Toggl Button. Requested a screenshot for reference, have not yet received. 

Intercom support was added in the first place via https://github.com/toggl/toggl-button/pull/739

case/676840

**Comment by maritoggl** [comment]
Case updated with a screenshot as well.

**Comment by danburkhol** [comment]
This doesn't seem to work. I am running toggl-button 1.11.1 in Chrome 68.0.3440.106 on macOS. Toggle-button has permission for intercom.io. I disabled all other Chrome extensions except toggl.

Any ideas?
