### ISSUE TITLE
Changes to Asana Integration

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/toggl-button#1020]
### Expected behavior
The Toggl Button will show (In the Asana page)
### Actual behavior
The Toggl Button isn't showing (In the Asana page)
### Steps to reproduce the behavior
Load up Asana page and attempt to track a time from a task in Asana
### Additional details

* screenshots or screencapture
![image](https://user-images.githubusercontent.com/18132080/38974548-bb3c0ef6-43e9-11e8-94b0-732b2c7baace.png)

Email from Asana below
case/679000
case/678884
case/678714

**Comment by VeljkoTN** [comment]
another case: 679095

**Comment by ApocalypticFish** [comment]
case: 679342

**Comment by maritoggl** [comment]
case/679430

**Comment by maritoggl** [comment]
case/679478

**Comment by VeljkoTN** [comment]
case/679504

**Comment by mrkeysh** [comment]
same thing, not opening another case

**Comment by juanlaube** [comment]
case/679543

**Comment by juanlaube** [comment]
case/679570

**Comment by epagnini** [comment]
case/679574

**Comment by ricotheque** [comment]
/case/679795
/case/680169

**Comment by ricotheque** [comment]
/case/680044
