### ISSUE TITLE
Toggl button disappeared from Asana (list layout project)

### ISSUE THREAD

**Issue by igorkurochka** [toggl/toggl-button#1023]
Hey there, we've noticed two days ago that the Toggl button is missing for Asana project with List layout, however, it is still working fine for Board layout 

### Environment details

* Operation system: MacOS, Chrome browser version 66.0.3359.117
* Extension version: Version (1.10.4)

### Expected behavior
Toggle button expected to be after a task title 

### Actual behavior
it's not there (see screenshot)

### Steps to reproduce the behavior
create a project, choose List layout, create a new task

* screenshots or screencapture
![image](https://user-images.githubusercontent.com/19435540/39094284-c3ec6aac-4635-11e8-8ef8-e8cb33384b88.png)

**Comment by Pashkella** [comment]
Similar problem

**Comment by shantanuraj** [comment]
Looks related to #1020 which should be fixed when #1021 is merged

**Comment by dnovikov** [comment]
Confirm the bug.

**Comment by shantanuraj** [comment]
Should be fixed now that #1021 is merged, we'll push an update to the extension out soon.

**Comment by dlgenterprises** [comment]
Is this fixed?  I have one work space that has the button missing, and the rest are working fine.
