### ISSUE TITLE
No Longer Appears in Asana Since Recent Asana UI Changes

### ISSUE THREAD

**Issue by aeromorrison** [toggl/toggl-button#1026]
### Environment details

* Operation system: Windows 7 and Windows 10
* Extension version: 1.10.4

### Expected behavior
The Toggle button appears in the task pane (right side) near the top of the task information.

### Actual behavior
It does not appear at all.

### Steps to reproduce the behavior
Install Toggl button
Open Asana
Click on any task

### Additional details
I've been using toggl-button for about a year and it has largely worked fine. Over the past 1-2 weeks, I've noticed that it no longer appears at all in asana. Asana recently made some UI tweaks, and it seems to be aligned with the timing of those changes getting rolled out.

I verified this because I also have a unpaid version of asana for my personal use. This version does not yet have the new UI tweaks and the Toggl button appears normally. In the paid asana for my business that has the recent UI tweaks, the button does not appear.

**Comment by ricotheque** [comment]
Hey @aeromorrison, thanks for the heads-up! We've been working on this over the past few days, and a fix should come out with the next update. :)

Please see #1020

**Comment by langri-sha** [comment]
Hi @aeromorrison! 

Thanks for pointing things out! We tried recent changes on the updated UI and indeed the integration button isn't being added as it is on the legacy UI. We'll work on publishing a fix for this soon.

**Comment by langri-sha** [comment]
We've added fixes via #1028, the button should now appear both on the old and new UI. We're going to make a release soon.

Thanks :raised_hands:!
