### ISSUE TITLE
Toggl button Trello/Jira issues

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggl-button#1053]
Some reports that starting Toggl button in Trello is causing crashes/lockups/isn't working

"I am trying to start a timer from a card in trello, i can input the project
(so it does link to toggle) but when i click the 'Done' button nothing
happens.
Even if i close the card the 'start timer' popup window hangs there
uncloseable and i can't do anything but refresh my browser.

Chrome 1.10.6"
/case/717583

"When using the Trello extension, the extension crashes and does not begin timing. Chrome latest version."

case/717865

**Comment by VeljkoTN** [comment]
Could this be the reason:

> For me, it works. My Chrome language is set to English, however, my teams
Chrome is set to Chinese and they cannot get it to work with Trello or
Google Docs.

**Comment by shantanuraj** [comment]
Set my language in Chrome and Trello to Chinese, added some title to the board

![image](https://user-images.githubusercontent.com/1716853/41039190-50ab9e38-69b6-11e8-9a68-40c4202cc82f.png)

Works fine for me https://streamable.com/94moz

**Comment by Michelle112** [comment]
Nick requested that the user provide more info. These are the users extensions;
![gonzalo extensions](https://user-images.githubusercontent.com/19910107/41304452-d0dda762-6e35-11e8-917e-d2272121c536.png)

He also says he's using Chome Version 67.0.3396.79 (Build Official) (64 bits) 
Windows 10 pro 64 bits

**Comment by shantanuraj** [comment]
Installed all the extensions from the screenshot, enabled them on my test card; the button still [works](https://streamable.com/3yqai)

Can we request the user to try the button with the other extensions disabled? If the button still doesn't work, send us a screen-recording with the browser console open.

**Comment by ricotheque** [comment]
@shantanuraj The user still encountered problems unfortunately.

They were able to get a screenshot with a console error. Please check the case on Desk, and let us know if you need access to that. :)

**Comment by maritoggl** [comment]
JIRA user having a similar issue - case/725339, also includes a screenshot of the error in console.

**Comment by maritoggl** [comment]
Another one - case/729276
