### ISSUE TITLE
Xero integration likely broken

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1059]
Case 725662

A user is reporting that the button is shown behind the "files" icon in Xero on all screens and is not affected by resizing. 

![image](https://user-images.githubusercontent.com/36152180/41652464-625c9a56-7483-11e8-8aac-4a377f4cb64e.png)

**Comment by maritoggl** [comment]
conversations/18450436436 reporting the same.

**Comment by tcrammond** [comment]
Seen errors across multiple users in error reporting.

```
TypeError: Cannot read property 'appendChild' of null
scripts/content/xero.js:14:28
scripts/common.js:1:16142Object.renderTo
```
