### ISSUE TITLE
Firefox Add-On: Add Permissions Disable All Settings

### ISSUE THREAD

**Issue by EthanJStark** [toggl/toggl-button#1060]
## Updated Issue

Firefox Add-On currently lacks the following settings menu that's present in the Chrome Extension.

<img src="https://user-images.githubusercontent.com/1894530/41723489-855ca4a4-756b-11e8-8c40-afda1e6a646e.png" />

## Original Issue
Hi Toggl team,

Big fan of this extension, thanks for your work on it. 

This is a feature request; if **Issues** isn't an appropriate place for this, feel free to close.

I love having the button available in my browser, and really wish that the button was _not_ [integrated](https://github.com/toggl/toggl-button/wiki/Where-can-I-find-the-Button%3F) into the DOM.

I'd imagine that there are others who'd desire a setting that allows a user to turn off these integrations.

**Comment by rudivs** [comment]
Hi @EthanJStark,
 
You can already disable the DOM integration through the settings. If you click on the Toggl button in the browser, then click on the Open Settings gear button, then select the Permissions tab. You should be able to use the "Disable all" button to prevent the button from showing up on any websites.

![image](https://user-images.githubusercontent.com/1894530/41723489-855ca4a4-756b-11e8-8c40-afda1e6a646e.png)

I'm not part of the Toggl team, just a fellow user.

**Comment by EthanJStark** [comment]
Brilliant, thanks, @rudivs !  I'd hunted around for how this might be possible, but didn't find it. Closing!

**Comment by EthanJStark** [comment]
Actually, doesn't look like this is available on Firefox's add-on yet. Ah, well.

**Comment by rudivs** [comment]
Just checked and it does seem that the settings page is different in Firefox. Maybe reopen, since it's still an issue.

**Comment by EthanJStark** [comment]
Updated description + issue title.

**Comment by langri-sha** [comment]
Thanks! We're going to take a look at this for the next FF release.

**Comment by bryanph** [comment]
Due to limitations in how firefox permissions are defined for injecting javascript in arbitrary pages we have decided to hide the permissions functionality mentioned here (see PR #1172).

Hopefully we can revisit this when we find a way to resolve this.

**Comment by tcrammond** [comment]
Thanks for your patience. Firefox permission settings will be available again in the next release 🎉  It may take a few days to roll out to you.
