### ISSUE TITLE
Missing or invalid workspace_id

### ISSUE THREAD

**Issue by sverress** [toggl/toggl-button#1066]
### Environment details

* Operation system: Chrome 67.0.3396.87
* Extension version: 1.10.7

### Expected behavior
Starting a new timer from pressing start new in the chrome extension 

### Actual behavior
I get a error message: Missing or invalid workspace_id.

### Additional details
 I am connected to the workspace of my boss

![skjermbilde 2018-06-27 kl 11 27 13](https://user-images.githubusercontent.com/22891302/41965594-356fcd40-79fd-11e8-8876-ccfdcdcca008.png)

where can I fix this problem? thank you in advance

**Comment by ricotheque** [comment]
Hey @sverress! Sorry if we didn't get back to you earlier.

How did you sign up for a Toggl account? Did someone invite you to their Workspace? 

I'd like to continue this conversation, but it might require either you or I to share private account-related details. Would you mind emailing us at support@toggl.com?

**Comment by sverress** [comment]
thank you, I will continue the conversation over mail.

**Comment by langri-sha** [comment]
Hi @sverress. We've fixed this in https://github.com/toggl/toggl-button/pull/1079. Please re-open if you have any more issues and let us know.

**Comment by filip-paral** [comment]
@langri-sha Hi, Im having same problem with Missing or invalid workspace_id warning in console. Could you please guide me on how to resolve this issue?

* **OS version**: Windows 11
* **Browser version**: Chrome 111 
* **Extension version**: 2.0.20

When I click on Toggl start button in extension timer won't start and exception "Missing or invalid workspace_id" is thrown.
