### ISSUE TITLE
Set nannyInterval input is hidden

### ISSUE THREAD

**Issue by lee-tts** [toggl/toggl-button#1074]
Being able to set how long the extension waits before reminding the user to start tracking would be really great. A reminder every 60 minutes is far too infrequent for me.

As for my own usage, I have tried messing with the nannyInterval in db.js but it doesn't seem to give me more reminders. 

Basically I want it to annoy the heck out of me if I'm not tracking.

**Comment by ricotheque** [comment]
@shantanuraj the user has reached out to us via /case/743592 as well.

I've been able to test out the extension on my computer, and found that the input controlling the nannyInterval in the settings is hidden for some reason. Please see screenshot below:

![image](https://user-images.githubusercontent.com/5687885/42919629-6e213d28-8b45-11e8-955f-a5c20fc39b58.png)

I had to use DevTools to uncheck `overflow: hidden` for `.subsettings-details`.

I'm using extension version `1.10.9`, on Chrome `67.0.3396.99 (Official Build) (64-bit)`

In any case, I'm not sure why changing nannyInterval in db.js isn't having any apparent effect.

**Comment by lee-tts** [comment]
Thanks Rico! Could it be inheriting the css from this change? 

https://github.com/toggl/toggl-button/pull/848/files

**Comment by ricotheque** [comment]
I'll let our FE answer that... to be honest I haven't looked through the codebase, probably as much as you 😬

**Comment by ricotheque** [comment]
Thanks @shantanuraj!
