### ISSUE TITLE
Can't log in to server and no clear reason given

### ISSUE THREAD

**Issue by joncage** [toggl/toggl-button#1080]
### Environment details

* Operation system: Windows 7
* Extension version: 1.10.7

### Expected behavior

I  click the 'Log In' button and the client connects or gives me feedback as to _why_ the log in attempt fails.

### Actual behavior

I click the 'Log In button and it just says 'Error connecting to server'.

### Steps to reproduce the behavior

See above.

### Additional details

* screenshots or screencapture

![image](https://user-images.githubusercontent.com/73681/42685227-529c78ca-868a-11e8-9ba2-f57918cdf8bc.png)

**Comment by joncage** [comment]
To be clear, the same username / password works fine on both the dekstop app and the website itself it's just the button that's failing.

**Comment by tcrammond** [comment]
Sorry this was not resolved at the time, but we now have an entirely new login procedure for the extension.

Please let us know if there are any issue with the latest version of the extension.
