### ISSUE TITLE
No togg button on new Jira Dialog

### ISSUE THREAD

**Issue by FrancoisLorrain** [toggl/toggl-button#1081]
### Environment details

* Operation system: Windows 10
* Extension version: 1.10.7

### Expected behavior
To have toogle button into the new Dialog

### Actual behavior
No button

### Steps to reproduce the behavior
In Jira sprint overview, when you click on a card a modal appears without the toggle button.

### Additional details

* screenshots or screencapture
![image](https://user-images.githubusercontent.com/9095719/42692921-56d314da-867b-11e8-9e8e-5c7e3251984d.png)

**Comment by nicktoggl** [comment]
Case /17878407579

**Comment by VeljkoTN** [comment]
Case/17878407579
