### ISSUE TITLE
Cannot login on Chrome Canary

### ISSUE THREAD

**Issue by robinwittebol** [toggl/toggl-button#1083]
### Environment details

* Operation system: Windows 10 Home 1803 - Build 17134.165
* Extension version: 1.10.7

### Expected behavior
After entering login info and clicking login button it should either show an error or continue login.

### Actual behavior
Nothing happens. Login doesn't continue and no errors are shown.

### Steps to reproduce the behavior
Enter login info and click the log in button.

### Additional details
Works in normal Chrome.
Both normal chrome and chrome canary installed.
Reinstall of extension did not help.

**Comment by dpsxp** [comment]
Seem to be working on the current version of canary. So I'm closing this, feel free to reopen if the issue happens again.
