### ISSUE TITLE
Add control mechanism for collecting performance and usage data

### ISSUE THREAD

**Issue by langri-sha** [toggl/toggl-button#1085]
On July 18th of 2018 the publishing of versions `1.10.8` and `1.10.9` inclusively have been disabled after their review on Mozilla Add-ons.

In order to continue publishing releases, we must conform to [Add-ons
Add-on Policies](https://developer.mozilla.org/en-US/Add-ons/AMO/Policy/Reviews). 

This requires us to disclose how the add-on collects, uses, stores and shares user data in the privacy policy field on AMO. In addition, users must be provided a clear way to control this data collection and the control mechanism must be shown during the installation process of the add-on.

This issue should handle the introduction of the control mechanism, where we provide users the ability to control the collection of performance and usage data.

**Comment by fonorobert** [comment]
copy for privacy notice for add-on:

> We collect automated error and crash reports as well as general usage statistics.  
> We use this information to better understand the most used integrations and to help us fix issues as they appear. 
> All information we collect is anonymized. 
> 
> We collect usage statistics through Google Analytics:
> 
> - analytics tracking ID
> - generated user ID (anonymized, not tied back to Toggl account)
> - user activity in the add-on (which features and integrations are used)
> - add-on settings
> 
> When a crash or error occurs, we collect the following information via Bugsnag:
> 
> - Toggl user ID
> - add-on version, the user's operating system
> - log of the error and error message
> 
> The data collected in the add-on is also covered by the policies in our Privacy Policy: https://toggl.com/legal/privacy/
>

**Comment by langri-sha** [comment]
We're back on :fox_face:, with new privacy controls and an updated policy. Thank you everyone for your patience :bowing_man:!
