### ISSUE TITLE
All options in permissions tab are disabled without ability to enable them in chrome dev channel

### ISSUE THREAD

**Issue by yusitnikov** [toggl/toggl-button#1087]
When opening Permissions tab of extension settings dialog, all options there are disabled:
https://i.gyazo.com/7b7bf397995242d038a876ce392e2aaf.png
Clicking on option checkbox or on "enable all" button doesn't change anything: options are being checked off immediately, no system permission dialogs appear, and I see "Unchecked runtime.lastError: This function must be called during a user gesture" error message in the console.
I'm using latest chrome from dev channel. I confirm that the extension works as expected on "regular" chrome on same PC with same settings.

### Environment details

* OS: Windows 10
* Browser: Chrome 69.0.3493.3 (Official Build) dev (64-bit)
* Developer mode: off
* Extension version: 1.10.9

**Comment by langri-sha** [comment]
Thank you for the heads up, we'll take a look and make sure things work before this gets released to the stable channel!

**Comment by rylek90** [comment]
Please try to update Canary, it appears to be working again

Chrome: Version 70.0.3529.3 (Official Build) canary (64-bit)
Extension: 1.10.9

**Comment by yusitnikov** [comment]
Thanks, it's working!
