### ISSUE TITLE
Button click area is inconsistent in trello integration

### ISSUE THREAD

**Issue by shantanuraj** [toggl/toggl-button#1088]
### Environment details

* Operation system: All
* Extension version: 1.10.9+

### Expected behavior

Clicking any where on the "Start timer" button should trigger the start of the timer.

### Actual behavior

![image](https://media1.tenor.com/images/1bf75cb750fc152de7155c9b6a3c794d/tenor.gif?itemid=12218919)

Clicking on the button outside the text/link content is a no-op, even though visually the button state changes. This is misleading and inconsistent with the other buttons on the card.

### Additional details

![image](https://user-images.githubusercontent.com/1716853/43158826-516f7084-8f9e-11e8-90ac-a9ecfa7b7457.png)

The button link to start the timer is wrapped in a `div`
The link doesn't fill the dimensions of its parent.

**Comment by VeljkoTN** [comment]
Just an update from the user - he confirmed it works every time if you hit the text part of the button.

**Comment by tcrammond** [comment]
This was improved recently 🚀  closing.
