### ISSUE TITLE
MeisterTask updated their interface. Start button no longer visible.

### ISSUE THREAD

**Issue by Michelle112** [toggl/toggl-button#1093]
A user wrote in to say that MeisterTask just updated their interface and the Chrome plug-in start button isn't visible anymore.

/conversations/17792928737

### Environment details

* Operation system: (Windows NT 10.0; Win64; x64) 
* Extension version: TogglButton/1.10.9

### Additional details

* screenshots or screencapture

**Comment by VeljkoTN** [comment]
A user reported that the button is again missing from Meistertask. They have the latest version of Meistertask and Toggl Button on Chrome. 

Intercom conversation/18120690851

**Comment by rylek90** [comment]
Hmm, I wonder if it helps 🤔 
https://github.com/toggl/toggl-button/pull/1118
