### ISSUE TITLE
Button no longer appearing in Chrome / Mac for Asana

### ISSUE THREAD

**Issue by alancolyer** [toggl/toggl-button#1095]
**### Environment details**

* Operation system: Mac OSX 10.12.6
* Extension version: 1.10.9
* Chrome Version 68.0.3440.84 (Official Build) (64-bit)

**### Expected behavior**
Start Timer button displays to right hand side of Date on task in asana

**### Actual behavior**
Button does not display

**### Steps to reproduce the behavior**
Loginto Asana, create a task, view task & look for button

**### Additional details**
This was working up until about a week ago, maybe a recent update? I've checked permissions in the extension, and all are enabled for asana.com. I've tried removing & installing the extension again, unsetting & resetting permissions, and clearing cache / cookies.

![screen shot 2018-08-08 at 09 35 31](https://user-images.githubusercontent.com/2302728/43826300-eab98404-9aee-11e8-9d1d-bb0d60588c08.png)

![screen shot 2018-08-08 at 09 36 09](https://user-images.githubusercontent.com/2302728/43826152-870de152-9aee-11e8-9626-3b4ac6e662ae.png)

**Comment by demoklion** [comment]
Also true in my setup:

### Environment

    Operation system: Windows 10 Pro 1803 17134.165
    Extension version: 1.10.7
    Firefox Developer edition 62.0b16 (64-bit)

**Comment by josipjelic** [comment]
Was true for my setup as well. It just came back today...
![image](https://user-images.githubusercontent.com/91408/44188952-cde28500-a120-11e8-9a07-e4e6c49ca96e.png)

**Comment by khoi** [comment]
Still true in my setup

OS: macOS 10.13.6 (17G2208)
Extension version: 1.10.7
Firefox 61.0.2 (64-bit)

**Comment by alancolyer** [comment]
@josipjelic mine has come back too now, although position has changed from before, I'm seeing the same as yours but for me there is no "start timer" button next to the date like there was before.

**Comment by ckrf** [comment]
I just got this problem for the first time today with Chrome Version 68.0.3440.106 (Official Build) (64-bit) on Windows 10.
