### ISSUE TITLE
Toggl Button Firefox extension hangs when used in JIRA

### ISSUE THREAD

**Issue by maritoggl** [toggl/toggl-button#1097]
User 4213569 reports that Toggl Button Firefox extension has stopped working with JIRA - when attempting to start the timer, popup just hangs. User has not recently installed any new browser extensions that could be conflicting with our button. 

### Environment details

User agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:61.0) Gecko/20100101 Firefox/61.0 
Extension version: 1.10.07

### Expected behavior

Clicking "Start Timer" starts the timer

### Actual behavior

After user clicks the start timer button, selects the project and hits the done button, popup hangs and timer does not start. 

### Steps to reproduce the behavior

Could not reproduce the issue myself as I don't have access to any JIRA setup. 

### Additional details

![issue selecting project](https://user-images.githubusercontent.com/35216651/44013315-107cf6b0-9ec5-11e8-8518-0793b6355c0d.jpeg)

conversations/17911299431

**Comment by langri-sha** [comment]
This has been resolved in https://github.com/toggl/toggl-button/pull/1079. Waiting for the next Firefox release.
