### ISSUE TITLE
Freshdesk extension no longer works

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggl-button#1099]
User reports that Freshdesk have updated their website layout and the Toggl button extension no longer works

Inter:18089136049

**Comment by maritoggl** [comment]
+1 conversations/18467416551

**Comment by maritoggl** [comment]
+1 conversations/18725378868

**Comment by TheSoloJake** [comment]
+1 conversations/19175574669

**Comment by TheSoloJake** [comment]
+1 conversations/19175690718

**Comment by epagnini** [comment]
@tcrammond per slack convo :)

**Comment by tcrammond** [comment]
Latest versions of Toggl Button do indeed support Freskdesk Mint after all. The button shows in the "single ticket" view, i.e. when you have clicked on and opened one ticket. Jacob was able to check with a user if they can see it now, and they could 🎉.

Closing issue.

**Comment by TheSoloJake** [comment]
@tcrammond User is reporting that the extension is constantly adding timer buttons to a ticket: 

![screen shot 2018-12-13 at 1 42 15 pm](https://user-images.githubusercontent.com/25573455/49963378-69bcab80-fedd-11e8-91c8-ec185295c4ab.png)

**Comment by tcrammond** [comment]
Thanks @TheSoloJake. Issue here https://github.com/toggl/toggl-button/issues/1228

**Comment by TheSoloJake** [comment]
UPDATE: user is stating that, due to a UI change that FreshDesk has made, the integration doesn't work anymore: 

[case link](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/19196386078)

**Comment by TheSoloJake** [comment]
@tcrammond FYI, user is reporting that because FreshDesk changed some of the Mint UI, the TogglButton doesn't work anymore. I don't have Freshdesk to test, so I haven't seen it personally

**Comment by tcrammond** [comment]
@TheSoloJake, will investigate 👍
