### ISSUE TITLE
Button missing on Airtable

### ISSUE THREAD

**Issue by Resalee** [toggl/toggl-button#1105]
### Environment details
* Extension version: Chrome 1.10.9

### Additional details
![image](https://user-images.githubusercontent.com/14049164/44696981-5dd2e800-aaac-11e8-99ea-4c5a2632e2a9.png)

**Comment by langri-sha** [comment]
Hi @Resalee. Can you please try the newly released version v1.11.0, the integration should be working again after #1013.
