### ISSUE TITLE
API errors when using Toggl Button [resolved]

### ISSUE THREAD

**Issue by jb-nuuk** [toggl/toggl-button#1108]
### Environment details

* Operation system: macOS High Sierra version 10.13.6 running Chrome version 68.0.3440.106 (Official Build) (64-bit)
* Extension version:
Version (1.10.9)

### Expected behavior
Starting timer (with no existing timer running) using an authorised webpage (In my case Todoist with extensions permissions granted) starts a new timer at toggl/app/timer

### Actual behavior
The timer is shown to be running on the authorised webpage, however does not get started on my Toggl account

### Steps to reproduce the behaviour
Attempt to start the Toggl timer from an authorised website (In my case Todoist) and wait for the stop timer message to appear. Open the Toggl timer website in another tab and observe that no timer was started. Navigate back to authorised website and view that stop timer message has disappeared, indicating a failed timer start.

### Additional details
* Logging out of the Toggl extension and attempting to log back in causes an "Error connecting to server" error.
* Current workaround = start an empty Toggl timer on the Toggl/timer webpage and then start a timer in my authorised webpage

* screenshots or screencapture
<img width="237" alt="screen shot 2018-08-29 at 12 05 17" src="https://user-images.githubusercontent.com/42244528/44781159-ed979580-ab83-11e8-9824-915995d3c049.png">

**Comment by langri-sha** [comment]
We've introduced a fix in #1090 and we'll be publishing a release for Chrome soon. We'd kindly ask Firefox users to wait patiently while we resolve #1085 with the Mozilla Add-ons team.

**Comment by langri-sha** [comment]
Thank you everyone, version v1.11.0 has been published in the Chrome Web Store.

We'll keep this thread open for Firefox users.

**Comment by langri-sha** [comment]
Everything should be fine for Firefox users now as well.

**Comment by jb-nuuk** [comment]
Brilliant! Thanks for quick response and fixes, everything is working perfectly again 👍
