### ISSUE TITLE
Timer starts automatically even though setting for starting automatically is unchecked

### ISSUE THREAD

**Issue by nhanisch** [toggl/toggl-button#1116]
### Environment details

* Operation system: Linux Debian 9
* Extension version: Firefox Toggl browser extension 1.10.7

### Expected behavior
Timer will only start if I explicitly click to start the timer through the browser extension or on Toggl.com. This behavior should only change if I change my setting in the Toggl settings to "Start automatically". 

### Actual behavior
Timer will occasionally start while I am using my web browser sometime shortly after beginning work. It is unclear when it starts because i am usually very focused and only catch it 30+ minutes into working.  

### Steps to reproduce the behavior
From a computer running Debian 9 and the Firefox Toggl extension 1.10.7, it seems to happen randomly. It does not start immediately after opening Firefox. I rarely close my browser at all, but I suddenly notice it will be running and be 30+ minutes into running.

**Comment by tcrammond** [comment]
Hi @nhanisch. I know it's been a while, but have you seen this issue much since you first reported it? Do you know if the timer being started is related to a particular integration, or is it a blank entry?

**Comment by nhanisch** [comment]
@tcrammond It always starts the timer with a blank entry. At this point my Toggl browser extension has updated to v1.12 and the issue is still occurring.

Occasionally the extension will sign me out, and so I open the Toggl web app and it automatically signs me back in on the extension. In addition to this, I occasionally open the Toggl web app to fix time entries or look at reports.
