### ISSUE TITLE
JIRA | No "Start Timer" Button in new Jira issue view

### ISSUE THREAD

**Issue by eLenoAr** [toggl/toggl-button#1117]
Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

### Environment details

* Operation system: Windows 10 with Chrome Version 68.0.3440.106 (Official Build) (64-bit)
* Extension version: v1.11.1

### Expected behavior
* "Start Timer" button to be visible

### Actual behavior
* no "Start Timer" button visible

### Steps to reproduce the behavior
* using the latest Jira issue view (cloud version)

`The new issue view is live for all boards in business projects, and is available for all Jira Software boards and backlogs. To turn the new issue view on or off in Jira Software projects for now, head to Your profile and settings -> Personal settings and toggle the switch for the New Jira issue view.`

### Additional details
* https://confluence.atlassian.com/jiracorecloud/the-new-jira-issue-view-938040503.html
![image](https://user-images.githubusercontent.com/1316732/44905599-d5a24c00-ad12-11e8-9805-453bc9a2e8c3.png)
![image](https://user-images.githubusercontent.com/1316732/44905618-e94db280-ad12-11e8-9fe9-5bbc3fb76540.png)

**Comment by nicktoggl** [comment]
18315050291
18323808212

**Comment by nicktoggl** [comment]
General question from user re integration, Jira has been updated and there is a new Issue view presentation. Are there any plans to integrate the Toogl Button into the new view?

**Comment by maritoggl** [comment]
conversations/18968063290

**Comment by tcrammond** [comment]
Looking to get this into the next release 👍

**Comment by bryanph** [comment]
There is an existing PR here: #1121
