### ISSUE TITLE
Can't set default project with Chrome

### ISSUE THREAD

**Issue by maritoggl** [toggl/toggl-button#1119]
### Environment details

* Operation system: macOS High Sierra v10.13.6
* Extension version: v1.11.1

### Expected behavior

Selecting the default project in Toggl Button Chrome extension settings results in the default getting saved and attached to new time entries that don't have any project selected. 

### Actual behavior

Default does not get saved nor attached to any new time entries. 

### Steps to reproduce the behavior

Try to save a default project in extension settings and start a new time entry or check extension settings again after thinking you've saved them.

**Comment by larslindnilsson** [comment]
This is also an issue on Windows 10 (1803), Chrome 69, Extension v.1.11.1

**Comment by maritoggl** [comment]
Reported also by user 3523176

**Comment by VeljkoTN** [comment]
Reported by two users on Chrome Web Store

**Comment by rylek90** [comment]
💥 https://github.com/toggl/toggl-button/pull/1147

**Comment by TheSoloJake** [comment]
Reported by additional Chrome user on latest stable build

**Comment by kimfaint** [comment]
I still had this on v 1.17.1.  Fixed by removal of extension, restart Chrome, re-add extension.
