### ISSUE TITLE
Wiki & Contribution documentation: needs update to reflect building changes, #lint 

### ISSUE THREAD

**Issue by vladdancer** [toggl/toggl-button#1123]
Current Wiki and Documentation recommends:
1. to run `make lint` but there is no more Makefile in this repository.
2. to add special linting header

This changes were introduced in 6db940d439e5074e07eb473aed529ba9f65b58da
as a part of a new build system.

Solution: remove references to the runnig a lint as also as adding special lint header in
- [x] wiki
- [ ] .github/CONTRIBUTING.md

**Comment by tcrammond** [comment]
Thanks for making this issue, these documents were updated recently and should reflect current practices now. We'll revisit it again after making some tooling upgrades.

**Comment by vladdancer** [comment]
+1
