### ISSUE TITLE
Intercom.io Toggl Button Missing

### ISSUE THREAD

**Issue by danburkhol** [toggl/toggl-button#1124]
### Environment details
* Operation system: 
macOS 10.12.6 (16G29)
* Extension version:
1.11.1
* Chrome Version
Chrome 68.0.3440.106 and 69.0.3497.81

### Expected behavior
Toggl button to appear in the chat box in an Intercom conversation.

### Actual behavior
No Toggle button

### Steps to reproduce the behavior
N/A

### Additional details
This was supposedly fixed in #1015 
I disabled all other Chrome extensions during my troubleshooting.

* screenshots or screencapture
![screen shot 2018-09-07 at 12 19 31 pm](https://user-images.githubusercontent.com/661091/45230880-4fe54a00-b298-11e8-93e5-3d698848f56f.png)

**Comment by arthur-roose** [comment]
Any update on this ? I still can't see the button on Intercom.io

**Comment by TheSoloJake** [comment]
Another user is reporting that the button is missing and they'd like it back: [case link](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/22944439798)

Perhaps remove the domain from the Permissions list until we can commit to a fix, or is this a quick fix?
