### ISSUE TITLE
VSTS not working properly with the "New Navigation" option enabled

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggl-button#1132]
Chrome user reported a problem in Visual Studio Team Services. The Start timer button breaks if the user turns on the “New Navigation” preview (https://blogs.msdn.microsoft.com/devops/2018/06/19/new-navigation/)

@shantanuraj successfully reproduced the issue
https://toggl.slack.com/archives/C029W49FT/p1537426030000100

**Comment by hfaran** [comment]
@rylek90 Is there a plan to get your PR for this merged? Toggl button still doesn't work with the new navigation preview.

**Comment by shantanuraj** [comment]
@hfaran the PR is merged now we'll deploy a new version to the store soon.
