### ISSUE TITLE
Broken Todoist dark mode integration

### ISSUE THREAD

**Issue by rylek90** [toggl/toggl-button#1134]
### Environment details

* Operation system: Any
* Extension version: Any 

### Expected behavior
Working Todoist integration

### Actual behavior
New Time Entry popup is broken

### Steps to reproduce the behavior
* Fire Todoist dark mode 
* 💥 

### Additional details
https://twitter.com/MatthewSoakell/status/1044940759030530048/photo/1

<img width="672" alt="screenshot 2018-09-26 at 16 59 04" src="https://user-images.githubusercontent.com/10184544/46085013-b1207f00-c1ad-11e8-9153-e4b398ec1fd3.png">

**Comment by Malanius** [comment]
I've tested this on chrome, the project label actually gets parsed, but is not visible as the text has a white colour, it is even visible in the toggl pop-up that the Start timer text is white.
Seems that the text color is inherited from the dark theme styling.

![image](https://user-images.githubusercontent.com/6827667/46163221-d800b300-c28a-11e8-95b6-7fbce055edaf.png)
