### ISSUE TITLE
Text not visible with Todoist dark theme

### ISSUE THREAD

**Issue by rschuetzler** [toggl/toggl-button#1140]
### Environment details

* Operation system: Windows 10
* Extension version: 1.11.1

### Expected behavior
Click "Start timer" and see task name

### Actual behavior
Task name is white text on a white background

### Steps to reproduce the behavior
* Apply Todoist dark theme (dark background, white text)
* Click "Start Timer" on a task

### Additional details
The Todoist dark theme was just released this week.

* screenshots or screencapture

![2018-10-02 09_01_06-eye tracking_ todoist](https://user-images.githubusercontent.com/600775/46353454-d552e480-c621-11e8-8bd3-c675b0df7d00.png)

![image](https://user-images.githubusercontent.com/600775/46353434-cb30e600-c621-11e8-8967-be4a46a2b99e.png)

**Comment by rylek90** [comment]
Hi! 

Thank you for your submission. [Fix](https://github.com/toggl/toggl-button/pull/1135) has been already merged to master so, please hold on and wait for update 🙏
