### ISSUE TITLE
"Stop automatically at the end of the day" feature does not stop timer at set time 

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1143]
### Environment details

User-agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36 
Version: TogglNext-4.10.65 (snowball) 
User ID: 4318910

"Stop automatically at the end of the day" feature does not stop the timer at set time. I've tested it out as well and was able to reproduce the issue, the timer just keeps running past the set "end of day" time.

### Expected behavior

A running time entry should stop when local time reaches the custom selected time of day a user has selected for their "Stop automatically at the end of the day" setting. 

### Actual behavior

The timer just keeps running until it's manually stopped. 

### Steps to reproduce the behavior

Go to the settings page of the Toggl Button extension, General tab, check the box next to "Stop automatically at the end of the day" and select a specific time. Let the timer run and see if it stops at a custom selected time of day.

**Comment by VeljkoTN** [comment]
Nope, it does not stop at all.

**Comment by rylek90** [comment]
Hmm, it would be nice to get some additional details, like console screenshot.
It appears to be fully functional on my end
<img width="380" alt="screenshot 2018-10-09 at 13 50 24" src="https://user-images.githubusercontent.com/10184544/46667603-6863bf80-cbca-11e8-8549-7dcd7a8fea3a.png">

**Comment by rylek90** [comment]
@VeljkoTN can you please do some debugging for me?

We need two local storage entries for further investigation. Here's detailed instruction how to obtain them:
* Navigate to `chrome://extensions/` in Chrome
* Locate Toggl button extension and click on `background page` (as below)
   <img width="432" alt="screenshot 2018-10-09 at 18 03 13" src="https://user-images.githubusercontent.com/10184544/46682460-e2f20680-cbed-11e8-8ebf-54fb03e80749.png">
* New window should popup, pick local storage for Toggl button:
  <img width="439" alt="screenshot 2018-10-09 at 18 06 12" src="https://user-images.githubusercontent.com/10184544/46682530-15036880-cbee-11e8-8441-3c917cadbde3.png">
* We need two values (you can filter by them)
   * `dayEndTime` 
   * `stopAtDayEnd`

**Comment by VeljkoTN** [comment]
@rylek90 This time around it worked for me as well. I still wanted to check out local storage for the extension and after quitting that window to try replicating again I now can't get back into the Extension settings to set up a different stop time, it just shows blank:

![image](https://user-images.githubusercontent.com/36152180/46723367-f649b400-cc77-11e8-80a0-5102455a048d.png)

**Comment by rylek90** [comment]
Hmm, @VeljkoTN did you try to update extension? Maybe it is related with https://github.com/toggl/toggl-button/pull/1142

**Comment by VeljkoTN** [comment]
Tried, it, clicking on the Update button instantly shows the notification "extension updated" and the same thing still happening

**Comment by rylek90** [comment]
Do you have any errors in console? 🤔

**Comment by VeljkoTN** [comment]
Nope, the console is suspiciously empty: 

![image](https://user-images.githubusercontent.com/36152180/46725575-c224c200-cc7c-11e8-875d-b310609f88af.png)

**Comment by VeljkoTN** [comment]
All good now, restarting the browser helped 😕

**Comment by VeljkoTN** [comment]
![image](https://user-images.githubusercontent.com/36152180/46726119-ec2ab400-cc7d-11e8-8a86-70c9df6a5670.png)

All is good this time around, should I just ask the user to remove and then add the extension again?

**Comment by rylek90** [comment]
Probably 🤔

**Comment by VeljkoTN** [comment]
Figured this out finally. The user is closing their laptop effectively putting it to sleep, the extension will not function if the browser is not up and running.
