### ISSUE TITLE
Youtrack integration

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggl-button#1161]
From twitter "youtrack has updated so the tracking from the plugin no longer works, is there a way we can enable it for the new layout"

### Environment details

* Operation system: Windows 10
* Extension version: 1.11.2

### Expected behavior
Toggl button works with Youtrack
### Actual behavior
Youtrack update and integration no longer works

**Comment by tcrammond** [comment]
This was fixed in #1160.
