### ISSUE TITLE
Extension settings are reset after a while on firefox

### ISSUE THREAD

**Issue by bebosudo** [toggl/toggl-button#1167]
### Environment details

* Fedora 25;
* firefox 57 - automatic updates disabled;
* toggl button extension version 1.10.7, 13 september 2018:

### Expected behavior
The extension settings should remain, but sometimes they are reset.

### Actual behavior
Extension settings are reset.
I notice this because sometimes the popup inviting to track time appears, and it starts tracking even if I do not touch it (which is rather stupid, if I'm AFK I don't want it to start tracking time).

### Steps to reproduce the behavior
Install the extension, disable all the options in the extension settings page (navigate to `about:addons`, then select toggl button preferences) under the `General` tab (in particular the "Remind me to track" option, then browse for some time (today I was browsing for an hour); the tracking reminder popup appears because the settings have been reset.
Firefox automatic updates are disabled.

**Comment by tcrammond** [comment]
Hello @bebosudo, thanks for reporting this. 

Some updates were released recently that fixed misbehaving notifications and settings options. Can you please let me know if you've noticed this problem in the latest versions? (we're up to `1.14.0`/`1.15.0` now).

**Comment by bebosudo** [comment]
Hi! Thanks for the update, I've just updated to 1.15.0; I'll come back to this issue in case I'll see the same old behaviour.

**Comment by terodev** [comment]
I'm running 1.21.3 and see this behavior. Looks like it's related to clearing browsing history.

**Comment by bebosudo** [comment]
In the last two months I've updated to Fedora 29 with FF 64, and right now I've updated the toggl button to 1.21.3, but I haven't seen this behavior since November.
Like @terodev I've set FF to clean cache and history at exit (I keep cookies and logins).

**Comment by terodev** [comment]
I clear both History and Data and have set the time range to Everything.

**Comment by VeljkoTN** [comment]
Another user is having this issue, intercom 20381982462

**Comment by tcrammond** [comment]
Thanks for the additional information about your use cases here 🙌 

Unfortunately if site data or cookies are cleared, **extension data will also be deleted**. This will probably include the "Delete cookies and site data when Firefox is closed" setting and clearing history with either the "Offline Web Site Data" or "Cookies" option checked (whether manually clearing history or using "when closing Firefox" option).

We do have plans to use Firefox Sync and Google Account sync for settings which should resolve most cases of this problem. Please feel free to watch the issue #1296 for updates.

Until then, I'm sorry that the only suggestion I can make is to consider tweaking your data settings. I don't know if there is a sensible way to whitelist extension data in Firefox to prevent it being reset.

**Comment by terodev** [comment]
Thanks for your reply. I also use LastPass a lot and their FF extension is able to operate even I clear the browser history. Could you have a look of their implementation, please?

**Comment by tcrammond** [comment]
Apologies for the late update. These issues should be resolved on later versions of the extension 🎉 

The extension now uses "synced web extension storage" and you should no longer lose settings as described after version `1.24.1`.

Please re-open this issue if there are problems after this version 👍 .
