### ISSUE TITLE
Adding custom service doesn't work in Firefox

### ISSUE THREAD

**Issue by anotherbugmaster** [toggl/toggl-button#1169]
### Environment details

* Operation system: Arch Linux
* Extension version: 1.12.0

### Expected behavior

Able to add custom service.

### Actual behavior

Custom url adds with AgenoCRM setting only.

### Steps to reproduce the behavior

- Try to add new custom domain url permission
- Fail

![image](https://user-images.githubusercontent.com/3992246/47641170-6a3ff380-db76-11e8-82ba-4a275c4b8c05.png)
![image](https://user-images.githubusercontent.com/3992246/47641186-7461f200-db76-11e8-8bd3-df30e3a358c9.png)

**Comment by netbrothers-tr** [comment]
I can confirm this with Firefox Developer Edition 64.0b5 (64-Bit) on a Windows 10 host. Due to this bug, `AgenoCRM` remains the only self hosted software the add-on can handle.

**Comment by maritoggl** [comment]
Also reported in conversations/19362847602

**Comment by 4ndv** [comment]
Same issue on Firefox 63.0.1, Mac OS 10.14

**Comment by 4ndv** [comment]
Temporary solution:

1. Open `about:debugging`
2. Enable extensions debugging
3. Find toggle button and press on "Manifest URL"
4. Replace "manifest.json" in address bar with "html/settings.html" and open
5. Add your domain
6. In this file: https://github.com/toggl/toggl-button/blob/6565ec50c6e4c667e81ba9fdccf53a21c55dc925/src/scripts/origins.js find key for your service (for example, it's myjetbrains.com for YouTrack)
7. Open inspector -> Storage -> Local storage, find "TogglButton-origins" key, replace "agenocrm.com" with the value from step 6

**Comment by tcrammond** [comment]
Thanks for your patience. Firefox permission settings, including custom URLs, will be available in the next release 🎉  It may take a few days to roll out to you.
