### ISSUE TITLE
Closing the notification popups saying "click here to...." still execute the action

### ISSUE THREAD

**Issue by atleta** [toggl/toggl-button#1170]
I've found this happening in two situations (there may be more):
* when "remind me to track" is enabled
* when "idle detection" is enabled

The extension will show me a popup when/if the condition for the above is triggered (e.g. I'm idle while I'm tracking time OR I'm active while I'm not tracking time). The popup will say that I should click it to do some action (discard idle time or start tracking). Now I'd expect to be able to prevent this from happening if I just close the popup with the [X] button, but even if I do that, the action will be executed as if I clicked the popup.

### Environment details

* Operation system: Ubuntu 17.04
* Extension version: 1.12.0
* Browser: Firefox 57.0.4

### Expected behavior
Close popup without executing the action I'm being reminded of/being asked about by the popup. (E.g. discard idle time.)

### Actual behavior
It does it anyway. (I.e. it will discard the idle time even if I close the popup instead of clicking it.)

### Steps to reproduce the behavior
Enable "idle detection" and/or "remind me to track" and be idle or be active (depending on which one you want to test) then click the [X] icon on the popup.
### Additional details

* screenshots or screencapture

**Comment by tcrammond** [comment]
Hi, thanks for reporting this issue. Hoping to have this one resolved in the next release.

related to #778, #1116.

**Comment by tcrammond** [comment]
Fixed and released in `1.13.0`👌.
