### ISSUE TITLE
Settings controls on Firefox appear odd

### ISSUE THREAD

**Issue by langri-sha** [toggl/toggl-button#1182]
### Environment details

* Operation system: Linux
* Extension version: 1.12.0

### Expected behavior

I would expect I can fully see the input controls on the settings page.

### Actual behavior

Some content appears to be clipped now.

### Steps to reproduce the behavior

- install the add-on on Firefox
- go to the settings page

### Additional details

![image](https://user-images.githubusercontent.com/77084/48263621-0b586500-e427-11e8-83dd-44d579f5e81e.png)

**Comment by shantanuraj** [comment]
Looks fine on macOS + Firefox

![image](https://user-images.githubusercontent.com/1716853/48356508-be7ac580-e696-11e8-9b59-43305d08bcdd.png)

**Comment by langri-sha** [comment]
This might not be valid anymore after settings page improvements.

**Comment by tcrammond** [comment]
as above, closing
