### ISSUE TITLE
Automatic tagging

### ISSUE THREAD

**Issue by bryanph** [toggl/toggl-button#1186]
This was a feature that was added by a user back in 2015. The idea is that given the services that toggl integrates with often also implement some kind of tagging support. The idea is to automatically add the tags used in the service also to the toggl time_entry.

Original PR: #260 
Related issues: #547

If we decide to implement this feature, please give credit to the original contributor :+1:.

**Comment by tcrammond** [comment]
We cleared some things up and we don't need to add any new features around this. The button API already supports including tags but very few integrations actually do it. We should be more vigilant with checking that new integrations include tags if the service has a concept of them.
