### ISSUE TITLE
Buttons no longer showing on Trello (Firefox)

### ISSUE THREAD

**Issue by ColinCee** [toggl/toggl-button#1202]
Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

### Environment details

* Operation system: macOS Mojave 10.14.1 
* Extension version: Firefox 1.14

### Expected behavior
Show toggl button in trello

### Actual behavior
Toggl buttons do not show in any trello board, including boards I own

### Steps to reproduce the behavior
Open up any card in trello and no Toggl button shows up

### Additional details
I can still use the tracker normally to track time by clicking the add on or right clicking

**Comment by janpapenbrock** [comment]
Same for JIRA, since latest update.

**Comment by tcrammond** [comment]
Hey @ColinCee, can you please check your permission settings and re-enable the extension for Trello if needed?

You can find instructions in the above comment if you need them. Let us know if the button still doesn't show.

**Comment by ColinCee** [comment]
@janpapenbrock @tcrammond Can confirm this works by enabling the permissions again, not sure why this was the case as it worked originally when I first installed it. Thanks for the help though!

**Comment by xstable** [comment]
What will this `about:addons` be for Chrome?
TMetric injecting a nice button directley in the Trello-Card like this: 
![image](https://user-images.githubusercontent.com/1778068/49946208-c7a5bf00-feee-11e8-882a-484fd3d8e22c.png)

Would expect, that Toggl Button also appear there. Is this possible?

**Comment by tcrammond** [comment]
Hi @xstable, for Chrome I'd recommend looking at this article: https://support.toggl.com/toggl-button-chrome-extension/#settings (this link should jump to the `Toggl Button Settings` section)

It shows how to open the settings, and then enable permissions under the next section `Permissions and Custom Domains`. You'll want to either enable everything or tick `trello.com` in the permissions list.

Once you have enabled Trello in the settings, the Toggl Button should appear in the location you pointed to.

**Comment by xstable** [comment]
That works. Thank you.

**Comment by jhbertra** [comment]
Why is this not documented here? https://toggl.com/trello-time-tracking/

From what I can tell, this is a _necessary_ setup step.  Very confusing!

**Comment by shantanuraj** [comment]
@jhbertra we hear you, there's a WIP PR https://github.com/toggl/toggl-button/pull/1598
that will help improve the onboarding process, and show how to enable integrations and use other extension features

**Comment by Shadrock** [comment]
I am having this issue now. I have selected settings for Toggl Button as listed above (checked permissions for atlassian.net and atlassian.com). Sill no button showing up...

**Comment by lise-toggl** [comment]
@Shadrock could you please get in touch with our support team (support[at]toggl.com) with some screenshots of your Toggl Button settings and the Atlassian page where the button isn't showing? Thanks!
