### ISSUE TITLE
Remove extra spaces from description in Podio

### ISSUE THREAD

**Issue by cebreus** [toggl/toggl-button#1204]
Thank You for great extension.

### Environment details

* Operation system: WIN 10, macOS Mojave
* Extension version: 1.14.0

### Expected behavior

Trim all white chars on start and end of the description.

### Actual behavior

White chars (spaces) are not trimmed.

### Steps to reproduce the behavior

Click on extension icon on the Podio.com page.

### Additional details

* https://ctrlv.cz/FC2c
* https://ctrlv.cz/gGwP

**Comment by tcrammond** [comment]
Thanks for the report! We'll have this fixed for you in the next release.
