### ISSUE TITLE
[Toggl Button] Rework tag selection

### ISSUE THREAD

**Issue by ricotheque** [toggl/toggl-button#1216]
## 🐛 Bug Report

When I type a tag I have to click on it in the chrome extension menu which breaks flow and is clunky. If I push enter, the menu goes away but none of my tags are added if I had not clicked on them. It's also not clear when a Tag is assigned to a Time Entry.

## Expected behavior

Toggle Button extension's tagging interaction should be similar to the desktop app's (macOS 7.4.231 beta)

## To reproduce

Attempt to assign a Tag to a Time Entry via Toggl Button, and do the same with the desktop app

## Suggestions

Toggle Button extension's tagging interaction should be similar to the desktop app's (macOS 7.4.231 beta)

## Context

From [this conversation](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/19904025332). @dooart requested the creation of this issue [here](https://toggl.slack.com/archives/C9LMUPD9T/p1544097099119700).

**Comment by eezhal92** [comment]
Let me work on this :)
