### ISSUE TITLE
Auto-Adding of Todoist Labels as Tags as an Option?

### ISSUE THREAD

**Issue by ErikOsterud** [toggl/toggl-button#1217]
### Environment details

* Operation system: Windows 10
* Extension version: 1.15.0
* Browser: Google Chrome
* App using Toggl Button: Todoist

Are there any plans to add an option to enable/disable the new automatic creation of Toggl Tags from Todoist Labels ( #1197 )? Since you need to explicitly tell the Toggl button for each time entry to NOT bring over the Label/Tags, people are having dozens of new tags created in Toggl every day for our company and we don't really want them in Toggl since everyone uses them differently.

**Comment by tcrammond** [comment]
Thanks for bringing this to our attention and for your suggestion. We're considering adding an option in the extension settings for this.
