### ISSUE TITLE
Detect parent project of Todoist

### ISSUE THREAD

**Issue by 5000164** [toggl/toggl-button#1223]
### Environment details

- Operation system: macOS Mojave
- Extension version: 1.15.1
- Browser: Google Chrome
- App using Toggl Button: Todoist

### Expected behavior

Detect parent project name when the same project name does not exist. (Previously behavior)

### Actual behavior

Does not detect parent project name.

### Additional details

The toggl-button behavior was changed by #1197 .
A Todoist project can be had hierarchy.
If a parent project is not detected, we need to prepare the same project names of Toggl as project names of Todoist.
However, it is difficult for me to create the same project names of Toggl as project names of Todoist because I often create and remove a subcategory.
For example,  I often create and remove Feature subcategory when my category is Work > Client name > Project name > Feature name.

**Comment by tcrammond** [comment]
Hey @5000164, thanks for bringing this to our attention. We'll bring back the "nested project" detection. Sorry for the inconvenience in the meantime.

**Comment by 5000164** [comment]
It's working in version 1.16.0.
Thank you!
