### ISSUE TITLE
Button missing from Google Calendar (Chrome)

### ISSUE THREAD

**Issue by maritoggl** [toggl/toggl-button#1234]
* **OS version**: macOS Mojave 10.14.1
* **Browser version**: Version 71.0.3578.98
* **Extension version**: Version (1.17.0)

### 🐛 Describe the bug

Google Calendar has updated their design, Toggl Button no longer displayed. 

### Expected behaviour

Toggl Button present in the updated Google Calendar views. 

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to https://calendar.google.com
2. See no button

### Other details or context

User reported issue in [conversations/20031234511](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/20031234511), problem reproduced by myself.

**Comment by tcrammond** [comment]
Just caught this as well 👌 Will fix promptly.
