### ISSUE TITLE
Remember the Milk 

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggl-button#1239]
#### Relevant integration (if any):

Remember the Milk

### 🐛 Describe the bug

"Toggl Button stopped working in RememberTheMilk recently. I noticed it a few days ago.

Hovering over the the Toggl Button for an RTM task displays the "Start timer" tool tip, but clicking it merely toggles the detail view of the task, rather than starting the timer like it should."

### Expected behaviour

Timer should start when clicked

### Steps to reproduce

Use Toggl button and hover over the the Toggl Button for an RTM task displays the "Start timer" tool tip, but clicking it merely toggles the detail view of the task, rather than starting the timer like it should."

https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/20107713855

**Comment by ezaki** [comment]
I check this bug, but I cannot find it.

![anim](https://user-images.githubusercontent.com/13980441/50430776-5d871400-0909-11e9-9bc7-2630f1c473d8.gif)

- Toggl Button Version: 1.17.1
- Browser:
  - Firefox Developer Edition 65.0b6
  - Google Chrome 71.0.3578.98
- OS: Windows 10 Pro 1803

Can you write this details?
I want more information.

**Comment by tcrammond** [comment]
It's been reported that this is no longer a problem, closing the issue. Thanks for checking it out @ezaki.
