### ISSUE TITLE
"Start/stop timer" text in timer popup becomes incorrect after multiple uses

### ISSUE THREAD

**Issue by tcrammond** [toggl/toggl-button#1247]
* **OS version**: *
* **Browser version**: *
* **Extension version**: * 

### 🐛 Describe the bug

When using the same integration button more than once in the same page load, the text in the **edit form / popup** "Start/stop timer" becomes out of sync with reality almost 100% of the time. It'll say "Start timer" even though you already started the timer (it should say stop).

### Expected behaviour

The "start/stop timer" text is always showing the correct version, both in-page and in the popup.

### Steps to reproduce

Steps to reproduce the behaviour:
1. Use an integration, e.g. GitHub
2. Start a timer using the in-page button *(note that popup says Stop Timer)* and then close the popup.
3. Stop the timer
4. Start the timer again. Even though you just started the timer, the text link in the popup will say "Start timer".

There may be other situations in which the text in the popup, or even on the timer link in the page itself, becomes out of sync.

### Other details or context

It's confusing.

**Comment by bryanph** [comment]
Does this happen when webapp is open, or also when toggl-button is running alone?

**Comment by tcrammond** [comment]
independent of webapp, it's not a sync thing just broken logic in the edit form
