### ISSUE TITLE
Can not disable Pomodoro or change intervals after initial setting

### ISSUE THREAD

**Issue by xiaobitou** [toggl/toggl-button#1248]
* **OS version**: Mac 10.14.2
* **Browser version**: NA
* **Extension version**: NA

### 🐛 Describe the bug

I recently started using Toggl and have installed the desktop app on my mac. Initially, I enabled the Pomodoro to 15 min work + 1 min break.  Ever since then, any new timer would stop at 15 mins even if I disable Pomodoro or change the interval setting.

### Expected behaviour

I would like to be able to turn on/off the Pomodoro function in Toggl and change the length of work intervals.

### Steps to reproduce

NA

### Other details or context

I logged into Toggl using my gmail account without signing up. I also tried toggl on my iPhone and the same problem happened, presumably because toggl syncs across platforms. Pomodoro also ceased playing the notification tone recently even when the Pomodoro timer is enabled.
I don't use chrome or its extension. But for testing purposes, I installed the toggle extension. Changing the Pomodoro setting in the chrome extension did not solve the problem, either.

**Comment by xiaobitou** [comment]
Never mind. I just realized that I also installed Toggl on my work computer and have left the Pomodoro setting there unchanged. Once I disable the Pomodoro on that computer, everything works fine. Apparently, Toggl cannot have two different settings, probably because of syncing function ...

**Comment by ToDestiny** [comment]
Helpful thank you!
