### ISSUE TITLE
Replace "Start timer"-button on JIRA Issue pages - in order to allow better copy-pasting of JIRA information

### ISSUE THREAD

**Issue by oliveratgithub** [toggl/toggl-button#1249]
* **OS version**: Google Chrome
* **Browser version**: 71.0.3578.98 (Official Build) (64-bit)
* **Extension version**: Version (1.17.1)

### 🐛 Describe the bug
Related to the Atlassian JIRA integration: the _Start timer_ inline-button is placed between the JIRA-Issue ID and the Issue description.

We commonly have to copy-paste this information – but with the Toggl-button in between the Issue-ID and -Description, it always copies "Start timer" along with the JIRA text. E.g.:

`MYPROJECT-123Start timer
Title of what needs to be worked on`

### Expected behaviour
Could you change the inline button placement to be either on the very left of the Issue breadcrumb; or e.g. to the right of the Issue description field – in order to allow selecting & copy-pasting the Issue-ID and -Description without the Toggl-button text?

Expected copy-paste output:

`MYPROJECT-123
Title of what needs to be worked on`

### Steps to reproduce
Prerequisite:
* Toggl-Button browser extension installed
* In the Toggl-Button settings under "Permissions" enable: "jira.com"

Steps to reproduce the behaviour:
1. Go to a JIRA project & open a JIRA issue
2. The Toggl-button "Start timer" should be displayed next to the Issue-ID
3. Select the Issue-ID text including the Issue-Description below it – click CMD+C / Ctrl+C to copy the text
4. Paste the text from the clipboard somewhere: it will display "ISSUE-123Start timer…"

### Other details or context
Affects JIRA version Jira v7.12.3

**Comment by tcrammond** [comment]
Thanks for reporting this. In the next release the "Start timer" text will no longer be highlightable and you shouldn't have the inconvenience anymore.

**Comment by oliveratgithub** [comment]
I can confirm that this issue is fixed with Toggl Button Chrome Extension Version (1.19.0)
