### ISSUE TITLE
Can't fill in password - modal closes when password field takes focus

### ISSUE THREAD

**Issue by Spone** [toggl/toggl-button#1257]
* **OS version**: Ubuntu 18.04
* **Browser version**: Firefox 64.0
* **Extension version**: 1.18.0

### 🐛 Describe the bug

I can't login because every time the password field takes the focus, the modal window closes.

### Expected behaviour

I should be able to type or copy-paste my password, then click "Log in"

### Steps to reproduce

Steps to reproduce the behaviour:
1. Install the add-on
2. Click the ![image](https://user-images.githubusercontent.com/38524/51169558-7e111100-18ac-11e9-9ba1-eab0501a4dce.png) button
3. Fill in the e-mail field
4. Click the password field or press Tab

### Other details or context

I tried to focus the password field by clicking it or using keyboard "Tab", but it doesn't solve the problem.

**Comment by shantanuraj** [comment]
Hey @Spone! 
Could you try login with the new release? (version 1.34.0 and up)
We revamped the login process to allow login from the toggl.com website.

**Comment by Spone** [comment]
Yes it's fixed! Thanks!
