### ISSUE TITLE
Continuing a task does not copy over tags

### ISSUE THREAD

**Issue by pcjmfranken** [toggl/toggl-button#1259]
* **OS version**:  Win 10 x64
* **Browser version**: Chrome 71.0.3578.98 (Official Build) (64-bit)
* **Extension version**: 1.18.0

### 🐛 Describe the bug

Continuing an entry from the button dropdown does not add tags that were included in the previous entry. This issue is limited to the extension, it does not occur in the web interface at https://toggl.com/app/timer.

### Expected behaviour

When continuing a previously made entry that contains a tag, the new entry should copy those tags.

### Steps to reproduce

1. Click extension button in top-right of browser window
2. Start a new entry with one tag selected
3. Stop the entry after a few seconds
4. Again click the extension button in top-right of browser window
5. Hover over the most recent entry and click the green continue button
6. Stop the entry after a few seconds
7. The new entry will not contain any tags, while the entry that it was based off of does

**Comment by tcrammond** [comment]
Thank you for reporting this. Fix will be included in next release.
