### ISSUE TITLE
Injected Toggl Button on webpages browsed with Google Chrome doesn't trigger new time entries anymore

### ISSUE THREAD

**Issue by oliveratgithub** [toggl/toggl-button#1263]
* **OS version**: macOS Mojave 10.14.2 (18C54)
* **Browser version**: Version 71.0.3578.98 (Official Build) (64-bit)
* **Extension version**: Version (1.19.0)

### 🐛 Describe the bug

With Toggl Button Version (1.19.0) and configured "URL permissions", the Toggl button does show up on webpages; however once clicking it, it immediatly changes to "Stop timer" – without showing a field for entering data before. And it does NOT actually initialise a new time entry.

So clicking on "Stop timer" just changes the button back to "Start time", but without any actual action.

### Expected behaviour

The injected Toggl Button on webpages in Google Chrome should show a popup with detail fields, and then actually starting a new time log entry on Toggl.

### Other details or context

Tested on webpages of the following services:
- JIRA
- Confluence Wiki
- Microsoft AzureDev Ops

**Comment by tcrammond** [comment]
Sorry to hear this. Can you please try some of the following?

* Make sure the webpages have been reloaded since the update
* Check for any extension errors in the Chrome devtools console when using a service
* Log out and back in to the extension
* Restart Chrome
* re-install the extension *(you may lose some settings)*

**Comment by KlausNie** [comment]
Same problem and setup as @oliveratgithub .
Reloaded the webpage.
No error regarding toggl in the console. Neither when clicking the button.
Did a logout/login.
Restarted chrome.
None of the above worked.

I'll try to re-install the extension later.

**Comment by oliveratgithub** [comment]
> * Make sure the webpages have been reloaded since the update
Done. No effect.

> * Check for any extension errors in the Chrome devtools console when using a service
Done. No errors – Toggl Button extension doesn't log anything, neither when loaded nor when clicked (DevConsole set to `verbose`).

> * Log out and back in to the extension
Done. No effect. Remark: I have to login on toggl.com with my Google Account, the extension will then "inherit" the login there – because the Toggl extension doesn't support a dedicated Google login.

> * Restart Chrome
Done. No effect.

> * re-install the extension _(you may lose some settings)_
Done. No effect. (lost ALL settings though)

**Comment by oliveratgithub** [comment]
Same here – updated the Chrome extension manually to 1.19.1 and the injected Toggl button works again! Thanks a lot for the quick fix! 🥇
