### ISSUE TITLE
Cannot login to Toggl on Chrome

### ISSUE THREAD

**Issue by clarsen** [toggl/toggl-button#1273]
* **OS version**: Mac OS 10.14
* **Browser version**: Chrome Version 71.0.3578.98 (Official Build) (64-bit)
* **Extension version**: Version (1.20.0)

#### Relevant integration (if any):

Using with Trello, however issue is chrome plugin cannot login so it happens before interacting with any integrations.

### 🐛 Describe the bug
on attempting to login with email and password (same email and password that works with toggl.com site), error "Wrong email or password!" is shown

### Expected behaviour
Expected a successful login

### Steps to reproduce

Steps to reproduce the behaviour:
1. Open plugin login dialog, 
2. enter email and password
3. click "Log In"

### Other details or context

Only recently (2 hours ago) set up a new password for account - was using OAUTH signin through google before.

**Comment by tcrammond** [comment]
Sorry to hear about this. Are you still having the problem now? We don't have any known issues with the Chrome extension login at the moment.

To eliminate one factor - please check `chrome://settings/content/cookies` settings:
* `Block third-party cookies` needs to be **disabled**

It may be worth deleting cookies for `toggl.com` in `chrome://settings/siteData` as well. Please let me know if anything changes.

**Comment by clarsen** [comment]
block third-party cookies was disabled.
i removed all cookies from *.toggl.com

still not able to log in via the extension.

**Comment by clarsen** [comment]
> @clarsen we recently revamped the login process
> can you try login with either Google or username/password on the extension (v1.34.0 and up)

I confirmed that with Chrome extension installed from the web store it can authenticate me via Google OAUTH and manipulate my toggl entries.

Thanks!
