### ISSUE TITLE
Add support for Tags in MeisterTask

### ISSUE THREAD

**Issue by TIIUNDER** [toggl/toggl-button#1274]
If you start the Toggl button in MeisterTask (meistertask.com), the popup gets filled with task name (as description) and selects the correct project. But it doesn't use the task tags. It would be nice, if the Toggl button would use the tags of the current MeisterTask task for the Toggl tags aswell.

**Comment by tcrammond** [comment]
Hey @TIIUNDER, tags are supposed to be supported already in MeisterTask 2.0.

Would you mind checking if you have the "Enable automatic tagging" setting enabled in your Toggl Button extension settings? It's near the top of the `General` tab of the settings screen.

**Comment by TIIUNDER** [comment]
@tcrammond Thank you, that works.
