### ISSUE TITLE
TargetProcess Integration Broken 

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggl-button#1279]
User in [this case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/20686602050) is reporting that the TogglButton integration with TargetProcess is broken; this after (apparently) TargetProcess has changed their platform.

**Comment by vedr4n** [comment]
User now reporting that it works fine. Closing. Will report if another user reports the same issue.

**Comment by TheSoloJake** [comment]
Since @vedr4n has noted that the issue is gone, closing issue now.
