### ISSUE TITLE
Project name is not pre-filled with board name in Trello

### ISSUE THREAD

**Issue by almirbi** [toggl/toggl-button#1280]
#### Relevant integration (if any):

trello.com

### 🐛 Describe the bug

Project name is not pre-filled with board name in Trello

### Expected behaviour

Project name pre-filled with board name when starting timer on Trello

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to a trello board
2. Create a card
3. Start a timer

### Other details or context

Seems that the first option [here](https://github.com/toggl/toggl-button/blob/master/src/scripts/content/trello.js#L14) `.board-header > a` does return an element but it's `textContent` (see [here](https://github.com/toggl/toggl-button/blob/master/src/scripts/content/trello.js#L51)) would be an empty string. The other selector, `'board-header-btn-name'`, should work

**Comment by TheSoloJake** [comment]
[Case link](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/20743547086)

**Comment by almirbi** [comment]
![screen shot 2019-02-08 at 8 34 46 pm](https://user-images.githubusercontent.com/6254473/52501601-000d0500-2be1-11e9-9bdd-4bc2e33a0870.png)

**Comment by ricotheque** [comment]
[convo](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/20749809410)
