### ISSUE TITLE
Settings: Standalone page

### ISSUE THREAD

**Issue by tcrammond** [toggl/toggl-button#1287]
Currently, the extension settings live inside the browser's own extension management window. This has caused problems with layout, styling, etc. due to differences between Chrome and Firefox. It limits what we can do in such a small space as well.

We should let the settings open in a standalone page:

- Update extension manifests to open the settings separately
- Any needed style tweaks to make it work in an unrestricted viewport size.

**Comment by shantanuraj** [comment]
![screenshot 2019-02-20 at 10 37 13](https://user-images.githubusercontent.com/1716853/53096920-3b46f680-3546-11e9-9140-82133667c82a.png)

Another edge case is portrait computers that should be fixed with the standalone page

**Comment by tcrammond** [comment]
Most definitely complete. Follow ups in #1313.
