### ISSUE TITLE
Login: Public web standalone log in page

### ISSUE THREAD

**Issue by tcrammond** [toggl/toggl-button#1288]
Currently the login occurs in the "toolbar pop up", and we have to conditionally render various states in there, including the no-workspace-state. Some users have trouble logging-in via passwords-managers mostly on Firefox.

We will ~move it to a standalone page~ create a new page on public web for Toggl Button log in.

- Remove all login-related views in the toolbar popup
  - Instead, direct to the new button login page when clicking the toolbar button when login is required.
- No workspace state: would it be best if we send people to webapp to resolve this? The alternative is we maintain the existing toolbar popup view.
- Ensure the button still indicates when user needs to log in, any other similar states.

Firefly page:
- Base off existing login page *(check for not needed conditions, states, API calls etc)*
- New copy
- Relevant other useful links - store links? Main toggl button page? Looking for web app instead?
- Login
  - Logs in and redirects to **Toggl Button extension landing page**

Extension landing page:
- Some text saying you're logged in and to start tracking
- Useful help links and settings link etc.

**Comment by shantanuraj** [comment]
I'd say we should explore the possibility of using public web to simplify our login process

This should help us deal with google login and other subsequent changes to the login flow later on (eg. if we add 2FA support)

See trello's login flow below

#### Login page
![image](https://user-images.githubusercontent.com/1716853/52998213-bc1fc880-3448-11e9-9226-6a602ae806d4.png)
#### Oauth login
![image](https://user-images.githubusercontent.com/1716853/52998231-ccd03e80-3448-11e9-8294-5035a39d4906.png)
#### Extension Landing on login
![image](https://user-images.githubusercontent.com/1716853/52998286-ef625780-3448-11e9-945f-f821f4371c17.png)

**Comment by shantanuraj** [comment]
Closed via #1367
