### ISSUE TITLE
Timer popup: best effort improvements

### ISSUE THREAD

**Issue by tcrammond** [toggl/toggl-button#1291]
Until we work on a dedicated re-design later, we'll do a best effort clean up and improvement of layout and appearance, possibly lifting some designed **styles** from the web app.

![screenshot2019-01-31at12 15 24](https://user-images.githubusercontent.com/6432028/52565198-06c49380-2dfe-11e9-9800-4d46b5e3375a.png)

Toolbar popup issue here: #1290.

The goal is to improve first impressions and perceived quality.

**Notes**

* Better buttons, icons, colours
* Improve UX of popdowns (Tags popdown is particularly olden)

**Comment by shantanuraj** [comment]
Closed via #1386
