### ISSUE TITLE
Uninstall page feedback

### ISSUE THREAD

**Issue by tcrammond** [toggl/toggl-button#1293]
After a user uninstalls the extension, a page on the Toggl website will be opened in their browser **to provide feedback *(via web extension).*

This page will **anonymously** ask for:

1. The reason(s) the user uninstalled, selected from a short list
    1. Things like "It didn't work with services I use", "I didn't want to sign up", "Too complicated", "I had to use the web app as well" etc.
2. Optionally, a text feedback message can be entered.

**Plans:**
* Add paged based off 'contact' page to Firefly.
* Adjust to include only radio options and a message field.
* Create cloud-function endpoint in Firebase project
  * Support CORS for `toggl.com`
  * Validate payload - accept `message` and array of `reasons` - fallback to a default message in case of unexpected problems.
  * Sanitizes input a bit
  * Save to Firestore record
* Send form to endpoint, handle outcomes (If there is unhandled server error, let's show the success state anyway?)
* Create a "success/thank you" state
* Include important button links that may help the user etc.
* Set up uninstall hook in the extension to open the uninstall page in a new tab.

**Comment by shantanuraj** [comment]
## ZenHub's uninstall page

![image](https://user-images.githubusercontent.com/1716853/52938998-0f324680-3389-11e9-98f2-f55770692c91.png)

https://www.zenhub.com/goodbye

**Comment by shantanuraj** [comment]
Closed via #1392
