### ISSUE TITLE
Passive review prompt

### ISSUE THREAD

**Issue by tcrammond** [toggl/toggl-button#1295]
A passive prompt somewhere inside the new settings page for very active users, suggesting to leave a review for the extension. This way it will only be seen if the settings page is being visited. It will not involve any kind of notification.

The prompt can be dismissed, e.g. "Never ask again".

**Plans:**
- Detect "Active user" in the settings page. We'll probably need to start ticking a storage value for active days, or entries created in button etc.
- Show the passive prompt. Perhaps it can go in the footer? It's even less intrusive there than in the main body of any settings tabs.
- The prompt must open the correct web extension store for the browser being used.
  - If it is opened, never show it again.
  - If it is **dismissed**, never show it again.
- If user uses the **Reset all settings** feature, **DO NOT** reset the sync storage value for this feature.

**Comment by shantanuraj** [comment]
Store interaction with the button in sync storage
Do not delete on reset all settings click
