### ISSUE TITLE
Sync user preferences

### ISSUE THREAD

**Issue by tcrammond** [toggl/toggl-button#1296]
Sync user preferences across browsers, i.e. Firefox Sync and Google Accounts, via web extension APIs.

* Refactor to use `storage.sync` API
* We don't need any kind of setting for this - it's up to the user's sync settings in the browser account.

[https://developer.chrome.com/extensions/storage#property-sync](https://developer.chrome.com/extensions/storage#property-sync)

[https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/storage/sync)

**Comment by shantanuraj** [comment]
Should be toggl-e-able (default to yes)

**Comment by shantanuraj** [comment]
Should have a reset option
