### ISSUE TITLE
The tracked time is not logged in Jira issue

### ISSUE THREAD

**Issue by revolter** [toggl/toggl-button#1301]
* **OS version**: macOS 10.14.2 (18C54)
* **Browser version**: Google Chrome 72.0.3626.96 (Official Build) (64-bit)
* **Extension version**: 1.21.1

#### Relevant integration (if any):

https://atlassian.net

### 🐛 Describe the bug

The tracked time is not logged in the issue.

### Expected behaviour

The issue's logged time should increase after stopping the timer.

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to an existing issue
2. Click the Toggl button
3. Wait for a bit
4. Click the Toggl button again

### Other details or context

I tried going directly to the issue instead of using Jira's side panel.

**Comment by tcrammond** [comment]
Hi, thanks for posting this issue. I'm afraid this is not a feature of Toggl Button; the time is only tracked inside your Toggl account. So I'll close this issue now. Feel free to let us know about any other feedback you have 🙇

**Comment by cscholtzdevprox** [comment]
This extension does it https://chrome.google.com/webstore/detail/jira-toggl/llmkgghnjkmdniffbfjhgcinekkkicki
