### ISSUE TITLE
Button not appear anymore in FreshDesk

### ISSUE THREAD

**Issue by teusch** [toggl/toggl-button#1304]
* **Windows 10 Enterprise**: 
* **chrome Version 71.0.3578.98 (Official Build) (64-bit)**: 
* **Version (1.21.1)**: 

https://basicorange.freshdesk.com/a/dashboard/default
### 🐛 Describe the bug

The button does not appear anymore in FreshDesk on an open ticket

![image](https://user-images.githubusercontent.com/5502583/52787424-13dfbd80-305e-11e9-8e38-14a13658f7a7.png)

**Comment by tcrammond** [comment]
Thank you for reporting this @teusch. A fix is in the works, we'll update you when it has been released.
