### ISSUE TITLE
Allow Toggl Button to pull Todoist Labels as Tags

### ISSUE THREAD

**Issue by ricotheque** [toggl/toggl-button#1307]
### Describe the new feature

I would like Toggl Button to automatically pull a Todoist Task's Labels, then convert them into Toggl Tags

### How does this help you?

Users rely on Todoist to plan their day, and Toggl to track how they accomplish that plan. This closer integration between both services would facilitate time analysis on Toggl, leading to more productivity.

### If we couldn't add this feature, is there a compromise you can think of?

None at this time.

[convo](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/20838174787)

**Comment by lise-toggl** [comment]
[Another request](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/23260198445)

**Comment by tcrammond** [comment]
This has been supported for a while now 🎉
