### ISSUE TITLE
Microsoft Todo integration broken

### ISSUE THREAD

**Issue by tcrammond** [toggl/toggl-button#1312]
* **Extension version**: Latest

#### Relevant integration (if any):

Microsoft Todo

### 🐛 Describe the bug

It does not show Toggl Buttons anymore. Something weird is also happening with the search bar which  hopefully isn't because of the integration 🙈 

### Other details or context

![](https://user-images.githubusercontent.com/1716853/53090162-95d75700-3534-11e9-951f-3bcc343ca40a.png)

**Comment by shirehobbits** [comment]
@shantanuraj
I don't even see 'Toggl Button' list Microsoft todo.
Is it because the url has changed from https://todo.microsoft.com/ to https://to-do.microsoft.com/ ?

**Comment by shirehobbits** [comment]
Could you please confirm if Microsoft Todo integration is broken?
As Microsoft Todo is one of the most used tool, could you prioritize the fix for this?

**Comment by shirehobbits** [comment]
Verified the fix. Works fine now.
