### ISSUE TITLE
Investigate feasibility of Google Login

### ISSUE THREAD

**Issue by tcrammond** [toggl/toggl-button#1314]
Investigate the feasibility of Google Login for the extension (likely not implementing at this stage)

**Comment by shantanuraj** [comment]
Investigation complete

Result similar to #1315 google-assited login for button is possible

See [video](https://toggl.slack.com/archives/CFQ81NG5P/p1552653443017100?thread_ts=1552652468.015200&cid=CFQ81NG5P) for example.
