### ISSUE TITLE
Login: Investigate feasibility of login via public web

### ISSUE THREAD

**Issue by tcrammond** [toggl/toggl-button#1315]
I'd say we should explore the possibility of using public web to simplify our login process

This should help us deal with google login and other subsequent changes to the login flow later on (eg. if we add 2FA support)

See trello's login flow below

#### Login page
![image](https://user-images.githubusercontent.com/1716853/52998213-bc1fc880-3448-11e9-9226-6a602ae806d4.png)
#### Oauth login
![image](https://user-images.githubusercontent.com/1716853/52998231-ccd03e80-3448-11e9-8294-5035a39d4906.png)
#### Extension Landing on login
![image](https://user-images.githubusercontent.com/1716853/52998286-ef625780-3448-11e9-945f-f821f4371c17.png)

_Originally posted by @shantanuraj in https://github.com/toggl/toggl-button/issues/1288#issuecomment-465023729_

**Comment by tcrammond** [comment]
Currently, logging in to webapp will in fact "log in" the extension as well, already. It's just a little bit janky.

With that in mind, the next steps may be:

* Make web login support "to/from Toggl Button" - allowing you to log in without launching the webapp afterwards, probably re-directing to a "login landing page" of some kind inside the extension.
* Open this login page from the extension when login is required and toolbar button is clicked.

It may then be worth considering a ticket for doing the same for sign up in future, for new users coming from web store (would be sensible for us to have the improved onboarding and UI before that as well)

**Comment by shantanuraj** [comment]
Perfectly summarized 👏 

- I'm just wondering should we do it in a pseudo-oauth login (?) where it's not actually oauth but we have a separate page on firefly dedicated for button logins (like the trello example)
- or just pass some params to firefly to trigger a redirect to button's landing page instead of webapp

**Comment by shantanuraj** [comment]
On discussing with product next step should be

> Make a separate page dedicated for button logins (Like the Trello example here
> https://github.com/toggl/toggl-button/issues/1315#issue-412452527)

Closing this one
