### ISSUE TITLE
Continuing TEs sometimes creates new TEs

### ISSUE THREAD

**Issue by shantanuraj** [toggl/toggl-button#1324]
* **OS version**: All
* **Browser version**: Chrome 74
* **Extension version**: master 35bbd9a

### 🐛 Describe the bug

* Continuing a blank entry (no description, no project/tag etc) creates a new entry randomly
* See screenshot for reference

![image](https://user-images.githubusercontent.com/1716853/53477449-bbb3ad00-3a9a-11e9-9553-a43bfb5e5557.png)

Similar issue faced by a customer
https://toggl.slack.com/archives/C02AT86CD/p1550779931033600

### Expected behaviour

* It should match the grouping logic used by the webapp

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to webapp add a blank TE to a previous day
2. Continue the TE and Stop it
3. In toggl-button click Continue Latest
4. See new entry added to button, but still grouped in webapp
5. This is slightly nondeterministic and I'm not able to reliably reproduce it 100%

**Comment by TheSoloJake** [comment]
[case link](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/20888641325)
