### ISSUE TITLE
Q: How Customizable is the Database? (from the dev-end)

### ISSUE THREAD

**Issue by BeksOmega** [toggl/toggl-button#1334]
### Problem Statement

I'm working on an integration with workflowy.com (who I am _not associated with_) and I was wondering if the functionality I want to add would be possible with your current database setup.

workflowy is basically a tree structure, with parents, children, and siblings:

![structure](https://user-images.githubusercontent.com/25440652/53742367-54f11380-3e4d-11e9-91f6-ae19de9699a8.jpg)

I want to use this to semi-intelligently predict what project the user will assign to a given node. It would work by assuming people group tasks in the same project together.

For example, say you assigned the RedProject to node A1. The extension would then associate that project with nodes A1, A, and Top Node.

![assignred](https://user-images.githubusercontent.com/25440652/53742441-77832c80-3e4d-11e9-9fa8-054b587818c7.jpg)

Then if you went to start a timer for A1b It would automatically populate the project slot with RedProject, because that is the closest assigned project (the great thing about this method is it would only have to traverse parents in the tree, not siblings or children).

![detectred](https://user-images.githubusercontent.com/25440652/53742503-9aaddc00-3e4d-11e9-8f40-8d111c0d949c.jpg)

Then say you want to start a timer for A2a. It automaticaly populates with RedProject,

![detectred2](https://user-images.githubusercontent.com/25440652/53742766-435c3b80-3e4e-11e9-883d-8440a812cb3f.jpg)

but then you manually set it to BlueProject. The extension then climbs the tree, associating parent nodes with the new project until it reaches one that has already been assigned.

![assignblue](https://user-images.githubusercontent.com/25440652/53742571-cd57d480-3e4d-11e9-93d6-3cc2ce1c7b5c.jpg)

The great thing is that as long as I can manually assign simple key-value pairs this should work, since each node has a custom id that is available through the DOM. I would just assign (nodeID -> projectID) and do the traversal inside the projectSelector.

**Comment by tcrammond** [comment]
Hi @BeksOmega, the simplest answer is: no, you can't assign any key value pairs or anything like that with projects in Toggl Button. We do have long-term wishes to support better project selection options.

Something that may inspire you is the Todoist integration. When starting a timer, it climbs the nested tree of Todoist projects and tries to find the closest leaf that matches an existing project in Toggl. You could achieve something similar to this with the Workflowy nodes (just watch out for performance implications in a big document). If you decide to tackle it, please make a separate PR for it after your first one is released 😄
