### ISSUE TITLE
"Remind me to track" from time doesn't save when changed

### ISSUE THREAD

**Issue by tcrammond** [toggl/toggl-button#1339]
* **OS version**: *
* **Browser version**: *
* **Extension version**: Latest

### 🐛 Describe the bug

Changing the "from" time of the tracking reminder does not save by itself. It is only saved when you changed the "to" time.

### Expected behaviour

Changes to only the "from" time is saved.

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to settings
2. Change the reminder "From" time and blur the field
3. Refresh settings
4. Your change was not saved.

### Other details or context

Looks like the event handler is incorrectly calling `Settings.saveSetting();` without any values.

**Comment by nicktoggl** [comment]
https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/21192008290

**Comment by nicktoggl** [comment]
https://app.intercom.io/a/apps/ayixs927/conversations/21189600004
https://app.intercom.io/a/apps/ayixs927/conversations/21192008290
https://app.intercom.io/a/apps/ayixs927/conversations/21192097547

Referencing cases for examples and to contact users when fixed

**Comment by epagnini** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2146384/conversations/21190415444)
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2146384/conversations/21189406981)

**Comment by epagnini** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2146384/conversations/21192340379)

**Comment by epagnini** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/21190351885)

**Comment by epagnini** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2146384/conversations/21190899646)

**Comment by nicktoggl** [comment]
At the moment we're recommending users disable the extension to prevent the problem from occurring, That is working as an option while we await a solution.

**Comment by nicktoggl** [comment]
Just marking that all users were contacted

**Comment by DivineMK** [comment]
This issue occurs to me for both from and to keys. I am using Linux, Firefox with Toggl Track 3.0.29.
