### ISSUE TITLE
Timer stops abruptly if stop at end of day is enabled

### ISSUE THREAD

**Issue by shantanuraj** [toggl/toggl-button#1341]
* **OS version**: ?
* **Browser version**: Firefox+Chrome ?
* **Extension version**: ?

#### Relevant integration (if any):

* Jira

### 🐛 Describe the bug

> suddenly have issues using your timer in JIRA via Firefox & Chrome. Timer stops after 31 seconds every time. Everything was fine just yesterday. Are you experiencing server downange?

### Expected behaviour

* Timer shouldn't stop abruptly

### Steps to reproduce

- needs info

### Other details or context

https://twitter.com/nextcommuter/status/1105888387469402113

**Comment by shantanuraj** [comment]
- What version of the extension is being used?
- Does this happen on other enabled integrations as well?
- Is Pomodoro mode enabled?
- Are any of these settings enabled?

#### Stop automatically on browser close
![image](https://user-images.githubusercontent.com/1716853/54302568-2b6f7f00-45e7-11e9-910f-e3250da3cb9c.png)

#### Stop at end of pomodoro interval
![image](https://user-images.githubusercontent.com/1716853/54302573-2dd1d900-45e7-11e9-9bcb-bce868712f57.png)

**Comment by shantanuraj** [comment]
Couldn't reproduce, original tweet was removed so closing for now.

**Comment by nicktoggl** [comment]
Awaiting more info but a similar case, will reopen if confirmed https://app.intercom.io/a/apps/ayixs927/conversations/21189600004

**Comment by nicktoggl** [comment]
https://app.intercom.io/a/apps/ayixs927/conversations/21192008290

**Comment by nicktoggl** [comment]
https://app.intercom.io/a/apps/ayixs927/conversations/21192097547

**Comment by nicktoggl** [comment]
@shantanuraj Looks like there is a problem

**Comment by nicktoggl** [comment]
Probably related to https://github.com/toggl/toggl-button/issues/1339

**Comment by shantanuraj** [comment]
Support Cases from #1339 

- https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/21192008290
- https://app.intercom.io/a/apps/ayixs927/conversations/21189600004
- https://app.intercom.io/a/apps/ayixs927/conversations/21192008290
- https://app.intercom.io/a/apps/ayixs927/conversations/21192097547
- https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2146384/conversations/21190415444
- https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2146384/conversations/21189406981
- https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2146384/conversations/21192340379
- https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/21190351885
- https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2146384/conversations/21190899646

**Comment by nicktoggl** [comment]
Still getting some reports of the problem persisting after the update, 

Twitter ref 1108339093606404096

"The issue persists, also with 1.23.3. And "Stop automatically at the end of the day" is disabled."

**Comment by tcrammond** [comment]
We're monitoring at this stage. @nicktoggl please keep us updated if consistent reports come in.

**Comment by vweevers** [comment]
> "The issue persists, also with 1.23.3. And "Stop automatically at the end of the day" is disabled."

That was me (didn't know Toggl was on GitHub). I avoided using Toggl Button in the past few days but will try again and update here if I have further issues. Thanks!

**Comment by vweevers** [comment]
Just happened again. The "Time is up! Take a break" notification popped up at the same time so the Pomodoro Timer might be the culprit. Disabled it to see if the bug happens without. I'm on version 1.24.1 in Chrome 72.0.3626.121.

**Comment by shantanuraj** [comment]
Hey @vweevers 

I just verified the extension (1.24.1) it seems to work fine.

Are your time entries still getting stopped with the "Stop tracking..." disabled under Pomdoro settings

![image](https://user-images.githubusercontent.com/1716853/55072499-4a731400-50b1-11e9-856e-71964eb808d4.png)

If you have Pomodoro mode enabled and "Stop tracking..." disabled, you'll get the
"Time is up! Take a break" notification but the time-entry should not stop.

**Comment by vweevers** [comment]
@shantanuraj Oh that makes sense! Was this "Stop tracking..." feature recently introduced? If so, the default should probably be false? Because I didn't change any setting before the "bug" (which I now realize is a feature) started happening.

Testing now with these recommended settings.

**Comment by shantanuraj** [comment]
@vweevers yeah `true` doesn't seem to be the right default but it's been this way for quite a while

https://github.com/toggl/toggl-button/blob/6db940d439e5074e07eb473aed529ba9f65b58da/src/scripts/lib/db.js#L21

It might have been a side-effect of a recent settings revamp we did.

I'll discuss it with the team to switch the default
Thanks for pointing it out 🙇

**Comment by shantanuraj** [comment]
On discussing it with the team, we've decided to keep the default for now,
and change it if we get more complaints on our support channel.

Closing this for now
