### ISSUE TITLE
Settings are not saved

### ISSUE THREAD

**Issue by FeBe95** [toggl/toggl-button#1353]
* **OS version**: Windows 10 (1809)
* **Browser version**: Firefox 66.0
* **Extension version**: 1.23.3

### 🐛 Describe the bug
Settings are reset every time the browser is restarted 

### Expected behaviour
Settings like `idle detection` are persistent

### Steps to reproduce
- login in the extension popup
- open the new standalone settings page by clicking the settings icon or via the add-ons page
- change something
- optionally wait some time, refresh the page, do some stoff
- quit Firefox
- re-open Firefox
- open settings page again
- many settings are restored to its default values

### Other details or context
- happening since the last update, works fine in 1.22.2 (previous version, installed from mozilla.org)

**Comment by nicktoggl** [comment]
ref - 21290798500

**Comment by tcrammond** [comment]
Thanks for reporting this. A fix is in the works.

**Comment by tcrammond** [comment]
`1.23.4` has been published and should arrive in your browser in the next few hours. Thanks for your patience.
