### ISSUE TITLE
Button Disappeared from Freshdesk Mint

### ISSUE THREAD

**Issue by jpklwr** [toggl/toggl-button#1356]
* **OS version**: MacOS 10.14.2 (18C54)
* **Browser version**: Chrome Version 73.0.3683.75 (Official Build) (64-bit)
* **Extension version**: Version (1.23.3)

#### Relevant integration (if any):

Freshdesk Mint (freshdesk.com)

### 🐛 Describe the bug

The toggl button is no longer appearing in the ticket toolbar.

### Expected behaviour

The toggl button would appear in the toolbar next to the other buttons.

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to freshdesk
2. View a ticket page
3. Note that the button is missing

### Other details or context

This most recently occurred due to some layout changes by Freshdesk on 2/14/19. #1304

**Comment by tcrammond** [comment]
Hello @jpklwr , we're not seeing any problems in Freshdesk Mint on our side at the moment. We fixed the referenced issue some time ago. 

First of all, please can you double check that `freshdesk.com` is ticked in the "Permissions" section of the extension's settings?

Let me know if your ticket page looks different to mine. Do you have a ticket number being shown?

![Screen Shot 2019-03-21 at 15 49 06](https://user-images.githubusercontent.com/6432028/54765402-5b271400-4bf1-11e9-9ace-4afdd3ba0b01.png)

**Comment by jpklwr** [comment]
Hello @tcrammond - so the button had disappeared but it turns out that the issue was just that the extension lost my preferences for custom domains. I readded the custom domain that we use with freshdesk and it is working again. Thank you!!
