### ISSUE TITLE
Unable to dismiss the "Welcome to Toggl Button!" popup in settings

### ISSUE THREAD

**Issue by devsuitup** [toggl/toggl-button#1357]
Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

### Environment details

* Browser : Firefox 65.0.2 (64 bits)
* Operation system: Windows 10
* Extension version: 1.23.4

### Expected behavior
Being able to dismiss the popup to access settings

### Actual behavior
The popup doesn't close.

### Steps to reproduce the behavior
New installation in Firefox, then going to settings

### Additional details
In the browser console :
TypeError: NetworkError when attempting to fetch resource.
URL de la ressource : moz-extension://4b89327d-5531-4826-8157-9e32d28ef34d/scripts/settings.js
URL du lien source : settings.js.map[En savoir plus]

* screenshots or screencapture
![image](https://user-images.githubusercontent.com/2380987/54820225-af3c0200-4c9e-11e9-839c-e5cdbdd73c1f.png)

**Comment by flexchar** [comment]
Same on Firefox 67 on Win 10 / macOS Mojave

**Comment by tcrammond** [comment]
This issue should be resolved in versions `1.24.0` onwards. Sorry for the inconvenience, please let us know if anything else comes up with the settings.
