### ISSUE TITLE
Toggl Button missing in all integrations

### ISSUE THREAD

**Issue by HenriqueBaron** [toggl/toggl-button#1360]
* Windows 10 Pro v10.0.17763: 
* Google Chrome v73.0.3683.86 : 
* Toggl Button v1.24.0 : 

### 🐛 Describe the bug

The Toggl Button does not show up in any integration anymore. I have the following integrations enabled:
* atlassian.com
* atlassian.net
* bitrix24.com
* bitbucket.org
* github.com
* trello.com

I looked up in all of these sites, and the "Start Timer" button is missing (as shown for example in the screenshots from BitBucket and Trello).

### Expected behaviour

I expected the Start/Stop Button to show up in these pages, as shown in the attached screenshots.

### Other details or context

I have already tried removing and reinstalling the extension, clearing the cache and browsing data, and also uninstalling and reinstalling Chrome. None of them made any difference.

![Captura 1](https://user-images.githubusercontent.com/37144857/54920226-7b9cea00-4ee1-11e9-8a53-cae1aff24e28.png)
![Captura 2](https://user-images.githubusercontent.com/37144857/54920227-7cce1700-4ee1-11e9-87e1-b17e06ba8cbf.png)

**Comment by teusch** [comment]
same issue : trello in chrome and firefox 
And freshdesk

**Comment by Airgunster** [comment]
+1, I confirm that Todoist integration is also affected.

**Comment by tcrammond** [comment]
Thank you for reporting this, we're on the case. Thanks for your patience in the meantime.

**Comment by shxfee** [comment]
Damn i just started using toggl. missing it dearly on todoist.

**Comment by tcrammond** [comment]
Version `1.24.1` has been published and should arrive in your browsers soon. Thanks again for your patience while this was resolved.

**Comment by HBaronAuttom** [comment]
Yay, just updated and it's working! Thanks for the lightspeed support. 😄

**Comment by teusch** [comment]
Yes it is working. In Trello and Freshdesk.
Thanx !!
