### ISSUE TITLE
Toggl Timer Stops When List is Closed

### ISSUE THREAD

**Issue by DerekBoothSEO** [toggl/toggl-button#1368]
* **Win10 Pro**: 
* **Version 73.0.3683.86 (Official Build) (64-bit)**: 
* **Toggl Version 1.26.0**: 

#### Relevant integration (if any):
https://trello.com
Toggl Chrome Integration

### 🐛 Describe the bug

When I open a list in Trello my Toggl integration is there as expected. I start the timer and choose the project.

If I now close the list to actually do the work the timer stops. I have to keep the list item open to keep the timer running.

### Expected behaviour

I expect the toggl timer to keep running until I select stop regardless of the state of the list which instigated the timer.

### Steps to reproduce

Create board on Trello, integrate toogl timer into Chrome browser.
add card and list to a board
open list item to see task at hand
start timer from within list
close list
timer now stops

### Other details or context

manual use of toggl timer from desktop app

**Comment by shantanuraj** [comment]
Hi Derek

I cannot seem to reproduce the problem
https://streamja.com/1emr

- Do you have any other extensions installed that might be interacting with the page
- Do you have any of the stop timer automatically preferences enabled?
  #### General
  ![image](https://user-images.githubusercontent.com/1716853/55479131-01840800-563b-11e9-97c2-76040e1c3264.png)
  #### Pomodoro
  ![image](https://user-images.githubusercontent.com/1716853/55479135-05178f00-563b-11e9-8f37-66cec3b4b53e.png)

Can you try to reproduce the error on a different chrome profile this will help us rule out other extensions interfering with toggl-button

- Add a new profile

  ![image](https://user-images.githubusercontent.com/1716853/55478379-3727f180-5639-11e9-95e9-fb60b85733ec.png)
  ![image](https://user-images.githubusercontent.com/1716853/55478473-6b9bad80-5639-11e9-883c-c3cd18abef7e.png)

- Sign in to [toggl.com](https://toggl.com/login/)
- Install https://chrome.google.com/webstore/detail/toggl-button-productivity/oejgccbfbmkkpaidnkphaiaecficdnfn?hl=en
- Enable Trello integration
- Try to reproduce the bug you faced

**Comment by dooart** [comment]
closing for lack of response
