### ISSUE TITLE
Show project for currently running task

### ISSUE THREAD

**Issue by ckrf** [toggl/toggl-button#1370]
### Describe the new feature

In a previous version of the Toggl Button, the project for the currently running task was visible when you clicked on the Toggl Button. Now only the task description is shown. I would like to see the project name when I click on the Toggl Button. 

### How does this help you?

I have some projects that don't have tasks associated with them: I just go to Project "Email" or project "Meals". With the current version, I only see "(no description)" when one of these logs is running. 

### If we couldn't add this feature, is there a compromise you can think of?

No, sorry

**Comment by tcrammond** [comment]
Thanks for pointing this out. We'll make it happen 👍
