### ISSUE TITLE
Timer not affected by closing or opening the browser

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggl-button#1375]
* **OS version**: MacOS Mojave
* **Browser version**: Firefox 66.0.2
* **Extension version**: 1.26

### 🐛 Describe the bug

The `Start timer automatically` and `Stop timer automatically` features don't appear to work. Starting or closing the browser doesn't do anything to the timer. I tested in Firefox, but I have a user saying the features aren't working in Chrome either. 
 
### Expected behaviour

The timer should start or stop depending on what you're doing with the browser. 

### Steps to reproduce

1. Enable both relevant options.
2. Start the timer and quit the browser. 
3. Was the timer stopped?

### Other details or context

[Intercom case
](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/21329215466)

**Comment by shantanuraj** [comment]
I should have the fix ready before EOD
