### ISSUE TITLE
Long Description Pushes Stop Button and Duration Out Of View

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggl-button#1381]
### 🐛 Describe the bug

Pretty much what the title says: place a very long description into the TogglButton and the stop button and running duration disappear. 

### Expected behaviour

Regardless of length of description, stop button and running duration should always be present. 

### Steps to reproduce

1. Start a time entry in the button. 
2. Place a very long description into the description area 
3. Issue becomes present.

### Other details or context

User is experiencing this issue: [case link
](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/21630152706)

Screenshot video of issue using test account: https://drive.google.com/open?id=1Ant8pEqPDrHZ1hMRYUEmCcrsEXQF0h6_ (can only be accessed while signed into Google/Toggl account)

**Comment by francescarpi** [comment]
Hi,

I've the same. I attach another capture.

![image](https://user-images.githubusercontent.com/287872/56198071-704d6200-603a-11e9-84fc-2d2d42499caf.png)

Thanks!
