### ISSUE TITLE
Jira Kanban Board Issue

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1408]
* **OS version**: Windows 10
* **Browser version**: 74.0.3729.131
* **Extension version**: TogglButton/1.35.0-jira2018

#### Relevant integration (if any):

Jira: https://....atlassian.net (their URL is visible in the recording they sent over, it's in the [**intercom](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22023298488) convo**.

### 🐛 Describe the bug

When they open up a Kanban board card the Toggl Button shows up only for a moment and goes away after the full content of additional info on the right side is loaded, you'll see that on the video they sent over. 

### Expected behaviour

The Toggl Button should not go away. 

### Steps to reproduce

Was not able to reproduce this with our Jira test account, actually, even with the Jira integration enabled I was not able to see the button at all.

**Comment by tcrammond** [comment]
Hey @VeljkoTN just FYI, you may have had trouble seeing the button at all as the permissions are not clear for Jira at the moment. You have to enable `Atlassian - atlassian.net`. Will include better naming in the PR for this issue

**Comment by VeljkoTN** [comment]
Makes sense, thanks @tcrammond
