### ISSUE TITLE
Timer value is hard to change

### ISSUE THREAD

**Issue by edlongman** [toggl/toggl-button#1417]
* **OS version**: 
* **Browser version**: Chrome 66
* **Extension version**: 1.35.4

### The Timer value is hard to edit in the popup. E.g. For when starting a timer late and chainging it to a larger value.

When the user clicks on the task duration field `name="toggl-button-duration"` The cursor momentarily flashes in the position where clicked then it goes to the end of the field. This is due to the updating field when the timer is running. As soon as a char is typed at the end of the field the timer stops and then it is not a problem.
### Expected behaviour
Cursor remains in position where clicked allowing the user to backspace or type etc.
As soon as a user modification is detected then the timer stops.

### Steps to reproduce
1. Start a timer. 
2. Click to edit in the popup
3. Click in the middle of the timer value to edit

**Comment by vedr4n** [comment]
Another user reported the same issue. #22843408813

**Comment by rhys-vdw** [comment]
Can I make a PR on this or this just for looking at?

**Comment by rhys-vdw** [comment]
> As soon as a char is typed at the end of the field the timer stops and then it is not a problem.

This is not the experience I'm having.

**Comment by vedr4n** [comment]
We are fine either way. If you have the know-how and feel like creating a PR - go for it. However, you are definitely not expected to do so.
