### ISSUE TITLE
Selecting projects after scrolling does not work

### ISSUE THREAD

**Issue by lise-toggl** [toggl/toggl-button#1418]
* **OS version**: Windows 10
* **Browser version**: Chrome 74
* **Extension version**: 1.35.4

#### Relevant integration (if any):

N/A

### 🐛 Describe the bug

When changing projects, scrolling down and clicking a project makes the list pop up to the top again, and doesn't select the project

![scroll](https://user-images.githubusercontent.com/50156618/57890861-a0c42e00-787c-11e9-9c37-3e4a5f26d004.gif)

### Expected behaviour

Scrolling and clicking a project should select the project.

### Steps to reproduce

1. Start a new time entry
2. Click on it to edit the entry
3. Click on the projects dropdown to open it
4. Scroll down the projects dropdown
5. Click a project

### Other details or context

([case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/21629883186)) - Chrome on Arch Linux

**Comment by ricotheque** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22059011407) - On Linux Mint/Ubuntu + Firefox

(However, was able to reproduce on my Windows 10 + Chrome machine as well)

**Comment by ricotheque** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22058428967) - Windows 10 + Chrome

**Comment by chrisaligent** [comment]
Experiencing this on Centos7 + Chrome too, extension version 1.35.4 using the Atlassian/Jira integration.

**Comment by nidarasheed** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22075382445)
