### ISSUE TITLE
Tag dropdown and then Project dropdown will not stay open in Extensions

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/toggl-button#1422]
* **OS version**: 10.14.4
* **Browser version**: Firefox 66.0.5
* **Extension version**: 1.35.6

#### Relevant integration (if any): Teamweek and Bitrise
https://app.teamweek.com/

### 🐛 Describe the bug
Press the Toggl integration button within an app
Click the Tag drop down
(It should immediately close itself again)
After doing this several times it began happening to the Projects drop down as well.
### Expected behaviour
To be able to select a tag or project
### Steps to reproduce
Listed above

### Other details or context
Conversation 21957864690
I reproduced this as well as the user and there's a GIF in the conversation if you're unable to reproduce.

**Comment by lise-toggl** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3155115/conversations/22988136255)

gif showing how you can reproduce the issue:
![ezgif com-gif-maker](https://user-images.githubusercontent.com/50156618/61944860-03a31580-afe2-11e9-9c5e-e1b52949395b.gif)

**Comment by DustinWoods** [comment]
This has been happening to for a while too. I'm using Firefox 69.0. It happens on Github and Asana pages, as well as the extension pop up. Happens more often than not.

**Comment by DustinWoods** [comment]
![Peek 2019-09-18 10-52](https://user-images.githubusercontent.com/5541776/65172895-a5ebe200-da02-11e9-89a4-17e4b63f3cd4.gif)

**Workaround**: It seems if you right-click the tag drop down (or the project list dropdown) that the menu will stay open on the subsequent left click. See gif.

**Comment by dooart** [comment]
there's a big chance this will be fixed by https://github.com/toggl/toggl-button/pull/1504

**Comment by dooart** [comment]
nevermind, just tested it and the problem still happens. will schedule for next backlog cycle

**Comment by DustinWoods** [comment]
@dooart Thank you! This one is a big deal for me.

**Comment by DustinWoods** [comment]
I'd be happy to help troubleshoot this issue or gather more info if needed.

**Comment by VeljkoTN** [comment]
conversations/23731381826 - video reproducing the issue included in one of the messages

**Comment by DustinWoods** [comment]
Thank you!!! I'll report back here after I update the extension in my browser.

**Comment by dooart** [comment]
Hey @DustinWoods! Just wanted to let you know it'll take a couple days until we roll out this version to all users. If you want early access to the fix, you can try installing it locally from the release files.

**Comment by DustinWoods** [comment]
@dooart I hate to be _that guy_, but I think there might still be an issue. I'm updated to 1.42.1 in Firefox.

 - The issue looks fixed with the Toggl toolbar dialog box (whatever it's called) - (HUGE improvement already with this)
 - But the issue still seems present with dialog box that is embedded on pages.

I was able to reproduce the issue on Github, for example:
![Peek 2019-10-02 19-27](https://user-images.githubusercontent.com/5541776/66095003-d4ada080-e54a-11e9-9e71-15acf7e35e28.gif)

I also tested this in Chrome (same updated version), but no issue. So to summarize: I can produce the issue on **Firefox 69.0.1** with Toggl extension ver **1.42.1**, but **only with the on-page Toggl dialog**.

**Comment by dooart** [comment]
Thank you @DustinWoods! We'll look into this again.

**Comment by lise-toggl** [comment]
[User report - Trello (with recording)](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24018982792)

**Comment by DustinWoods** [comment]
Confirmed! I am no longer seeing this issue. Thanks Toggl team!
