### ISSUE TITLE
Basecamp: Improve broken layout

### ISSUE THREAD

**Issue by tcrammond** [toggl/toggl-button#1426]
### Describe the changes you'd like

The Basecamp integration is looking a little worse for wear, the UI has probably changed a bunch since the last update to this integration.

Let's fix it up and make it pleasant to use again. Also check if the buttons are displayed in all the pages relevant to tasks.

### Relevant links or screenshots

![Screen Shot 2019-05-22 at 12 25 53](https://user-images.githubusercontent.com/6432028/58170945-b70f2700-7c8c-11e9-8474-68f1273f416b.png)

![Screen Shot 2019-05-22 at 12 22 43](https://user-images.githubusercontent.com/6432028/58170764-42d48380-7c8c-11e9-9e2e-2a61149fd936.png)

#### Additional context

in particular, "Lists" of tasks should use `minimal` button type, and follow the [guidelines](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md#toggl-button-style-guide)

**Comment by dooart** [comment]
ℹ️ this is basecamp 3 btw
