### ISSUE TITLE
Notion Integration Isn't appearing.

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/toggl-button#1454]
* **OS version**:  MacOS 10.14.5
* **Browser version**: 75.0.3770.100
* **Extension version**: 1.37.4

#### Relevant integration (if any):Notion

www.notion.so

### 🐛 Describe the bug
The Toggl button integration isn't appearing within Notion

Some other users have also mentioned it [here](https://github.com/toggl/toggl-button/issues/896) and [here](https://github.com/toggl/toggl-button/pull/1203) also in this [case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/22009910172)

### Expected behaviour

The Toggl button won't appear in Notion

### Steps to reproduce
A Togglr opens Notion and looks for the Toggl button.
They scream for it is not here and thus they cannot Toggl.

**Comment by lise-toggl** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22967004212)

**Comment by zdericnina** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/23085282853)

**Comment by karlhorky** [comment]
As I mentioned in https://github.com/toggl/toggl-button/pull/1203#issuecomment-499456043, this may be a result of a changed DOM structure:

> Haven't taken the time to look as to why this is yet, but it could be that Notion changed their DOM structure, which was somewhat precarious (see the selectors here 😱: https://github.com/toggl/toggl-button/pull/1203/files#diff-488208c474f920402f55f0f58320950cR4).

**Comment by TheSoloJake** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/23378522257)

**Comment by ivillacreative** [comment]
I think I have a fix for this.. the only problem is I can't commit because of some git command error. 
-__-

<img width="435" alt="Screen Shot 2019-09-01 at 1 25 45 AM" src="https://user-images.githubusercontent.com/9972541/64073822-11d6f800-cc58-11e9-885e-ee12792f43cc.png">

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/23769290672)

**Comment by zdericnina** [comment]
[user report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/24058314611)

**Comment by VeljkoTN** [comment]
[user report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24629045099)

**Comment by dianetoggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/24741851064)

**Comment by tcrammond** [comment]
Toggl Button in Notion has been restored in the "pop up views", such as when opening a card:

![Screenshot 2019-12-10 at 10 54 12](https://user-images.githubusercontent.com/6432028/70523649-6af9d600-1b3b-11ea-8cb2-5689bb0cf689.png)
