### ISSUE TITLE
Toggl button no longer showing in Asana

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/toggl-button#1456]
OS version: macOS Mojave 10.14.5
Browser version: Version 75.0.3770.100
Extension version: 1.39.1
Relevant integration (if any):
🐛 Describe the bug
Asana changed the layout of its task popup which caused Toggl button not to show up anymore

Expected behaviour
Toggl button should be visible in Asana

Steps to reproduce

Go to Asana (enable it from Integrations in Toggl button settings)
Click on any Task
No Toggl button in the task popup

**Comment by ApocalypticFish** [comment]
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2144650/conversations/22900286640)

**Comment by shantanuraj** [comment]
> Teamweek changed the layout of its task popup which caused Toggl button not to show up anymore

Is this supposed to be

> Asana changed the layout of its task popup which caused Toggl button not to show up anymore

**Comment by ApocalypticFish** [comment]
Just updated it.

**Comment by ApocalypticFish** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22920505067)

**Comment by nidarasheed** [comment]
Closing this. I've checked cases, and they are related to this bug here: https://github.com/toggl/toggl-button/issues/1457
I've linked the cases to the correct issue now.
