### ISSUE TITLE
Toggl button not picking up project from Asana

### ISSUE THREAD

**Issue by nidarasheed** [toggl/toggl-button#1457]
* **OS version**: Windows 10 (users) and I've reproduced this on MacOS 10.14.5
* **Browser version**: Chrome 
* **Extension version**: Version 1.39.1

#### Relevant integration (if any):
Asana

### 🐛 Describe the bug
When you start the timer from an Asana task, it should pick up the project name. This only seems to work once after a hard-refresh, but stops working after that. You can hard-refresh the browser, and it will start working again, but only once. 

### Expected behaviour

I would expect the project to be populated each time. 

### Steps to reproduce
Video sent to Shantanu. Steps are: 

- Make sure you have matching projects in Toggl and Asana
- Open Asana, hard-refresh browser
- Go to Project > Task
- Click the Toggl button in the task (it will show the correct project) 
- Stop the Toggl button 
- Change task
- Click Toggl button (now it will not show Project) 
- Hard-refresh browser
- Click the Toggl button (project name will be populated). 

### Other details or context
Linked Cases: 
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/22900286640)
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/22920505067)
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/22895751079)
[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/22903768870)

**Comment by nidarasheed** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/22877805229)

**Comment by Lars-** [comment]
It still doesn't work... If I click the "Start timer" button in Asana, it just adds no project at all. Also the case for my colleagues.

**Comment by zdericnina** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/22996036800)

**Comment by Lars-** [comment]
case? I don't have access to that, please just reply...

**Comment by TheSoloJake** [comment]
@Lars- Sorry about that; "case" is for Toggl's internal use. 

As for your issue, we're actively looking into the issue, and hope to have better news soon
