### ISSUE TITLE
Toggl Button disappears on Todoist when switching projects

### ISSUE THREAD

**Issue by nidarasheed** [toggl/toggl-button#1462]
* **OS version**: Reproduced on Windows and MacOS
* **Browser version**: Chrome Version 75.0.3770.142 
* **Extension version**: Version 1.39.1

#### Relevant integration (if any):

Todoist. (https://todoist.com/)

### 🐛 Describe the bug
A Toggl Button shows next to each Todoist task when you hover at the end of the task title. However, the button stops showing in Todoist (in Dark Theme) after you switch projects. It will reappear if you refresh browser. 

![image](https://user-images.githubusercontent.com/49634673/61940684-63cc9400-afaf-11e9-9390-9ca8495f2f6f.png)

### Expected behaviour

The button should show every time you hover at the end of the task title. 

### Steps to reproduce

First switch your Todoist webapp theme to Dark. 

Steps to reproduce the behaviour:
1. Log into Todoist
2. Open a project
3. Hover over the end of task title (button will appear) 
4. Repeat this with one more project
5. Open the third project
6. Hover over the end of the task title (no button will appear) 
7. Refresh page to fix issue. 

### Other details or context

[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/22984503308)

**Comment by VeljkoTN** [comment]
Just adding to this that this is not related to dark mode only, the issue is there without dark mode as well. It was reported on the Toggl Button Chrome listing and we tested with normal (non-dark) mode.
