### ISSUE TITLE
[Build] Local dev server is losing the manifest after changes

### ISSUE THREAD

**Issue by tcrammond** [toggl/toggl-button#1468]
After making changes while running the local dev server the manifest files are lost from the `dist/` folders.

This means the extension cannot be reloaded and you have to a) restart the whole dev server, b) enable all integrations you're working on again.

Probably introduced with #1433.

**Comment by dooart** [comment]
tagging as `high` because i was told "work/maintenance on toggl button is severely hindered by this build problem"

**Comment by shantanuraj** [comment]
To anyone who reads (probably me after the conference)
bisecting with a script that touches any of the files would probably help narrow the problem down
I am certain it is related to some upgrade/change in the webpack config

**Comment by langri-sha** [comment]
Seems to work fine for me. I added some changes to the manifest to make sure they're added :thinking:.

Did notice `package-lock.json` changing after running `npm install`, though.

**Comment by shantanuraj** [comment]
Yeah I think you need to change the content scripts, but randomly after emiting the new content scripts the manifest is deleted.

**Comment by rylek90** [comment]
It also cleans all image assets 🤷‍♂
