### ISSUE TITLE
Azure Devops: Clean up integrations

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1475]
* **OS version**: Windows 10
* **Browser version**: 70.0.3538.77
* **Extension version**: TogglButton/1.40.1
--

#### Relevant integration (if any):

Azure Devops

### 🐛 Describe the bug

> The Toggl-button used to stand next to the task name. However, recently this has been changed to be hidden in a menu. Next to that, it takes a lot more time now for the dialog to start up and to actually start the timer. In general, it takes about double the time start a toggl-timer than before. 

### Expected behaviour

Toggl button should show up next to the task name and the dialog shouldn't be slow

**Comment by VeljkoTN** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/23186481657)

**Comment by BluePhoenix91** [comment]
To clarify the issue, the button is now in the list, in organge, while it used to be positioned in the green square. Which was much more user friendly. Also clicking on it now gives a different pop-up then it used to give. This new pop-up  seems to work much slower.

![image](https://user-images.githubusercontent.com/39919833/63152912-4b2f2700-c00d-11e9-94ad-15f8c5f210bb.png)

**Comment by BluePhoenix91** [comment]
The issue was solved by activitating the right integration (I'm guessing azure.com). I'm guessing it was deactivated or changed as Azure Devops changed URL.

![image](https://user-images.githubusercontent.com/39919833/63279614-96fdfc80-c2a9-11e9-9c21-036a9a39d66a.png)

**Comment by dooart** [comment]
This was actually fixed in in https://github.com/toggl/toggl-button/commit/8841ddfb46157386c754bc8bbafd9f2e89932904#diff-410acca4c20921ff47d45874b81e621ab8d4b53d434719c9e4656f043eb36369
