### ISSUE TITLE
Worksection Integration Stopped Working

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggl-button#1496]
#### Relevant integration (if any):

Worksection (worksection.com) 

### 🐛 Describe the bug

Integration no longer appears in Worksection UI 

### Other details or context

[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/23505456658)

**Comment by ApocalypticFish** [comment]
[case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2144650/conversations/23822092727)

**Comment by VeljkoTN** [comment]
[case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097020/conversations/24770037914)

From the screenshot shared with the user it appears that the layout is changed and that's probably why the integration is not working
