### ISSUE TITLE
Toggl Button popup inside Trello goes outside of screen

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1498]
* **OS version**: Windows 7
* **Browser version**: Chrome 76.0.3809.132
* **Extension version**: 1.40.7

###⛑️ User Support
A user reported that when they click on the Toggl Button icon inside a Trello card, the popup shows up and goes outside of the screen towards the bottom:

![image](https://user-images.githubusercontent.com/36152180/64428427-fafb3000-d0b3-11e9-9380-79f6376ab16d.png)

###About the user
User ID: 2990659
Workspace ID: 3557085
Workspace plan: Free
[Link to Case 🔗
](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/23553469844)

###Expected behavior
The popup should open up upwards to avoid going out of the screen, as it does in Firefox:
![image](https://user-images.githubusercontent.com/36152180/64428472-12d2b400-d0b4-11e9-8da8-16f8a8177cc7.png)

###To Reproduce
Was not able to reproduce, I'll be creating an issue for what I'm getting: #1499

**Comment by vedr4n** [comment]
User mentioned it only happens on small screens.

**Comment by Dan2D** [comment]
I'll take a shot at this if it's still available.

**Comment by lise-toggl** [comment]
I've reproduced something similar in Chrome but not sure if it's the same issue:

1. Open Trello in a fairly long (~700px+) window
2. Resize the window to some thing quite short
3. Open a card
4. Scroll down until you can just see the "Start a timer" link
5. Click the link
6. The popup is partially hidden

Will work on a fix for this :point_up:
