### ISSUE TITLE
Toggl Button popup not showing inside a trello card

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1499]
* **OS version**: Windows 10
* **Browser version**: 76.0.3809.132
* **Extension version**: Version 1.40.7

#### Relevant integration (if any):

Regular Trello integration

### 🐛 Describe the bug

I have the button inside trello but when I click on it it just starts a timer, no popup:

![Toggl Button trello](https://user-images.githubusercontent.com/36152180/64429043-714c6200-d0b5-11e9-82cd-8f8b5751518c.gif)

### Expected behaviour

A popup allowing me to change the time entry description should show

**Comment by jbutz** [comment]
I was unable to replicate this issue. I tried in both Firefox and Chrome with the versions currently in their respective web stores.

**Comment by Whizkevina** [comment]
Can I work on it.

**Comment by lise-toggl** [comment]
Hey @Whizkevina, you're most welcome to work on this if it's still an issue! :)

@VeljkoTN can you let us know if you're still experiencing this? I tried to reproduce it as well but wasn't able to.

**Comment by tcrammond** [comment]
Not known to be an issue in the current version. Please re-open if it comes up again.
