### ISSUE TITLE
TickTick integration issue

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1514]
* **OS version**: Windows 10
* **Browser version**: Chrome 77.0.3865.90
* **Extension version**: 1.40.7

### 🐛 Describe the bug

The Toggl Button is no longer visible on TickTick's site

### Expected behaviour

Should be visible like so (outdated image in regards to TickTick but the placement should be the same): 

![image](https://user-images.githubusercontent.com/36152180/65878832-404b0e80-e38f-11e9-945d-436c6a01bad9.png)

[Intercom case link: 🔗 ](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/23888761954)

**Comment by lise-toggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/23899723518)

**Comment by mwcarew** [comment]
Exact same issue on latest version of Chrome on Windows 10.

**Comment by TheSoloJake** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/24008786550)

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24022133255)

**Comment by TheSoloJake** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24261499512)

**Comment by Airgunster** [comment]
+1, is there any ETA for this to be fixed? _This is really painful :/_

**Comment by VeljkoTN** [comment]
Another user [reached out](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24475510903).

**Comment by shantanuraj** [comment]
@VeljkoTN 
We have a PR now it should be merged first thing in the morning.

**Comment by TheSoloJake** [comment]
@Airgunster Just wanted to ping you here in-issue to make sure you saw that the integration has been fixed!
