### ISSUE TITLE
Support new Todoist Web Interface

### ISSUE THREAD

**Issue by vicampuzano** [toggl/toggl-button#1521]
Hello!

Please, take a look at https://beta.todoist.com . New web interface is coming and Toggl Extensions break in the "task subject" recognition. 

When I try to start the timer, everything works fine but the task subject was not recognized.

Thanks! :)

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24087278732)

**Comment by TheSoloJake** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24061146127)

**Comment by opennomad** [comment]
It's no longer just beta. The new UI is now live.

**Comment by Michelle112** [comment]
[User report.](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24215657314)

**Comment by shantanuraj** [comment]
Has PR at #1526 if someone wants to review
