### ISSUE TITLE
Timer does not sync with webapp until extension is opened

### ISSUE THREAD

**Issue by nidarasheed** [toggl/toggl-button#1527]
* **OS version**: Catalina 10.15
* **Browser version**: Version 77.0.3865.120 (Official Build) (64-bit)
* **Extension version**: Version 1.42.1

#### Relevant integration (if any):
N/A
### 🐛 Describe the bug
Toggl Button doesn’t sync with the webapp timer until you open the extension. 

For example, I have had the webapp tracking time all day, but the chrome extension was still grey. I clicked on it, and when it opened the time entry I was currently running showed up.

### Expected behaviour

I would expect the extension to immediately pick up the running timer info, regardless of being opened or not. 

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to webapp 
2. Start a timer
3. Don't open the extension. It will stay grey
4. Open extension, it will pick the timer up. 

### Other details or context
More details [here](https://toggl.slack.com/archives/C9LMUPD9T/p1571656308164300).

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24189741146)

**Comment by dianetoggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/24160785921)

**Comment by nidarasheed** [comment]
[User Report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24341578312)

**Comment by tcrammond** [comment]
Technical notes:

not 100% sure on any of this yet.

I think background scripts are no kept loaded as much of the time, and we don't have a case to set it to be persistent.

We'll need to poll, inside `chrome.runtime.alarm` calls, to see if anything is running (and for how long), rather than using websocket for that (which is what I'm currently assuming we do).

**Comment by tcrammond** [comment]
Hopefully will be much improved by #1556, currently going through incremental release. Keeping issue open to track things.

**Comment by tcrammond** [comment]
This is **significantly** improved (fixed?) in the latest versions.

I don't think we need to keep this open anymore, so let's close it and make new issues for any specific problems that come up in future 🎉 .
