### ISSUE TITLE
Text in search boxes not visible in Todoist dark theme (and possibily other integrations as well)

### ISSUE THREAD

**Issue by dooart** [toggl/toggl-button#1531]
### 🐛 Describe the bug

When searching for projects and tags, the text is not visible inside the text input:
<img width="366" alt="Screen Shot 2019-10-23 at 07 57 04" src="https://user-images.githubusercontent.com/371426/67516421-88acd200-f698-11e9-8c00-d3d6a3820fdf.png">

<img width="365" alt="Screen Shot 2019-10-23 at 07 57 11" src="https://user-images.githubusercontent.com/371426/67516426-8a769580-f698-11e9-9110-959838ac89f8.png">

### Steps to reproduce

Steps to reproduce the behaviour:
1. Open Todoist
2. Click the Toggl Button inside the Todoist UI
3. Open the Projects (or Tags) popdown
4. Type something in the search box

**Comment by rpanczer** [comment]
Hi there, I can fix this one

**Comment by tcrammond** [comment]
Should be resolved in `1.44.5` 🚀
