### ISSUE TITLE
Toolbar window: Minimum height has gone missing

### ISSUE THREAD

**Issue by tcrammond** [toggl/toggl-button#1534]
### 🐛 Describe the bug

The toolbar window now looks like this with no recent entries:

<img width="478" alt="Screenshot 2019-10-28 at 11 04 17" src="https://user-images.githubusercontent.com/6432028/67673962-3529d500-f973-11e9-8246-dfcfbf8d0653.png">

### Expected behaviour

It should have some kind of height, it used to be `300px` or something like that, I think. A change to the way browser extensions work has probably broken it.

I believe this is usually set in the Manifest, but I can't quite remember. Maybe it was a minimum height in the content.

### Steps to reproduce

1. Install in Chrome
2. Log into account with no recent entries or few recent entries
3. See that the window is not very tall when you open it.

**Comment by alpha-bytes** [comment]
For me the edit form doesn't even appear after today's bug fix. I just see the top left toggl logo/text, and the three top-right icons (popout / refresh / settings). This is true even after clicking a "start timer" link.

**Comment by tcrammond** [comment]
@alpha-bytes Hmm, that doesn't sound great. I would recommend first trying a browser relaunch, or logging out and back in to the Toggl Button extension (you can log out via `Settings > My Account`)

**Comment by alpha-bytes** [comment]
Yeah I tried both of those, but still no edit frame.

**Comment by tcrammond** [comment]
@alpha-bytes Sorry for the slow response. Is everything OK now on version `1.45.0`?

**Comment by alpha-bytes** [comment]
Yes, it started working again, thank you!

**Comment by lise-toggl** [comment]
Is this what it's meant to look like? (Added 300px minimum height)
![image](https://user-images.githubusercontent.com/50156618/68727514-bd1d0980-0618-11ea-9946-69d3230966df.png)

**Comment by shantanuraj** [comment]
@lise-toggl I think the content view is still not taking the full height of the popup
It should load have the `See more on toggl.com` button as well
![image](https://user-images.githubusercontent.com/1716853/68730920-73bac300-05f4-11ea-9b35-9afcd1755a54.png)

**Comment by lise-toggl** [comment]
That message doesn't appear for me until the first time entry is made ([maybe because of this?](https://github.com/toggl/toggl-button/blob/master/src/scripts/popup.js#L210)). Should it always appear, or should we add another placeholder message like "Start tracking your time to see entries here"?

![image](https://user-images.githubusercontent.com/50156618/68731090-fc505800-0622-11ea-852b-dd97e41bd651.png)

![image](https://user-images.githubusercontent.com/50156618/68731117-1427dc00-0623-11ea-88ab-58de3400d11a.png)
