### ISSUE TITLE
Some tags don't show up in autocomplete popdown

### ISSUE THREAD

**Issue by shantanuraj** [toggl/toggl-button#1535]
* **OS version**: All
* **Browser version**: All
* **Extension version**: Latest

### 🐛 Describe the bug

- Some tags don't show up in the autocomplete popdown
- On doing some debugging I found if a user has the same tag-names across different workspaces
  one of them is overwritten
  ![image](https://user-images.githubusercontent.com/1716853/67734216-74652e00-fa26-11e9-86aa-fa939f30a53b.png)
- This happens because we have a `tagMap` object that **uses the tag-name as the key**

### Expected behaviour

- All tags from your workspace should show up in the tags autocomplete popdown

### Steps to reproduce

- Create two workspaces set first one as default
- Create a tag "test-tag" in both workspaces 
- In the autocomplete no tags should show up

### Other details or context

- Just drop the use of `tagMap` in favour of `tags`
- If that's not possible consider using the tag.id as keys

**Comment by lise-toggl** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/conversation/24211007253)
