### ISSUE TITLE
Unable to use toggl-button on my account

### ISSUE THREAD

**Issue by nopantsmonkey** [toggl/toggl-button#1538]
* **OS version**: 
mac-os mojave 10.14.6

* **Browser version**: 
Google Chrome 78.0.3904.70

* **Extension version**: 

### 🐛 Describe the bug
I have used toggl a couple of years back today when i installed toggl-button it showed me the login screen, i successfully logged in but then on clicking on the extension icon in chrome toolbar is showing me only the header.

### Expected behaviour
It should show the complete popup.
 

### Steps to reproduce

UserId: 2243527
email: aamir.shah.92@gmail.com

Steps to reproduce the behaviour:
1. Login with my account
2. Try to run toggl-button

### Other details or context

<img width="571" alt="Screenshot 2019-10-29 23 00 09" src="https://user-images.githubusercontent.com/1303176/67795874-c9458a80-faa0-11e9-84fe-d87fed230cc4.png">

<img width="816" alt="Screenshot 2019-10-29 23 00 37" src="https://user-images.githubusercontent.com/1303176/67795887-d2365c00-faa0-11e9-8bcd-76b7442dcc00.png">

**Comment by dooart** [comment]
already fixed by https://github.com/toggl/toggl-button/pull/1537
