### ISSUE TITLE
Toggl button Chrome pomodoro issues

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggl-button#1561]
* Windows 10 and Mac OS 
* awaiting more detail on Chrome version
* Chrome button 1.46.5

#### Relevant integration (if any):

Chrome button

### 🐛 Describe the bug

Two users have reported that the Pomodoro sound alert is extremely loud and distorted. One user has reported that they cannot change the volume from the settings.

In addition, the pomodoro timer seems to be triggering prematurely (case 1 has a 25 minute timer triggering after 15 minutes), the 2nd case was also distorting entry end times. 

### Expected behaviour

Pomodoro sound alert should be at a reasonable level and should trigger after the expected times

### Steps to reproduce

I've been unable to reproduce so far.

### Other details or context

[Case 1](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/24551384792)
"The alarm sound, although it sounds fine when I test it in the settings, is extremely loud and distorted when the alert goes off'
"alarm went off in 13 minutes, but recorded 25 minutes"

[Case 2](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/24533374721)

"it seemed to be about 10-15 minutes off. Like it would say it tracked until 9:08pm but it was only 8:55 or so in reality. And the timer keeps going off again after it's stopped and I'm taking a break."

**Comment by tcrammond** [comment]
🙉 Should be fixed in version `1.46.6`, from PR #1563.
