### ISSUE TITLE
[Phoenix] Add a clock view for running Pomodoro entry

### ISSUE THREAD

**Issue by shantanuraj** [toggl/toggl-button#1567]
- Make it optional
- Only render the current running entry in a circular countdown clock
- Add stop entry button

![image](https://user-images.githubusercontent.com/1716853/69024142-7f88f980-09e7-11ea-8e0d-47b34f6e0cb6.png)

**Comment by lise-toggl** [comment]
- use a svg circle with css animation for the outside ring ([quick test here](https://codepen.io/lise-toggl/pen/QWWYjEo?editors=1100))
