### ISSUE TITLE
Integration popup does not close when you click outside of it

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1585]
* **OS version**: Windows 10
* **Browser version**: Edge Chromium Beta (Basically Chrome) Version 79.0.309.25
* **Extension version**: Version 1.46.6

### 🐛 Describe the bug

If you start a timer and navigate away without closing the popup it stays visible: 

![Toggl Button popup issue Asana](https://user-images.githubusercontent.com/36152180/69226636-c1997300-0b80-11ea-9078-9bba639d8ee9.gif)

**Comment by tcrammond** [comment]
I think this is a global problem that we should handle
