### ISSUE TITLE
Asana: Button does not always pick up the project

### ISSUE THREAD

**Issue by tcrammond** [toggl/toggl-button#1591]
### 🐛 Describe the bug

The project is not being picked up in spreadsheet/list views.

### Other details or context

[Thread](https://toggl.slack.com/archives/C9LMUPD9T/p1574241938121100?thread_ts=1573221761.455200&cid=C9LMUPD9T)

**Comment by nidarasheed** [comment]
[Case Reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/534741/conversations/24661790414)

**Comment by tcrammond** [comment]
Should have been fixed in #1586  🎉
