### ISSUE TITLE
Integrations Popup ignores changes made to it

### ISSUE THREAD

**Issue by shantanuraj** [toggl/toggl-button#1596]
* **OS version**: All
* **Browser version**: All
* **Extension version**: 1.48.0+

#### Relevant integration (if any):

All

### 🐛 Describe the bug

- The popup in the embedded in pages ignores changes made on pressing `Done`

### Expected behaviour

- Changes should be persisted and sent to the API

### Steps to reproduce

Steps to reproduce the behaviour:
- Start any integrated timer
- Make some changes in the popup
- Changes aren't saved the next time you open the main popup or any other client

### Other details or context

- TBD

**Comment by VeljkoTN** [comment]
[case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24701988334)
