### ISSUE TITLE
Jira integration: cannot select project from modal view

### ISSUE THREAD

**Issue by mrjones2014** [toggl/toggl-button#1623]
* **OS version**: Windows 10
* **Browser version**: Chrome 79
* **Extension version**: Version 79.0.3945.79 (Official Build) (64-bit)

### 🐛 Describe the bug

the Project dropdown is no longer clickable when you click "Start Timer". Also the "Start Timer" button appears twice.

### Expected behaviour

There should only be 1 "Start Timer" button and the "Project" dropdown should be clickable.

### Steps to reproduce

1. Enable the Jira integration
2. Go to a board for a sprint
3. Open a Jira story modal view
4. Click "Start Timer" on the Jira story
5. Attempt to set the Project. It won't work.

### Other details or context

It _does_ work if you go to the full page for the Jira story, but not the modal view.

**Comment by lise-toggl** [comment]
@mrjones2014 thank you for the bug report!

We are working on a fix for the project dropdown at the moment. Could you confirm if both the project and tag dropdowns don't work for you, or just the project one?

Re the timer appearing twice, are you comfortable saving or taking a screenshot of the relevant DOM portion and sending it into our support team?

**Comment by mrjones2014** [comment]
@lise-toggl confirmed, the issue is for both dropdowns.

Here's some screenshots of the DOM with sensitive information censored.

![image](https://user-images.githubusercontent.com/8648891/71669404-8ae77880-2d3a-11ea-9f23-67cb63bc22c5.png)


![image](https://user-images.githubusercontent.com/8648891/71669468-c08c6180-2d3a-11ea-9562-f3b5b7cef4d1.png)

**Comment by mrjones2014** [comment]
If it helps, the URL I am using if of the format myorgname.atlassian.net

**Comment by lise-toggl** [comment]
Thanks @mrjones2014! We're trying some ideas for the dropdown issue and hopefully will find a solution soon.

For the double button issue, would you be able to show me any ancestor DOM elements with the `.toggl` class? Thanks :)

**Comment by mrjones2014** [comment]
@lise-toggl I think it may be on Jira stories that are part of an Epic, because it shows 2 Jira numbers (the Epic number / the Story number)

![image](https://user-images.githubusercontent.com/8648891/71976479-6aa93500-31e4-11ea-90eb-319b96771f50.png)

**Comment by lise-toggl** [comment]
@mrjones2014 awesome - it was indeed the epic and we've been able to reproduce it now. Thanks for the screenshots, I should be able to fix it soon :)

**Comment by mrjones2014** [comment]
@lise-toggl any idea when this version will be published to the chrome web store?

**Comment by tcrammond** [comment]
Hey @mrjones2014, we'll be publishing to the web stores shortly. It sometimes takes a little while to be rolled out to all users, but you should find yourself on the new version some time today 🤞
