### ISSUE TITLE
Asana Clients/Projects logic

### ISSUE THREAD

**Issue by krazyjakee** [toggl/toggl-button#163]
This is confusing so bare with me...

In Asana you have "Projects" and "Sections"
In Toggl you have "Clients" and "Projects"

To me, they amount to the same thing so I previously modified the toggl button to automatically assign the Asana "Project" name as the Toggle "Client" (or create if non-existent) and the Asana "Section" as the Toggl "Project".

This meant we could always stay in Asana and at the end of the week, go through the toggl recordings and log our time. Awesome workflow.

Sadly, a chrome update killed our customised button.
I would argue that this is a workflow others could use on the main branch of this Toggl button.

Please let me know your thoughts on this.

**Comment by IndrekV** [comment]
Haven't gotten any feedback with a similar request. Will close this issue.
