### ISSUE TITLE
Button not showing up anymore in Asana task detail

### ISSUE THREAD

**Issue by panfanky** [toggl/toggl-button#1633]
* **OS version**: Win8
* **Browser version**: 79.0.3945.88 (Official Build) (64-bit)
* **Extension version**: 1.54.1

### 🐛 Describe the bug

The button is visible in List view, but not in the head of the task detail where I remember it.

### Expected behaviour

When opening the task detail, the button used to be in the upper right. When working in Board view, I wouldn't ever find it

Thanks

**Comment by TheSoloJake** [comment]
Related to #1631 ?

**Comment by ckrf** [comment]
Yes, this looks like the same thing I reported in #1631

**Comment by TheSoloJake** [comment]
[User report](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/25114598250)

**Comment by lise-toggl** [comment]
Closed with #1636 :tada:
