### ISSUE TITLE
Button Does Not Appear in Asana Board

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggl-button#1634]
* **OS version**: 
* **Browser version**: 
* **Extension version**: 

#### Relevant integration (if any):

Asana (https://app.asana.com)

### 🐛 Describe the bug

In Asana's Board view, clicking on a card to open it does not show "Start Timer" button 

### Expected behaviour

Button should appear in card when clicked 

### Steps to reproduce

Visit Asana webapp 
Click on "Boards" tab 
Click on card to open 
Button should appear on card 

### Other details or context

Possibly related to greater changes in Asana UI; (possibly includes #1631 ) 

<img width="1076" alt="Screen Shot 2019-12-26 at 11 52 24 AM" src="https://user-images.githubusercontent.com/25573455/71485598-6db12800-27d7-11ea-8178-963e169ab616.png">

**Comment by lise-toggl** [comment]
Closed with #1636 :tada:
