### ISSUE TITLE
Jira intergration adds "Copy the link to this issue" to the title

### ISSUE THREAD

**Issue by mrjones2014** [toggl/toggl-button#1644]
* **OS version**: Windows 10
* **Browser version**: Chrome version 79.0.3945.117
* **Extension version**: 1.56.1

#### Relevant integration (if any): Jira

myorganizationname.atlassian.net

### 🐛 Describe the bug

When you click "Start Timer", if you then to to toggl.com/app/timer, it shows "Copy the link to this issue" directly after the issue number in the title of the toggl item.

### Expected behaviour

it should not include the text "Copy the link to this issue"

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to a Jira issue
2. Click "Start Timer"
3. Go to toggl.com/app/timer
4. The title will include the text "Copy the link to this issue"

**Comment by tcrammond** [comment]
Hey, sorry you are experiencing this problem. We'll fix it as soon as possible 👍 

For future selves: I tracked it down, it happens only when viewing an issue in a project of the "Next generation scrum" project format.

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/25368229300)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/25371860423)
