### ISSUE TITLE
Projects dropdown: Strange scrolling behaviour in Todoist

### ISSUE THREAD

**Issue by tcrammond** [toggl/toggl-button#1659]
* **OS version**: *
* **Browser version**: *
* **Extension version**: 1.58.0

#### Relevant integration (if any):

Todoist. I did a quick check in an other integration and did not see the same issues, but it's worth checking more of the popular integrations.

### 🐛 Describe the bug

The projects drop down in particular has some strange behaviour in Todoist; it could be due to a Todoist update or something.

It expands much more than it should, and can also have odd scrolling behaviour. It can also be off the screen (and if I remember correctly, we're supposed to have "stay on the screen" behaviour).

### Expected behaviour

Works normally, does not expand too much or go off screen, all projects can be scrolled to.

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to Todoist
2. Start a timer on a task
3. Open the projects dropdown
4. See strange behaviour

Capture of my strange behaviour: [capture](https://toggl.slack.com/archives/C029W49FT/p1580127963006200)

### Other details or context

[Case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/25474063392) with gif of one bad behaviour

**Comment by lise-toggl** [comment]
This is due to the popup position being changed to `fixed` here https://github.com/toggl/toggl-button/pull/1625/commits/56e29d3015e9b710f498473d09bf2eeaca0e9492#diff-06c72a7198e9adae75546aab4cd17b53R330, working on a patch
