### ISSUE TITLE
Workflowy integration doesn't seem to work

### ISSUE THREAD

**Issue by troggy** [toggl/toggl-button#1662]
* **OS version**: MacOS Mojave 10.14.4
* **Browser version**:  Brave Browser 1.2.43 Chromium: 79.0.3945.130 (Official Build) (64-bit)
* **Extension version**:  1.59.1

#### Relevant integration (if any):

Workflowy
https://workflowy.com/

### 🐛 Describe the bug

No "Start timer" item shown in menu

### Expected behaviour

I would expect to see "Start timer" menu item like described in https://github.com/toggl/toggl-button/pull/1593 

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to workflowy.com
2. Create any item
3. Reveal item menu (hover the bullet on the left from the item)
4. Notice there is no "Start timer" in the menu 

### Other details or context

Tried toggling "Faster menu item" feature of workflowy as well — didn't help, the timer menu item still is not visible

**Comment by pavel64-sutyrin** [comment]
+1 Firefox, Ubuntu.
