### ISSUE TITLE
Opening Chrome causes Toggl button settings to open on every load

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggl-button#1663]
* **Windows 10**: 
* **Chrome awaiting more information from user**: 
* Windows v7.4.1112

### 🐛 Describe the bug

The case [here](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/25617417587), is the second case I've seen where a user reports that the Toggl button settings menu opens each time they open Chrome. 

### Expected behaviour

Opening Chrome shouldn't open the Toggl button settings menu

### Steps to reproduce

I cannot reproduce, but the users involved open Chrome, the Toggl button settings open immediately each time.

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/25637645096)

Resetting all settings, uninstalling and reinstalling.
This user is on Windows 7
Happens an estimated 25% of the time when opening a new Chrome window with no other windows open.
Button version 1.59.1

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2097915/conversations/25449019707)

**Comment by VeljkoTN** [comment]
I've seen other cases of this as well I think, let's make it one of the 3 priority cases for next week.

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3540765/conversations/25733017361)

**Comment by nicktoggl** [comment]
users notified, thanks 👍
