### ISSUE TITLE
Long task title overlaps task title below

### ISSUE THREAD

**Issue by teusch** [toggl/toggl-button#1667]
### Environment details

* Operation system: windows 10
chrome and firefox

### Expected behavior
All titles of tasks should be readable.

### Actual behavior
If the tile of a task is too long it  continues over the title of the next task rendering the next task illegible
### Steps to reproduce the behavior
open project with long tasks and see that som task titles are unreadeble

### Additional details
In chrome 

* screenshots or screencapture
![image](https://user-images.githubusercontent.com/5502583/73841433-eb2a7800-481a-11ea-977f-bec51f718c3f.png)

**Comment by tcrammond** [comment]
Thanks for reporting this, will work on a fix 🔍
