### ISSUE TITLE
TickTick integration issue: _What are you doing_ field is not populated

### ISSUE THREAD

**Issue by Airgunster** [toggl/toggl-button#1670]
* **OS version**: macOS 10.15.3
* **Browser version**: Firefox 72.0.2
* **Extension version**: 1.59.3

#### Relevant integration (if any):
TickTick: https://ticktick.com/#c/all/calendar/w

### 🐛 Describe the bug
When you click on the task in TickTick and then click on _Start timer_ button _What are you doing_ field left empty (which means that this activity will be captured in Toggl with empty _Description_ field). This issue started to happen after small re-design of TickTick.

![Screenshot 2020-02-06 at 14 14 00](https://user-images.githubusercontent.com/7937957/73945578-6c9e0b00-48ec-11ea-8b45-a9dffcc81029.png)

### Expected behaviour
When you click on the task in TickTick and then click on _Start timer_ button _What are you doing_ field populated with the task name from TickTick.

### Steps to reproduce
1. Navigate to https://ticktick.com/#c/all/calendar/w page.
2. Create any task with title.
3. Click on newly created task name.
4. Click on _Start timer_ button and observe _What are you doing_ field left empty.

### Other details or context
No workaround found for this issue.

Thanks in advance,
Alexey

**Comment by ygeorgik** [comment]
I confirm the problem. The button does not accept the value of the task description field from anywhere. Not just from the calendar. For example here: https://www.ticktick.com/#q/all/tasks 
![Image 2020-02-08 at 10 46 41 PM](https://user-images.githubusercontent.com/43469777/74091121-218b2000-4ac5-11ea-9896-ca7b55b7cf52.png)

OS version: macOS 10.15.3
Browser version: YandexBrowser 20.2.0.1145
Extension version: 1.59.1 (the last from Chrome Webstore)

Thanks!
Georgiy

**Comment by VeljkoTN** [comment]
Any updates here? :)
