### ISSUE TITLE
Trello: Task list buttons no longer working

### ISSUE THREAD

**Issue by tcrammond** [toggl/toggl-button#1672]
#### Relevant integration (if any):

Trello

### 🐛 Describe the bug

Buttons do not show on the list of tasks (when viewing card details)

![Screenshot 2020-02-13 at 10 12 53](https://user-images.githubusercontent.com/6432028/74424236-79b97d80-4e49-11ea-8851-d90deb4c9609.png)

Looks like the UI has changed a bit.

### Expected behaviour

Buttons show next to each task on hover

**Comment by kadrihvl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/3724360/conversations/25755941554)

**Comment by zdericnina** [comment]
[case reference](https://app.intercom.io/a/apps/ayixs927/inbox/2759100/conversations/25752347554)

**Comment by zdericnina** [comment]
[case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2759100/conversations/25762181694)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/unassigned/conversations/21560455613)
