### ISSUE TITLE
Duplicate Start timer link on GitLab merge requests

### ISSUE THREAD

**Issue by RazerM** [toggl/toggl-button#1677]
* **OS version**: macOS Sierra
* **Browser version**: Firefox 73.0.1
* **Extension version**: 1.60.4

#### Relevant integration (if any):

GitLab. Bug appears on gitlab.com or a custom URL

### 🐛 Describe the bug

The "Start timer" link is shown twice on merge request pages:

![image](https://user-images.githubusercontent.com/1337586/74835618-04085280-531e-11ea-8236-d7da60787b01.png)

### Expected behaviour

There should be only one link.

### Steps to reproduce

Go to any merge request page, e.g. https://gitlab.com/gitlab-org/gitlab-foss/-/merge_requests/18557

### Other details or context

Here's the HTML of both buttons. It's always the case that one link is missing the merge request title.

```html
<a class="toggl-button gitlab" href="#" title="MR18557::Add background migration to fill file stores from `NULL`  to `1` - GitLab FOSS">Start timer</a>
<a class="toggl-button gitlab" href="#" title="MR18557:: - GitLab FOSS">Start timer</a>
```

**Comment by tcrammond** [comment]
Thanks for reporting the issue. This has been fixed in #1676 by mskrip and should be released in the coming days 🎉
