### ISSUE TITLE
Asana automatic tagging isn't working

### ISSUE THREAD

**Issue by smurfman111** [toggl/toggl-button#1691]
* **OS version**: Windows 10 Pro
* **Browser version**: Chrome 80.0.3987.132
* **Extension version**: 1.60.5

#### Relevant integration (if any):

https://app.asana.com/

### 🐛 Describe the bug

When I start a timer for a task in Asana, the project populates automatically but tags never populate. I have tried it in virtually every different page/view in Asana and it never works. I have created the exact tag name in Toggl and the tags show up in the Toggl button extension dropdown list, but they never auto populate.

### Expected behaviour

Tags should auto populate just like the project does when i slick the toggl button for a task in Asana.

### Steps to reproduce

Simple. Using any toggl button from any view it does not work. But as the simplest of cases, see below...

Steps to reproduce the behaviour:
1. I click a Project to open it
2. Click "List" view
3. press the toggl button next to one of my tasks
4. Task name populates fine as the time description and the project auto populates but nothing populates for the tags.

### Other details or context

See attached short video recording a couple examples. Also this link you can play the video but attaching in case the link doesn't work.

https://www.screencast.com/t/ZYTCXKogjZ
[Toggl auto tagging issue with asana.zip](https://github.com/toggl/toggl-button/files/4347219/Toggl.auto.tagging.issue.with.asana.zip)

**Comment by smurfman111** [comment]
Did this get looked at by anyone? Thanks

**Comment by tcrammond** [comment]
Thanks for posting this issue @smurfman111 and sorry that there wasn't a response before now.

Good news - automatic tagging will be working in Asana very soon 😄 The issue will be updated when the extension update is released.

**Comment by tcrammond** [comment]
This feature is now available in the latest version 1.63.0 🚀 

Please note that some pages in Asana don't show all of the tags associated with a task, or in some cases any tags at all, unless you click on the task to open the details. In those cases, we can't automatically add tags.
