### ISSUE TITLE
Not able to open Project/tags dropdown in Todoist Task view

### ISSUE THREAD

**Issue by zdericnina** [toggl/toggl-button#1704]
* **OS version**: macOS
* **Browser version**: Chrome 80.0.3987.149
* **Extension version**: Version 1.60.7

### 🐛 Describe the bug

Todoist rolled out it's new centered task view, and Toggl button doesn't let you to select a project or add tags. The field to add Project/Tag is unresponsive.

### Expected behaviour

Clicking on the Add Project/Add tags field should open up the dropdown to select the Project or a Tag

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to Todoist
2. Click on any Task to open its Task view
3. Click on Toggl Buttton
4. Click on either Add Project or Add Tag, nothing will happen

### Other details or context

User shared a [screencast](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/26501395012)

**edit:** 
Same problem is happening in the Visual Studio (https://dev.azure.com) integration, in the Board view.

**Comment by kadrihvl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3724360/conversations/26512576460)

**Comment by kadrihvl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3724360/conversations/26517547933)

**Comment by dooart** [comment]
the same problem is happening in the Visual Studio (https://dev.azure.com) integration, which leads me to believe it is a more widespread thing

**Comment by VeljkoTN** [comment]
Case reference from a user who reached out with the same issue with the Visual Studio [🔗 ](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/26481011430)

**Comment by rylek90** [comment]
I've managed to find the root cause for Todoist. Gonna verify if the same applies to Visual Studio and will submit a PR with fix

**Comment by rylek90** [comment]
Moving dev-azure integration fix to separate issue, cause it quite differs @VeljkoTN @dooart
