### ISSUE TITLE
Not able to open Project/tags dropdown in Dev Azure

### ISSUE THREAD

**Issue by rylek90** [toggl/toggl-button#1709]
* **OS version**: macOS
* **Browser version**: Chrome 80.0.3987.149
* **Extension version**: Version 1.60.7

### Expected behaviour

Clicking on the Add Project/Add tags field should open up the dropdown to select the Project or a Tag

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to Dev Azure
2. Open board view
3. Open any task
4. Click on Toggl Buttton
5. Click on either Add Project or Add Tag, nothing will happen

### Other details or context
See also: https://github.com/toggl/toggl-button/issues/1704#issuecomment-610060302
And similar fix for Todoist: https://github.com/toggl/toggl-button/pull/1708

Dev Azure seems to use https://github.com/microsoft/fluentui I couldn't find reliable way to fix it just as in Todoist's case. After an hour spend on reading the FluentUI code I doubt it's even possible without submitting issue there 🤷

**Comment by VeljkoTN** [comment]
Another user reached out, [Intercom reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/26822808723)

**Comment by VeljkoTN** [comment]
[intercom reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/27090210847)
