### ISSUE TITLE
TeamWork integration is no longer visible

### ISSUE THREAD

**Issue by dianetoggl** [toggl/toggl-button#1716]
* **Extension version**: 1.60.7

### 🐛 Describe the bug

The Toggl Button icon is no longer appearing on the TeamWork page - the page looks different from what is shown in the original Toggl Button screenshots. 

### Expected behaviour

Toggl Button should show up on TeamWork page as shown in the screenshots.

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/26723111787)

**Comment by TheSoloJake** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/26891979634)

**Comment by TheSoloJake** [comment]
Also appears to be reported in #1713

**Comment by TheSoloJake** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/27091188059)

**Comment by allisonletts** [comment]
I'm having this problem, and happy to support if that's helpful.

**Comment by TheSoloJake** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481300025831)
