### ISSUE TITLE
"Discard idle time and continue" does not keep the previous entry's tags

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1717]
* **OS version**: Windows 10 
* **Browser version**: Chrome 81.0.4044.113 
* **Extension version**: 1.60.7
NOTE: This is my own setup, but this should be an issue with both OSs and also happens with FF

### 🐛 Describe the bug

If you enable the Pomodoro timer and/or Idle detection and discard idle time (or Pomodoro) with continuing tracking the tag that was applied to the previously running time entry will not be saved and applied to the new time entry that "continues" tracking based on the old running TE before the Idle detection/Pomodoro notification was triggered. 

### Expected behaviour

If a user chooses to discard Idle time or Pomodoro and continue tracking the new running time entry should be exactly the same as the one before the notification, including the tag. 

### Steps to reproduce

1. Enable Pomodor or Idle detection using the Toggl Button
2. Start a running timer with a tag
3. When the Pomodoro or Idle detection notification is triggered select to discard and continue tracking
4. Check the new running TE for a tag, it should be missing

**Comment by VeljkoTN** [comment]
I need to correct this a bit after testing again. The issue is only related to Idle time and only if you select the "discard idle time and continue" option. This starts a new identical time entry only without the tag and it should bring the tag over as well.

**Comment by tcrammond** [comment]
@VeljkoTN it seems to work as expected for me so far 🤔 I'll keep trying, perhaps there's another dependent setting

**Comment by tcrammond** [comment]
Got it! Looks like it depends on `automatic tagging` setting - it should not IMO. Will look for a fix.
