### ISSUE TITLE
Toggl Button and broken Todoist Chrome Extension Integration 

### ISSUE THREAD

**Issue by jnardiello** [toggl/toggl-button#1719]
* **OS version**: macOS Catalina 10.15.4
* **Browser version**: Chrome 81.0.4044.122
* **Toggl Extension version**: Toggl Button Version 1.60.7

#### Relevant integration (if any):

* **Todoist Extension version for Chrome**: Todoist Version 9147

### 🐛 Describe the bug

Toggl button is missing from todoist chrome extension as per: https://get.todoist.help/hc/en-us/articles/212102645-Use-Toggl-with-Todoist

### Expected behaviour

I would expect to the the toggle button in each todoist task

### Steps to reproduce

Try installing following these steps:
https://get.todoist.help/hc/en-us/articles/212102645-Use-Toggl-with-Todoist

### Other details or context

I have tried to disable/re-enable the integration from Toggl a number of times. I've also tried to uninstall and re-install all extensions. As a last resort, I tried to change the todoist app theme as the standard one (I used night mode before).

Nothing solved the problem.

---

#### Important

Quick addition: from todoist.com the integration works fine. It's the interaction todoist extension <> toggl extension not working.

**Comment by lise-toggl** [comment]
Hi @jnardiello, are you using this Todoist for Chrome extension https://chrome.google.com/webstore/detail/todoist-for-chrome/jldhpllghnbhlbpcmnajkpdmadaolakh?

Due to the way extensions work, we can only insert the Toggl Button into a webpage, so unfortunately it's not compatible with the Todoist extension.

**Comment by jnardiello** [comment]
Yes, I got it - that's not ideal but I guess there's nothing we could do. Thanks for the feedback
