### ISSUE TITLE
Disable "Don't forget to track your time" notification

### ISSUE THREAD

**Issue by orlando** [toggl/toggl-button#172]
Is there a way to achieve this?

Thanks!

**Comment by dimitko** [comment]
@IndrekV I am using Chrome 39 and I can't.

**Comment by IndrekV** [comment]
Please write to support[at]toggl.com with more details so I can look into this issue.

**Comment by MeganBeckett** [comment]
Hi, I am getting this annoying alert "Don't forget to track your time" and I cannot see how to disable it. I am just using the web app. I do not have the extension.

How can I stop this reminder popping up?

**Comment by JayeMcC** [comment]
I thought I was having the same issue in the chrome extension, but it turns out the pomodoro feature creates notifications too.
