### ISSUE TITLE
Todoist.com integration broken

### ISSUE THREAD

**Issue by CyanoKobalamyne** [toggl/toggl-button#1723]
* **OS version**: Windows 10 Version 2004
* **Browser version**: Firefox 75.0
* **Extension version**: 1.60.7

#### Relevant integration (if any):

Todoist.com

### 🐛 Describe the bug

The Toggl button doesn't appear next to Todoist tasks since Todoist updated their UI yesterday (04/28/2020).

### Expected behaviour

There should be Toggl buttons next to each task.

### Steps to reproduce

Steps to reproduce the behaviour:
1. Turn on todoist.com integration for Toggl Button.
1. Go to https://todoist.com/app/ (while signed in).
1. Hover over any task.
1. Observe that the is no Toggl button.

### Other details or context

See description.

**Comment by VeljkoTN** [comment]
@CyanoKobalamyne can you try again? I just tried reproducing the issue and the Toggl Button does show up when I hover over tasks. The latest version of the Toggl Button is version Version 1.60.9, please make sure that's the one you are using.

**Comment by CyanoKobalamyne** [comment]
I am on version 1.60.9, and I still can't see the button.

Screenshot:
![image](https://user-images.githubusercontent.com/4078712/82091528-83ab8080-96c5-11ea-8ec0-951df82d2b42.png)

**Comment by lise-toggl** [comment]
@CyanoKobalamyne can you let us know if the button is working for you again on the latest version (1.62.1)? Thanks :)

**Comment by CyanoKobalamyne** [comment]
Yes, now I can see it in both the "Today" and "Upcoming" views. Although now the timer buttons are always shown for all tasks, instead of becoming visible with the rest of the task controls upon hovering over a task. But that's more of an aesthetic problem than a functional one.

**Comment by lise-toggl** [comment]
@CyanoKobalamyne thanks for the update! We will have another version out soon which will fix the visibility issue :)

If you run into anything else please let us know here here or through our support team support@toggl.com.
