### ISSUE TITLE
Button Not Appearing in Salesforce Lightening

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggl-button#1724]
* **Browser version**: Chrome Latest Stable
* **Extension version**: 1.60.9

#### Relevant integration (if any):

Salesforce (specifically Lightening UI) 

### 🐛 Describe the bug

Button no longer appears within UI 

### Other details or context

[case reference
](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/26891979634)
Also may be related to already-closed #1041

**Comment by allisonletts** [comment]
Happy to clarify or test if needed (this was my case)

**Comment by TheSoloJake** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/26924026751)

**Comment by allisonletts** [comment]
Immediately after clearing my cache, I was able to see the toggl button in Lightning--but when I went back later it was no longer available...

**Comment by VeljkoTN** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/26988726595)

**Comment by tcrammond** [comment]
Hey @allisonletts, could you let us know which pages in Salesforce Lightning you see the problem (if not all of them)? Or what steps you specifically take to see the button appear briefly and then vanish?

Just checking that your Salesforce URL looks something like this as well? `https://xyz.lightning.force.com/lightning`

Today I'm not having any problems using the Toggl buttons in Tasks or Accounts for example, but these problems vary a lot depending on account settings and so on - I may just be lucky.

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/27146386152)

**Comment by allisonletts** [comment]
@tcrammond Fascinating. I have the problem on Contacts, Opportunities, and a bunch of custom objects, but not Accounts or Tasks (once I went to those pages specifically). To add to the weirdness, in a Salesforce sandbox, I can see the button on Contact as well.

Something that I just noticed is that going to a record detail page, loading it all the way and having the button not appear--then leaving the page and returning to it (by clicking out to another Salesforce tab and then back in) puts the toggl button on the page. This makes me wonder whether it's something about Lightning pages and how they don't load all at once.

My URL looks like your example.

I'm a Salesforce consultant, so I spend a lot of time in Salesforce but my usage patterns may be atypical.

**Comment by tcrammond** [comment]
Thanks so much for the details. We'll be looking into ironing out the problems.

**Comment by VeljkoTN** [comment]
@lise-toggl one user says that the button is back but it appears at the foot of the page in Salesforce rather than against the task/contact etc as it used to do

**Comment by tcrammond** [comment]
@VeljkoTN Sorry, this was an intentional change but we didn't reach you before it arrived on the browser stores.

The button is located in the "Utility bar" at the bottom of the page now in Salesforce Lightning. We had difficulty restoring the original behaviour. Feedback is appreciated, but if there's much of it then let's collect it in a new issue.

![Screenshot 2020-06-01 at 10 22 16](https://user-images.githubusercontent.com/6432028/83395210-cc677700-a3f1-11ea-9a07-f410df578cff.png)
