### ISSUE TITLE
Evernote: integration reported as not working

### ISSUE THREAD

**Issue by tcrammond** [toggl/toggl-button#1725]
Chrome 80.0.3987.163 (Official Build) (64-bit).

### 🐛 Describe the bug

Evernote reported as not working in a recent Chrome store review (can't link directly to it)

### Expected behaviour

Evernote integration is working

### Steps to reproduce

Haven't tried to reproduce yet, just passing through.

**Comment by VeljkoTN** [comment]
Just got another report for this, I created an Evernote account and can confirm that the button is not there 🤷 @tcrammond @lise-toggl reopen?

**Comment by tcrammond** [comment]
@VeljkoTN I think `1.60.13` is not available in the stores yet. stand by 🤞

**Comment by VeljkoTN** [comment]
also a new Evernote layout 
![image](https://user-images.githubusercontent.com/36152180/83756962-1493cd00-a670-11ea-8c64-7ee0247be5e4.png)

**Comment by VeljkoTN** [comment]
> @VeljkoTN I think `1.60.13` is not available in the stores yet. stand by 🤞

👍
