### ISSUE TITLE
TB is not matching projects when used in Asana

### ISSUE THREAD

**Issue by nidarasheed** [toggl/toggl-button#1730]
* **OS version**: 10.15.4
* **Browser version**: chrome Version 81.0.4044.129 (Official Build) (64-bit)
* **Extension version**: 1.60.9

#### Relevant integration (if any):
Asana

### 🐛 Describe the bug

When using TB in Asana, the project is not being picked up even though matching project exists in Toggl. 
### Expected behaviour

Project should be automatically chosen. 

### Steps to reproduce
Steps to reproduce the behaviour:

1. Create a project with the same name in Asana and Toggl 
2. Open that project in Asana 
3. Create TE for  that task using TB in Asana
4. It will not pick project. 

### Other details or context

[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/26404446116)
This has been reproduced by multiple people in the support team.

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/27146461970)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/27145678134)

**Comment by edtamayo** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/27140069720)

**Comment by edtamayo** [comment]
[Case Reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/27140894283)

**Comment by dianetoggl** [comment]
Info from a user:
>Follow-up: Even though the Toggl buttons in the Task List pane do not *load* the Project name, if you hover your cursor over the button, the tooltip clearly *displays* the Project name (as well as the Task name).

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/27178712455)
