### ISSUE TITLE
GSuite admin unable to see Google Calendar button

### ISSUE THREAD

**Issue by dianetoggl** [toggl/toggl-button#1733]
* **OS version**: 10.15.3
* **Browser version**: 81.0.4044.138
* **Extension version**: 1.60.9

### 🐛 Describe the bug

User can see all other integrations they have ticked, but they are unable to see the Google Calendar one. Other members of their team can see it (on Windows PC), but not them (they are also the GSuite admin). User has cleared cache, tried in incognito.

### Expected behaviour

User would see the Toggl Button in Google Calendar

### Other details or context

[Intercom link](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/27112710611)

**Comment by lise-toggl** [comment]
@dianetoggl We haven't found any issues with the calendar, but Tyler found one with the integrations list where some integrations appear to be ticked, but are not actually ticked (see #1763).

Can you ask the user to untick the calendar integration and retick it (a popup asking for permission should show up here) then check again?

**Comment by dianetoggl** [comment]
Thanks @lise-toggl - asking now :D

**Comment by nunofmn** [comment]
Hopefully should be fixed with release v1.62.8 🤞 
https://github.com/toggl/toggl-button/releases/tag/1.62.8

**Comment by dianetoggl** [comment]
Fixed 😀

**Comment by tcrammond** [comment]
🎉 

Nice, let's consider it solved by https://github.com/toggl/toggl-button/pull/1763 then, until the time something changes
