### ISSUE TITLE
Automatically stop timer when browser is closed not working

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1735]
* **OS version**: Windows (can be any)
* **Browser version**: Latest version of Chrome and Firefox tested
* **Extension version**: 1.60.9

### 🐛 Describe the bug

The timer will not automatically stop when the browser is closed as it should when this feature is enabled.

### Expected behaviour

With the "stop the timer automatically when the browser is closed" feature is enabled the running TE should be stopped when you closed the browser.

### Steps to reproduce

Steps to reproduce the behaviour:
1. Enable "Stop timer automatically" (Stop the timer when the browser is closed.) feature
2. Start a running TE
3. Close the browser
4. Check if it is still running

### Other details or context

[Intercom case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/27153261744)

**Comment by tcrammond** [comment]
This was reported as working again, and I couldn't reproduce

It's possible it might be flakey though. shout if it comes up again 🙌
