### ISSUE TITLE
Tasks dropdown stops showing in button during and after searching for project

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/toggl-button#1737]
MacOS 10.15.4
81.0.4044.138 
Version 1.60.9

#### Relevant integration (Asana):

https://app.asana.com

### 🐛 Describe the bug
When searching for projects in the dropdown in Asana, the projects stop showing tasks. Then afterwards if you clear the search field. Tasks still aren't showing for all projects in the Projects window.

### Expected behaviour

You should be able to see the tasks in the dropdown as you are before searching.

### Steps to reproduce
Attempt to assign a project to an entry in Asana

### Other details or context
This user included a description and video should have helped.
[Case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2144650/conversations/27144312837)

**Comment by edtamayo** [comment]
[Case Reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/27285412709)

In this case, the Task dropdown does show up when searching for projects but it does not show up when searching for clients.
