### ISSUE TITLE
Notion not recognising a running timer

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggl-button#1744]
* **OS version**: Windows 10
* **Browser version**: chrome 83.0.4103.97
* **Extension version**: 1.60.12

### 🐛 Describe the bug

Toggl Button is visible on a Notion page, next to header. You can click TB to start an entry, but when you move away from that page, TB appears greyed out on the next page. It is not recognised that you have a running timer > you're not able to stop it. 
User also noticed that the tooltips that are displayed when hovering over button are incorrect. 
### Expected behaviour
When moving to another page, TB should know if there's a running timer and indicate it accordingly showing the option to stop. 

### Steps to reproduce

Steps to reproduce the behaviour:
I was able to replicate it in our Notion
1. Open any page in Notion
2. Start timer via TB
3. Move to another page
4. Notice that you'll see a greyed out TB as if timer wasn't started

### Other details or context

[Case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3724360/conversations/27361079020)

**Comment by kornelijepetak** [comment]
Hey, @kadrihvl.

The behavior is indeed intended.
As per the [Toggl Button style guide](https://github.com/toggl/toggl-button/blob/master/.github/CONTRIBUTING.md#toggl-button-style-guide), the button should be `red` only when the timer is active. 

In this particular case, if you start a timer, the TE description will be set to the name of the page. The red button will only be visible on the same page, that is, the descriptions must match. If they do not, the button is not considered active for that particular page.

**Comment by kornelijepetak** [comment]
Closing as `works-as-intended`.
