### ISSUE TITLE
Todoist integration no longer working

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1747]
* **OS version**: Windows 10 (not relevant I'd say)
* **Browser version**: Chrome 83.0.4103.97
* **Extension version**: 1.60.13

#### Relevant integration (if any):

https://todoist.com/app

### 🐛 Describe the bug

The button is no longer appearing in Todoist. They made recent changes, you can find details **[here 🔗.](https://get.todoist.help/hc/en-us/articles/115005442125-Web-application)**

If we fix this we should also fix the fact that it was not appearing in the "upcoming" view before, issue #1726

**Comment by VeljkoTN** [comment]
User ID: 5675119
I am also able to reproduce, I can's see it in the task list hovering over tasks, only when I open a specific task view 

It's not here: 

![image](https://user-images.githubusercontent.com/36152180/84141092-e983f180-aa52-11ea-813b-c50b69a5db93.png)

It is here: 

![image](https://user-images.githubusercontent.com/36152180/84141127-f4d71d00-aa52-11ea-8518-1e51a1865b07.png)

**Comment by TheSoloJake** [comment]
[user report](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/27431170302)
