### ISSUE TITLE
 Todoist.com integration has stopped working

### ISSUE THREAD

**Issue by mclois** [toggl/toggl-button#1750]
The Toggl button doesn't appear next to Todoist tasks since Todoist's [version 1006](https://get.todoist.help/hc/en-us/articles/115005442125) (updated 2020/06/08)

### Environment details

* Operation system: Windows 10
* Extension version: 1.60.13

### Expected behavior
There should be a Toggl button next to each task.

### Actual behavior
No Toggle button shown

### Steps to reproduce the behavior
1. Turn on todoist.com integration for Toggl Button.
2. Go to https://todoist.com/app/ (while signed in).
3. Hover over any task.
4. Observe that the is no Toggl button.

### Additional details
Similar to #1723 but not duplicate, this is a different update

**Comment by shantanuraj** [comment]
Hi @mclois we recently merged and released a fix for the Todoist integration
(https://github.com/toggl/toggl-button/pull/1748)

It's deployed in version 1.62.1, which we rolled out earlier today.
Could you check it after you receive the update and let us know if the problem still persists?

**Comment by ricotheque** [comment]
Hey @mclois a fix was merged in #1748. 

Could you please close your browser and restart? This should grab the updated version of the extension and allow you to use it on Todoist again. :)

**Comment by mclois** [comment]
I have just update the extension and the Toggl button is back. Thanks!
