### ISSUE TITLE
Todoist button duplicating issue

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1752]
* **OS version**: Windows 10
* **Browser version**: 83.0.4103.97 Chrome
* **Extension version**: 1.62.1

#### Relevant integration (if any):

https://todoist.com/app/

### 🐛 Describe the bug

In a list of tasks, if you click on the "calendar" option to add a due date, each time you click the button will duplicate, also each time you click away: 

![Toggl Button duplicating clickin calendar](https://user-images.githubusercontent.com/36152180/84502625-028ddc00-acb9-11ea-8e3e-ad26025386d5.gif)

### Expected behaviour

The button should not duplicate 😄 

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to https://todoist.com/app/
2. Go to a list view for today or another section that has a list of tasks
3. Hover over a task and click on the "calendar" icon
4. Clicking away as well will duplicate the button

[Intercom case 🔗](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/27435789995)

**Comment by pwalen** [comment]
The same issue for:
OS version: macOS Catalina, OSX 10.15.5
Browser version: 83.0.4103.97 Chrome
Extension version: 1.62.1
![CleanShot 2020-06-15 at 12 22 58](https://user-images.githubusercontent.com/41115724/84647487-cc906800-af03-11ea-82a5-54dfb684388b.gif)

**Comment by pwalen** [comment]
Thank you. I installed the latest version.
The issue doesn't occur anymore 👏 👏 👏 

OS version: macOS Catalina, OSX 10.15.5
Browser version: 83.0.4103.106 Chrome
Extension version: 1.62.3
