### ISSUE TITLE
Button not showing in webapp Todoist

### ISSUE THREAD

**Issue by nidarasheed** [toggl/toggl-button#1774]
* **OS version**: 
* **Browser version**: 
* **Extension version**: 

#### Relevant integration (if any):

Todoist
### 🐛 Describe the bug

After a recent update, the button isn't showing in Todoist. It's there, we can click on it, but it won't show. 

![image](https://user-images.githubusercontent.com/49634673/86890265-7aafbc00-c116-11ea-8ec8-037bfe2e94a6.png)

![image](https://user-images.githubusercontent.com/49634673/86890322-9024e600-c116-11ea-8f58-a5af01a173e8.png)

### Expected behaviour

Button should show on hover. 
### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to todoist
2. Open any task list
3. Hover where TB should be. 

### Other details or context

[Case Reference 1
](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/search/conversations/106481300026004)

[Case Reference 2
](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/search/conversations/106481300025950)

[Case Reference 3](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/search/conversations/106481300025965)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481300026033)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2144650/conversations/106481300026080)

**Comment by edtamayo** [comment]
[Case Reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/106481300026172)

**Comment by sKawashima** [comment]
console err

> Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-eval' <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL> <URL>". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

> /app/#agenda%2F%E4%BB%8A%E6%97%A5%20%26%20(%23DVS*%20%7C%20%23Zaim*%20%7C%20%23Mission):1 Refused to load the image 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABMAAAATCAQAAADYWf5HAAABIklEQVR4AYWSu0qDURCEN80fkUCwSCPk8iJ5DF/BF1Aw1Ye2NhpLQSwFn8EiMd4qb6WNEDCkEdIETVLogDm7RyzMMvwzO8ue4eRY/GiyQ583ZsKleBNLlcgqh8z5yku6q342VuM+7LzUr6WxgrvMmHAuuJZX/hk7kIh6xoSsI9+MBotIo4QnmJAlld8ydl1OaVPhFBMq4lN39owrF9us87o89EV8y50bY+SrqxxHNvGqx3k3Zks6lP2UjT1iDNO+2DahRC+7kJ70JLYNPEGbjbgG8bbza6Pj4paCTcZiY30L6eR0jDofLi9oUGJNaIin7id1w9gXjavscyYsoiffDKMc/+nfkrfy/wt5kPfrvXX9oAhwFO8tqkWHASPmwkC8Fd430YaitSJltegAAAAASUVORK5CYII=' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-eval' wss://*.todoist.com https://avatars.doist.com https://www.google-analytics.com https://sentry.todoist.net https://image-resize.todoist.com https://d3ptyyxy2at9ui.cloudfront.net https://dcff1xvirvpfp.cloudfront.net https://x-api.rollout.io https://statestore.rollout.io https://conf.rollout.io https://push.rollout.io https://analytic.rollout.io https://browser.sentry-cdn.com https://www.dropbox.com/static/api/2/dropins.js https://apis.google.com https://twemoji.maxcdn.com". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300026347)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/27427018499)

**Comment by langri-sha** [comment]
I'm not sure if we'll have a lot of luck adding HTML CSP tags to allow data URIs for `img-src`. Maybe we should try adding SVG assets in directly as a workaround.

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300026358)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300026395)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481300026613)

**Comment by edtamayo** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/106481300026882)

**Comment by edtamayo** [comment]
[Case Reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300026892)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300027151)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481300027407)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481300027441)

**Comment by dianetoggl** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300029223)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481300029618)

**Comment by dpsxp** [comment]
I guess that for safety, we'll have to transform all the images into `svgs` 🤔

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481300029954)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300029996)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300030109)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300030203)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300030331)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300030582)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300030622)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481300030632)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481300030861)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300033421)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481300033584)

**Comment by sKawashima** [comment]
thanks!!!!!!!!!!
