### ISSUE TITLE
Switching on Asana integration doesn't "stick" 

### ISSUE THREAD

**Issue by nidarasheed** [toggl/toggl-button#1775]
* **OS version**: MacOS 10.15.4
* **Browser version**: Chrome Version 83.0.4103.116 (Official Build) (64-bit)
* **Extension version**: 1.63.0

#### Relevant integration (if any):

Asana

### 🐛 Describe the bug

Choosing Asana as integration does not stick. When you refresh the page, it is unselected again. 

### Expected behaviour
Integration selection should stick. 

### Steps to reproduce
1. Open Integrations tab
2. Choose Asana
3. Refresh 

### Other details or context

[Slack](https://toggl.slack.com/archives/C9LMUPD9T/p1594203735014500)
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481300026065)

**Comment by kornelijepetak** [comment]
This in fact happens with all of the following:

* asana.com
* breeze.pm
* brokerengine.com.au
* clubhouse.io
* codeable.io
* dom-integration
* khanacademy.org
* gqueues.com
* heflo.com
* helpscout.net
* huskymarketingplanner.com
* liquidplanner.com
* meistertask.com
* nozbe.com
* osticket.com
* sourcelair.com
* teamleader.eu
* vivifyscrum.com
* zenhub.com
