### ISSUE TITLE
Issue logging in via website

### ISSUE THREAD

**Issue by leafi** [toggl/toggl-button#1785]
* **OS version**: Mac
* **Browser version**: Chrome/Firefox
* **Extension version**: Latest

### 🐛 Describe the bug

A member of the support team was having issues logging in to the Toggl Button extension. Once it works it seems to work, but when it doesn't work it keeps not working.

They experienced this last Friday in Firefox, and today in Chrome.

I've been messing with the code in this area in the website, so I should probably review the changes I made to the website & carefully examine the redirect-to-Toggl-Button code... And try and figure out the exact nature of the issue.

The issue is probably not with Toggl Button itself, but it does affect it.

### Expected behaviour

Reliable login via website

### Steps to reproduce

Dunno yet - need to figure this out!

**Comment by rylek90** [comment]
Is it still reliable @leafi?

**Comment by nidarasheed** [comment]
Please let me know if you guys need me to try anything else 🙈

**Comment by leafi** [comment]
Well, it's stopped happening to Nida - a successful login worked - and I was still unable to reproduce it, so I'm assuming whatever bad state happened, it's gone for now...

One for another day.
