### ISSUE TITLE
The Toggl Button doesn't display on the Todoist page.

### ISSUE THREAD

**Issue by pwalen** [toggl/toggl-button#1790]
* **macOS Catalina 10.15.5**: 
* **Chrome  84.0.4147.89**: 
* **Toggl Button 1.64.1**: 

Relevant integration (if any):
[https://todoist.com/app/](https://todoist.com/app/)

### 🐛 Describe the bug
The Toggl Button doesn't display on the Todoist page.

### Expected behavior
When hovering over a task, the Toggl Button appears, next to the Edit icon 🖊️ 

### Steps to reproduce
1. Go to extension option an enable integration wit Todoist.
2. In the new Chrome tab/window open/reload the following URL: https://todoist.com/app/
3. Hover over a task.

### Other details or context
Although the button is not present, the user can start the timer by clicking on the place on the right of the Edit icon 🖊️ 

![CleanShot 2020-07-16 at 10 01 55](https://user-images.githubusercontent.com/41115724/87657173-bc65e580-c75a-11ea-8d76-4fecb608f054.gif)

**Comment by rylek90** [comment]
Hi @pwalen thank you for your request 🙇 

Although we currently have [an existing issue](https://github.com/toggl/toggl-button/issues/1774) for this and [ongoing PR](https://github.com/toggl/toggl-button/pull/1788) with fix for it. I'm going to close it as a duplicate then.
