### ISSUE TITLE
Zedesk integration TE description issue

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1794]
* **OS version**: Windows 10
* **Browser version**: Chrome 84.0.4147.89
* **Extension version**: 1.64.1

#### Relevant integration (if any):

zendesk.com

### 🐛 Describe the bug

If you start a timer from the ticket header the description for the TE will be pulled from there, but, if you start it using the sidebar you get the following: 

![image](https://user-images.githubusercontent.com/36152180/88180997-7adbab80-cc2e-11ea-9169-4441ec001c87.png)

![image](https://user-images.githubusercontent.com/36152180/88181200-cdb56300-cc2e-11ea-847d-2f4c61d440a0.png)

### Expected behaviour

The description should be grabbed from the ticket header with both approaches 

[Intercom case 🔗 
](url
![image](https://user-images.githubusercontent.com/36152180/88181268-e6257d80-cc2e-11ea-858d-04a43ac3807c.png)
)

**Comment by davidwindell** [comment]
@rylek90 @VeljkoTN I'm still experiencing this issue in 1.66.10, can you re-open?

**Comment by davidwindell** [comment]
I think the problem is on Zendesk Agent workspaces and recent changes have broken the fixes applied for #1696
