### ISSUE TITLE
TB Causing Outlook to "Crash"

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggl-button#1800]
* **OS version**: 
* **Browser version**: 
* **Extension version**: 

#### Relevant integration (if any):

Outlook webapp 

### 🐛 Describe the bug

User reports that using the TB in Outlook prevents him from opening any emails (ie, page "freezes"). Forces him to close and reopen browser window. After user investigated this issue, he found that disabling the TB extension caused the Outlook webapp to operate properly. 

### Other details or context

[User report](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481300034549)

**Comment by TheSoloJake** [comment]
[User report](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481300038204)

**Comment by VeljkoTN** [comment]
I'd reconsider the impact level assigned to this issue. @ApocalypticFish is using Outlook as his main email client and he can reproduce the freezing of it:

> You can see your list of emails but the second you click on one to open it it just freezes up entirely

**Comment by VeljkoTN** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481301348127)
