### ISSUE TITLE
Toggl Button Not Appearing with Unpacked Version for Dev

### ISSUE THREAD

**Issue by dominic-ks** [toggl/toggl-button#1805]
* **OS version**: Windows 10 1903 Home Edition 64-bit
* **Browser version**: Chrome Version 84.0.4147.105 (Official Build) (64-bit) & Firefox 78.0.2 (64-bit)
* **Extension version**: Current Master Branch

#### Relevant integration (if any):
* https://calendar.google.com/
* https://trello.com/

### 🐛 Describe the bug
I am looking to contribute with an integration, however when running the unpacked version of the extension in Firefox or Chrome the Toggl buttons don't seem to appear where they would with the current released versions, giving Google Calender and Trello as examples here...

### Expected behaviour
That the Toggl extension would work in the same way whether running locally for development or the current release from the official browser extension stores.

### Steps to reproduce

1. Activate the latest release of the Toggl button from Chrome or Firefox store.
2. Navigate to Google Calendar, click an event and see the Toggl button. 
3. Repeat the same for a Trello card. 
4. Deactivate release version of Toggl button and activate unpacked version. 
5. Login to Toggl button via extension icon (works OK)
6. Navigate to Google Calendar, click on an event and see that the Toggl button is not present
7. Repeat above for Trello card

### Other details or context
N/A - not sure where to start with this...

**Comment by shantanuraj** [comment]
@dominic-ks just doublechecking did you enable the GCal and Trello integrations from the settings page of the dev extension?

![Screen Recording 2020-08-01 at 8 13 55 PM](https://user-images.githubusercontent.com/1716853/89104038-dfb7b280-d433-11ea-85c2-dc045b936da5.gif)

**Comment by dominic-ks** [comment]
Ah, no I did not, that does indeed seem to resolve that. Do you normally have to do that? I don't recall specifically allowing sites when I first started using the button.

**Comment by shantanuraj** [comment]
Yeah, the extension needs to be given permission to access the websites to insert the content-scripts at.

**Comment by dominic-ks** [comment]
Well, cheers for that! I must have just enabled them all when I first installed.
