### ISSUE TITLE
[Dark-Mode] Increase contrast in project popdown hover state

### ISSUE THREAD

**Issue by shantanuraj** [toggl/toggl-button#1813]
> Could someone increase the contrast when hovering in the project dropdown list? When I'm choosing project in the projects list, I couldn't see which one I am selecting.

_Originally posted by @nmiquan in https://github.com/toggl/toggl-button/pull/1769#issuecomment-673277646_

**Comment by nmiquan** [comment]
Thanks

**Comment by devnetkc** [comment]
@nmiquan do you happen to have a screen shot of the part you want improved? Going to check this out here in a bit.

**Comment by nmiquan** [comment]
@devnetkc  sorry for being late to reply. When you hover the pointer on the dropdown list of projects. There is no contrast on the item that's being pointed at. It kind of threw me off at first, but getting used to it is possible.

![](https://media.giphy.com/media/hPqhlHUJI4Vhyz3ROf/giphy.gif)

**Comment by devnetkc** [comment]
@nmiquan did you get a chance to look at the images for my fix PR?

Pretty sure I got what you wanted after seeing this from you -- thank you btw, I like that you got the mouse hover in there.

**Comment by nmiquan** [comment]
@devnetkc Yes, it looks as how it should be.
