### ISSUE TITLE
"Open Toggl" button at the top does not redirect to timer

### ISSUE THREAD

**Issue by edtamayo** [toggl/toggl-button#1831]
* **OS version**: MacOS 10.15.6
* **Browser version**: Chrome 84.0.4147.135
* **Extension version**: 1.6600

### 🐛 Describe the bug

The button to open the timer page from the Toggl Button extension does not work

### Expected behaviour

The Button should take you to https://track.toggl.com/timer

### Steps to reproduce

Click the button to go to the website at the top of the extension

![image](https://user-images.githubusercontent.com/61245582/92413032-1d7abb80-f103-11ea-8672-0b333f9b8502.png)

**Comment by edtamayo** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/106481303543074)

**Comment by edtamayo** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3824737/conversations/106481303543051)

**Comment by shantanuraj** [comment]
Fixed in https://github.com/toggl/toggl-button/pull/1830, just needs deployment

**Comment by shantanuraj** [comment]
Deployed in release [1.66.3](https://github.com/toggl/toggl-button/releases/tag/1.66.3) should start showing up on stores soon
