### ISSUE TITLE
Clickup integration not working 

### ISSUE THREAD

**Issue by nidarasheed** [toggl/toggl-button#1833]
* **OS version**: 10.15.5
* **Browser version**: Chrome 85
* **Extension version**: 1.66.1

#### Relevant integration (if any):

ClickUp
### 🐛 Describe the bug

TB is not showing in Clickup

![image](https://user-images.githubusercontent.com/49634673/92460799-d44d6900-f1e1-11ea-97e0-c518647bb59a.png)

### Expected behaviour

TB should show 
### Other details or context

[Slack](https://toggl.slack.com/archives/C9LMUPD9T/p1599556983200900)
[case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/106481303544395)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481303546237)

**Comment by kornelijepetak** [comment]
I don't know what the issue is for the user, maybe they have something cached.
For me, the clickup looks a bit different (note the dark theme) and I can **clearly see** the Toggl Button.
It also correctly starts/stops the time entry.

![image](https://user-images.githubusercontent.com/7033216/93779651-83009900-fc27-11ea-95a7-1b0922671b94.png)

@nidarasheed can you check with the user whether the problem still appears for them?

**Comment by nidarasheed** [comment]
@kornelijepetak This is from my Clickup account 
![image](https://user-images.githubusercontent.com/49634673/93973486-b0675700-fd8d-11ea-83e6-92a776012d8e.png)
In the extension  settings 
![image](https://user-images.githubusercontent.com/49634673/93973509-ba895580-fd8d-11ea-948f-91d7296d71a3.png)
Version 1.66.3

I also cleared cache and tried again, no change. :(

**Comment by kornelijepetak** [comment]
Since this integration (for now) depends on them providing a UI element in which we inject the button, I have contacted Clickup about this and am awaiting their response.

**Comment by kornelijepetak** [comment]
I got back from the ClickApp support. 

This is a non-issue.

The user simply needs to have two things turned on: 
* `Time Tracking` in their `ClickApps` settings (see screenshot below)
* The permission for ClickApp enabled in Toggl Track browser extension integration settings

The button will then normally appear.

![image](https://user-images.githubusercontent.com/7033216/94685316-8b448c80-0329-11eb-83f3-276266f740b3.png)
