### ISSUE TITLE
Todoist integration not working 

### ISSUE THREAD

**Issue by nidarasheed** [toggl/toggl-button#1834]
* **OS version**: 10.15.6
* **Browser version**: Chome 85
* **Extension version**: 1.66.1

#### Relevant integration (if any):
Todoist 
### 🐛 Describe the bug

Here's how the button looks 
![image](https://user-images.githubusercontent.com/49634673/92461141-52aa0b00-f1e2-11ea-8ba2-6660ae8ee939.png)

### Expected behaviour
The button should show correctly. 
### Other details or context

[Slack](https://toggl.slack.com/archives/C9LMUPD9T/p1599556983200900)

**Comment by zdericnina** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/106481304668595)

**Comment by MarijaGrigorjeva** [comment]
I'd also like to add that it is shown in the wrong locations in the task view:

![image](https://user-images.githubusercontent.com/67943692/95729364-76e78480-0c85-11eb-8ea7-7a0c6896662e.png)

**Comment by Phenome** [comment]
Created [a milestone](https://github.com/toggl/toggl-button/milestone/21) to track this, as there are a few related issues that can probably get solved together.
