### ISSUE TITLE
Point Short-Link to new Login-Page

### ISSUE THREAD

**Issue by xstable** [toggl/toggl-button#1836]
The Toggl-Redesign has now swtich the Login-Packe for Toggle-Tracker: 
![image](https://user-images.githubusercontent.com/1778068/92488096-6491ab00-f1ee-11ea-9904-9e06455aabd1.png)

It still points to: 
https://toggl.com/track/app/timer

But have to point to: 
https://track.toggl.com/

**Comment by shantanuraj** [comment]
Hi @xstable can you confirm the extension version you are using?

**Comment by shantanuraj** [comment]
This has been fixed in 1.66.3 https://github.com/toggl/toggl-button/issues/1831#issuecomment-688719695

**Comment by xstable** [comment]
Up from today, it works again: Version 1.66.3
