### ISSUE TITLE
Issue with some integrations when required fields for TEs are enabled

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1846]
* **OS version**: OS X 10.14.6
* **Browser version**: Chrome 85.0.4183.102
* **Extension version**: 1.66.3

#### Relevant integration (if any):

https://app.asana.com
https://trello.com/

### 🐛 Describe the bug

A user reached out saying that (when they have required fields turned on) if they have a time running already via the Track extension and they click on the Track button to start a new time entry from Asana or Trello they previous timer doesn't get saved but it actually gets renamed and both timers are basically turned into one when the currently running one is stopped. 

We managed to get to the point where asking them to turn of required fields for time entries and they confirmed that this helped. But they also confirmed (and shared a video of this issue happening coroborating their actions) that they are using all the required fields when starting a timer via the Track extension. 

They also say that this is not an issue with other tools they use the Track button with. 

You can check  out the video **[here](https://drive.google.com/file/d/13j1ZlIUd6-98DWZR4Ql1THYfQ9K47CLn/view?usp=sharing)**. 

### Expected behaviour

When they start a new running timer using the Track button from the Asana or Trello web app it should save the old one. In the event that required fields are not filled out they should get a warning. 

### Steps to reproduce

I'm afraid that I was not able to reproduce this issue with required fields turnd on in either one of those apps.

**Comment by VeljkoTN** [comment]
You will also notice that the button is in dark mode and selecting tags looks a bit off, as if there's no visual feedback that they have been selected but I can see that when the user clicks away the tag gets applied.

**Comment by VeljkoTN** [comment]
Hey guys, the user was wondering about a timeframe on this: 

>Please can you let me have an idea of expected timeframe to resolve the issue, once you know this?

**Comment by VeljkoTN** [comment]
Any timeframe here? The user would like to know

**Comment by dpsxp** [comment]
@VeljkoTN We'll be scheduling to work on this issue this week. So, after some investigation, I hope I can have a better answer for you and the user.
