### ISSUE TITLE
Projects in Todoist no longer being autopopulated

### ISSUE THREAD

**Issue by zdericnina** [toggl/toggl-button#1856]
* **OS version**: macOS
* **Browser version**: Firefox 80
* **Extension version**: 1.66.3

#### Relevant integration (if any):

todoist.com

### 🐛 Describe the bug

Toggl button shows on Todoist but projects must be manually selected.

### Expected behaviour

Project should be automatically populated

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to todoist
2. Make sure to have the same project in Todoist and in Toggl Track
3. The Project needs to be manually selected in Firefox (while it gets autopopulated in Chrome)

### Other details or context

User mentioned they've switched to chrome in the meantime but that stopped working for them. I was able to reproduce it in Firefox but not in Chrome, [case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/106481304668595)

**Comment by dianetoggl** [comment]
[Case reference](https://app.sproutsocial.com/profile/twitter/221015126/reply/5445870/t:1316910730977968129)

**Comment by zdericnina** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/106481304723412)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481301349796)
