### ISSUE TITLE
Toggl button's pomodoro settings are taking over when time entry is started from another platform

### ISSUE THREAD

**Issue by dianetoggl** [toggl/toggl-button#1857]
* **OS version**: Widnows 10
* **Browser version**: Chrome
* **Extension version**:  1.66.4

### 🐛 Describe the bug

If a timer is starter from the webapp or desktop, the Toggl Button pomodoro settings are triggered where they weren't previously.

### Expected behaviour

If a time entry is started outside of Toggl Button, the pomodoro settings won't be taken into account.

### Steps to reproduce:

Steps to reproduce the behaviour:
1. Go to the webapp and start a timer (make sure you have pomodoro turned on on the button)
2. When the timer hits the pomodoro timer, the notification will pop up.

### Other details or context

[Intercom link](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/26850914360)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/106481304701666)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481304705793)

**Comment by zdericnina** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/106481304708094)

**Comment by zdericnina** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/106481304709163)

**Comment by zdericnina** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/106481304673837)

**Comment by zdericnina** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/106481304709309)

**Comment by Phenome** [comment]
I'm bumping this to `impact: high` because of the high number of reports, and the annoyance factor to those affected :D
We'll get to it soon.
