### ISSUE TITLE
Meistertask not working anymore

### ISSUE THREAD

**Issue by TIIUNDER** [toggl/toggl-button#1865]
* **OS version**: Ubuntu 20.04
* **Browser version**: Google Chrome 86
* **Extension version**: 1.66.9

#### Relevant integration (if any):

https://www.meistertask.com/

### 🐛 Describe the bug

The Toggl Button is missing in Meistertask.

### Expected behaviour

The Toggl Button is visible in Meistertask in the top right corner of the open tasks.

### Steps to reproduce

Open Meistertask with Toggl Button enabled

Steps to reproduce the behaviour:
1. Go to Meistertask
2. Open a project
3. Open a task
4. There is no Toggl Button

### Other details or context

Looks like it's not working anymore since the last update

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481304730054)

**Comment by TIIUNDER** [comment]
What's the status here? I can't see the case reference

**Comment by VeljkoTN** [comment]
@TIIUNDER the reference is a secure link to our support tool indicating that this was reported by another user. Once this issue gets triaged by the dev team someone will be assigned to it and you will start seeing updates here.

**Comment by VeljkoTN** [comment]
![image](https://user-images.githubusercontent.com/36152180/97687168-ce655d00-1a99-11eb-8509-695c97c3143b.png)

Apparently, there was a UI update by Meistertask resulting in the Track Button no longer being visible, this is how it looked like before: 

![image](https://user-images.githubusercontent.com/36152180/97687610-eccb5880-1a99-11eb-8c20-79d3f9ac20b4.png)

**Comment by TIIUNDER** [comment]
How long does it take to go live on Chrome Web Store?
