### ISSUE TITLE
Idle notification not being triggered

### ISSUE THREAD

**Issue by zdericnina** [toggl/toggl-button#1876]
* **OS version**: macOS 10.15.6
* **Browser version**: Chrome 86
* **Extension version**: 1.66.10

### 🐛 Describe the bug

The notification doesn't display when being idle

### Expected behaviour

The idle notification should display prompting the user to discard or save the time

### Steps to reproduce

Steps to reproduce the behaviour:
1. Enable idle detection
2. Start the timer
3. Be away for more than 5 minutes while your screen is still on
4. No notification

### Other details or context

[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/106481305522067)
Veljko and I were both able to reproduce the issue (Windows and macOS)

**Comment by almirbi** [comment]
<img width="586" alt="Screen Shot 2021-01-11 at 1 55 56 PM" src="https://user-images.githubusercontent.com/6254473/104185083-c1a7a280-5414-11eb-9bc8-244dfad7a38e.png">

Cannot reproduce, that's with the developer version set to 10 seconds. But I am also getting the 5 minute ones on my store version of the extension while tracking time.

Maybe check that the setting is on?

**Comment by almirbi** [comment]
Also I have 1.68.1 version of the extension, maybe update? But I doubt there are changes related to that.

**Comment by zdericnina** [comment]
i can still reproduce this issue on 1.67.1, the version available on Chrome webstore. the notification doesn't get triggered at all 🤷‍♀️

**Comment by zdericnina** [comment]
@almirbi Veljko and I did some additional testing and the 1.67.1 (production) version doesn't work but the 1.68.1 does show the idle notification for both of us so we can consider this issue fixed in the upcoming release
