### ISSUE TITLE
Labels/tags are broken in the new Gitlab

### ISSUE THREAD

**Issue by zdericnina** [toggl/toggl-button#1877]
* **OS version**: Windows 10
* **Browser version**: Chrome 86
* **Extension version**: 1.66.10

#### Relevant integration (if any):

gitlab.com

### 🐛 Describe the bug

From a User:

> In new gtitlab version x-s were added to gitlab labels and now toggl plugin can't read the labels properly.

It seems that the extension is reading the labels wrong and adding it as such to Toggl Track. Where the X has been added to remove it, Toggl Track imports it as "Remove label"
How the labels look in Gitlab:
![toggl_gitlab](https://user-images.githubusercontent.com/19727123/97995516-e5cc7f00-1de6-11eb-9593-c7ea23665246.png)

How they get imported in Toggl Track:
![toggl_display](https://user-images.githubusercontent.com/19727123/97995548-ed8c2380-1de6-11eb-9e1e-6b87adfc4616.png)

### Expected behaviour

Labels should be added as Tags the way they are displayed in Gitlab.

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to Gitlab
2. Enable the integration in extension
3. Add labels in Gitlab
4. Start the timer and see how Toggl Track imported them

### Other details or context

[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/106481305530746)

**Comment by glensc** [comment]
Submitted https://github.com/toggl/toggl-button/pull/1878

**Comment by rizerzero** [comment]
Hi @zdericnina, sorry for the question on the closed issue but how did you get the start button under Time tracking I only have it near the closing issue button ?
![image](https://user-images.githubusercontent.com/1518379/120101309-d4154500-c145-11eb-9c00-1a4b6511cb56.png)
