### ISSUE TITLE
Zendesk Agent Workspace - Time Entry undefined

### ISSUE THREAD

**Issue by davidwindell** [toggl/toggl-button#1880]
* Ubuntu
* Chrome 85
* 1.66.10

### 🐛 Describe the bug

When the new default "Agent Workspace" feature is enabled, the Toggl Time Entry shows "#TICKETID undefined". I think this was broken by either https://github.com/toggl/toggl-button/issues/1689 or https://github.com/toggl/toggl-button/issues/1794.

It was working earlier this year when support for Agent Workspace was added in https://github.com/toggl/toggl-button/pull/1745

### Expected behaviour

Time entry should include the Ticket title.

### Steps to reproduce

Enable ZenDesk Agent Workspace:

![screenshot-outeredge zendesk com-2020 03 26-06_28_49](https://user-images.githubusercontent.com/1720090/77617391-f8670780-6f2b-11ea-873c-f6028c3c99ae.png)

**Comment by TheSoloJake** [comment]
[User report](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481308472956)

**Comment by davidwindell** [comment]
Thanks!
