### ISSUE TITLE
Bitrix24 integration issue with custom domains

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1883]
* **OS version**: OS X 10.15.7
* **Browser version**: 86.0.4240.198
* **Extension version**: 1.66.10

#### Relevant integration (if any):

Bitrix24 - bitrix24.com / custom domains

### 🐛 Describe the bug

Track Button works with the bitrix24.com domain. Bitrix24 Russian cloud accounts are based in the .ru zone and a custom domain is needed but it doesn't work with a custom domain. 

### Expected behavior

For the user to add their Bitrix subdomain as a custom domain (for example toggl.bitrix24.com) and get the integration to work that way. 

### Steps to reproduce

Steps to reproduce the behaviour:
1. Log into Bitrix24
2. Try to add your Bitrix24 subdomain as a custom domain in the settings page > integrations view 
3. Refresh the Bitrix web app and see if it worked

For example, I got the following URL from the Bitrix24 web app: https://b24-9iehx3.bitrix24.com/company/personal/user/1/tasks/

The "b24-9iehx3" is the custom/random subdomain that was assigned when I added "https://b24-9iehx3.bitrix24.com" as a custom domain for the Track Button extension the integration did not work.

[Intercom case reference 
](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/106481305548169)

**Comment by nidarasheed** [comment]
User has updated us on this issue. 

> Do you see my past requests regarding the integration of Toggl with Bitrix24?
As I understand it, I was refused.

I don't know what happened, but the integration started working with the boxed version as well.
But:
There are two modes of working with tasks, the first one works when you go to a task by any link in the Bitrix24 interface, this is a pop-up from the left.
First screenshot.
There are no Toggle elements.
Bitrix24 has a trick to see the task in the entire window, you need to reload the page with the pop-up open.
If we do this, then we will not only see the task in full screen, but also see the Toggl element. Perfectly!
My big request, apparently, based on the work done, please make the Toggl elements available and pop-up them on the left.

[Screenshots here](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481308216919)

**Comment by nidarasheed** [comment]
User has updated us again. 

> Yes, a custom domain. Integration works partially. If the task is in the whole window, the integration works. If pop-up, there is no button. I suspect this is a simple feature. I'm already waiting for a solution to the issue for half a year))

[Case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481308991393)
