### ISSUE TITLE
TB is not matching projects when used in Asana [My Tasks view]

### ISSUE THREAD

**Issue by zdericnina** [toggl/toggl-button#1885]
* **OS version**: macOS
* **Browser version**: Chrome 86
* **Extension version**: 1.66.10.

#### Relevant integration (if any):

Asana [My Tasks view]

### 🐛 Describe the bug

When using TB in Asana on My Tasks view, the project is not being picked up even though matching project exists in Toggl. However, the project is matched if using the Toggl button from Task details

### Expected behaviour

Project should be automatically chosen if the exact ones exist in Toggl.

### Steps to reproduce

Steps to reproduce the behaviour:

1. Create a project with the same name in Asana and Toggl
2. Go to Asana and click on My Tasks on the left
3. Create TE for that task using TB in Asana
4. It will not pick project.

<img width="1005" alt="Screenshot 2020-06-18 at 15 32 15" src="https://user-images.githubusercontent.com/19727123/85031492-07ea9b00-b17f-11ea-83ae-809c25773267.png">

If you click on a Task and click on TB from there, the Project will match automatically:

<img width="1434" alt="Screenshot 2020-06-18 at 16 16 43" src="https://user-images.githubusercontent.com/19727123/85031597-294b8700-b17f-11ea-8cc6-3d30e9c618a3.png">

### Other details or context

[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/search/conversations/106481305893036)
Old issue: #1757

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481305892742)

**Comment by zdericnina** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/106481305907889)

**Comment by VeljkoTN** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/106481305888306)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481305940906)

**Comment by kornelijepetak** [comment]
I have researched a bit into the issue. Here's what's going on.

There are four issues here.

1. They have changed their DOM.

	No worries, we can adapt. This part's fine.

2. Asana shows Projects and Tags in an indistinguishable way

	This is a problem. We have no way to know which is which. That means, it is clearly impossible for us to make sure that what we picked is actually a project, and not a tag. The only thing we can rely on (from my research at least, not 100% sure it's true) is that the projects are listed before the tags. However, that leads us to the #3.

3. A task can be without projects.

	Which makes #2 problematic on a different level. We can't even rely on the order and just pick the first to get the project, because they might not be a project at all. 

4. A task can find itself in multiple projects.

	There is a difference in the the data model between Asana and Toggl. In Asana, a task can be in multiple projects (or in none), while Toggl assigns at most one project to the Time Entry. Judging by the previous code, it would only look at the first thing in the list and try to match that, but because a task can be in multiple projects, it doesn't make sense. Maybe in Toggl, you have the Asana's second listed project.

Combined #2, #3 and #4 is a hell.

That all means that the best fix we can do is the following:

* Get the list of all projects and tags
* Find the first name that matches any of the user's projects

That's it.

That, of course, means that we might erroneously select a Toggl project by the Asana's tag, but at least, that allows us to be sure that if there is a matching project, it will be selected. If there are no matching projects, we might accidentally select Toggl's projects named like Asana's tags.

I assume that is an acceptable solution.

**Comment by VeljkoTN** [comment]
@kornelijepetak I think your proposed solution is a really good one, also, even if there is a Toggl Track project that matches a tag name in Asana it will be applied but the user will see that in real time and will be able to change if needed before clicking "done" to "save" the details of the new TE. I'm sure that this would be an edge case, if it's not too time-consuming or complicated I would go with this solution.

**Comment by kornelijepetak** [comment]
@VeljkoTN That solution has already been pushed as a PR #1890. 😉

**Comment by VeljkoTN** [comment]
I see the label now 😄 nice!

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481305952766)
