### ISSUE TITLE
GitLab integration issue

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1896]
* **OS version**: Windows 10
* **Browser version**: 86.0.4240.193 Chrome
* **Extension version**: 1.67.1

#### Relevant integration (if any):

gitlab.com

### 🐛 Describe the bug

One user is reporting that after a gitlab update the toggl track button is missing from the gitlab issue right sidebar- under section Time tracking.

### Expected behaviour

The button should be visible next to the issue title and on the right side, under time tracking.

### Steps to reproduce

Was not able to reproduce

[Intercom reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/106481306008413)

**Comment by almirbi** [comment]
@VeljkoTN is it possible they need to accept permissions again after a gitlab update or something? Also can we know what's the gitlab version the user has?

**Comment by VeljkoTN** [comment]
@almirbi I'll ask them and let you know

**Comment by VeljkoTN** [comment]
@almirbi here's what the user says: 

> I removed the extension and added it back, the outcome is the same- the toggl button is still missing from the right sidebar Time tracking field (after removing-adding the toggl button appeared back into the center part of the page as it should). Only right sidebar button is missing.

**Comment by VeljkoTN** [comment]
LOL I think I found a way around Gitlab's trial.. just don't confirm the email the second time around, they let you sign up again with the same email 😄 

With that said, here's what it looks like: 

![image](https://user-images.githubusercontent.com/36152180/106102380-996fb180-613f-11eb-92ab-24a2bdd076e8.png)

The button is at the top and the user is asking if it should show up on the right sidebar but when I click to find out more about the "time tracking portion" of the right sidebar I'm wondering if it ever worked there? 

![image](https://user-images.githubusercontent.com/36152180/106102502-ca4fe680-613f-11eb-8c5d-d5063ce9ae27.png)


Our "where can I find the button page" is outdated for a few of the apps listed there but it doesn't show the button on the right sidebar: 

![image](https://user-images.githubusercontent.com/36152180/106102582-e6538800-613f-11eb-90ae-912042688082.png)

@almirbi

**Comment by VeljkoTN** [comment]
Wondering if I can close this, from what I see on the "where can I find the button" page and my own testing the button does need some re-alignment because it's too close to the "close issue" button in GitLab but it was never positioned on the right side-bar?

**Comment by VeljkoTN** [comment]
> Wondering if I can close this, from what I see on the "where can I find the button" page and my own testing the button does need some re-alignment because it's too close to the "close issue" button in GitLab but it was never positioned on the right side-bar?

@almirbi do you know if the button was ever there?

**Comment by VeljkoTN** [comment]
Closing because there no more messages from the user and I think that the button was never on the right side in GL
