### ISSUE TITLE
Projects and Tasks not being picked up in Todoist

### ISSUE THREAD

**Issue by nidarasheed** [toggl/toggl-button#1899]
* **OS version**:  11.0.1
* **Browser version**: Chrome 87
* **Extension version**: 1.67.1

#### Relevant integration (if any):

Todoist
### 🐛 Describe the bug

When in Todoist projects, and pressing button to start timer, it does not pick project or task from Track even if matching data exists. This works in "Today" view
### Expected behaviour

I'd expect project, and where applicable, task to be picked. 
### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to Todoist Projects
2. Make sure you have matching project/task in Track
3. Click button to start timer
4. It will not pick data

### Other details or context

[slack](https://toggl.slack.com/archives/C9LMUPD9T/p1608551860218200)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481306025714)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481306039283)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481306057385)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481306852854)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481307099091
)
