### ISSUE TITLE
Zendesk button delay issue

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#1904]
* **OS version**: Windows 10
* **Browser version**: 87.0.4280.141
* **Extension version**: 1.67.1

#### Relevant integration (if any):

zendesk.com

### 🐛 Describe the bug

A workspace owner reached out about the WS members having issues with the button when starting a time entry or closing and opening new tickets in Zendesk. They shared videos showing a significant delay 10-60s  for the button to visually indicated it started tracking or that it is currently tracking when a ticket (basically a tab within zendesk where it's located) is closed and another one opened.

### Expected behaviour

The button should instantly show it's tracking and not stay in the "start timer" mode after tracking has been initiated or when you open a new ticket in zendesk

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to Zendesk
2. Start the timer and see how long it takes for the button to show that it's tracking
2. Close that ticked and open a new one - notice that the button will say "start timer", users were under the impression that tracking is being stopped automatically when the previous ticket was closed.

### Other details or context

You can find videos of this happening [here](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097020/conversations/106481306586007).

**Comment by almirbi** [comment]
We need some way to reproduce this, zendesk account?

**Comment by VeljkoTN** [comment]
Created one just now and can confirm, my timer is running but the extension is not showing it

**Comment by VeljkoTN** [comment]
![zen not working](https://user-images.githubusercontent.com/36152180/104735452-e451f800-5741-11eb-8c9b-0608e67f76a5.gif)

**Comment by VeljkoTN** [comment]
![zen two](https://user-images.githubusercontent.com/36152180/104735672-2b3fed80-5742-11eb-9422-f5f6ec8148fa.gif)

**Comment by VeljkoTN** [comment]
while we're at it with zendesk, there's another issue for it by @TheSoloJake https://github.com/toggl/toggl-button/issues/1880

**Comment by VeljkoTN** [comment]
A user asking for an update here

**Comment by VeljkoTN** [comment]
What's the status of this one, what else is needed to investigate further? The user would like an update
