### ISSUE TITLE
Button not showing in Atlassian/Jira 

### ISSUE THREAD

**Issue by nidarasheed** [toggl/toggl-button#1913]
* **OS version**: macOS
* **Browser version**: 88.0.4324.96
* **Extension version**: TogglButton/1.69.0

#### Relevant integration (if any):
Atlassian/Jira 
### 🐛 Describe the bug

The button is not showing. 
![image](https://user-images.githubusercontent.com/49634673/107201504-e181b480-6a1a-11eb-884a-368bead207c8.png)

### Expected behaviour

The button should show on this view 

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to ...
2. ...

### Other details or context

[Case 1
](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481307024813)
[Case 2](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481307026536)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481307026784)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481307027077)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481307027082)

**Comment by nidarasheed** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481307027674)

**Comment by zdericnina** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/106481307031300)

**Comment by zdericnina** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2759100/conversations/106481307032124)

**Comment by TheSoloJake** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481307030881)

**Comment by TheSoloJake** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481307037732)

**Comment by oluckyman** [comment]
thanks for the quick fix! when it will be available on [chrome web store](https://chrome.google.com/webstore/detail/toggl-track-productivity/oejgccbfbmkkpaidnkphaiaecficdnfn)?
For the moment there is 1.69.0
![image](https://user-images.githubusercontent.com/642673/107348470-53afd300-6ac7-11eb-9f36-e08c6a947e6c.png)
