### ISSUE TITLE
Asana Task button disappeared.

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggl-button#1916]
OSX 11.2 and OSX 10.15.7
Chrome 88.0.4324.150
Button version v1.69.2

#### Relevant integration (if any):

Asana - https://app.asana.com

### 🐛 Describe the bug

Multiple users report that the Asana button for Asana tasks has disappeared.

### Expected behaviour

Previously there was a button for Asana tasks and projects. The task button isn't appearing.

### Steps to reproduce

Check to see if the button appears with Asana Tasks, it isn't appearing for users and Rico in testing.

### Other details or context

Intercom cases below
[Case Reference 1](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481307076813)

[Case reference 2](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481307077333)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/106481307083131)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481307088703)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481307095286)

**Comment by ricotheque** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481307101024)

**Comment by dianetoggl** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/106481307108912)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481306850887)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481307137728)

**Comment by dianetoggl** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481307158059)

**Comment by dianetoggl** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/106481307158402)

**Comment by dianetoggl** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481307158055)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481307161036)

**Comment by dianetoggl** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481307154857)

**Comment by dianetoggl** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/106481307173916)

**Comment by dianetoggl** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481307174311)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481307174148)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/25114598250)

**Comment by TheSoloJake** [comment]
To clarify: the button still appears in some areas of the webapp: 

![Screen Shot 2021-02-16 at 11 40 25 AM](https://user-images.githubusercontent.com/25573455/108113521-3fd31680-705d-11eb-8d07-22f8017b84c3.png)

However, it appears that most users are utilizing the button from within either boards or individual task edit screens. It is in those areas that the button is not appearing.

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481307172393)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481307173136)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481307178232)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481307174157)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481307179362)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481307180152)

**Comment by willrowe** [comment]
Is there any update on this? I haven't been able to start the timer from tasks for the last week.

**Comment by dianetoggl** [comment]
[case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481307193663)

**Comment by VeljkoTN** [comment]
The button is also missing in Board View in asana: 

![image](https://user-images.githubusercontent.com/36152180/108367125-6c239a00-71f9-11eb-8f06-d296390b6f68.png)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481307210988)

**Comment by nicktoggl** [comment]
> Is there any update on this? I haven't been able to start the timer from tasks for the last week.

Work is progressing and we'll hopefully have an update soon :)
