### ISSUE TITLE
Jira picking up incorrect description

### ISSUE THREAD

**Issue by dianetoggl** [toggl/toggl-button#1918]
* **OS version**: Windows
* **Browser version**: 10
* **Extension version**: 1.69.2

### 🐛 Describe the bug

When a user start a timer from the button, the incorrect description is picked up

### Expected behaviour

The correct description would be picked up

### Other details or context
[Slack thread](https://toggl.slack.com/archives/C9LMUPD9T/p1613076860191900?thread_ts=1612771511.146800&cid=C9LMUPD9T)
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481307048046)

**Comment by VeljkoTN** [comment]
There are a couple of more cases linked in the slack thread, linking a new case [here](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481307150450).
