### ISSUE TITLE
Add support for custom YouTrack installs

### ISSUE THREAD

**Issue by timgaunt** [toggl/toggl-button#192]
It's great to see that YouTrack is enabled but we host our own instances of YouTrack rather than using it in the cloud.

Would it be possible to add additional URLs to the button to identify additional YouTrack instances?

Relates to: https://github.com/toggl/toggl-button/issues/43

**Comment by IndrekV** [comment]
We try to keep the permission to a minimum, so global permissions are out of the question.

There are two ways of using custom urls with Toggl Button. 

1. Create your own custom version of Toggl Button. Clone the repo add your needed url-s and package a separate extension. Here is a guide on how to do it ["Adding custom domains"](https://github.com/toggl/toggl-button/wiki/Adding-custom-domains)

2. Use the non-official customizable version of Toggl Button. 
This is a separate version that an user created for custom domain usage purpose. He said he would keep it up to date with the main application. It is also available in the Chrome Web Store [Toggl Button for custom domains](https://chrome.google.com/webstore/detail/toggl-button-for-custom-w/cblhgnnnpnonkonnfcfkfhhkoldjpdno)

**Comment by 1ed** [comment]
The non-official version is not usable if you are using the current version of youtrack (6.x) as the UI changed, but the extension was not updated (this patch was fixed the problem https://github.com/toggl/toggl-button/pull/162), it seems abandoned already.
