### ISSUE TITLE
Wishlist: Remember latest used project

### ISSUE THREAD

**Issue by fsateler** [toggl/toggl-button#193]
When working on several issues from the same project, it would be very convenient if toggl button remembered the last project used, so that one doesn't need to look it up again.

Possible algorithm would be: If the current timer is being started while another one is running, preselect the same project as the currently running timer.

Also the logic could be extended to also pick up the timers started in the past x minutes: Apply the above logic if there is a current timer, else pick the last timer from the past 5 minutes.

**Comment by dandaka** [comment]
+1.

Even better solution would be remembering selection of project with relation to URLs. Example. Asana has URL structure like /%project-id%/%task-id%. So when I have selected once specific project from Toggl for URL asana.com/%project-id%, it is essential to remember my choice. And select same project for same URL as a default.

**Comment by floriangosse** [comment]
+1

**Comment by gianpaj** [comment]
Similar to this after the timer stopped there should be an option to restart the previous Toggl task. Not only from the Notification box.
For example you work for 25min, you take a 5 min break, you press one button to restart the previous time/Toggl task.

**Comment by IndrekV** [comment]
@gianpaj the "continue latest" functionality is already implemented and will be available in the next version.

<img width="212" alt="screen shot 2016-03-21 at 16 01 25" src="https://cloud.githubusercontent.com/assets/842229/13920946/377ebff8-ef7e-11e5-97e5-652cd68ccad9.png">

**Comment by IndrekV** [comment]
Similar functionality (See latest tracked projects) will be implemented with #673
