### ISSUE TITLE
Chrome browser extension not available anymore

### ISSUE THREAD

**Issue by lunule** [toggl/toggl-button#1933]
* **OS version**: Windows 10 
* **Browser version**: Chrome  89.0.4389.114 

### 🐛 Describe the bug

Currently there's no more Chrome extension available. 
The URL https://chrome.google.com/webstore/detail/toggl-button/oejgccbfbmkkpaidnkphaiaecficdnfn throws a 404 page. 
I also checked the Chrome webstore, and the search for the official Toggl extension gives no result.

**Comment by bytrangle** [comment]
> * **OS version**: Windows 10
> * **Browser version**: Chrome  89.0.4389.114
> 
> ### 🐛 Describe the bug
> Currently there's no more Chrome extension available.
> The URL https://chrome.google.com/webstore/detail/toggl-button/oejgccbfbmkkpaidnkphaiaecficdnfn throws a 404 page.
> I also checked the Chrome webstore, and the search for the official Toggl extension gives no result.

I've just checked it and the extension is still available on Chrome webstore.

**Comment by lunule** [comment]
I'm not sure why it was unavailable for some days, but now it's available again, indeed.
Thanks for your follow-up on this, I'm closing the issue.
