### ISSUE TITLE
Toggl button unavailable in Redmine

### ISSUE THREAD

**Issue by Den4ik** [toggl/toggl-button#195]
Open redmine task but button not showing
http://screencast.com/t/cqE5Cj4D6w7

**Comment by IndrekV** [comment]
Just tested this in redmine demo account and it seems to be working. Tested with this url http://demo.redmine.org/issues/77490

"Start timer" is shown in the issue detail view. Toggl button supports all services on their default domains. If you have redmine on some other domain than redmine.org please refer to this article https://github.com/toggl/toggl-button/wiki/Adding-custom-domains
