### ISSUE TITLE
Toggl Button shown multiple times for Asana Board view

### ISSUE THREAD

**Issue by przemekciacka** [toggl/toggl-button#1958]
* **OS version**: 11.3.1 (Mac OS Big Sur)
* **Browser version**: 90.0.818.62 (Microsoft Edge)
* **Extension version**: 1.70.1

#### Relevant integration (if any):

https://app.asana.com

### 🐛 Describe the bug

The Toggl Button is added to the Asana Task's card multiple times.

### Expected behaviour

There should be only one Toggl Button visible for Asana Task's card.

### Steps to reproduce

1. Enable integration with Asana for Toggl Button Browser Extension as described on https://toggl.com/track/asana-time-tracking/
2. Go to your Asana Project's Board
3. Hover over one of the cards - the Toggl Button icon should be visible on the card, next to the Like This button.
4. Click the card to open the side pane. The second Toggl Button is added next to the previous one.
5. Close details pane. Next Toggl Button is added. Now are three Toggl Buttons visible ion the card.
6. Open side pane for the same card again. Next Toggl Button added. Now are four.

### Video

https://user-images.githubusercontent.com/200286/118836373-c7fdcd80-b891-11eb-8a21-0a6669fe4396.mov

### Other details or context

* Microsoft Edge with Strict Privacy mode enabled. Disabling it didn't help.
* This problem exists in the Board view only.

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481309474188)

**Comment by willrowe** [comment]
I started seeing this issue recently as well.
