### ISSUE TITLE
The Toggl timer project field does not get filled automatically

### ISSUE THREAD

**Issue by eddiesmo** [toggl/toggl-button#1976]
* **OS version**: Windows 10
* **Browser version**: Chrome, Firefox
* **Extension version**: 1.70.2

### 🐛 Describe the bug

When I start the Toggl timer from a task, the "Project" field in the Toggl timer is not filled automatically - it remains empty even when there is an obvious project to be filled.

Loom video demonstration here:
https://www.loom.com/share/3187892bb8704f239e44019c07da79d4

### Expected behaviour

When the task belongs to a project in Asana or Microsoft-todo (or any other service), the project field of the timer should be filled in automatically.

### Steps to reproduce

Steps to reproduce the behaviour:
1. Create a task within a project on Asana or Microsoft to do (or I suppose any other service).
2. Click the Toggl timer button and see that the project field remains empty.

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481309474188)

**Comment by LulzAugusto** [comment]
I made [PR](https://github.com/toggl/toggl-button/pull/2001) fixing the project selector for MS To-Do. As for Asana, it's working as demonstrated in the video below. 

@eddiesmo your issue might be the fact the project doesn't exist in the workspace already, the extension won't automatically create them for you. 

https://user-images.githubusercontent.com/254107/132251208-68308172-f605-453d-972a-ae4123b0d28e.mp4
