### ISSUE TITLE
Zendesk is broken (again)

### ISSUE THREAD

**Issue by davidwindell** [toggl/toggl-button#1979]
Since the latest change to Zendesk:

![screenshot-outeredge zendesk com-2021 07 07-10_56_33](https://user-images.githubusercontent.com/1720090/124739799-1cc4d880-df12-11eb-8df3-a7110c6172c6.png)

The button no longer shows at all above tickets.

Tested in module Version 1.70.2

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309475010)

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309476815)

**Comment by maritoggl** [comment]
Any updates?

**Comment by rylek90** [comment]
@maritoggl fix is here https://github.com/toggl/toggl-button/pull/1985 and waiting for brave reviewers :)
