### ISSUE TITLE
Setting tags

### ISSUE THREAD

**Issue by jalbstmeijer** [toggl/toggl-button#198]
Hi,

I have not found a way to select existing 'tags' automatically yet with a content js.

I was expecting:

    description: 'test description',
    projectName: 'test project',
    tags: ['critical']

Any suggestion?

Gr, J

**Comment by IndrekV** [comment]
Currently there is no functionality to automatically select tags.

**Comment by jalbstmeijer** [comment]
Can this issue be marked as feature request than?

**Comment by IndrekV** [comment]
We will currently not implement this as analog items to tags is not present in many of our integrated tools.
