### ISSUE TITLE
Toggl Button login not working if the WS has too many projects or clients

### ISSUE THREAD

**Issue by alexcr** [toggl/toggl-button#1986]
* **OS version**: Windows 10
* **Browser version**: Chrome 91.0.4472.124
* **Extension version**: 1.70.2

### 🐛 Describe the bug

Login fails due to `QuotaExceededError` on these lines:
https://github.com/toggl/toggl-button/blob/1e78c202c303dce18f816e9a070333fb06e0f28e/src/scripts/background.js#L220-L221

### Expected behaviour

Login should work!

TBD how exactly we'll handle this.

Note that the stored data is used here:
https://github.com/toggl/toggl-button/blob/9ae9a81d92aff4d12c97d6547e2ff8e784c0a720/src/scripts/settings.js#L214-L219

### Steps to reproduce

Steps to reproduce the behaviour:
1. Simply try to login to the extension on a WS that has >5MB data of projects/clients (e.g. user 6671101)

### Other details or context

Fore more info see Slack convo:
https://toggl.slack.com/archives/C9LMUPD9T/p1623793352149700

**Comment by Phenome** [comment]
I think we should switch to IndexedDB for storage. Much more quota there.
