### ISSUE TITLE
Add screenshots of all tools to wiki

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#199]
It would be good if screenshots would be in an unified size (about 1080x800)

_I keep this issue open as I upload screenshots here. 
I'm not sure you can upload images to wiki. 
I haven't closed it because I'm not sure if images are kept if issue is closed_

Missing tools:
- [x] Unfuddle
- [x] Gitlab
- [x] Worksection
- [x] JIRA
- [x] Sifter
- [x] Redmine
- [x] Youtrack
- [x] CapsuleCRM
- [x] Xero
- [x] Toodledo
- [x] Teamwork
- [x] Google Mail
- [x] Podio
- [x] Taiga
- [x] HabitRPG
- [x] Countersoft Gemini
- [x] esa.io
- [x] Drupal.org
- [x] Help Scout
- [x] GetFlow
- [x] Sprint.ly
- [x] TestRail
- [x] Wunderlist
- [x] Bugzilla
- [x] Breeze
- [x] Bambam
- [x] GQueues
- [x] Wrike
- [x] Assembla
- [x] Waffle.io
- [x] Salesforce

Bam bam (detail view)
<img width="1303" alt="bambam-detail" src="https://cloud.githubusercontent.com/assets/842229/8650992/1dd856c4-297f-11e5-8401-da62a9c4f1fa.png">
Bam bam (list view)
<img width="1303" alt="bambam-overview" src="https://cloud.githubusercontent.com/assets/842229/8650990/1dcfda58-297f-11e5-9f1e-1c15cdd53e73.png">
Bugzilla
<img width="1303" alt="bugzilla" src="https://cloud.githubusercontent.com/assets/842229/8650991/1dd677c8-297f-11e5-8e69-9d0c80b813c2.png">

Breeze (list view)
<img width="1303" alt="breeze-overview" src="https://cloud.githubusercontent.com/assets/842229/8650996/1def5a5e-297f-11e5-87b6-52a8dc876a14.png">

Breeze (detail view)
<img width="1303" alt="breeze-detail" src="https://cloud.githubusercontent.com/assets/842229/8650993/1ddd5e80-297f-11e5-9b30-41e87350dfb3.png">

GQueues
<img width="1303" alt="gqueues" src="https://cloud.githubusercontent.com/assets/842229/8650994/1de35f42-297f-11e5-88c5-613041457386.png">

Wrike
<img width="1303" alt="wrike" src="https://cloud.githubusercontent.com/assets/842229/8650995/1de3bbae-297f-11e5-8011-03b986fb9eee.png">

Podio
![podio](https://cloud.githubusercontent.com/assets/842229/5863813/ed2a1250-a284-11e4-9046-4071299545ff.png)

Taiga
![taiga_detail](https://cloud.githubusercontent.com/assets/842229/6000617/92cfa290-aae8-11e4-8e5f-9acfd6935c5b.png)

![taiga_backlog](https://cloud.githubusercontent.com/assets/842229/6000620/97260d5c-aae8-11e4-80bf-011a9a9080a3.png)

HabitRPG
![habitrpg](https://cloud.githubusercontent.com/assets/842229/6000618/92d2f1e8-aae8-11e4-865f-03d8e3ba4fc0.png)

JIRA
![jira](https://cloud.githubusercontent.com/assets/842229/6038469/f7deab3a-ac65-11e4-81dd-5bf89f792a43.png)

Countersoft Gemini
![gemini](https://cloud.githubusercontent.com/assets/842229/6148609/b0f0b3f2-b20b-11e4-85bd-9b30cc227aa8.png)

Drupal issue tracker
![drupal](https://cloud.githubusercontent.com/assets/842229/6148610/b10d2d8e-b20b-11e4-86f0-0d8f75e83ca6.png)

Esa.io
![esa](https://cloud.githubusercontent.com/assets/842229/6148611/b11fdde4-b20b-11e4-81d4-8510f5abe222.png)

Google mail
![gmail](https://cloud.githubusercontent.com/assets/842229/6148750/bf64a9f6-b20c-11e4-90e9-9edda05b4a89.png)

Redmine
![redmine](https://cloud.githubusercontent.com/assets/842229/6245396/0015ffc2-b767-11e4-8f81-1bfe0f340876.png)

Toodledo
![toodledo](https://cloud.githubusercontent.com/assets/842229/6245688/be7631b0-b769-11e4-9041-38c5b9bfef86.png)

Help Scout
![helpscout](https://cloud.githubusercontent.com/assets/842229/6246095/dbb2afe8-b76d-11e4-9d47-221315c883cd.png)

Youtrack
![youtrack](https://cloud.githubusercontent.com/assets/842229/6438725/8895e62a-c0d4-11e4-9354-19c6a30ae96b.png)

GetFlow
![getflow](https://cloud.githubusercontent.com/assets/842229/6441134/6b7af77e-c0ed-11e4-89b6-63fe3e65e95b.png)

Sprint.ly
![sprintly](https://cloud.githubusercontent.com/assets/842229/6441106/107767d6-c0ed-11e4-81b0-0f3babf12ae3.png)

TestRail
![testrail](https://cloud.githubusercontent.com/assets/842229/7767040/e99d5ace-0077-11e5-9fd0-1ad66fe97835.png)

Wunderlist
![wunderlist](https://cloud.githubusercontent.com/assets/842229/7767052/08e63e0a-0078-11e5-82b5-d37e64ae40fb.png)

---
### Any.Do

![anydo](https://cloud.githubusercontent.com/assets/842229/7767148/db34595a-0078-11e5-9e67-74c16ce8704b.png)
### Asana

![asana1](https://cloud.githubusercontent.com/assets/842229/7767161/e6c47a34-0078-11e5-9220-7e24a91a7238.png)
### Basecamp

![basecamp](https://cloud.githubusercontent.com/assets/842229/7767164/ec56a21a-0078-11e5-8a2f-352f5b1f5b61.png)
### Bitbucket

![bitbucket](https://cloud.githubusercontent.com/assets/842229/7767165/ec599c36-0078-11e5-8a0c-99d73a9130b3.png)
### Google Drive

![gdrive](https://cloud.githubusercontent.com/assets/842229/7767166/ec720424-0078-11e5-8fa3-d4c894c1d87b.png)
### Github

![github](https://cloud.githubusercontent.com/assets/842229/7767167/ec74347e-0078-11e5-9119-0cabe8813588.png)
### Pivotal Tracker

![pivotal1](https://cloud.githubusercontent.com/assets/842229/7767168/ec7f6e70-0078-11e5-9d9b-c5ab6d7cc6a4.png)
### Proucteev

![producteev](https://cloud.githubusercontent.com/assets/842229/7767169/ec81ffdc-0078-11e5-8c0c-f599b797098c.png)
### Redbooth

![redbooth](https://cloud.githubusercontent.com/assets/842229/7767170/ec8308d2-0078-11e5-8307-28e59010c0c7.png)
### Teamweek

![teamweek](https://cloud.githubusercontent.com/assets/842229/7767171/ec86008c-0078-11e5-9d1d-9b484d39ad74.png)
### Todoist

![todoist](https://cloud.githubusercontent.com/assets/842229/7767173/ec8b1be4-0078-11e5-93ad-3b4977513b79.png)
### Trac

![trac](https://cloud.githubusercontent.com/assets/842229/7767174/ec8ce4ec-0078-11e5-92ea-7eafee823c95.png)
### Trello

![trello](https://cloud.githubusercontent.com/assets/842229/7767175/ec99c18a-0078-11e5-875b-e2b74716483f.png)
### Zendesk

![zendesk](https://cloud.githubusercontent.com/assets/842229/7767224/5882a7fe-0079-11e5-80b4-7443c469af87.png)
### Assembla

<img width="1180" alt="assembla" src="https://cloud.githubusercontent.com/assets/842229/9305541/d8b651da-44fa-11e5-9a76-e3dfbe7e4a8a.png">
### Waffle.io

<img width="1369" alt="waffle io" src="https://cloud.githubusercontent.com/assets/842229/9305549/eab2ef06-44fa-11e5-84a8-47e7d5ca6b3d.png">
### Wrike

<img width="1468" alt="wrike" src="https://cloud.githubusercontent.com/assets/842229/10393694/c6a8e36c-6e9a-11e5-8cd8-64fbca65460a.png">
### Asana

<img width="1468" alt="new-asana" src="https://cloud.githubusercontent.com/assets/842229/10393695/c6c8df46-6e9a-11e5-9b14-9b1a2ac90ff6.png">
### Salesforce

![salesforce_list](https://cloud.githubusercontent.com/assets/842229/10479069/66841cd0-726a-11e5-8544-85809e9c5a27.png)
![salesforce_detail](https://cloud.githubusercontent.com/assets/842229/10479068/6683406c-726a-11e5-8b18-51f2420a98ec.png)
### GitLab

![screen shot 2015-10-16 at 14 23 47](https://cloud.githubusercontent.com/assets/842229/10540551/aabd53d2-7411-11e5-94f9-0ed8d9c7a091.png)

**Comment by IndrekV** [comment]
### Assembla Update
![assembla](https://cloud.githubusercontent.com/assets/842229/12017296/717eee7a-ad5d-11e5-9b07-094f5fdb7bdb.png)

**Comment by IndrekV** [comment]
Trello Update
![trello_v2](https://cloud.githubusercontent.com/assets/842229/12321148/4e859850-bab5-11e5-986e-d257d4ca5ae9.png)

**Comment by IndrekV** [comment]
### Youtrack
![youtrack_agile_board](https://cloud.githubusercontent.com/assets/842229/13952110/34d53c68-f03d-11e5-8094-39d09fa0b617.png)
### GetFlow
![getflow](https://cloud.githubusercontent.com/assets/842229/13951691/617e69f8-f03b-11e5-94ad-aa180ab0b092.png)
### Redbooth
Modal
![redbooth_modal](https://cloud.githubusercontent.com/assets/842229/13951692/61881b9c-f03b-11e5-99c8-a1684062c3ba.png)
### Phabricator
Details view
![phafricator_details](https://cloud.githubusercontent.com/assets/842229/13952130/53511e82-f03d-11e5-8ffa-fcfb8491decf.png)
Workboard view
![phabricator_workboard](https://cloud.githubusercontent.com/assets/842229/13951694/618fff7e-f03b-11e5-8b5e-0e3ed78beb6a.png)
### Visual Studio Online
![visual_studio_online](https://cloud.githubusercontent.com/assets/842229/13951695/6193c316-f03b-11e5-8ec9-2abe8c58c1f4.png)
### Target Process
![target_process](https://cloud.githubusercontent.com/assets/842229/13951696/619541e6-f03b-11e5-942a-d191cd4d4757.png)
### ProWorkflow
![proworkflow](https://cloud.githubusercontent.com/assets/842229/13951697/619f9b82-f03b-11e5-9403-358a755bf489.png)
### Mantishub
![mantishub](https://cloud.githubusercontent.com/assets/842229/13951699/61b0deba-f03b-11e5-8d7e-b804671ac505.png)
### Evernote
![evernote](https://cloud.githubusercontent.com/assets/842229/13951698/61b012f0-f03b-11e5-9235-6b6c00a85f79.png)
### Remember The Milk
![rememberthemilk](https://cloud.githubusercontent.com/assets/842229/13951700/61b1efbc-f03b-11e5-9529-b567d6d005fd.png)
### SourceLair
Start button is at the bottom right corner of the app
![sourcelair](https://cloud.githubusercontent.com/assets/842229/13951701/61b60476-f03b-11e5-94a3-d57f5682d17a.png)
### LiquidPlanner
![liquidplanner](https://cloud.githubusercontent.com/assets/842229/13951702/61b888a4-f03b-11e5-9020-28009a0c79a6.png)
### Wordpress
![wordpress_](https://cloud.githubusercontent.com/assets/842229/13951703/61c0e292-f03b-11e5-8fb1-f84948a03b31.png)
### Kanbanery
![kanbanery_](https://cloud.githubusercontent.com/assets/842229/13951704/61d14542-f03b-11e5-8f78-3460cb1609c7.png)
### Google Inbox
![inbox](https://cloud.githubusercontent.com/assets/842229/13951705/61d4ab10-f03b-11e5-9f87-d2b087520d72.png)
### Slack
![slack](https://cloud.githubusercontent.com/assets/842229/13951706/61d9cab4-f03b-11e5-937c-16a789ad704f.png)
### Sunrise Calendar
![sunrise_calendar_](https://cloud.githubusercontent.com/assets/842229/13951707/61def7b4-f03b-11e5-925f-76dad9e71014.png)
### Confluence
![confluence_atlassian](https://cloud.githubusercontent.com/assets/842229/13951708/61e25e40-f03b-11e5-895a-c4217d76199a.png)
### Newsletter2go
![newsletter2go](https://cloud.githubusercontent.com/assets/842229/13951709/61e9b5f0-f03b-11e5-91bc-e0ba6effae47.png)
### eProject.me
![eproject](https://cloud.githubusercontent.com/assets/842229/13951710/61f4e308-f03b-11e5-90ab-9ae7b4eaa202.png)
### Freshdesk
![freshdesk](https://cloud.githubusercontent.com/assets/842229/13951711/61f8c842-f03b-11e5-9481-5879d34295c7.png)
### Cloudes.me
![cloudes me](https://cloud.githubusercontent.com/assets/842229/13951712/61ff15c6-f03b-11e5-8ced-9dbc738f2d94.png)
### OTRS
Edit view
![otrs_edit](https://cloud.githubusercontent.com/assets/842229/13951714/62113b52-f03b-11e5-9f76-16b4efc042ff.png)
Main view
![otrs](https://cloud.githubusercontent.com/assets/842229/13951715/6211fd6c-f03b-11e5-84d1-7d701322c759.png)
### Doit.im 
Project edit view
![doit_project_edit](https://cloud.githubusercontent.com/assets/842229/13951716/621f133a-f03b-11e5-922c-a3a5d857ff9f.png)
List view
![doit_list](https://cloud.githubusercontent.com/assets/842229/13951717/6221079e-f03b-11e5-9a6e-fb2286adeda5.png)
Task detail view
![doit](https://cloud.githubusercontent.com/assets/842229/13951718/622d89e2-f03b-11e5-85c3-cbeb6616cead.png)
### Zoho Books
Invoice view
![zoho_books_invoice](https://cloud.githubusercontent.com/assets/842229/13951719/623a2814-f03b-11e5-94c8-77c007c6ec54.png)
Estimate view
![zoho_books_estimate](https://cloud.githubusercontent.com/assets/842229/13951720/6243fe84-f03b-11e5-8879-6468b763394e.png)
### Planbox
![planbox](https://cloud.githubusercontent.com/assets/842229/13951721/62488846-f03b-11e5-9168-c1a871c6246e.png)
### Gingko App
![gingkoapp](https://cloud.githubusercontent.com/assets/842229/13951723/6252ecbe-f03b-11e5-8f5c-92655880ea01.png)

**Comment by IndrekV** [comment]
![screen shot 2016-03-23 at 12 37 35](https://cloud.githubusercontent.com/assets/842229/13982703/2cf76d56-f0f4-11e5-8134-61c04a448de0.png)

**Comment by IndrekV** [comment]
### TeamWork
#### Tasks list
![teamwork_task_list](https://cloud.githubusercontent.com/assets/842229/13989821/aeb6c1fe-f11a-11e5-9226-211aec492618.png)
#### Task Details
![teamwork_task_detail](https://cloud.githubusercontent.com/assets/842229/13989822/aeb95338-f11a-11e5-9676-73d6e7410d45.png)

**Comment by IndrekV** [comment]
### SmartBoard

![smartboard_cl](https://cloud.githubusercontent.com/assets/842229/14012391/18d60c82-f1ae-11e5-9ece-4beca60a0607.png)

**Comment by IndrekV** [comment]
### Capsule CRM
![capsulecrm](https://cloud.githubusercontent.com/assets/842229/14018109/8d02fb1c-f1d4-11e5-89f4-51794ba648dd.png)

**Comment by IndrekV** [comment]
### Unfuddle
![unfuddle](https://cloud.githubusercontent.com/assets/842229/14018407/4cf37f22-f1d6-11e5-8b79-50b198a1cf6d.png)

**Comment by IndrekV** [comment]
### Open Project
#### Listing view
![openproject_list_view](https://cloud.githubusercontent.com/assets/842229/14044180/10b8535a-f296-11e5-914d-fadcc4cecdf9.png)
#### Detail View
![openproject_detail](https://cloud.githubusercontent.com/assets/842229/14044192/37d9c874-f296-11e5-988f-ddf73e725e63.png)

**Comment by IndrekV** [comment]
### Xero
![xero](https://cloud.githubusercontent.com/assets/842229/14064185/57c122a6-f401-11e5-9823-c60dd4190e9a.png)

**Comment by IndrekV** [comment]
### Worksection
![worksection](https://cloud.githubusercontent.com/assets/842229/14064247/0a894e34-f404-11e5-8235-331edf722f6c.png)

**Comment by IndrekV** [comment]
### SifterApp
#### Issues listing view
![sifterapp_listing](https://cloud.githubusercontent.com/assets/842229/14077924/c74ede26-f4f9-11e5-9e03-4401728e9cd5.png)
#### Issue detail view
![sifterapp_detail](https://cloud.githubusercontent.com/assets/842229/14077923/c747615a-f4f9-11e5-8dec-68121b3ff80e.png)

**Comment by IndrekV** [comment]
#### MantisHub ClassicUI
![mantishub_classic](https://cloud.githubusercontent.com/assets/842229/14078621/f44cbe38-f4ff-11e5-94db-1526c61d2c4a.png)

**Comment by IndrekV** [comment]
### Zube
#### Board view
![zube_board_view](https://cloud.githubusercontent.com/assets/842229/14103318/3b96ea5e-f5a8-11e5-9aad-34310f8c0461.png)
#### Modal view
![zube_modal](https://cloud.githubusercontent.com/assets/842229/14103301/23c7153e-f5a8-11e5-8ba3-e4af6e08a39b.png)
#### Ticket detail view
![zube_ticket_detail](https://cloud.githubusercontent.com/assets/842229/14103303/23c82780-f5a8-11e5-943d-5110e4c03167.png)

**Comment by IndrekV** [comment]
### AgenoCRM
![agenocrm](https://cloud.githubusercontent.com/assets/842229/14355010/3879bf1c-fce8-11e5-973f-9ba4eadb4e98.png)

### MiniCRM
![minicrm](https://cloud.githubusercontent.com/assets/842229/14355009/38780a1e-fce8-11e5-9404-c9b7c39974e7.png)

**Comment by IndrekV** [comment]
### Google Calendar
![gcalendar](https://cloud.githubusercontent.com/assets/842229/14418846/280487fe-ffca-11e5-821c-7c561c6d004a.png)

**Comment by IndrekV** [comment]
### Gitlab update
![gitlab_update](https://cloud.githubusercontent.com/assets/842229/14953295/16c18138-1071-11e6-83d9-1a02a038cc80.png)

**Comment by IndrekV** [comment]
### Salesforce Lightning

![salesforce_lightning](https://cloud.githubusercontent.com/assets/842229/15008062/3296d194-11e6-11e6-8325-f7735390dfb8.png)

**Comment by IndrekV** [comment]
### Rindle
![rindle](https://cloud.githubusercontent.com/assets/842229/15922962/2637e668-2e33-11e6-9c7e-d3ea97f6c7ce.png)

### Bitrix24
![bitrix24](https://cloud.githubusercontent.com/assets/842229/15922963/263aca22-2e33-11e6-981d-f5a2172c6724.png)

**Comment by IndrekV** [comment]
![added](https://cloud.githubusercontent.com/assets/842229/15925138/ac0a5734-2e3e-11e6-8b36-30bf5831e0d0.png)
![add](https://cloud.githubusercontent.com/assets/842229/15925140/ac2791aa-2e3e-11e6-8f0f-752006809d43.png)

**Comment by IndrekV** [comment]
### TickTick
![ticktick](https://cloud.githubusercontent.com/assets/842229/15925677/d06ae98e-2e40-11e6-9b0e-bb2dbebaa390.png)

**Comment by IndrekV** [comment]
### Workfront
![workfront_](https://cloud.githubusercontent.com/assets/842229/18247331/96aa1ad8-737a-11e6-8342-494b493a0144.png)

**Comment by IndrekV** [comment]
### OnlyOffice
#### Project view
Start timer link for tasks
![onlyoffice_project_view](https://cloud.githubusercontent.com/assets/842229/18626149/d392152c-7e5b-11e6-9bc5-743aa81d1752.png)
#### Task Detail view
Start timer link for task and subtask(s)
![onlyoffice_subtask](https://cloud.githubusercontent.com/assets/842229/18626148/d2fd3e34-7e5b-11e6-95d0-e609f5cb1783.png)

**Comment by IndrekV** [comment]
### MeisterTask

![meistertask](https://cloud.githubusercontent.com/assets/842229/18910238/c575b054-857f-11e6-9cf2-760fbdf8fa27.png)

**Comment by IndrekV** [comment]
![overv io](https://cloud.githubusercontent.com/assets/842229/19432617/0faaef6e-9466-11e6-8103-26e05cfd86be.png)

**Comment by IndrekV** [comment]
### Salesforce  (update)
![screen shot 2016-10-26 at 13 55 52](https://cloud.githubusercontent.com/assets/842229/19723586/929c1158-9b84-11e6-993d-d296a3b53e6a.png)

**Comment by IndrekV** [comment]
### TargetProcess Table view
![target_process_table](https://cloud.githubusercontent.com/assets/842229/19856474/34c4a64c-9f82-11e6-954c-1eaa642adf62.png)


### Zendesk new UI
![zendesk_new](https://cloud.githubusercontent.com/assets/842229/19856479/3bce2332-9f82-11e6-88f8-3324452a05e2.png)

**Comment by IndrekV** [comment]
### eProject.me

**Home view**
![eproject_home](https://cloud.githubusercontent.com/assets/842229/20058961/71ca5c1a-a4fc-11e6-85a8-e8630d0289be.png)

**Task list**
![eproject_task_list](https://cloud.githubusercontent.com/assets/842229/20058959/71c3e862-a4fc-11e6-92fb-68db4a061174.png)

**Task detail**
![eproject_task_detail](https://cloud.githubusercontent.com/assets/842229/20058960/71c68888-a4fc-11e6-8ae2-5894d966fe72.png)

**Comment by IndrekV** [comment]
**Issue detail**
![taiga_issue_detail](https://cloud.githubusercontent.com/assets/842229/20059601/b536dcd2-a4ff-11e6-8f14-ae066db47191.png)
**Issues list**
![taiga_issue_list](https://cloud.githubusercontent.com/assets/842229/20059602/b554cf58-a4ff-11e6-8a9b-551659423a25.png)
**Kanban view**
![taiga_kanban](https://cloud.githubusercontent.com/assets/842229/20059603/b567cca2-a4ff-11e6-8797-8c8ce76add51.png)

**Comment by IndrekV** [comment]
### Teamleader
![teamleader](https://cloud.githubusercontent.com/assets/842229/21501397/3c8a7fb4-cc50-11e6-90ad-165558078329.png)

### Feedly
![feedly](https://cloud.githubusercontent.com/assets/842229/21501398/3ca5f460-cc50-11e6-8100-6e59ed199e36.png)

**Comment by janv8000** [comment]
# GitHub update

![image](https://cloud.githubusercontent.com/assets/1412705/23610762/1e0352a0-0274-11e7-9268-a3983f36cf72.png)

**Comment by janv8000** [comment]
# Workfront

![image](https://cloud.githubusercontent.com/assets/1412705/23611083/ccb73388-0275-11e7-8cbd-fe69084a8959.png)

**Comment by syko** [comment]
ProcessWire
![processwire](https://cloud.githubusercontent.com/assets/317674/24801051/4a4a2f28-1bab-11e7-88d5-663833463fdd.png)

**Comment by syko** [comment]
Nozbe

![image](https://user-images.githubusercontent.com/317674/26925649-4255c95c-4c53-11e7-8398-87003c4b1392.png)

Khan Academy
![image](https://user-images.githubusercontent.com/317674/26925818-e959f304-4c53-11e7-8e9b-597d3033f6b3.png)

Husky Marketing Planner
![image](https://user-images.githubusercontent.com/317674/26926039-9f237962-4c54-11e7-97e1-7eb164caf2c6.png)

**Comment by syko** [comment]
osTicket
![screenshot 2017-07-18 13 21 46](https://user-images.githubusercontent.com/317674/28410406-4652fbce-6d46-11e7-983c-dabe6542bb05.png)


Dokuwiki

![screenshot 2017-07-18 13 26 44](https://user-images.githubusercontent.com/317674/28410413-4a63fd9e-6d46-11e7-8d4a-7f1d3499b303.png)

**Comment by syko** [comment]
Codebase
![screenshot 2017-08-21 13 15 18](https://user-images.githubusercontent.com/317674/29514977-24dbbdaa-8673-11e7-9cfd-080d42494cec.png)
![screenshot 2017-08-21 13 15 39](https://user-images.githubusercontent.com/317674/29514979-27abbe36-8673-11e7-93e7-85d9f6df4013.png)

**Comment by syko** [comment]
Rallydev
![screenshot 2017-08-30 11 51 58](https://user-images.githubusercontent.com/317674/30593337-dbe3d578-9d52-11e7-8286-5b3f1030cc36.png)

Spidergap
![screenshot 2017-08-30 12 00 58](https://user-images.githubusercontent.com/317674/30593356-ef577aba-9d52-11e7-8797-494a68c3878b.png)

New Zube
![screenshot 2017-09-12 14 50 14](https://user-images.githubusercontent.com/317674/30593357-f4b187d0-9d52-11e7-85f2-5f50dd970540.png)
![screenshot 2017-09-12 14 50 57](https://user-images.githubusercontent.com/317674/30593365-f9e302ec-9d52-11e7-90c1-cd2580cf0410.png)

Rollbar
![screenshot 2017-09-12 15 17 36](https://user-images.githubusercontent.com/317674/30593374-ff6e0018-9d52-11e7-81ff-8e7c61739e7f.png)

**Comment by syko** [comment]
Pagerduty
![screenshot 2017-12-14 13 43 25](https://user-images.githubusercontent.com/317674/33993251-6c8690a6-e0de-11e7-8acf-641d620ecb2d.png)

Onshape
![screenshot 2017-12-14 13 48 40](https://user-images.githubusercontent.com/317674/33993256-6fb350de-e0de-11e7-831e-44047f029543.png)

Airtable
![screenshot 2017-12-14 14 32 36](https://user-images.githubusercontent.com/317674/33993257-7284b870-e0de-11e7-939d-ac5a4302c1f6.png)

Protonmail
![screenshot 2017-12-14 14 35 42](https://user-images.githubusercontent.com/317674/33993258-756692c0-e0de-11e7-82fb-e0a77fdbe829.png)

Clickup
![screenshot 2017-12-14 14 50 30](https://user-images.githubusercontent.com/317674/33993260-77dd237a-e0de-11e7-8f65-fadc6e6a9ef5.png)

**Comment by dooart** [comment]
### Habitica new UI
![image](https://user-images.githubusercontent.com/371426/34733832-e0c5571e-f550-11e7-996b-7a0ccd779038.png)

### JIRA new UI

#### Issue view
![image](https://user-images.githubusercontent.com/371426/34734431-e637ba96-f552-11e7-87e6-abcdc7ac0e97.png)

#### Board view
![image](https://user-images.githubusercontent.com/371426/34734469-02f8e8a8-f553-11e7-87dd-bebe1f76a2f5.png)

### Gitlab new UI
![image](https://user-images.githubusercontent.com/371426/34734821-51f00ab2-f554-11e7-8337-4de0dd04b3ad.png)

### Google Calendar new UI
![image](https://user-images.githubusercontent.com/371426/34735414-823853da-f556-11e7-93b5-81bb1a22bd8e.png)

### Basecamp new UI
![image](https://user-images.githubusercontent.com/371426/34735661-57e7531e-f557-11e7-985e-f9d9ae79b25c.png)

**Comment by dooart** [comment]
ManageEngine

![manageengine](https://user-images.githubusercontent.com/371426/37479672-f40db97c-285b-11e8-8cf8-e422a4976a5b.png)

**Comment by dooart** [comment]
VersionOne

![image](https://user-images.githubusercontent.com/371426/38257567-d89e8560-3736-11e8-8993-a7b9926859a8.png)

**Comment by tcrammond** [comment]
### Freshdesk Mint

![screen shot 2019-01-03 at 13 36 37](https://user-images.githubusercontent.com/6432028/50640423-bc2d3d00-0f5c-11e9-8f7c-cf94c1c44a48.png)

**Comment by tcrammond** [comment]
### Produck

![Produck](https://user-images.githubusercontent.com/29934350/50020149-d73b0b80-ffb3-11e8-8692-2dc564d9520c.png)

**Comment by tcrammond** [comment]
### Kanbanist

![](https://user-images.githubusercontent.com/42759138/53190955-06be6200-364e-11e9-8410-5498c06964ed.png)

### Focuster

![](https://user-images.githubusercontent.com/1222598/53034777-8b846280-3439-11e9-85d8-b6b459645866.png)

![](https://user-images.githubusercontent.com/1222598/53034806-9e973280-3439-11e9-976e-6a4a47e21ab7.png)

### Scrapbox

![](https://user-images.githubusercontent.com/1734148/53694034-34dd3800-3dec-11e9-8ef7-86a46e29d487.png)

**Comment by dooart** [comment]
Missing screenshots:
- Dynamics 365
- Kantree
- Corgee
- Workflowy
