### ISSUE TITLE
Zendesk Broken

### ISSUE THREAD

**Issue by TheSoloJake** [toggl/toggl-button#1992]
* **Extension version**: 1.70.3

#### Relevant integration (if any):

Zendesk 

### 🐛 Describe the bug

Button no longer appears in Zendesk

### Expected behaviour

Button should appear within the Zendesk UI

### Other details or context

[Discussion](https://toggl.slack.com/archives/CLZCZ3669/p1627480419086900) in Slack

**Comment by dianetoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/3540765/conversations/106481309625771)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481309625283)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481309625349)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481309625654)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481309623803)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309632883)

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309633214)

**Comment by TheSoloJake** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2137598/conversations/106481309634706)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309623803)

**Comment by edtamayo** [comment]
[Case Reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/24231495613)

**Comment by maritoggl** [comment]
User reports:
> I have one comment, it used to take the ticket number along with the subject and it doesn't anymore

**Comment by maritoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309466035)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309651976)

**Comment by nicktoggl** [comment]
[Case Reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/unassigned/conversations/106481309652355)
