### ISSUE TITLE
Projects not showing in Projects dropdown on extension

### ISSUE THREAD

**Issue by nidarasheed** [toggl/toggl-button#2011]
* **OS version**: Windows 10
* **Browser version**: 93.0.4577.82
* **Extension version**: 1. I 70.4

#### Relevant integration (if any):

N/A

### 🐛 Describe the bug

The Projects dropdown is not showing projects. It says No Projects even though projects exist. 

### Expected behaviour

Projects should show. 

### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to ...
2. ...

### Other details or context

[Case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/conversation/106481309704969)
[Slack](https://toggl.slack.com/archives/C9LMUPD9T/p1632819244419400?thread_ts=1631866899.289100&cid=C9LMUPD9T)

**Comment by Phenome** [comment]
Merged with #2004
