### ISSUE TITLE
Button not showing on every Notion page 

### ISSUE THREAD

**Issue by nidarasheed** [toggl/toggl-button#2012]
* **OS version**: 
* **Browser version**: 
* **Extension version**: 1.70.4

#### Relevant integration (if any):

Notion

### 🐛 Describe the bug

The button is not showing on every Notion page. [Slack thread for more info](https://toggl.slack.com/archives/C9LMUPD9T/p1632730467380500)
### Steps to reproduce

Steps to reproduce the behaviour:
1. Go to a bottom-level page [like this one](https://www.notion.so/toggl/78452e1a5e7d4093b34edef8d8920456?v=46787a693e9c40b49689118da1504a34) – it has 
2. Go to a [folder-level page](https://www.notion.so/toggl/Team-f9acf7b43d554697883e5d2909594a23) and see now button

### Other details or context

It seems like the current selector `.notion-page-controls + div` always matches anything. For some pages, it doesn't work. We probably need to add a fallback selector to show the Toggl Button™ on those pages.

**Comment by nidarasheed** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481309704979)

**Comment by nicktoggl** [comment]
[Case reference](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/2097915/conversations/106481309706791)

As an example, it appears when I open a task from a database, but if I open that task as a page, there is no button appearing.


<img width="965" alt="windowed" src="https://user-images.githubusercontent.com/17441860/136320776-135f5bc6-13e3-4013-954d-ab5e1f420769.png">
