### ISSUE TITLE
Pomodoro notifications popup not appearing if you have sound notifications switched off. 

### ISSUE THREAD

**Issue by nidarasheed** [toggl/toggl-button#2018]
* **OS version**: 
* **Browser version**: 
* **Extension version**: 

#### Relevant integration (if any):

N/A

### 🐛 Describe the bug

This user is not getting any notification from the browser extension 1.70.7 when pomodoro ends and I can reproduce. My question is more about this section and whether I am understanding functionality right. See screenshot. 

![image](https://user-images.githubusercontent.com/49634673/140051201-f5e0d000-26c7-449d-b434-cebd7da2b702.png)

I understand this msg to mean that when the pomodoro period ends, I will get a notification. I do not assume that I need to enable sounds below this for this to happen. 

### Expected behaviour

I would assume a popup notification would show telling me period has ended. 

### Steps to reproduce

Enable pomodoro, but do not enable Sound notifications. 

### Other details or context
[Slack](https://toggl.slack.com/archives/C9LMUPD9T/p1635756423160300)
[Case](https://app.intercom.com/a/apps/ayixs927/inbox/inbox/534741/conversations/106481309711903)

**Comment by nunofmn** [comment]
@nidarasheed Do we know which OS and browser the user is using?

I tested it on Mac in Chrome Canary and initially it didn't show the notification, because I didn't allow notifications in Chrome on Mac OS system settings.
When I enabled them, the notification showed up.

**Comment by nidarasheed** [comment]
User is on OS X 10.15.7, Chrome 95.0.4638.54
I can reproduce it on macOS 11.6, 95.0.4638.69
Adding video of screen recording showing my settings and no notification in the Slack thread:
