### ISSUE TITLE
Button not showing up in JIRA v6.1.7

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#215]

**Comment by nramirez** [comment]
+1

**Comment by IndrekV** [comment]
I've created a new demo account for JIRA and it works fine. The url I'm using JIRA from is https://*.atlassian.net/  JIRA implementation supports addresses
        "*://*.atlassian.net/*",
        "*://*.atlassian.com/*",
        "*://*.jira.com"

Are you using one of these addresses.

**Comment by tb3088** [comment]
And if people are using hosted Jira installations that use none of those 'magic' URL patterns? The program still needs to function. Perhaps '*.jira.*' should also be under consideration.

**Comment by IndrekV** [comment]
@tb3088  For hosted Jira you can define custom domains in the preferences "Permissions" tab. See attached screenshot. 


![custom_domain](https://cloud.githubusercontent.com/assets/842229/19304910/3255061e-9077-11e6-89af-31e870e6aac8.png)
- Just type in url
- select the tool (in your case JIRA)
- Press Add

Item appears in the list of custom domains
