### ISSUE TITLE
Does not show start tracking button in Basecamp

### ISSUE THREAD

**Issue by petrhasalik** [toggl/toggl-button#229]
I have tried everything, but I am unable to see the start tracking button in Basecamp (both new and old versions). 

I am using the newest version of Chrome extension.

Any suggestions?

**Comment by IndrekV** [comment]
Please double check that you are logged in to Toggl and there is no "x" symbol on the Toggl Button extension icon thats right from the address bar. In Basecamp the "Start timer" links are attached to the todo list items. They are visible when hovering over the item. See this screenshot for reference. https://github.com/toggl/toggl-button/wiki/Where-can-I-find-the-Button%3F#basecamp

**Comment by petrhasalik** [comment]
I can confirm that I am logged in to Toggl and there is no "x" symbol on the Toggl Button extension. I have laso tried to re-install the plugin and re-log, but nothing helped.

I also confirm that I am unable to see the "Start timer" link even when I hover over an issue. 

This happens in both:
* new Basecamp - https://basecamp.com/something
* old Basecamp - https://something.basecamphq.com (I have also tried to add it between custom URL addresses with my own build of your plugin, but that did not solved my problem)

I have the newest version of Chrome on OS Windows 8.1.

**Comment by IndrekV** [comment]
Thank you for the feedback. I will look into it.

**Comment by petrhasalik** [comment]
Thanks, please contact me in case that you will need me to test something.

**Comment by IndrekV** [comment]
I've looked into this and it seems that currently Toggl Button supports only basecamp.com

**Comment by petrhasalik** [comment]
Do you think that there is a chance that the support will be extended?

**Comment by IndrekV** [comment]
I will look into it.

**Comment by petrhasalik** [comment]
Thanks, I will gladly assist as a tester.

**Comment by petrhasalik** [comment]
You are the man! Thank you. 

I have only noticed that it created some gaps white space.

![white spaces](https://cloud.githubusercontent.com/assets/8112552/6531874/d9e37d7e-c43c-11e4-8af5-7474c6872902.png)

**Comment by petrhasalik** [comment]
I think that I have discovered one more issue. It adds a name of the user who is assigned to that ticket to the description. I am not sure if that is the desired behaviour, because at least in my case that is something I always remove.

**Comment by petrhasalik** [comment]
Thank you, it seems that the name issue was fixed.

The previous issue with those white gaps remains.
