### ISSUE TITLE
openproject integration

### ISSUE THREAD

**Issue by hknochi** [toggl/toggl-button#251]
Hey at all, 

it would be very nice to get an integration for openproject in toggl

maybe you can evaluate if it is possible 

thanks in advance

**Comment by KeopsZ** [comment]
Good evening. 

I have using Toogl Button inside OpenProject but it is not saving the time expend in every module inside OpenProject

Anyone know what happen?

I have installed OpenProject inside a local server

Thank you

**Comment by KeopsZ** [comment]
Finally I made my own sync file with API Toogl and PostgreSQL database (Required for OpenProject V9).

If anyone want to use it ask me ;)

**Comment by Keopss** [comment]
I made my own sync php file with API Toogl and PostgreSQL database (Required for OpenProject V9).

Automatically sync the input timing to modules with same name or if not found goes to a "Others" module.

If anyone want to use it ask me ;)

**Comment by raphael-thibierge** [comment]
@Keopss i'm interested into using your script if you do agree , and why not contributing to it :)

**Comment by KeopsZ** [comment]
Hi @raphael-thibierge i create a repository with it ->

https://github.com/KeopsZ
