### ISSUE TITLE
Cannot pick tags when I start timer

### ISSUE THREAD

**Issue by eimajenthat** [toggl/toggl-button#259]
When I click the start timer button (mine is in Jira, but I assume the button is the same everywhere), there is a multi-select drop-down to pick tags.  I can pick a tag by clicking it, or pick multiple tags with ctrl+click.  However, when I click out of the box, the whole dialog disappears and my tags are not persisted.  I have to go to the web app to pick my tags, major bummer.

I've tried:
* Clicking in the window
* Hitting tab
* Hitting escape
* Clicking in the little dialog.

Whatever I try, with the drop down remains, or the whole dialog goes away.  So I never get to click the start timer button, which I really wanted to do.

Now, I will readily admit I'm a moron, so it could certainly be user error, but regardless, I can't get it to work.  Help?

**Comment by eimajenthat** [comment]
Confirmed: I am a moron.  After discussing this with a colleague, it turns out clicking in the original drop down works fine.  Could have sworn I tried that.

I still think there's room for improved user experience here.  If you click anywhere else, you lose the dialog and have no way to modify what you entered, other than opening the full app.

**Comment by IndrekV** [comment]
Currently we don't have the functionality to edit running entry after you have closed the edit dialog. We have an issue to add this functionality #109
I'll close this issue.
