### ISSUE TITLE
Connect boards with projects in Trello

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#264]
In my usage of Trello many of my projects get their own board. It would be great if there was a way (on user-config option of some sort) where I could designate on certain trello boards that any card on that board that I start a timer from, by default fills in the project number. It's a small thing but would save a ton of repetition for me (and I assume others who use per-project boards) to not have to select the project on *every* timer we start. Thanks and keep up the good work!

**Comment by IndrekV** [comment]
Trello integration syncing 
- the boards as projects 
- cards as tasks automatically

**Comment by annaseufert** [comment]
This one annoyed me aswell, so I took a look into the code. With the current version the toggl project will be set automatically according to the trello board name.
I would also love to configure the trello-toggl-project relationship. But until this is possible you could just use the same naming for a trello board and its toggl project. This way the "project" and "task" fields are filled automatically if you hit the "start timer" button.

**Comment by IndrekV** [comment]
We will not implement this special board project setting to the extension as this is too specific to one tool. We try to keep the extension as general as possible. Keeping the board names in sync with projects seems to be currently the best way to connect these two.

**Comment by maccesch** [comment]
Given the popularity of Trello this is absolutley a feature that makes sense. To keep the extension general which is totally sensible you could have an advanced setting that allows to set default projects to different URL patterns. That way other project management tools could benefit as well.

**Comment by ibes** [comment]
This is also something that is annoying for me every day. 
So seems like I really need to fork the extension for me.

Boards have unique base IDs like
https://trello.com/b/wr38gV9F/ (if this is a valid ID, it's not on purpose)
It should be easy enough to say: This URL start defaults to a certain project. 

Maybe there could be a configuration for 
regex -> project ?!
