### ISSUE TITLE
Integration with Pivotal Tracker broken

### ISSUE THREAD

**Issue by hubertlepicki** [toggl/toggl-button#267]
Toggl button when using with Pivotal breaks. You can "Start timer", it opens toggl pop-up. Nothing more can be done with this pop-up, however, it has hanged. Cannot be dismissed. You cannot select project. At the same time, time tracking was started properly on toggl.com site, so that integrration works, just the UI that hangs.

This is happening to me and my colleagues. Our set up is Chrome 41 on Linux. Error in JavaScript console:

    Error in event handler for (unknown): TypeError: Cannot read property 'parentNode' of undefined    
    at Object.togglbutton.generateProjectLabel (chrome-extension://oejgccbfbmkkpaidnkphaiaecficdnfn/scripts/common.js:137:26)
        at togglbutton.addEditForm (chrome-extension://oejgccbfbmkkpaidnkphaiaecficdnfn/scripts/common.js:247:133)

**Comment by IndrekV** [comment]
This issue appears when the popup doesn't have all the latest projects that are present in the application. I will add a failsafe for this. Until then a simple refresh should make this go away.

**Comment by hubertlepicki** [comment]
I tried clicking toggl button -> sync but that does not help. Or there is something else I should do?

**Comment by hubertlepicki** [comment]
Also, it's not a new project...

**Comment by IndrekV** [comment]
I would suggest refreshing the page or disabling and enabling the extension.

**Comment by hubertlepicki** [comment]
That solves the issue partially. Widget does not crash (loaded extension from gh master). But I do not see the project on the list in the drop-down. So, I think, it might be in fact problem with the api or something. This project is on client's workspace, I do not see the whole workspace in the drop-down, but I do see it when I log into toggl web app

**Comment by IndrekV** [comment]
If you want us to look into it more, please write to support@toggl.com with all the details. The project name and workspace that is causing the issue.

**Comment by IndrekV** [comment]
Also please mention that you have discussed this with Indrek so I the case gets assigned to me.
