### ISSUE TITLE
Running time, when it is not running

### ISSUE THREAD

**Issue by dandaka** [toggl/toggl-button#268]
1. In desktop client and web client timer is not running
2. In Toggle Button it is running
http://take.ms/UAORC

**Comment by IndrekV** [comment]
Toggl Button uses websocket for live updates. At times the socket connection gets lost. This is when the timer can go out of sync. Clicking "Sync" in the menu would get everything up to date again.

Never the less I would like to look into this to see if I can replicate the issue. How did you stop the entry? From web, desktop?

**Comment by IndrekV** [comment]
Found the troublemaker.
