### ISSUE TITLE
Add support for Visual Studio Online

### ISSUE THREAD

**Issue by GersonDias** [toggl/toggl-button#273]
Hello,

Toggl is awesome! I really want a button at [Visual Studio Online (VSO)](https://www.visualstudio.com/products/what-is-visual-studio-online-vs). If approve that, I can work in this enhancement! 

Cheers!

**Comment by IndrekV** [comment]
There is actually a pull request for that already #190. So it is possible that it will be added in one of the next releases.

**Comment by GersonDias** [comment]
Indrek, I merged the actual toggl-button master branch and the fork of #190 PR. I made some tests, corrections and enhancements. What is the best practice? Do a new PR to toggl repo or make an PR to #190 (ReddwarfCro) repo and let him do a new PR to toggl repo?


![image](https://cloud.githubusercontent.com/assets/1994582/7801522/3a9c57b4-02fc-11e5-936e-8bd7aff24447.png)

My changes are already on my fork..

**Comment by IndrekV** [comment]
For faster merging it would be great if you could do a new pull request that merges without conflicts. That way I can easily look how it works and add it.

**Comment by GersonDias** [comment]
Created pull request #274 .

Cheers!

**Comment by Mardaneus86** [comment]
Current PR has some issues with the new work item layout (which is in preview right now). I've added a comment on the PR that works for the new layout, so it needs some more work to support both the old and new scenario.

More info on the new work item layout on http://vsalmdocs.azurewebsites.net/library/vs/alm/work/process/new-work-item-experience

**Comment by IndrekV** [comment]
Closed with 2a790419f34ae73bd22722cc9a7de6b607150a43
