### ISSUE TITLE
Add Evernote support

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#286]
Feedback from user in Chrome store

**Comment by artembeloglazov** [comment]
+1

**Comment by IndrekV** [comment]
As the number of integrations is already more than 40 we have decided not to add any integrations ourselves. We do how ever welcome all pull request of new tools. I will add this link to our challenge page that show all asked and not implemented tools. There is a guide on how to add a new integration to Toggl Button at https://github.com/toggl/toggl-button/wiki/Adding-new-integrations
