### ISSUE TITLE
add tags 

### ISSUE THREAD

**Issue by cobrowserAlex** [toggl/toggl-button#290]
I have been able to add tags upon starting an entry using the 'tags' property.

The problem i have run into is that the select box might not contain these tags and certainly does not have them marked as selected. 

So when the user clicks teh 'done' button in the popup it sends an update to toggl with no tags, effectively deleting the tags.

Does anybody have a way to handle this?

Step 1: add the newly added tags to TogglButton.$user.tagMap in background.js
Step 2: mark them selected
Step 3: submit them as selected when clicking 'done' -> updateTimeEnrty

Alex

**Comment by cobrowserAlex** [comment]
Since the user really didn't need to add any other tags, i just created a way to hide the popup at all times.

Did this by adding a wrapper around the popup:
```
$editForm:
  '<div id="toggl-button-edit-form-wrapper">' +
    '<div id="toggl-button-edit-form">' +
```
and then adding a stylesheet in the document to always hide this:
```
document.addStyle = function (str, hoo, med) {
      var el = document.createElement('style');
      el.type = "text/css";
      el.media = med || 'screen';
      if (hoo) el.title = hoo;
      if (el.styleSheet) el.styleSheet.cssText = str;//IE only
      else el.appendChild(document.createTextNode(str));
      return document.getElementsByTagName('head')[0].appendChild(el);
    };

    document.addStyle('#toggl-button-edit-form-wrapper {display: none}');
```
if you're interested I can make a PR for this.

**Comment by IndrekV** [comment]
Currently there is no functionality to add new tags from the edit popup. Also there is a setting that hides the hides the edit popup. It's called `Show post-start popup` and unchecking that will not show any popup.

**Comment by IndrekV** [comment]
You can open settings from the extension icon menu.

**Comment by cobrowserAlex** [comment]
@IndrekV  It is possible to add new tags on the fly by just adding them to in the configuration object under 'tags', any new tags are automatically added.

I know about the settings menu, but I wanted to make it as hassle free as possbile.

Now I just created a custom crx that is distributed in the company, the sales manager is satisfied!

Thanks

**Comment by IndrekV** [comment]
@cobrowserAlex I'm not exactly sure what you mean by adding tags. Do you mean adding tags from the edit popup or do you mean something else.

**Comment by cobrowserAlex** [comment]
I created a toggle button for ZohoCRM and needed to add tags based on lead source and Lead or Deal name. All of which initially aren't in Toggl.

So when creating the button i added tags like this, and it works well:
```
    link = togglbutton.createTimerLink({
      className: 'zoho',
      description: description,
      projectName: 'Sales',
      tags: tags
    });
```

**Comment by IndrekV** [comment]
ok, thanks for the clarification.

**Comment by cobrowserAlex** [comment]
As the button is quite specific for our purpose I won't be making a pull request, unless there is strong demand...
