### ISSUE TITLE
Buttons invisble in taiga.io

### ISSUE THREAD

**Issue by rnique** [toggl/toggl-button#292]
The button is not visible by default even after reloading the pages.
I only managed to show it in the taskboard, here:
(https) tree.taiga.io/project/"project name"/taskboard/"sprint name"

Even there (taskboard), to show the button on the task, I need to click the name of the programmer and open & close the assign popup. After that, the button appears near the pencil icon. When I stop tracking, the button disappears again.

**Comment by IndrekV** [comment]
I guess the latest Taiga update must have changed something. We'll look into it.

**Comment by IndrekV** [comment]
Was unable to reproduce the missing start button issue.
Fixed description being empty issue in details view with 0b4c483a37c78e0dc29e7c87301bc146c27c985e
