### ISSUE TITLE
Firefox support

### ISSUE THREAD

**Issue by sagikazarmark** [toggl/toggl-button#295]
Do you plan to make this extension firefox compatible?

**Comment by IndrekV** [comment]
Currently there are no plans to create Plugin for Firefox.

**Comment by pipflinx** [comment]
why no firefox ??

**Comment by IndrekV** [comment]
@pipflinx We have now changed our plans and are going to look into it this summer. There is a separate issue for that #360

**Comment by pipflinx** [comment]
for now I can not use two browsers at the same time so for now I will use tmetric that works fine even tmtreic has far fewer functions Toggl
