### ISSUE TITLE
Toggl Button doesn't recognise Desktop app

### ISSUE THREAD

**Issue by orschiro** [toggl/toggl-button#298]
Hi there, 

I just noticed that Toggl Button doesn't properly recognise the Linux Desktop app.

When I start to track time using the Linux desktop app, the button will still notify me to `Don't forget to track your time!`.

Can anyone reproduce this? Is it Linux Desktop specific?

Thankfully,

Robert

**Comment by IndrekV** [comment]
Hi,

Toggl Button uses websocket to get live updates. Toggl Button is meant to be simple tool for tracking, it is not meant to be a total replacement for other Toggl apps. The extension is not always up to date with the server as the websocket connection will be closed when the extension or chrome is not used.

**Comment by orschiro** [comment]
@IndrekV 

Thanks for your clarification! I can live with this limitation. 

Thankfully,

Robert
