### ISSUE TITLE
Add icons of new tools to screenshot

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#301]
<ul>
<li><a href="https://bugzilla.mozilla.org/">Bugzilla</a></li>
<li><a href="http://www.breeze.pm/">Breeze</a></li>
<li><a href="https://www.dobambam.com/">BamBam</a></li>
<li><a href="https://www.gqueues.com/">GQueue</a></li>
<li><a href="https://www.wrike.com/">Wrike</a></li>
</ul>

**Comment by pe0ny** [comment]
![toggl-button-screens](https://cloud.githubusercontent.com/assets/5064445/8901042/2ed15776-344e-11e5-984f-0e940316272b.png)

**Comment by IndrekV** [comment]
Added to webstore
