### ISSUE TITLE
Post-start popup is not appearing after hitting Start

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggl-button#304]
Although the post-start popup setting is ticked the actual pop up doesn't appear hence there is no way to add projects, tags.
Reported with desk case #176506. Have tested in Chrome 44.0.2403.107 and see the same behaviour.
![screen shot 2015-07-29 at 14 32 38](https://cloud.githubusercontent.com/assets/12407134/8956499/44dd620a-35ff-11e5-9a3f-8594eebb6134.png)

**Comment by IndrekV** [comment]
This specific case is about starting the timer from the menu. Currently the edit form is not shown in this case it is in the future plans to add this functionality.

**Comment by IndrekV** [comment]
Fixed with 7f595e81af416c428f9272a28056b217c7547520 
Ref: #109
