### ISSUE TITLE
Project field not being populated by Asana project name

### ISSUE THREAD

**Issue by Saynah** [toggl/toggl-button#313]
Looks like this was an issue before that was fixed and closed.
However, I'm having this problem now (see my comment on the old issue https://github.com/toggl/toggl-button/pull/7).
Maybe Asanas API changed?

Project should be "per exercise metrics". Instead it's "no project"
(note, I already successfully imported Asana projects into Toggl)
![screen shot 2015-08-13 at 12 55 34 pm](https://cloud.githubusercontent.com/assets/637288/9260467/9a87f418-41bc-11e5-84e7-449a545f8ad3.png)

**Comment by IndrekV** [comment]
Just tested out the Asana integration and it worked ok for me. Please make sure the project name in toggl and in Asana is an exact match. Also can you confirm that you started the timer from the detail view as is showed in this screenshot.

![asana1](https://cloud.githubusercontent.com/assets/842229/7767161/e6c47a34-0078-11e5-9220-7e24a91a7238.png)

**Comment by Saynah** [comment]
Works now.
Sorry I should have tested more thoroughly.
Two things it could have been:

   - creating the task from focus view
   - not restarting Asana

Thanks for the help

On Thu, Aug 13, 2015 at 10:37 PM, Indrek V <notifications@github.com> wrote:

> Just tested out the Asana integration and it worked ok for me. Please make
> sure the project name in toggl and in Asana is an exact match. Also can you
> confirm that you started the timer from the detail view as is showed in
> this screenshot.
>
> [image: asana1]
> <https://cloud.githubusercontent.com/assets/842229/7767161/e6c47a34-0078-11e5-9220-7e24a91a7238.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/toggl/toggl-button/issues/313#issuecomment-130973747>.
>



-- 
Mark Sena

PhD
UCSF Orthopaedic Surgery
UCSF - UC Berkeley Bioengineering
