### ISSUE TITLE
Not filling project field when starting from gitlab in custom domain

### ISSUE THREAD

**Issue by rodrigobb** [toggl/toggl-button#314]
Maybe it's a bug of this extension or maybe not (could be a bgu in toggl page).

Clicking "Start timer" and filling project field starts timer OK.
But if you go to toggl page "task" field is completed but "project" field is not.

Then if you press STOP on toggl page, "project" is missed.

Also "Stop timer" does not get refreshed in toggl page and the user can press "STOP" button (missing "project" again). Toggle page must be reloaded to see the changes.

**Comment by IndrekV** [comment]
This seems to be issue with the live updates. We had some issues with this some time ago, but these issues should be resolved now.
