### ISSUE TITLE
Toggl Button missing in Youtrack

### ISSUE THREAD

**Issue by jaxxbo** [toggl/toggl-button#326]
Version of YouTrack: JetBrains Bug & Issue Tracker YouTrack 6.5
Build 16433 [21-08-2015 02:39]

**Comment by IndrekV** [comment]
Thank you for reporting, I will investigate.

**Comment by IndrekV** [comment]
I created a new account to youtrack and tested it. The Start timer button was visible and worked fine. Please make sure you are logged in to toggl button. Also note that "Start timer" button is shown in the issue detail view. See this image for reference: https://github.com/toggl/toggl-button/wiki/Where-can-I-find-the-Button%3F#youtrack

**Comment by IndrekV** [comment]
Also note that Toggl Button works only with the default youtrack domain address. If you want to use it with a custom domain you'll have to customize the extension. There is a guide how to do it at:  https://github.com/toggl/toggl-button/wiki/Adding-custom-domains

**Comment by jaxxbo** [comment]
Thanks for your replies. Here is the page of my YouTrack: http://screencast.com/t/iqOVC4zRy

Here is the link of the manifest.json [https://drive.google.com/file/d/0B_3e4eVsT-q7dWFfcVl2LTJBblE/view?usp=sharing] file that I edited as per your note. But it still does not appear.

**Comment by IndrekV** [comment]
There are some things out of place in your `manifest.json` you have added your domain to the toggl.com domain match array. It should have been added where the youtrack domain is. I've changed the manifest and it should now work for you. Get the manifest from https://www.dropbox.com/s/3ss9t2kx22v109h/manifest.json?dl=0
