### ISSUE TITLE
Timing with the chrome extension doesn't start time in Web UI

### ISSUE THREAD

**Issue by jkresner** [toggl/toggl-button#327]
1) If I time in one tab I have to open my web toggl timer and refresh the page. It used to poll and start timing.

2) The web app is so slow now and takes 4 seconds with a silly loading splash screen.

* General comment: the friction to use the tool is really growing.

**Comment by IndrekV** [comment]
This is issue with the web client not Toggl Button extension. I know that the web team is currently working on improving the load time of the web app. Thank you for the feedback.
