### ISSUE TITLE
The website can't count anymore

### ISSUE THREAD

**Issue by jkresner** [toggl/toggl-button#328]
Can't find a project to leave issues / bugs for the web app ...

![screen shot 2015-09-21 at 12 08 26 am](https://cloud.githubusercontent.com/assets/979542/9981082/41b454c4-5ff5-11e5-9d99-927b4a8d3dc2.png)

**Comment by IndrekV** [comment]
To report issues about the web app, please use the help page feedback form inside the web app. Help page can be accessed from the `?` mark on the top right.
