### ISSUE TITLE
add Kanboard support

### ISSUE THREAD

**Issue by thob** [toggl/toggl-button#329]
would be very helpful > https://github.com/fguillot/kanboard

**Comment by IndrekV** [comment]
As the number of integrations is already more than 40 we have decided not to add any integrations ourselves. We do how ever welcome all pull request of new tools. I will add this link to our challenge page that show all asked and not implemented tools. There is a guide on how to add a new integration to Toggl Button at https://github.com/toggl/toggl-button/wiki/Adding-new-integrations
