### ISSUE TITLE
Context menu entry

### ISSUE THREAD

**Issue by orschiro** [toggl/toggl-button#332]
Dear all, 

Would it be possible to add Toggl to Chrome's right mouse click context menu? 

This way, users of [Gmail Offline](https://chrome.google.com/webstore/detail/gmail-offline/ejidjjhkpiempkbhmpbfngldlkglhimk) would be able to launch a timer directly from within Gmail. 

Thankfully,

Robert

**Comment by IndrekV** [comment]
Hi Robert, 

Thank you for your request. We don't currently have any offline functionality in Toggl Button so adding offline mode would be a much bigger task than just adding item to context menu. I do like the idea thou and will look into this.

**Comment by orschiro** [comment]
Hi @IndrekV,

I appreciate your response! Actually, Gmail Offline can also be used while being offline. I use it over the standard Gmail interface because it is amazingly fast. 

Thus, it would be possible to use Gmail Offline together with Toggl while being online if Toggle was to support Gmail Offline (through the context menu entry) and thus any other possible site. 

Warmly,

Robert

**Comment by IndrekV** [comment]
Ok, I will look into it and see if this is something that can be added to the extension.

**Comment by orschiro** [comment]
@IndrekV 

Thanks! I could foresee how many websites could potentially benefit from it for which Toggl doesn't provide a button yet.

Warmly,

Robert

**Comment by orschiro** [comment]
@IndrekV,

Cool, thanks a lot for implementing my request so quickly. Very appreciated! :+1: 

~ Robert
