### ISSUE TITLE
Update webstore screenshots

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#345]
Change the order of logos according to analytics

Also add Salesforce,Draftin, FogBugz logo

Analytics show that most important tools are:
- Trello
- Asana
- Jira
- Todoist
- Google mail
- Google docs
- Toodledo
- Google calendar
- Pivotal Tracker

Salesforce should also be in the top as it was just added and has a lot of potential.

These tools should be more visible either in the top row or some other way.

**Comment by pe0ny** [comment]
![toggl-button-screens-2](https://cloud.githubusercontent.com/assets/5064445/11742148/e2cfab0e-9ffd-11e5-8b32-d218e0c5de99.png)

**Comment by IndrekV** [comment]
Added to webstore and updated KB article.
