### ISSUE TITLE
Add login with Google

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#347]
http://stackoverflow.com/questions/7217137/chrome-extension-login-best-practices
https://developer.chrome.com/apps/app_identity

**Comment by Clijsters** [comment]
+1 'causeiIf you register at Toggl with your Google Account you aren't able to log into Toggl Button.

**Comment by langri-sha** [comment]
@Clijsters the experience is a bit flaky, but signing in on Toggl should also authorize the extension, even if you authenticated with Google Accounts.

**Comment by mbifulco** [comment]
I use Google login for my toggl account, but typcially don't log into my google account on my main chrome windows (Instead, I use an incognito window for that org, for reasons not worth getting into here).  It'd be really nice to be able to log in through the extension, keeping it separate from what's going on in a given browser window.

**Comment by shantanuraj** [comment]
Closed via #1367
