### ISSUE TITLE
Button doesn't show up in new GitLab design.

### ISSUE THREAD

**Issue by ramboldio** [toggl/toggl-button#349]
![screenclip](https://cloud.githubusercontent.com/assets/5238799/10512153/8019e498-733e-11e5-8ac3-f44b289ac959.png)

**Comment by IndrekV** [comment]
I just checked a public project on gitlab and it seems to work for me.
Make sure you are logged in to Toggl.com or Toggl Button and that you use the supported domain address. Toggl Button supports the default gitlab domain `*.gitlab.com/*`

https://gitlab.com/gitlab-org/gitlab-ce/issues/3083
![screen shot 2015-10-16 at 14 23 47](https://cloud.githubusercontent.com/assets/842229/10540551/aabd53d2-7411-11e5-94f9-0ed8d9c7a091.png)

**Comment by IndrekV** [comment]
I tested gitlab and the design has not changed. It is a permissions issue.

For anyone having the same issue try to uncheck the gitlab permission checkbox and then recheck it again. This will refresh the permission and should fix it.

**Comment by PaoloFalomo** [comment]
@IndrekV i did that but didn't worked for me. only adding a custom permission as `*.gitlab.com/
*`. For more debug i am available at info@paolofalomo.it :)
