### ISSUE TITLE
Show indicator when websocket is not working

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#357]
Maybe show a dot on the icon. (Only if websocket is enabled)
- `Green dot` working ok
- `Red dot` not working 

Also show same status in Settings view.

In there show two statuses:
- Websocket ok/down
- Api connection ok/down

**Comment by tcrammond** [comment]
Future plans will hopefully make the whole sync thing more solid and not need symptom checkers like this, closing.
