### ISSUE TITLE
Investigate Creating Firefox extension

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#360]
http://stackoverflow.com/questions/17967442/convert-google-chrome-extension-to-firefox
https://hacks.mozilla.org/2015/10/porting-chrome-extensions-to-firefox-with-webextensions/
https://blog.mozilla.org/addons/2015/08/21/the-future-of-developing-firefox-add-ons/

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Chrome_incompatibilities
https://wiki.mozilla.org/WebExtensions

- [x] Fix opening Settings 31719b33b2cae991f933b894d5db965dcac0cd7f
- [x] Fix settings design 762394bd4b2a9683f2f6722e5b775baad30fb8b6
- [x] Fix popup resize issue when switching to edit form (https://bugzilla.mozilla.org/show_bug.cgi?id=1215025) (Currently no fix, we keep the size always the same be85fcaac26fb960c171373a00e16a32d1df93de
- [x] Test functioning of all settings and hide the ones that are not supported
- [x] Fix project dropdown opening. #580
- [x] Add back Bugsnag

**Comment by claytonrcarter** [comment]
Yes, please!

**Comment by DrColossos** [comment]
:+1:

**Comment by ginfuru** [comment]
:+1:

**Comment by dan-santana** [comment]
:+1:

**Comment by BrianGilbert** [comment]
Currently uses API's and permissions not supported by Firefox.
![monosnap 2016-05-27 11-18-43](https://cloud.githubusercontent.com/assets/114017/15596493/489ca554-240b-11e6-9640-da648567f191.png)

**Comment by IndrekV** [comment]
Yes it probably needs some work to either disable the unsupported API's or replace with the Firefox versions.

**Comment by aairey** [comment]
It's closed ... so abandoning Firefox?

Please kindly look into this as it is a blocker for us at our company.

**Comment by leafi** [comment]
Hi - the Firefox version is still in progress. IndrekV will be able to tell you better, but I believe it's still a ways off.

**Comment by bbinet** [comment]
As a firefox user, I'm also interested to know if porting toggl-button to Firefox is still on the roadmap.

**Comment by aairey** [comment]
I am using [this](https://gitlab.paragon-es.de/groups/toggl-button) for now. 

However the implementation is not the same.

**Comment by bbinet** [comment]
Does it support Trello?

**Comment by aairey** [comment]
No, but you can ask @jurgenhaas to implement by creating an issue on his GitLab.

I managed to get JIRA supported like that. ;)

It's a nice project, however I still hope to see an official Toggl-Button add-on in Firefox.
It is good as a workaround for the time being.

**Comment by bbinet** [comment]
thanks @aairey, I've create an issue on Gitlab: https://gitlab.paragon-es.de/toggl-button/general/issues/1
