### ISSUE TITLE
Allow users to add custom permissions

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#361]
Would remove the need to maintain customised extension if user uses integrations with custom domains

https://developer.chrome.com/extensions/permissions

**Comment by IndrekV** [comment]
Custom permissions can be added on runtime, but not content_script matches. To execute content scripts we need to bring back the `tabs` permission.

Then we check if url is in the permissions list and execute the service js that it's connected to.

tests in stash `permissions`

**Comment by DrColossos** [comment]
There is a fork that does this: https://chrome.google.com/webstore/detail/toggl-button-for-custom-w/cblhgnnnpnonkonnfcfkfhhkoldjpdno We had to use this extension since using it on *.redmine.org makes no sense for our self-hosted version so a solution like the fork would be very appreciated.
