### ISSUE TITLE
Pomodoro updates

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#362]
- [x] Show progress somehow. Like in the popup ad a progressbar or in the extension icon.
- [x] Add more settings. User can define if the timer stops when time ends or just notifies and keeps tracking.
- [x] Restart timer continues the exact same entry that was running last. (should maybe be setting)

**Comment by pdxrlk** [comment]
I agree with these, and I'd add:

- Add support for short (5 min) and ling (15 min) breaks. 

Right now, when I "take a break" the timer stops, and that's it. I need to remember to focus again in 5 minutes. It's much more useful IMO if "take a break" initiates a true break timer (with a "Back to work" button when done).

**Comment by IndrekV** [comment]
Comment from user

>It would be even nicer if once toggl stopped the timer after 25m, the next restart notified you of 5m (or a set break time). I suppose turning off the time on that second stretch could be a hassle for some people, but just a ping saying break time is up would be great. There’s no visual on the actual timer, so it’s easy to go over your break time.

**Comment by rosshinkley** [comment]
@pdxrlk @IndrekV I might even go a step further and say the break time should be customizable and also be tracked.  Breaks ought to be functionally equivalent to a pomodoro, complete with the reminders at the end.  I like the "back to work" button idea for this.  Thoughts?

**Comment by IndrekV** [comment]
I've already started looking into the possibility of adding a break timer that notifies when it's time to start tracking again.

**Comment by eatskolnikov** [comment]
@IndrekV how about this to show the progress, using a badge (https://developer.chrome.com/extensions/browserAction#badge) we could show the remaining time in text and i propose the following rules:

If the time is greater or equal to 100 minutes (is an edge case but bare with me) show 99+m 
![screen shot 2016-04-04 at 10 22 12 pm](https://cloud.githubusercontent.com/assets/1693000/14269606/3bd4e514-fab4-11e5-8a81-49114c313efe.png)
If the time is less than 100 minutes then show the number of minutes remaining like this: 25m 
![screen shot 2016-04-04 at 10 22 55 pm](https://cloud.githubusercontent.com/assets/1693000/14269611/50f047b8-fab4-11e5-9081-d4f245ad2765.png)
If the time is less than a minute start counting the seconds: 39s
![screen shot 2016-04-04 at 10 23 17 pm](https://cloud.githubusercontent.com/assets/1693000/14269616/635ae3a4-fab4-11e5-97ed-e2f1543ade65.png)

**Comment by IndrekV** [comment]
I like the idea. Currently we use the badge to show that app is not logged in. It might conflict and be confusing using the badge for multiple things. If we can figure out how to show `logged out` state differently then we could use the badge for pomodoro progress.

One solution would be to create a different icon for logged out state.

This is a really good idea @eatskolnikov

**Comment by eatskolnikov** [comment]
Cool, I'll proceed to add the badge timer once #514 is dealt with

**Comment by IndrekV** [comment]
I've looked into this a bit more and one solution would be to use canvas in the browser icon. It is possible to animate the icon with canvas but I'm not sure how easy it is. I will do some more digging and if the animated icon is not possible we'll proceed with the badge solution.

I've thought about the logged out icon also. The logged out state could be black icon to separate it from the other states.

**Comment by eatskolnikov** [comment]
@IndrekV I'll look into the canvas thing too

**Comment by eatskolnikov** [comment]
I added two PRs regarding showing progress with canvas, #523 and #528. I feel like #528 looks better.

**Comment by IndrekV** [comment]
closed with 90718c2ec5a5084dd73e16083b6063ef9d6254bd
