### ISSUE TITLE
No longer working with latest JIRA Software version 

### ISSUE THREAD

**Issue by dhilgarth** [toggl/toggl-button#363]

**Comment by fillup** [comment]
I'm also having this problem with Jira v6.3.14

**Comment by allanlewis** [comment]
I'm not seeing the button on v6.3.15 or v6.4.7.

**Comment by IndrekV** [comment]
I'm unable to reproduce this issue. I tested with demo projects. For example this url
https://jira.atlassian.com/projects/CRA/issues/CRA-1342?filter=allopenissues

JIRA version seems to be 7.1.2

**Comment by dhilgarth** [comment]
OK, I see the button there as well. But what about my own installation on my own server?

**Comment by IndrekV** [comment]
Currently custom domain addresses are not supported. It is planned to be added in coming months.

If you really want to use custom domain addresses right now you would have to create your own version of the extension. There is a guide with instructions: https://github.com/toggl/toggl-button/wiki/Adding-custom-domains
