### ISSUE TITLE
Button isn't displayed in Redbooth

### ISSUE THREAD

**Issue by fonorobert** [toggl/toggl-button#368]
Redbooth has done a redesign lately, this is probably the reason

**Comment by fonorobert** [comment]
update:
Toggl Button is not visible when task is opened in modal

**Comment by IndrekV** [comment]
Might be connected to #142

**Comment by pmcgriff** [comment]
Be nice to see this fixed.

**Comment by IndrekV** [comment]
Fixed with 97bfb9d0126354193cef224b97b1bfccdde783f8
