### ISSUE TITLE
"Done" Button isn't displayed when i add tags on timer

### ISSUE THREAD

**Issue by JohnyNogueira** [toggl/toggl-button#371]
![toggl](https://cloud.githubusercontent.com/assets/5831242/11146251/d863fb18-89f3-11e5-89ec-0af28e3d0270.png)

Windows 8, Chrome 48.0.2561.0 canary (64-bit),

Using chrome extension, when i start time, 'done' button is not visible, but timer is started, this is so stranger

**Comment by IndrekV** [comment]
If you save the tags by clicking on "Save tags", tag selection closes and you can see the done button.
