### ISSUE TITLE
Pomodoro timer re-enables after restart (0.7.5)

### ISSUE THREAD

**Issue by xtoq** [toggl/toggl-button#377]
The Pomo timer doesn't play nicely with the desktop app (I haven't really done much troubleshooting, sorry!) and I prefer the timeline to the timer so I disable the Pomo timer from the Toggl button options in Chrome. The thing is, it re-enables itself after a restart and then messes up my timers.

Steps to reproduce
-----

1. Disable "Pomodoro timers" in Toggl button options (version 0.7.5)
2. Restart Chrome

Expected outcome
-----

- Chrome restarts and Toggl button Pomo timer is disabled

Actual outcome
-----

- Chrome restarts and Toggl button Pomo timer is enabled

Additional information
-----

- Version 0.7.5
- Happens when Toggl is the only extension/addon installed/activated in Chrome as well as with my full extension set.
- I'm using desktop timer at the same time, but it should not have an effect on the Chrome extension settings.

**Comment by IndrekV** [comment]
Thank you for the feedback I will investigate this.

**Comment by IndrekV** [comment]
This issue is similar to #380 and is fixed with aa008bfbde79cbb83839121bb3dca179c47df19f

**Comment by xtoq** [comment]
Any word on when this will be available in the Chrome store? (Can't install from GitHub for...dumb reasons...)

**Comment by IndrekV** [comment]
Release is planned to the middle of the week.

**Comment by xtoq** [comment]
Thanks! Really appreciate the quick fix. =D
