### ISSUE TITLE
Idle detection re-enables with every Chrome restart

### ISSUE THREAD

**Issue by neonkowy** [toggl/toggl-button#380]
When I'm restarting Chrome, I get "Idle detection" working every time. Magic happens when I try to disable it in settings. I open settings and it's checked, so I click it to disable. But then click is registered and it's still checked.

My assumption is that it wrongly shows ON state while checkbox internally knows i disabled it earlier, so with second click it goes to OFF state.

When I close and open settings before restarting browser, everything's fine and Idle detection is disabled.

Please give me instructions, how can I provide more information on that bug.

**Comment by IndrekV** [comment]
Thank you for reporting, there was indeed an issue with loading the settings properly.
