### ISSUE TITLE
Toggl button doesn't stop at 25 m for Pomodoro mode since today's update

### ISSUE THREAD

**Issue by dshan** [toggl/toggl-button#386]
It just keeps going.

**Comment by IndrekV** [comment]
I'm unable to reproduce this. Could you go more into detail.

Do you start the timer in Toggl Button or somewhere else?
Screenshot of settings would help.

Any other details to replicate this issue.

**Comment by IndrekV** [comment]
The Toggl Button Pomodoro timer works only if timer is started in Toggl Button and not in another Toggl app.
