### ISSUE TITLE
Show 5 latest unique entries so user can continue any of them

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#388]
Should be shown in the dropdown. 
Add `Continue entry` item that extends when hovering and shows the 5 most recent unique entries to choose from. Clicking on any of them starts the timer with the entry data.

**Comment by mjomble** [comment]
For a simpler version, a "Continue last entry" button would be very useful.
Especially when the Pomodoro popup has disappeared by the time you're ready to continue.

**Comment by syko** [comment]
I believe we have implemented this.
