### ISSUE TITLE
Custom site for Toggl button

### ISSUE THREAD

**Issue by usrbowe** [toggl/toggl-button#395]
Hi,

what is the best way to add Toggl button support for some internal website? Should I make copy of this repo and add JS for custom site, or is there some other way? Or do you plan add some support for adding custom scripts for sites manually via add-on.

Thanks

**Comment by IndrekV** [comment]
Hi,

If you want to use a tool not supported by Toggl Button you'll have to create a new extension. See this guide on how to add new site to the extension https://github.com/toggl/toggl-button/wiki/Adding-new-integrations
