### ISSUE TITLE
Add default project setting

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#396]
Might be useful when starting entries from dropdown.

**Comment by JoelAzaria** [comment]
If I had a 100 votes **I think I'd use 99 for this.**

Big time saver for us as we have about 60 checklist items we run through between my assistant and I (and time each one daily, typically 2-5 mins each, sometimes two or three times before it's complete.) 
These all start from a Trello card Checklist where the Project and a Tag would be consistent every single time every single day.  In fact keeping the project and tag consistent on each of these timers without human error/intervention is probably even bigger than just the time save/lazy factor.

So summary:  would be great to set both a default Project and default Tag(s) for a given item.

Remembering the last used selections could be good as an implementation I think.  Perhaps a simple check box to the effect of "Save these as default" on the Toggl Button dropdown would work out well or maybe a "split" DONE button. (see attached mock ups as examples)

![toggl default project tags mockup](https://cloud.githubusercontent.com/assets/470908/12040541/ed52e242-ae37-11e5-9c50-c8b6db977b15.png)
![toggl default project tags mockup alt](https://cloud.githubusercontent.com/assets/470908/12040544/f15eaeca-ae37-11e5-88bf-1ad81c492748.png)
