### ISSUE TITLE
Support for Gmail Inbox?

### ISSUE THREAD

**Issue by orschiro** [toggl/toggl-button#399]
Dear all, 

Is it possible to add a support for the new Gmail Inbox interface to start a timer directly from within an email conversation?

Thankfully,

~ Robert

**Comment by IndrekV** [comment]
Thank you for the suggestion. This looks definitely something that needs to be added.

**Comment by orschiro** [comment]
@IndrekV 

Thanks for your positive response. 

I look forward to a first test release!

Warmly, 

~ Robert

**Comment by oktayacikalin** [comment]
:+1:

**Comment by IndrekV** [comment]
There is actually a pull request for this #422 . Pull requests will be reviews starting from next week.
