### ISSUE TITLE
Create the description from selected text?

### ISSUE THREAD

**Issue by orschiro** [toggl/toggl-button#404]
Dear Toggl team, 

I've just had an idea how (maybe) Toggl could extract the description from a text selection. 

I demonstrated the possible workflow in this video screencast: 

https://www.youtube.com/watch?v=I7mQTl4PpWo

Would this be technically possible?

Thankfully,

Robert

**Comment by IndrekV** [comment]
Thank you for the feedback. We actually have similar thing already. We added context menu item that can start timer with selected text. See this animation.

![context-menu](https://cloud.githubusercontent.com/assets/842229/11865769/e3d848a2-a4ae-11e5-84e5-e14ce03de633.gif)

**Comment by orschiro** [comment]
Dear @IndrekV,

This is working perfectly. 

Thank you for your animation!

~ Robert
