### ISSUE TITLE
Show time tracked in Asana tasks and Project views

### ISSUE THREAD

**Issue by nsudds** [toggl/toggl-button#416]
It would be great to see the time tracked within the Asana task and project views.  I love how Toggl works but not being able to see the time tracked in context makes it only so useful. 

Other timing apps like Everhour have this feature but I prefer Toggl's timing features and reporting. 
Example - https://luna1.co/795348.png

**Comment by IndrekV** [comment]
We are currently adding this feature to Trello and if the basics are done it should be easy to add the feature to other tools. The main issue is #414 

I'll add Asana to the list of integrations that need this feature.

**Comment by nsudds** [comment]
That's brilliant, I've been inspired by all the activity that I saw recently on this project -- I've been watching it and noticed your comment about adding this to Trello so that's what triggered my request.   Thanks @IndrekV !  I use Trello sometimes too so if I can help with testing let me know.

**Comment by dthowell** [comment]
@IndrekV - Any updates on this for asana? It's exactly what I need for my project management see the time against the tasks and projects :)

**Comment by IndrekV** [comment]
@dthowell This feature has been put back into the ideabox. The first solution that was done for Trello used local data that meant that you would only see the sum of your own trackings. This was not a good solution and we decided to drop it. Currently there is no clear date for this feature to be added with the full functionality. Thank you for showing interest.

**Comment by tcrammond** [comment]
Closing this one now, any future development will be in #508.
