### ISSUE TITLE
Git Squashing

### ISSUE THREAD

**Issue by oliverdunk** [toggl/toggl-button#420]
Hi,

This is more of a code style request more than anything. There's a command called 'git squash', which allows you to merge down a series of commits into one final commit which can be used for your pull request. You can even use the 'git push --force' command on your fork to do it after the PR has been created.

Rather than merging PRs and getting a huge number of user generated commits which don't explain changes well, perhaps it would make sense to ask people in the README to always squash their PRs?

**Comment by IndrekV** [comment]
Thank you for the insight. I've added a note about this to the readme and the "Add new integration" guide.
