### ISSUE TITLE
Red border?

### ISSUE THREAD

**Issue by oliverdunk** [toggl/toggl-button#421]
Had an idea,
Thought gathering some feedback before actually implementing it might make some sense. How about an option which could be enabled, that would add a red border around every page if you were timing? For some people this may be annoying, but I feel for others that it'd be a good reminder that they were still being tracked.

Open to ideas, and if you think this is terrible, be honest! I can take it.

**Comment by IndrekV** [comment]
I think it's too "In your face" to have red border on all the pages. I like the idea of always being aware that time is tracking, but I think the red border is too much. Right now the red color of the extension icon is indicating that timer is running.
