### ISSUE TITLE
Add YouTrack

### ISSUE THREAD

**Issue by edzis** [toggl/toggl-button#43]
For an example repo please see http://youtrack.jetbrains.com/issues

As an extra it would be great to store the time spent also in YouTrack using http://confluence.jetbrains.com/display/YTD5/Create+New+Work+Item
Their API authorization is based on Cookies - http://confluence.jetbrains.com/display/YTD5/Log+in+to+YouTrack

**Comment by beinnova** [comment]
Hi,
Can I use toggl button on private (but on public domain) Youtrack installations?

**Comment by IndrekV** [comment]
Currently it is only possible if you add clone the repo and edit the code a bit. Here is a guide how to make it work https://github.com/toggl/toggl-button/wiki/Adding-custom-domains

We are however working on a solution that allows users to define custom domains in preferences without any need of making code changes. This will be probably ready in a few weeks.
