### ISSUE TITLE
Simple mode to quickly stop a running timer?

### ISSUE THREAD

**Issue by orschiro** [toggl/toggl-button#430]
Dear all,

I love the `https://www.toggl.com/app/timer` interface. It provides a great user experience. 

Nevertheless I would like to use the Toggl Button Chrome extension. 

What I am missing, however, is another setting for `General` which could be called `Simple mode`.

I imagine such a mode to stop a running timer with a simple click on the button instead of showing the pop-up.

This would have the advantage that one does not have to go back to the `/app/timer` interface to click stop, nor to open the pop-up of the button. 

What do you think?

Thankfully,

~Robert

**Comment by IndrekV** [comment]
I like the idea to make stoping timer as simple as possible. We will consider this when planning future developments. Thank you for your input.

**Comment by orschiro** [comment]
I am glad you like it, @IndrekV!

Looking forward to it. 

~Robert

**Comment by eatskolnikov** [comment]
@IndrekV  This just gave me an idea. How about adding a keyboard command? The command would stop the current entry and if there's no entry running it would continue the last entry. It could be something like: `ctrl+shift+t`

**Comment by IndrekV** [comment]
I like the shortcut idea. I'm not sure about the exact keys. T seems to be far from the other two. maybe something like `ctrl+shift+s` 

All the info about shortcuts https://developer.chrome.com/extensions/commands

**Comment by orschiro** [comment]
Wow really nice idea with the keyboard shortcut!

It would be cool if that was going to make it into the Desktop version, too. :+1: 

Warmly,

~Robert

**Comment by tcrammond** [comment]
We implemented a keyboard shortcut following this, closing.
