### ISSUE TITLE
Reminder should be disabled by default

### ISSUE THREAD

**Issue by plainclothes** [toggl/toggl-button#432]
This is a miserable thing to do by default. If I was only marginally less patient, I would have instantly uninstalled this without digging down to the options.

![screen shot 2016-01-21 at 09 35 48](https://cloud.githubusercontent.com/assets/10376510/12488954/da02502c-c022-11e5-87ab-bc994a19dbbe.png)

**Comment by IndrekV** [comment]
I've decided not to change the default setting. I've made the default time to be 60 minutes that makes more sense than 6 that was set before. 

Thank you  for your feedback.
