### ISSUE TITLE
Pomodoro goes one minute over time every time

### ISSUE THREAD

**Issue by ducedo** [toggl/toggl-button#449]
I've been playing around with the Pomodoro settings today and found that I get an additional minute independent of how many minutes I set. 1 -> 2 min, 2 -> 3 min, 5 -> 6 min. The timer just continues past the set time and stops with a notification when it's 1+ min over set time. I couldn't find anyone else mentioning the problem so I deleted the extension and re-installed it but I'm still getting the same issue. 

It's not a major issue since you can plan ahead and reduce the settings with one minute.

**Comment by IndrekV** [comment]
Thank you for reporting. We'll look into this.

**Comment by alepore** [comment]
confirm, i always have 26 minutes logs :)

**Comment by IndrekV** [comment]
Is this still happening with the latest version. I'm unable to reproduce this issue.

**Comment by ducedo** [comment]
Yes, just reinstalled and getting the same issue. Latest Chrome on latest OS X.
