### ISSUE TITLE
Make Project/Task selection UX more uniform across Button & Desktop

### ISSUE THREAD

**Issue by crashgordon** [toggl/toggl-button#462]
Currently project/task selection is somewhat counter-intuitive, as it varies between Button & Desktop.

**In Desktop**, tasks are listed under projects in project selection dropdown and are immediately selectable

**In Button**, task selection dropdown only becomes available when user has picked a project from project dropdown menu.

Would be less confusing/better UX practise if this selection worked the same way in both Desktop & Button.

**Comment by IndrekV** [comment]
Solved with #589
