### ISSUE TITLE
Replace our $ with $_ as some websites use jquery and it comflicts with our solution.

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#469]

**Comment by kretel** [comment]
Hi @IndrekV, Are you talking about function $ defined in common.js:5 ? 
thanks, Kris

**Comment by IndrekV** [comment]
Exactly. the $ conflicts on some tools with jQuery.

It would have to be changed in `common.js` and all the places that use it (all content script). 

Also all `document.querySelector` references can be replaced with `$_` after this replacement.

**Comment by IndrekV** [comment]
This is actually not needed as the content scripts are kept separate from the regular javascript used on the page and can't conflict. I was getting conflicts when testing things in the developer console.
