### ISSUE TITLE
Pomodoro not working

### ISSUE THREAD

**Issue by usrbowe** [toggl/toggl-button#472]
I enabled Pomodoro in extension settings, set 25 minutes and then I start Toggl timer, but after 25 minutes of tracked time past, there is no notification that Pomodoro cycle has ended. 
Any idea why it is behaving like this? 

I am using version: 0.8.1

**Comment by IndrekV** [comment]
Could you please try to set the time to 1 minute and record a video of how it works or doesn't work in your case.

Note: Pomodoro timer works when timer is started from Toggl Button. Starting from any other Toggl tool will not work.

Also could you please specify what operating system you are using.

**Comment by usrbowe** [comment]
I didn't expect that it will work only from Toggle Button, litle bit unsuable for me. I am using primarily Toggle website app to track. 
So Pomodoro works for me when I start it from Toggle Button extension.

Any plans to add Pomodoro to all Toggle apps? (desktop, website)

**Comment by IndrekV** [comment]
Pomodoro is already available on windows desktop app beta version and will also be available for mac desktop app beta version.

You can change the channel to beta from the About view.

But it's a good idea to add support of time entries started from other Toggl tools to Toggl Button Pomodoro. I'll create a separate issue for that.

**Comment by usrbowe** [comment]
Good :+1: 

I had some issues with Toggl desktop for mac so I switched to Toggl web, but I will try beta channel now and I am giving it second chance because I like Pomodoro :smile:

**Comment by bitshiftnetau** [comment]
This should be reopened. Pomodoro alarm is broken across ios,osx, and web app in all browsers: Firefox, Chrome, Brave.

**Comment by ehballah** [comment]
Agreed. Doesn't (really) work for me on Mac desktop app. Timer functions fine, but it simply resets to 0:00 after 25 minutes, without notification of any kind. The task continues to be tracked as if there is no break.

**Comment by pedroTirado** [comment]
same here, running win11 home v.22H2 build 22621.1194; pomodoro break timer does not produce a notification / reset, instead it just keeps ticking... (toggl track windows desktop v8.3.1 64-bit)

**Comment by Intradiction** [comment]
Also running into the same issue on ios

**Comment by Dottyeyes** [comment]
Same problem with Windows. Made sure to open both with the app and then with the browser version, each one alone. In neither did the pomodoro timer function work. It had been working a month ago.
