### ISSUE TITLE
Make Pomodoro work also when timer was started elsewhere

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#477]
Probably should be a setting. If enabled pomodoro timer is triggered when info comes in about running timer.

**Comment by gianpaj** [comment]
As in for example starting the timer in the Toggl website? I agree with that.

**Comment by IndrekV** [comment]
Starting from anywhere else than Toggl Button. Website, mobile, desktop app, any other tool that connects with toggl API.
