### ISSUE TITLE
Have you considered supporting self hosted Jira?

### ISSUE THREAD

**Issue by erquhart** [toggl/toggl-button#479]
Two thoughts:

1) This may be possible by allowing users to specify urls for the extension to access in addition to those hardcoded in the manifest.

2) This doesn't automatically predispose the Toggl team to support the disparate versions of Jira that folks will try to use this with - you can encourage reporters of version related bugs to provide a PR that will make the extension work for their version. I personally wouldn't find this unreasonable.

Thoughts?

**Comment by IndrekV** [comment]
Thank you for taking the time to write your ideas down. We have plans to change this part of the extension. In the future it is possible to use any integration with a custom url. The url-s can be configured in Toggl Button settings. More details about this is described in issue #361
