### ISSUE TITLE
Toggl start and stop time in Breeze.pm doesn't show in Toggl account

### ISSUE THREAD

**Issue by lizkaraffa** [toggl/toggl-button#481]
I can track my time within Breeze using the toggl-button on a task, but when I'm in my account on Toggl viewing all my time entries, they don't show up.

**Comment by IndrekV** [comment]
I'm unable to reproduce this issue. Starting and stopping entries with clicking on the toggl button icon works as expected. Please make sure you click on the Toggl button icon to start timer. You can also check if toggl is tracking by opening the extension menu from the top right of Chrome.
