### ISSUE TITLE
Suggestion: hide or dim timer icons in Remember the Milk

### ISSUE THREAD

**Issue by xtoq** [toggl/toggl-button#499]
Thank you so much for adding support for the new Remember the Milk web app. 

However, I think the icon being visible from the task list has visually cluttered up the interface drastically. For example, this is a screenshot of my today list:

![toggl rtm](https://cloud.githubusercontent.com/assets/120364/13971423/2ebac8f4-f05e-11e5-8a75-3270443ed539.png)

Perhaps if the timer icon was gray when not running, and then only changes to red when actually running? I think this would decrease the visual clutter and also illustrate what task is currently running without compromising the speed with which one can start the timer on the RTM web app.

Thanks again for supporting RTM!

**Comment by billmccord** [comment]
There should definitely be an option to disable this. I use RTM for personal things that I don't intend to track and I don't want all of the Toggl noise in there.

**Comment by IndrekV** [comment]
@xtoq It's possible to make the start timer button style to minimal. This means that the "Start timer" text is not shown and the button is gray when not active.

@billmccord We are developing a solution where users can select tools they want to use with Toggl Button. This will allow users to only enable tools they need. It's already in development so will be available soon.

**Comment by xtoq** [comment]
Thanks so much for the fix! Looks great now.
