### ISSUE TITLE
Buttons appear multiple times on Wordpress.com

### ISSUE THREAD

**Issue by orschiro** [toggl/toggl-button#501]
Dear all, 

Can someone reproduce the issue that the Toggl Buttons are shown multiple times?

![nimbus-image-1459155222804](https://cloud.githubusercontent.com/assets/170947/14074952/dcd15184-f4cc-11e5-9d4d-f05b66e1d5e1.png)

Thankfully,

~Robert

**Comment by IndrekV** [comment]
This should not happen as we check that there is not button present before we add a start timer button. I cannot reproduce this. Could you give more details so I can investigate.

**Comment by orschiro** [comment]
Dear Indrek,

Thank you for your response.

I don’t know, however, which additional information to provide you with.

It concerns the posts as well as pages editor of a Blog hosted on
Wordpress.com.

Moreover, I am using the latest version of Toggl Button as well as
Chromium.

Does this help?

Thankfully,

~Robert

On Monday, March 28, 2016, Indrek V notifications@github.com
<http://mailto:notifications@github.com> wrote:

This should not happen as we check that there is not button present before
> we add a start timer button. I cannot reproduce this. Could you give more
> details so I can investigate.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/toggl/toggl-button/issues/501#issuecomment-202374538>
>
​

**Comment by IndrekV** [comment]
It seemed to happen when scrolling the page.

**Comment by orschiro** [comment]
Thanks for rolling out that quick fix!

Warmly,

~Robert
