### ISSUE TITLE
Add logos of new tools to our Chrome webstore screenshot

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#502]
Added tools are:
  <a href="http://phacility.com" target="_blank">Phacility</a>, 
  <a href="https://www.liquidplanner.com" target="_blank">LiquidPlanner</a>, 
  <a href="https://keep.google.com" target="_blank">Google Keep</a>, 
  <a href="https://inbox.google.com" target="_blank">Google Inbox</a>, 
  <a href="https://gingkoapp.com" target="_blank">Gingko App</a>, 
  <a href="https://wordpress.com" target="_blank">Wordpress</a>, 
  <a href="https://kanbanery.com" target="_blank">Kanbanery</a>, 
  <a href="https://planbox.com" target="_blank">Planbox</a>, 
  <a href="https://www.zoho.com/books/" target="_blank">Zoho Books</a>, 
  <a href="https://slack.com" target="_blank">Slack</a>, 
  <a href="https://doit.im" target="_blank">Doit.im</a>, 
  <a href="https://sunrise.am" target="_blank">Sunrise Calendar</a>, 
  <a href="http://cloudes.me" target="_blank">Cloudes.me</a>, 
  <a href="https://eproject.me/&quot;&quot;" target="_blank">eProject.me</a>, 
  <a href="https://freshdesk.com/" target="_blank">Freshdesk</a>, 
  <a href="https://www.newsletter2go.com/" target="_blank">Newsletter2go</a>, 
  <a href="http://devdocs.io/" target="_blank">DevDocs</a>, 
  <a href="https://www.sourcelair.com/" target="_blank">SourceLair</a>, 
  <a href="https://www.rememberthemilk.com" target="_blank">Remember The Milk</a>, 
  <a href="https://evernote.com" target="_blank">Evernote</a>, 
  <a href="https://www.mantishub.com/" target="_blank">Mantishub</a>, 
  <a href="https://www.proworkflow.com/" target="_blank">ProWorkflow</a>, 
  <a href="https://www.targetprocess.com/" target="_blank">TargetProcess</a>, 
  <a href="https://www.visualstudio.com/" target="_blank">Visual Studio Online</a>, 
  <a href="http://smartboard.cl" target="_blank">SmartBoard</a>, 
  <a href="https://www.atlassian.com/software/confluence" target="_blank">Confluence</a>, 
  <a href="https://gogs.io/" target="_blank">Gogs</a>
  <a href="https://www.openproject.org/" target="_blank">OpenProject</a>
  <a href="https://zube.io//" target="_blank">Zube</a>

**Comment by IndrekV** [comment]
#### MantisHub
![mantishub-icon-152x152](https://cloud.githubusercontent.com/assets/842229/14100381/a394ce7c-f595-11e5-8aad-1b699e635c3e.png)

**Comment by pe0ny** [comment]
New integrations:
![toggl-button-screens-new only](https://cloud.githubusercontent.com/assets/5064445/14104422/ccff664c-f5ad-11e5-8063-0a11188caf55.png)

All:
![toggl-button-screens-all](https://cloud.githubusercontent.com/assets/5064445/14104428/d6587e68-f5ad-11e5-8142-08d85363f748.png)
