### ISSUE TITLE
Toggl button on JIRA Server

### ISSUE THREAD

**Issue by lonnelars** [toggl/toggl-button#509]
We're using JIRA Server, and I would really like to have the toggl-button work here also. I have solved it for now by forking this repo and adding our addresses to `manifest.json`, but this is obviously not a scalable solution. 

If there is interest in solving this problem, I would be happy to submit a PR, but I would like to discuss the solution with you first.

**Comment by IndrekV** [comment]
Thank you for showing interest in this issue. We are already developing a solution for adding custom domains to the extension. By current plans it will be release during April. There is already an issue for it #361

Here is a screenshot of the main idea.

![tb_permissions](https://cloud.githubusercontent.com/assets/842229/14202908/67ba0bcc-f803-11e5-8998-991464b70891.png)

This is the initial version so it can change, but the main idea is the same. Provide user with the possibility to define their custom domains.

**Comment by lonnelars** [comment]
Great! Looking forward to the update :-)
