### ISSUE TITLE
Lint is broken

### ISSUE THREAD

**Issue by eatskolnikov** [toggl/toggl-button#513]
When I run 
```
make lint
```
I'm getting this error.
![screen shot 2016-04-04 at 11 52 38 am](https://cloud.githubusercontent.com/assets/1693000/14254037/0196f43a-fa5c-11e5-9966-127837a9c362.png)

**Comment by IndrekV** [comment]
Added back the package.json file 0f9c528308692fa4dc6953bc83d23fab6fbaa11a
