### ISSUE TITLE
No Toggl button in Trello only

### ISSUE THREAD

**Issue by xtoq** [toggl/toggl-button#517]
I no longer have a Toggl button on my Trello cards. This happened since ~22:00 on 2016/4/9 (18 hours ago-ish) as that's the last time I remember using the Toggl button in Trello to start a timer (I usually use the desktop version - hi Indrek!).

I still have the Toggl button on other sites like Remember the Milk, GitHub & Google Inbox.

I've disabled all my extensions and tried with no luck. I've cleared my cookies and cache with no luck. I've uninstalled and reinstalled the extension with no luck.

I have Toggl Button version 0.9.0 (most recent in Chrome web store) in Chrome 49.0.2623.112 m running on Windows 10 Professional (64-bit).

Please let me know if there is any more information I can give you! Thanks.

**Comment by IndrekV** [comment]
It seems Trello has updated their design. I'll fix this before next release.
