### ISSUE TITLE
Fix Settings height

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#521]
Currently the workday end time field is off screen and could be unnoticed.

**Comment by eatskolnikov** [comment]
@IndrekV I want to consult with you first on this one, how about this:

```js
$("#stop-at-day-end").addEventListener("webkitTransitionEnd", function(event) { 
 window.scrollTo(0,document.body.scrollHeight);
}, false);
```
This would make the window scroll to the bottom when the checkbox is clicked. Rendering the input field visible.

**Comment by IndrekV** [comment]
The logic was good just the `#stop-at-day-end` was not working. Thanks for the idea.
