### ISSUE TITLE
Workflowy integration?

### ISSUE THREAD

**Issue by DenisGorbachev** [toggl/toggl-button#533]
Hey, thanks for the handy extension!

It would be great to see a Toggl button in [Workflowy](https://workflowy.com/) - what do you think?

**Comment by IndrekV** [comment]
Thank you for your suggestion. We'll consider this request.

**Comment by DoWhatYouMust** [comment]
I also have this request. Workflowy now makes a move to becoming more task oriented with their plans to add reminders - https://medium.com/workflowy-design/dates-reminders-in-workflowy-2b1c6e0a057b#.vozdcba6j So Toggl integration will be in the same trend.

**Comment by mccataldo** [comment]
@DenisGorbachev @IndrekV @laisan, I use the autotracker feature in the native app to trigger a notification when navigating to Workflowy. In my case, I have a Workflowy list called Work and a trigger for "Work - Workflowy" for my Toggl project called Work.

**Comment by tcrammond** [comment]
We now have a Workflowy integration 🎉 #1335
