### ISSUE TITLE
configure plugin to work on premise installations

### ISSUE THREAD

**Issue by glensc** [toggl/toggl-button#534]
hi

your current approach of  configuring button to work on premise installation is rather hardcode for end users
https://github.com/toggl/toggl-button#custom-domains

look what i found:
https://github.com/buunguyen/octotree/blob/63e111e438927bef0cf2f41c516f768ab7cbb404/src/view.options.js#L43-L68

basically:
- user should visit site where toggl button exists (some already whitelisted url)
- open toggl settings dialog
- input some extra urls
- on "save" action plugin will request from browser extra permissions

such on premise installations include:
- trac
- gitlab
- eventum
- ...

**Comment by glensc** [comment]
looks like you managed to implement it in 1.0.0?
http://toggl.github.io/toggl-button/

1.0.0 May 26th 2016
- Implemented new permissions system
- Added possibility to enable/disable integrations from Settings
- Added possibility to define custom domains in Settings
- Fixed Remember the milk search issue
- Fixed Slack integration

was the idea and implementation from this ticket?

also seems the 1.0.0 is not published on github:
https://github.com/toggl/toggl-button/releases
... last tag is 0.9.2

**Comment by IndrekV** [comment]
It was in our roadmap for some time actually as it had been requested by multiple users. It took some time as it changed a big part of the content script executing part and needed thorough testing.

**Comment by glensc** [comment]
thanks for pushing git 1.0.0 changes out
