### ISSUE TITLE
Update logos image

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#535]
Replace MantisHub screenshot

#### OLD MantisHub
![mantishub-icon-152x152](https://cloud.githubusercontent.com/assets/842229/14100381/a394ce7c-f595-11e5-8aad-1b699e635c3e.png)

#### NEW MantisHub
![mantishub_logo](https://cloud.githubusercontent.com/assets/842229/14909917/6619e1d0-0df1-11e6-816c-f49981358816.png)

Add Logo for SalesForce Lightning:
![salesforce-lightning](http://www.topcoder.com/wp-content/uploads/2014/10/s1-lightning.png)

**Comment by IndrekV** [comment]
Please also change/add the logos in new integrations image as shown in issue #502

**Comment by pe0ny** [comment]
Updated image:
![toggl-button-screens-new](https://cloud.githubusercontent.com/assets/5064445/14948126/a80ddbe0-1045-11e6-9aaf-30ee036f4b14.png)
