### ISSUE TITLE
Possibly add Start timer to goals and reminders on Google Calendar pop-ups

### ISSUE THREAD

**Issue by artbypravesh** [toggl/toggl-button#544]
It works with normal calendar enties
![capture](https://cloud.githubusercontent.com/assets/4307967/15060726/ceacc98e-1381-11e6-82a2-93bc290c3bcb.PNG)

but it would be great to see it on goal reminders
![capture2](https://cloud.githubusercontent.com/assets/4307967/15060741/ef91d978-1381-11e6-86e8-fd1800353e46.PNG)

**Comment by IndrekV** [comment]
Thank you for the feedback. I will look into this. Shouldn't be very difficult to add.
