### ISSUE TITLE
[Request] Add the capability to show total task duration

### ISSUE THREAD

**Issue by wesf90** [toggl/toggl-button#545]
Other chrome-plugin timers that integrate with apps (such as asana) have the capability of showing the total time tracked against a particular task.

This wouldn't apply to all integrations, but it would for many: Asana, Todoist, Trello, etc.

For example, in asana, the tracked time would be shown inline with the task title (and possibly in the task pane).

![screenshot_050516_113839_am](https://cloud.githubusercontent.com/assets/1448304/15049813/eceacbfc-12b5-11e6-82d1-68056d392c5d.jpg)

**Comment by IndrekV** [comment]
We have plans to add this functionality. There is an issue for that #508

**Comment by tcrammond** [comment]
Closing in favour of the mentioned #508.
