### ISSUE TITLE
Google Keep integration should load tags automatically

### ISSUE THREAD

**Issue by damianavila** [toggl/toggl-button#547]
Hi, feature request... google keep let you tag cards and when I use the toggl, regrettably, I have to add the tags in the toggl tag field as well. It would be nice that the toggl button reads the tags on keep and add those into its own tag field.

**Comment by IndrekV** [comment]
I like the idea. I'll look into it.

**Comment by damianavila** [comment]
Amazing! Quick question, how is your release cycle? When this will be available? Thanks!

**Comment by IndrekV** [comment]
We have plans to release a new version next week.

**Comment by damianavila** [comment]
Thanks for the info!
