### ISSUE TITLE
Google Keep integration... start timer on checkboxes

### ISSUE THREAD

**Issue by damianavila** [toggl/toggl-button#548]
Hi... another feature request... generally a google keep card contains checkboxes with several different points/tasks. Right now, you can start the timer for the whole card, but it would be very useful if you can start the timer for each of the checkboxes representing the different tasks. On way to do it would be just allowing the card timer to offer a dropdown defaulting to the card title but also offering the possibility to select any of the checkboxes... thoughts?

**Comment by IndrekV** [comment]
With other tools we have solved it by adding start timer link behind every item. I think we would do the same with google Keep.

See wunderlist integration for example.
![wunderlist](https://cloud.githubusercontent.com/assets/842229/7767052/08e63e0a-0078-11e5-82b5-d37e64ae40fb.png)

**Comment by damianavila** [comment]
That would be a nice, I agree... it is the other UI I was thinking about... so if you want to follow that path... that would be amazing!

**Comment by damianavila** [comment]
Is there any update on this feature request? Thanks!

**Comment by damianavila** [comment]
Thanks!!
