### ISSUE TITLE
Starting timer via context menu with empty selection should use website's title as description

### ISSUE THREAD

**Issue by dasilvacontin** [toggl/toggl-button#552]

**Comment by dasilvacontin** [comment]
Why: easy access. And an entry with no context/description is not so helpful.

**Comment by AlexNetman** [comment]
May be page name is better.

**Comment by dasilvacontin** [comment]
@AlexNetman Just in case, I mean the title as whatever is defined inside `<title></title>` in the `<head>`. Is that what you meant as well?

**Comment by dasilvacontin** [comment]
Thanks @IndrekV!
