### ISSUE TITLE
Improvements for Toggl Button public page

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#554]
Currently public page has only simple html changelog.

Design should be updated to simple clean Toggl related design.

Page should be converted to Jekyll for more simple maintenance. Also all images should be lazy loaded to make the page load faster.

Improved page should have following sections:
- Changelog
- Where can I find the button page
- Guides that are currently in the wiki
- documentation ( low priority )

**Comment by IndrekV** [comment]
Changelog should be generated from json data. That way it is easy to create automatic changelog generator script.

For loading changelogs from different files
http://stackoverflow.com/questions/17446472/how-to-list-files-in-a-directory-with-liquid

**Comment by tcrammond** [comment]
All of this has moved far along now 🎉 closing this issue
