### ISSUE TITLE
Slack integration fix

### ISSUE THREAD

**Issue by AlexNetman** [toggl/toggl-button#555]
According to the screenshot in guide - Slack should work like this:
https://cloud.githubusercontent.com/assets/842229/13951706/61d9cab4-f03b-11e5-937c-16a789ad704f.png
But I don't see any button on page.

**More over:** 
Would like to have the Toggl button next to each message.
So that I can start tracking when somebody ask to check something.
And time entry will be like "[Channel name] - message text"

**Comment by IndrekV** [comment]
Slack integration was fixed with b4e4ddd3f893c9f4430e234bb57cad7f41843766

We will not be adding timer link next to each message as it would add too much noise to Slack.

**Comment by AlexNetman** [comment]
Regarding enhancement: button could be added without visual noise. So that it appear on hover over message along with other options.
See example:
![image](https://cloud.githubusercontent.com/assets/4558228/16800873/2a57dd24-4900-11e6-8e7f-48f3c6b7c796.png)

And what about b4e4ddd: 
I see you are using different version of Slack.
My version is looking like this:
![image](https://cloud.githubusercontent.com/assets/4558228/16801284/7b51b7ac-4902-11e6-8254-98a47c88a4d9.png)
![image](https://cloud.githubusercontent.com/assets/4558228/16801490/952db896-4903-11e6-8452-4b3fa05537d6.png)
