### ISSUE TITLE
Todoist: use project name for Toggl project name when starting timer

### ISSUE THREAD

**Issue by tomchambers2** [toggl/toggl-button#557]
![image](https://cloud.githubusercontent.com/assets/4549380/15566095/e0b05bba-2316-11e6-9fae-21d0ab07c31f.png)

it would be great if the project name was used by Toggl, so that if I started this task it would automatically be matched with the 'Emotional Mirror' project I have in Toggl.

**Comment by IndrekV** [comment]
If task is assigned a project it will be matched. Note that it will do exact match so the project name should be exactly same (case sensitive) in Todoist and Toggl.

In your case if you would have project with name `emotional mirror` in Toggl it should match successfully.

**Comment by tomchambers2** [comment]
Great! I'll give that a go.
