### ISSUE TITLE
Custom domain url permissions should allow port specifications

### ISSUE THREAD

**Issue by cori** [toggl/toggl-button#564]
internally hosted instances of some ticketing systems are often hosted on a specific port. For example I work with a client who uses atlassian jira at a non-standard http(s) port. When adding a custom domain with a port the addition activity doesn't work (although when the domain is added without the port the Toggl button _does_ appear on the jira issue pages).

There seem to be a few options here:
1. accept and respect the port. This would be the preferable choice in cases where someone might want to enable the integration at a site on one port but not at a site on another port on the same host.  That seems like an edge case, though.
2. accept the addition with the port but either don't save it or save it for display but only use the host for the integration - in either case some user communication indicating what has transpired would be useful
3. do not accept the port but tell the user what's happened either in the description text or in an error message. This might be the easiest

Failing silently, as it does now, seems like an unfriendly option, though.

**Comment by IndrekV** [comment]
Thank you for the feedback I'll look into it. I think we should add support for ports.

**Comment by cori** [comment]
Probably closeable, but I added a couple of comments on the attached commit....

**Comment by Intellemerc** [comment]
Curious if/when this will be available in the main release?

**Comment by cori** [comment]
In my experience this is now working - I've got an internally-hosted instance of Jira on a custom url:port and the button shows up on those pages.

**Comment by langri-sha** [comment]
Thanks @cori. Could you please open up a new issue for https://github.com/toggl/toggl-button/commit/4c7665bfab1673c86c544586d6ae46584fcfe4dd#commitcomment-18655212 if you need improved support :bowing_man:.
