### ISSUE TITLE
Broken Youtrack integration AKA.myjetbrains

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggl-button#565]
"I have lost the youtrack (myjetbrains.com) integration with toggl using the chrome extension.

I used to be able to open a ticket and click the toggl button within the
ticket.
I have tested trello and it seems to be working there fine.

I have enabled all permissions."

CASE ID: 294694

**Comment by sanyatuning** [comment]
for me too 
https://AKA.myjetbrains.com/

I've tried to add custom domain "AKA.myjetbrains.com"
Not worked for me

Ubuntu 14.04
Browsers:
* Google Chrome
* Chromuim
 
google calendar works fine

**Comment by IndrekV** [comment]
Fixed with daebc3e7eeafdaaa22302e0aa72fce55e67b060b

Will be available with next release. (Release planned for the end of this week)

**Comment by sanyatuning** [comment]
thanks ;)
