### ISSUE TITLE
JIRA: JS conflict in issue filtering

### ISSUE THREAD

**Issue by AlexNetman** [toggl/toggl-button#566]
Go to search by Jira issues
Expected to see Basic filters by default
But they are not loaded
Only able to use Advanced filters

Filters in sidebar are not loaded.

![image](https://cloud.githubusercontent.com/assets/4558228/15691448/7ccc2c8a-2791-11e6-8560-7072bbabed2a.png)
The error below appear only with plugin enabled
![image](https://cloud.githubusercontent.com/assets/4558228/15691649/affc6f6a-2792-11e6-8c0f-32c23c67ebd0.png)

**Comment by IndrekV** [comment]
Are you sure this is connected to Toggl Button. The scripts from Chrome extensions are executed in different sandbox then the regular javascript on the page and it should not be possible for the two of them to conflict each other.

**Comment by IndrekV** [comment]
Hi, It seems that this is not connected to Toggl Button Chrome extension but the Toggl plugin for JIRA that is not an official Toggl product. You should contact the developer of this plugin with this issue.

**Comment by AlexNetman** [comment]
UP: Issue was resolved with clearing local storage for domain.
