### ISSUE TITLE
What is the "Read your browsing history" needed for?

### ISSUE THREAD

**Issue by michaelblyons** [toggl/toggl-button#568]
The "Toggl needs new permissions" dialog says it needs to read my browsing history. Why do you need this? What is it used for?

**Comment by IndrekV** [comment]
With the latest release we've added the possibility to define custom domains. This allows users who run the tool on their private server to also use the benefits of Toggl Button. This change required adding of the tabs permission (https://developer.chrome.com/extensions/tabs)

What this does is check if the current url in the tab is defined in Toggl Button and adds "Start timer" button if the answer is positive.

The only place this is used is in function `tabUpdated` that is visible in https://github.com/toggl/toggl-button/blob/master/src/scripts/background.js#L1309

**Comment by davordragic** [comment]
Why did this permission become mendatory in 2023?

**Comment by jdeanwallace** [comment]
Fixed in Chrome extension version 3.0.21 and [docs updated](https://support.toggl.com/en/articles/4175845-what-data-do-our-locally-installed-apps-store#h_199ec1a1e1).
