### ISSUE TITLE
Add eventum to custom domain select box

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#569]
Also this origin should not be visible in the main list as it is used only on custom domains.

**Comment by glensc** [comment]
oh, i just wanted to report that providers that have no public appearance, i.e installed only on premises have no option to add custom domain for them.

could add entry to `origins.js`:
```json
  "eventum": {"url": "*://*.eventum.example.org/*", "name": "Eventum"},
```

but that's not very correct afaik.
