### ISSUE TITLE
Toggle Button no longer showing up in Visual Studio Online

### ISSUE THREAD

**Issue by thomasonb** [toggl/toggl-button#572]
Since the latest update, the toggle timer button at the top of visual studio tasks/stories/features/etc... is not showing up. The right click menu is still there, but it doesn't automatically start the timer for the thing you are working on, you can't set tags, you can't choose a project, etc...

![image](https://cloud.githubusercontent.com/assets/3091040/15760769/c0b3945e-28e2-11e6-8967-5115205280b8.png)

**Comment by IndrekV** [comment]
Thank you for notifying. The fix will be available with next release.

**Comment by thomasonb** [comment]
Thanks! How often do updates occur?

**Comment by IndrekV** [comment]
Next release will be at the end of this week.
