### ISSUE TITLE
Location of Start Timer link VSO

### ISSUE THREAD

**Issue by thomasonb** [toggl/toggl-button#582]
The location of the Start Timer link in Visual Studio Online is in a weird spot now (tested in Google Chrome Version 51.0.2704.103 m)

![image](https://cloud.githubusercontent.com/assets/3091040/16233486/8c971c54-379c-11e6-938e-2eb9795f83c1.png)

**Comment by IndrekV** [comment]
Thanks for the heads up. It seems VSO has updated their UI and it might have broken the integration. We'll look into it.
