### ISSUE TITLE
Toggl button for Opera Browser

### ISSUE THREAD

**Issue by kidush** [toggl/toggl-button#583]
I think it's so easy port a version of toggl button for opera. It uses the same engine that chrome, I guess. At the current moment I can only add the extension in Opera developer mode.

**Comment by IndrekV** [comment]
I've looked into it and it seems that it should be possible to install the chrome extension to Opera right from the Chrome Webstore. See this article http://www.techsupportalert.com/content/how-install-chrome-extensions-opera.htm

**Comment by kidush** [comment]
nice @IndrekV, thanks 😄
