### ISSUE TITLE
Create permalink to Toggl timer

### ISSUE THREAD

**Issue by leefogel** [toggl/toggl-button#584]
It is critical for each timer to have its own permalink which can be referenced in another sites (e.g. toggl.com/app/timer/[timer_hashcode]).

For example, I'm using the Toggl Chrome Extension to integrate with Trello. Even if injecting the Toggl timer's permalink into Trello automatically isn't (*yet*) possible, it is crucial for me to be able to manually add a permalink to the Toggl timer into a Trello card. I don't think such a permalink to an individual timer exists today.

**Comment by IndrekV** [comment]
Hi Lee,

This kind of functionality would require some big changes on the web app part. We currently do not have plans to add functionality that allows users to refer to a certain time entry. Currently only way to do something similar that you are asking is to create Bookmarks about entries and reference them. Here's an article about Bookmarks https://support.toggl.com/bookmark-reports/

**Comment by leefogel** [comment]
Makes sense. Nevertheless, this is a critical feature for me and in its absence I'll have to use another product.
