### ISSUE TITLE
Chrome extension causes significant typing lag in Google Docs

### ISSUE THREAD

**Issue by nbrewster-broadsoft** [toggl/toggl-button#586]
When editing large Google Docs documents with the Toggl Button extension enabled, I experience significant typing lag (delay between my typing something, and it appearing on the screen in the Google Doc).

Also, I experience scenarios like the following:

1. Copy something from the Google Doc into my buffer with cmd-c.
2. Move the cursor elsewhere in the doc.
3. Hit cmd-v to paste. Note, the content does not yet appear at this step.
4. Move the cursor again (with the arrow keys).
5. Later - sometimes several seconds later - the content pastes at whatever location the cursor is in at that moment.

I have disabled all extensions and then enabled them one by one to isolate Toggl Button as the culprit. 

Details:
Chrome version 51.0.2704.84 (64-bit)
OSX version 10.11.5 (15F34)
Toggl Button: Productivity & Time Tracker version 1.0.1

Statistics of my example Google Doc:

- Pages	21
- Words	4475
- Characters	27552
- Characters excluding spaces	23854

Note, I also have the "WalkMe Extension 1.6.5" (because my corporate policy prevents me from disabling it), but it does not seem related. The problem clearly appears/disappears when Toggl Button is enabled/disabled.

**Comment by IndrekV** [comment]
Thank you for the detailed report. I'll try to replicate the issue and work on a fix.
