### ISSUE TITLE
Bug: Custom Domain Permission Dialog shows only "ArgenoCRM" (v1.0.1)

### ISSUE THREAD

**Issue by endrebock-home24** [toggl/toggl-button#590]
Hi,

We're working internally with Jira on own domain. 

**Problem**
The dialog to add the show only "ArgenoCRM" and no other System is selectable.

**Expected**
It would be good, to have all allowed sites also selectable for custom url.

**Workaround**

1. Add Custom URL as "ArgenoCRM"
1. Close all chrome instances
1. Edit the field `ToggleButton` in chromes local storage and change "ArgenoCRM" to wantet one (eg. "atlassian.com")
1. Start Google Chrome and see that button appear on custom domain

**Current Work Environment**
* Google Chrome 49.0.2623.75
* Toggle Addon Logged in via Google OAuth
* Jira on internal url

Best Regards
Endre

**Comment by IndrekV** [comment]
Hi,
Could you give more details on the issue. I just checked and for me the select box has all the needed tools to select from see the added animation.

![custom_domain](https://cloud.githubusercontent.com/assets/842229/16558817/0489ea44-41f1-11e6-9f99-a75577ae76c4.gif)

**Comment by enbock** [comment]
Hi,

sorry for late answer.
Exact that list was missing. At least now with v1.0.3 is the full list available.

Thanks anyway :)
