### ISSUE TITLE
"Task" dropdown no longer appears for projects with tasks

### ISSUE THREAD

**Issue by andrewmowe** [toggl/toggl-button#615]
The extension used to provide a dropdown list of available tasks when I started the timer and set it to a project that had tasks. Since the latest update(s) this functionality is no longer working. Is this a bug or an intentional change?

**Comment by IndrekV** [comment]
With the latest release tasks were moved into the project dropdown. You can filter the project dropdown according to projects,clinents or tasks. Tasks for project can be opened by clicking on the task link behind the project name. It works the same as in the web app.
![screen shot 2016-07-25 at 21 09 37](https://cloud.githubusercontent.com/assets/842229/17111857/21e2ccac-52ac-11e6-834f-70c26d9161d8.png)

**Comment by andrewmowe** [comment]
Great, thanks!
