### ISSUE TITLE
Inability to select a project's task in new UI

### ISSUE THREAD

**Issue by julesrenaud** [toggl/toggl-button#616]
If a project's title is too long the new task selector becomes unusable, pushed out of the bounds of the dropdown menu.

I will also add that this new UI breaks my workflow, where I make sure that each of my Trello and Toggl project titles are matching so that they are preselected when I start the timer from Trello. Now the project is still selected, but I need to open the dropdown menu to select a task (which I might not be able to select) and I'm presented with an endless list of projects, always starting from the top.

Thank you,

**Comment by IndrekV** [comment]
Thank you for the feedback. I will look into it. It would make sense to filter the dropdown according to selected project. That way when opening dropdown you would be able to see the tasks connected to the project right away.

**Comment by kyrpas** [comment]
I'm also unable to use the keyboard to select projects and/or tasks. Usually I'd start typing a task's name and then use the arrow keys to select a task but it's not working anymore. I can't select tasks using only the keyboard. Can you please look into it? It makes a huge difference. Thank you

In the meantime, is there an easy way to rollback to a previous version?

**Comment by IndrekV** [comment]
Sadly it's not possible to roll back the version downloaded from webstore. I'll create an issue to into the keyboard shortcuts issue.

**Comment by julesrenaud** [comment]
Any progress on this issue?

**Comment by IndrekV** [comment]
Sorry for the delay. I'll try to look more into this tomorrow.

**Comment by IndrekV** [comment]
@kyrpas There is an issue for adding keyboard support to autocomplete dropdown #617

**Comment by kyrpas** [comment]
@IndrekV thanks :)
