### ISSUE TITLE
Add keyboard support to autocomplete

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#617]
Moving up/down and opening tasks dropdown.

**Comment by kyrpas** [comment]
Would it be possible to also filter down tasks as we type in the search input? 

At the moment, if there is a project named "Work" which includes the tasks "Code", "Design", "Analyse", when typing "Cod" all the project tasks still show up in the results. 

Ideally (like in previous versions) only the task "Code" should be displayed. And ideally, it'd be possible to simply use the keyboard to select it.

Really looking forward to this. Thanks a lot for all your hard work so far :)

**Comment by kyrpas** [comment]
@IndrekV Any progress on this?

**Comment by IndrekV** [comment]
It is not in our near future plans, but it still remains in our roadmap.

**Comment by kyrpas** [comment]
@IndrekV ok, thanks for the update :)
