### ISSUE TITLE
Submit button shown in Asana

### ISSUE THREAD

**Issue by njgray** [toggl/toggl-button#621]
When clicking the toggl button in an Asana task the submit button is shown next to the "Done" button.
There is a class of hidden on the submit input, but it doesn't appear to have an associated style in the injected css.

Adding  a `.hidden` class with a style of `display: none;` should fix the issue.

Screenshot:
![screenshot at 13-56-22](https://cloud.githubusercontent.com/assets/989875/17305506/4efa1f62-57f0-11e6-94b5-b1c528543f46.png)

**Comment by willrowe** [comment]
This is also happening in Trello.
