### ISSUE TITLE
Desktop timer?

### ISSUE THREAD

**Issue by theredmanor** [toggl/toggl-button#624]
I like how in the desktop app we can have a small timer sitting in our screen no matter what window we are focusing on. It keeps us aware of the time we are using, even when we're not using the browser
Can we have that feature here in this extension?

Edit: I managed to find a hacky way of doing this by, using this script: http://www.howtogeek.com/howto/13784/keep-a-window-on-top-with-a-handy-autohotkey-script/
But it doesn't work so well since if I were to come back to the browser interact with it this extension dialog disappear

Edit: I found another hacky solution by opening an extra second chrome window that you won't use for work, load the extension dialog, activate the "window-on-top" script and then continue to use other programs or the first chrome window, but do not interact with the extra second chrome window.

If a solution like this this works, I imagine it wouldn't be so hard to implement it as an actual actual feature

Of course there is a huge disadvantage with this hacky solution, is that you can't drag the window around. So if it's covering an imporant button in the program you're working on, it's a huge hassle

**Comment by IndrekV** [comment]
Thank you for the suggestion I will investigate the possibilities. I know that similar functionality is possible with chrome apps but I'm not sure it's possible with extensions.

**Comment by IndrekV** [comment]
This kind of functionality is not supported by Chrome extensions. Keeping extra window open for this seems overkill. This functionality works for desktop app but not for Toggl Button. Thank you for the suggestion and for sharing your thoughts.
