### ISSUE TITLE
Panel height

### ISSUE THREAD

**Issue by GEp1c** [toggl/toggl-button#625]
Hello, I'm using Toggl Button and its pretty awesome. But I'm working at 20 projects at time, with different tags (about +- 15 tags). It's very hard to choose what I need cause the panel is very small.

Would be fine to configure heigth, I'm using 3 x 27" monitors.

**Comment by IndrekV** [comment]
The dropdown height in the extension icon popup is defined by the size of the popup. The dropdown that are show on the page can be bigger in height. Which one are you mostly using.

Currently typing to filter choices is the fastest solution for this issue.
