### ISSUE TITLE
Show name of last entry to make continuing easier

### ISSUE THREAD

**Issue by fonorobert** [toggl/toggl-button#627]
Right now there is no way to know what the last time entry was just by looking at the extension.
The description and project of the last entry should be viewable somehow without having to open the web app.

**Comment by IndrekV** [comment]
Currently hovering the "Continue latest" will show the description and project name of the latest entry in a tooltip. (in the example the description was "Work work" and no project was selected.

![tooltip](https://cloud.githubusercontent.com/assets/842229/17553106/9cf83b4a-5f0c-11e6-95d7-ed734ab4001c.png)

**Comment by IndrekV** [comment]
I think the tooltip is enough for now. We have plans to show last 5 or so entries so it will make it even easier to continue recent entries.
