### ISSUE TITLE
Investigate issue with self-hosted Visual Studio TFS

### ISSUE THREAD

**Issue by fonorobert** [toggl/toggl-button#628]
A user reports the button not showing up in a self hosted version of Visual Studio TFS. Desk case no. 320883

**Comment by IndrekV** [comment]
Discussed the issue with the user. It seems that the self hosted Visual Studio had different design. The integration with visualstudio.com does not work with self hosted one. Unless different integration is created for self-hosted version, toggl button cannot be used.
