### ISSUE TITLE
Todoist task's complete/check button should trigger 'Stop timer' for that task

### ISSUE THREAD

**Issue by dasilvacontin** [toggl/toggl-button#631]

**Comment by simonschllng** [comment]
But please optional through a configuration setting. If you have multiple projects with the same name or multiple tasks with the same title, the button gets confused. This could then lead to unexpected timer stops.

**Comment by IndrekV** [comment]
This is too specific functionality for one single tool. We try to keep the functionality very general to make it easy to maintain all the integrations we have. We will not add integration specific preferences.
