### ISSUE TITLE
Latest update broke finding the right project from the list when using keyboard

### ISSUE THREAD

**Issue by annikatoggl** [toggl/toggl-button#632]
How to recreate the bug in Trello:
Start the timer, click on the project select tab, type the first few letters of the project name - it used to select the project that matched the letters, but now it starts editing Trello card name instead.

**Comment by IndrekV** [comment]
Seems to be very specific to Trello. Trello ui seems to intercept focusing the filter field. This needs a workaround or new way of showing the filter input field.
