### ISSUE TITLE
Pomodoro synchronization problem

### ISSUE THREAD

**Issue by Stvad** [toggl/toggl-button#634]
I've noticed that if you stop tracking some task in the web application - the plugin will catch up with it but only partially. Pomodoro timer will continue working and will signal break at the specified moment of time. And as far as I can tell there is no way to prevent that besides starting and stopping tracking new task from within a plugin.

**Comment by the1ju** [comment]
I'm facing this issue too. Forcing the extension to sync doesn't update the Pomodoro timer. It still continues to run. The support for Pomodoro was a big consideration in using Toggl over other time tracking apps. Hope this gets resolved soon. Thanks for the great app.

**Comment by IndrekV** [comment]
Thank you for reporting this we'll look into this and try to fix it before next release. Release will be probably in the end of August.

**Comment by the1ju** [comment]
Great! I downloaded the source and did a quick test by stopping the timer on the webpage and the button quickly sync'd up! Thanks for the quick fix.
