### ISSUE TITLE
Pomodoro Synchronization

### ISSUE THREAD

**Issue by the1ju** [toggl/toggl-button#638]
I noticed the following issue with the toggl-button Pomodoro synchronization.

Say, I forget to start the timer on a task. I go to the web page, start the timer and adjust the start time of the task (I don't stop the timer though). Now, assuming the elapsed time is less than the length of a Pomodoro interval, I would expect 

1. the button extension to sync up to the timer on the web page and 
2. to stop the timer at the end of the Pomodoro interval. 

This doesn't seem to be the case. In fact the moment the start time is adjusted on the web page, 
the 'white ring' around the toggl-button completely disappears (the button stays red though indicating the timer is running).

**Comment by IndrekV** [comment]
At some point we had the syncing work with pomodoro. This created another issue. If user was not using Toggl Button, but their computer was on then the timer would be stopped at pomodoro end. it would appear very odd when timer on the mobile app would mysteriously be stopped. We actually have thought about adding start time or duration editing to Toggl Button that would work in your described case.

**Comment by ihodev** [comment]
Is it possible to return previous behavior via checkbox? I would like to stop all timers on the pomodoro end even if I start time entry from mobile or web.

**Comment by IndrekV** [comment]
@ihodev I created an issue for this request #732. We'll evaluate if this is something that should be added. Thank you for your feedback.
