### ISSUE TITLE
Not syncing settings between the extension and desktop app

### ISSUE THREAD

**Issue by fedegiust** [toggl/toggl-button#641]
I don't think the app is actually doing it, but I guess it would be great to have.

So, for example I've got the Chrome extension in one of my Google Chrome users as well as the Desktop version.

I've disabled the reminder today on my Desktop version, but I was still getting the popup reminders from the Chrome extension.

It would be great if the extension was able to get the same settings as in the Desktop version (syncing the settings somehow between the two).
Thanks

**Comment by IndrekV** [comment]
Most of the settings in Toggl Button and Toggl Desktop are app based and are only stored on user's side. We have no plans to currently make the setting cross app compatible. Thank you for the suggestions.
