### ISSUE TITLE
Toggl Chrome extension doesn't work on Trello (Mac and Ubuntu Linux)

### ISSUE THREAD

**Issue by yeremyjt** [toggl/toggl-button#643]
The toggl button stopped working on Trello. I confirmed this on both Mac and Ubuntu Linux. It works fine with other apps like Google Drive.

**Comment by IndrekV** [comment]
Please try to re-enable the needed tools in Toggl Button settings "Permissions tab".
![re-enable](https://cloud.githubusercontent.com/assets/842229/18263329/e1c746fc-7411-11e6-94d3-cf8f85b9bcee.gif)

**Comment by MammaSonnim** [comment]
The same problem with todoist, re-enable doesn't help, also like re-enable the whole toggle-ext.

**Comment by IndrekV** [comment]
@MammaSonnim  Todoist issue seems to be unreleated. The permission works but the design change in Todoist is what has broken the integration. I'll create another issue for this #644

**Comment by xtoq** [comment]
I also have this problem on Windows 10. I've re-enabled, reinstalled and tried the Toggl + Trello integration on another Chrome profile with no joy. If you need more information, please let me know!

**Comment by yeremyjt** [comment]
Thank you @IndrekV ! Re-enabling the permission on trello.com fixed this issue.

**Comment by dannycorker** [comment]
Still unable to get Zendesk working unfortunately by re-enabling the permissions.

**Comment by IndrekV** [comment]
@dannycorker We have release a new version with fixes to some of the users. If we validate that the version is good we will push it out to everybody.

**Comment by laurabennett** [comment]
The button shows up on my Trello board but it stops the timer before I'm done and doesn't store the time in my Toggl account.  So it appeared to work at first but is completely useless.
