### ISSUE TITLE
Todoist integration broken

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#644]
Seems UI might have changed.

**Comment by Metaneira** [comment]
FWIW, Chrome extension also does not work on Windows 7.

**Comment by IndrekV** [comment]
Seems to be permissions issue. This can be fixed by disabling and re-enabling the integration in the Settings "Permissions" tab. See this comment for reference: https://github.com/toggl/toggl-button/issues/643#issuecomment-244858452
