### ISSUE TITLE
Zendesk Integration Broken

### ISSUE THREAD

**Issue by dannycorker** [toggl/toggl-button#645]
As of this morning the 'Start/Stop Timer' button appears to have stopped coming through to Zendesk. Verified with several users.

**Comment by IndrekV** [comment]
Please try to disable and re-enable the zendesk permission in the Toggl Button settings "Permissions" tab. This should make it work again.

**Comment by dannycorker** [comment]
No such luck I'm afraid - I've just tried that and have tried full browser restarts also, I could try removing the whole extension and re-adding, however this has affected everyone at the same time today which makes me think a change at either the Toggl or Zendesk side could be involved?

**Comment by IndrekV** [comment]
Just to verify the issue is with permissions not the extension itself. Please try to re-enable the needed integration to see if this fixes the issue. See this comment for reference: https://github.com/toggl/toggl-button/issues/643#issuecomment-244858452

**Comment by IndrekV** [comment]
We'll release a new version with the fix as soon as possible.
