### ISSUE TITLE
Button doesn't appear in Trello and Workfront

### ISSUE THREAD

**Issue by gonensh** [toggl/toggl-button#646]
Hi @IndrekV,

Thanks for merging my Workfront integration!

While testing it (on v1.0.4), I noticed that the Toggl button does not appear on either Workfront or Trello unless I specify the URL in the _Custom Domain Url Permissions_. Google Sheets does work for some reason.
I tried checking _Enable All_ and it still did not work.

Please let me know if I can help sort this out.

Thanks.

**Comment by IndrekV** [comment]
Please try to uncheck and the re-check the Trello and Workfront permissions in the list. This should fix the permissions issue. I'm going to fix this issue so that the permissions are repaired on update with the next version.

**Comment by IndrekV** [comment]
This should be fixed with version 1.0.6
