### ISSUE TITLE
No Meistertask Support

### ISSUE THREAD

**Issue by hennessyevan** [toggl/toggl-button#647]
We use meistertask and where it provides similar categorizations such as tags, titles, users and projects to toggl, it doesn't have support for the toggl button. What would be great to see would be a fully-functional button that would pull the project, user, tags and title from the task in meistertask and start the clock in toggl

**Comment by IndrekV** [comment]
Thank you for the suggestion. We currently are not developing new integrations ourselves. We do however accept pull requests. Check out this guide on how to create an integration: https://github.com/toggl/toggl-button/wiki/Adding-new-integrations

**Comment by hennessyevan** [comment]
Pull Request made, the team's already using the button. Hopefully you merge it soon.

**Comment by IndrekV** [comment]
MeisterTask is already live!!
