### ISSUE TITLE
Can't use custom domain with atlassian.net

### ISSUE THREAD

**Issue by dohzya** [toggl/toggl-button#648]
The select contains only `Atlassian`, which is `atlassian.com`.

<img width="167" alt="select" src="https://cloud.githubusercontent.com/assets/9595/18304861/1ba0152e-74e5-11e6-8638-e3b34d3d5a5a.png">
<img width="405" alt="result" src="https://cloud.githubusercontent.com/assets/9595/18304862/1ba4468a-74e5-11e6-9feb-6759d93f8a70.png">

**Comment by IndrekV** [comment]
If your domain is something like `https://company.atlassian.net` then there is no need to define custom domains. If your domain is something totally different then the atlassian selection works for both `.com` and `.net` atlassian version as they use the same file.
