### ISSUE TITLE
undefined in project list

### ISSUE THREAD

**Issue by syko** [toggl/toggl-button#649]
I'm not sure what it is but it appears when filtering for certain projects

Project `Webapp`, has client
![image](https://cloud.githubusercontent.com/assets/317674/18306280/c9743320-74f3-11e6-82af-60d0f948043c.png)

Project `Thumbler`, no client
![image](https://cloud.githubusercontent.com/assets/317674/18306291/d187c7c0-74f3-11e6-8660-71a59e6c8f3b.png)

**Comment by syko** [comment]
Oh I think it's a "No Client" grouping. It's always in the projectl ist and there seem to be projects without a client under it.
![image](https://cloud.githubusercontent.com/assets/317674/18306417/6e4ad91c-74f4-11e6-843c-f345ea4505f7.png)

**Comment by IndrekV** [comment]
Was caused by identical client names in different workspaces. The list generation broke.
