### ISSUE TITLE
No longer integrating with most of my services

### ISSUE THREAD

**Issue by andrewmowe** [toggl/toggl-button#652]
The newest update seems to have broken my integrations with Teamweek, Trello, and Basecamp. It still works in Google Inbox. I tried logging out and back in. Any ideas?

**Comment by biamorton** [comment]
same here for jira and github :(

**Comment by IndrekV** [comment]
What version are you running? Please try to manually disable and enable all integrations in the Toggl Button Settings "Permissions" tab. See this example that re-enables Trello.

![re-enable](https://cloud.githubusercontent.com/assets/842229/18263329/e1c746fc-7411-11e6-94d3-cf8f85b9bcee.gif)

**Comment by andrewmowe** [comment]
I'm using v 1.0.4 of the button and v 53.0.2785.101 of Chrome for Mac.

After disabling/enabling it started working again. However with Teamweek I had to manually add the URL for app.teamweek.com to get it to work.

Thanks

**Comment by IndrekV** [comment]
Thank you for getting back to me it will be fixed next release. We'll have it out as soon as we've validated the fix.
