### ISSUE TITLE
toggl not showing on any of my pages anymore

### ISSUE THREAD

**Issue by biamorton** [toggl/toggl-button#653]
I used to click on it from jira page and from github page but now it doesnt show anymore. Only displays on the browser window at the top.

**Comment by IndrekV** [comment]
What version of the extension you have installed. if it's bigger than 1.0.3 try disabling and enabling the integration from the Toggl Button settings "Permissions" tab

**Comment by biamorton** [comment]
I've tried the disabling and enabling it again already with no luck. I'll check the version tomorrow when I'm back in the office.

**Comment by IndrekV** [comment]
We've released a new version (1.0.6) with fixes to the permissions issues.
