### ISSUE TITLE
Option to modify start time of running timers

### ISSUE THREAD

**Issue by lachsen** [toggl/toggl-button#659]
I really like the chrome extension for that fact that it's lightweight and easy to reach from the browser. 

However, I very much need a feature to modify the start time of a running timer since very often forget to track the time from the very beginning and make adaptations afterwards. The desktop app supports this but having to run both the extension and the desktop app kind of beats the purpose.

**Comment by IndrekV** [comment]
This is in our list. We will either add start time or duration editing. This should work for your use case.

**Comment by lachsen** [comment]
Awesome!

**Comment by tcrammond** [comment]
The extension has had the ability to edit the duration of the running entry for some time now 🎉 closing the issue
