### ISSUE TITLE
Show total time of today's work and/or list of previous time entries

### ISSUE THREAD

**Issue by lachsen** [toggl/toggl-button#660]
I mostly use toggl to check my own productivity, so it would be very useful to see today's total time right in the popup of the extension. 

A small list of previous time entries done today would be even better. That way you can also easily decide what tasks to continue. The layout of the desktop app did a pretty good job in that sense, just that you don't need a list of all task from the last few days/weeks. Today would be enough.

**Comment by IndrekV** [comment]
This has actually been discussed and we have thought about adding 5 latest entries under the timer.

**Comment by lachsen** [comment]
That sounds pretty good! Having the total time of the current day would still be nice to have.

**Comment by tcrammond** [comment]
These features exist now 🎉 , closing.
