### ISSUE TITLE
Stopping timer automatically when closing Chrome does not work

### ISSUE THREAD

**Issue by harbra** [toggl/toggl-button#662]
I activated "Start automatically" and "Stop automatically" in the settings, however only the automatic start works. When I close Chrome, either via the close button or the CTRL+SHIFT+Q hotkey, the timer keeps running.

**Comment by IndrekV** [comment]
Thank you for reporting. We'll check it out.

**Comment by IndrekV** [comment]
I've tested this with macOs and windows and it worked for me every time. I think it depends on the connection also. If the connection is not good enough for the info to reach the servers than it will not stop the entry.

**Comment by evelinan** [comment]
Still seems to be a bug. I tried to replicate and it also didn't stop at the end of the set time for me.

**Comment by gabrielb86** [comment]
Same here. Any news on this?

**Comment by jankoweb** [comment]
Same problem - auto stop does not work, connection ADSL 100Mb/s.

Linux Mint 17.1., Chrome Version 57.0.2987.110 (64-bit)

**Comment by tcrammond** [comment]
We have made improvements to these areas and don't see any related problems now. If there are still problems in the latest versions of the extension, please feel free to open a new issue.
