### ISSUE TITLE
Trello integration opens up Tags automatically when I pick a project

### ISSUE THREAD

**Issue by annikatoggl** [toggl/toggl-button#666]
I don't use Tags, so it's an extra click to close this section - it didn't work this way before. Before I was able to pick a Project and click Done without the need to close the Tags section first.

**Comment by IndrekV** [comment]
@annikatoggl Please share more details. Are you talking about tags in the Toggl Button edit form? For me the Tags opens up only if I click on it or press TAB while in projects dropdown.

**Comment by annikatoggl** [comment]
it seems to be happening when I'm starting a timer from the same card the second time.
