### ISSUE TITLE
Move start tracking button from the top to the right sidebar on github

### ISSUE THREAD

**Issue by NoNameProvided** [toggl/toggl-button#669]
On Github the right sidebar is scrolling with the view, putting the "start timer" button there would allow users to easily click it from anywhere in the thread instead of scrolling up to the top to start tracking time.

Here is an image showing the issue, the title and the start timer button is not visible, but the sidebar has scrolled with the view and still visible.

<img width="1007" alt="screen shot 2016-09-27 at am 10 42 14" src="https://cloud.githubusercontent.com/assets/4706265/18866194/1b9f4792-849f-11e6-9205-eb56e862b8f2.png">

**Comment by IndrekV** [comment]
Thank you for the suggestion. I like the idea. I'll look into it.
