### ISSUE TITLE
GITLAB "start button" on issues : auto recon project by url

### ISSUE THREAD

**Issue by PaoloFalomo** [toggl/toggl-button#681]
## My issue

On toggl my project are named as on url of gitlab.
example:
My Gitlab project url is 

> gitlab.com/mygroup/**project-name**/issues/N

And my Toggl project is

> **project-name**

But my **Gitlab's Project Name** is

> **Project Name**

**Actually** toggl button takes the _nicename_ so it not founds any project named "Project Name".
![image](https://cloud.githubusercontent.com/assets/10535089/19343149/4df34886-9135-11e6-9965-6efbd8078414.png)

I do not know if it should be a standart for toggl to take the project name by url but it would be an amazing option for me 👍 
## Make it general (maybe?)

It could be a feature service-agnostic **if** the user can help the project auto selector with synonyms of project.

I my case with this feature i would be able to tell (just once) to toggl: "hey when u find "My Project" use "my-project" instead!"
![image](https://cloud.githubusercontent.com/assets/10535089/19343473/9e2175b6-9136-11e6-8016-ad8bf4cd654d.png)

**Comment by jayvdb** [comment]
A more generic version of this is https://github.com/toggl/toggl-button/issues/826

**Comment by tcrammond** [comment]
Closing this one in favour of the linked issue #826 - there are many similar suggestions floating around, we'll take them into consideration. Please feel free to leave further comments with your ideas.
