### ISSUE TITLE
Disappearing button in Asana (with Snowball)

### ISSUE THREAD

**Issue by kadrihvl** [toggl/toggl-button#684]
>My toggl button within asana keeps disappearing the past few days since I&#39;ve upgraded to the new interface (I&#39;m not sure if this is related or not).
I cleared all my cache, disabled the app and reauthorised access and when refreshing Asana the button reappeared on one task, but as soon as I navigate to another task it&#39;s disappeared again.
Case #367261

**Comment by syko** [comment]
Errr this surely has nothing to do with snowball. Just a coincidence. Making an issue in toggl-button repo

**Comment by syko** [comment]
(of course this is already in the toggl-button repo. sry I need more coffee :facepalm: )
