### ISSUE TITLE
Pomodoro not working in chrome v1.0.10

### ISSUE THREAD

**Issue by JherezTaylor** [toggl/toggl-button#686]
- Using Chrome for linux
- No notification sound or pop up when interval has elapsed

**Comment by IndrekV** [comment]
@JherezTaylor I just tested the extension on Xubuntu 15.04 and every thing worked ok. First of I'd suggest disabling and re-enabling pomodoro settings in preferences window. Secondly I'd suggest re-installing the extension. If all this is not working I would need more details to possibly replicate the issue.

Some questions for more details.

* Does the progressmeter start running when you start timer with pomodoro timer enabled.
It should look like this:

![pomodoro_progress](https://cloud.githubusercontent.com/assets/842229/19641030/0416a314-99e8-11e6-8b88-804954f6827c.png)

* How do you start the timer? From popup or from an integrated tool's page.

**Comment by JherezTaylor** [comment]
I can't seem to replicate it, probably user error. I'm gonna close the issue.
