### ISSUE TITLE
Change integrations pop up copy

### ISSUE THREAD

**Issue by naeemt** [toggl/toggl-button#687]
Rewording this guy: 
![image](https://cloud.githubusercontent.com/assets/1181246/19638925/5a220ce2-99d6-11e6-9bf2-caf4bff14e08.png)

New copy:

Title: Enable integrations!

Hey Toggler! We have a ton of integrations that make your time tracking life easier, faster & way more convenient

To use them, check off any integrations you'd like to enable under "URL Permissions" -- or click enable all.

You can also define custom domains on the second part of the page. Type in an address, select the tool and press 'Add'.

**Comment by IndrekV** [comment]
Thank you come again!
