### ISSUE TITLE
Button missing from github issues

### ISSUE THREAD

**Issue by oppianmatt** [toggl/toggl-button#695]
### Environment details

* Operation system: Windows 10 - chrome 54.0.2840.71 m (64-bit)
* Extension version: Version (1.0.12)

### Expected behavior

Button to start/stop tracking in github issues.

### Actual behavior

No more button.

### Steps to reproduce the behavior

Go to github issues and no button appears.

### Additional details

* screenshots or screencapture

![image](https://cloud.githubusercontent.com/assets/48596/19851402/a9bdaf84-9f55-11e6-8706-070c4381799b.png)

**Comment by IndrekV** [comment]
Fixed with 514928eb58f7822f921e27b9575f2be31ee25aef
It's just not released. We'll try to release as soon as possible. 
Thank you for your input.
