### ISSUE TITLE
The Pomodoro timer is activated only if the tracking is started via Toggl Button

### ISSUE THREAD

**Issue by Stvad** [toggl/toggl-button#702]
### Environment details

* Operation system: Arch Linux
* Extension version: 1.0.13

### Expected behavior

When I start time tracking via Toggl, the Pomodoro timer in Toggl Button is activated

### Actual behavior

The Pomodoro timer is activated only if the tracking is started via Toggl Button (and not, for example, mobile or web application).

### Steps to reproduce the behavior
Start tracking time on the entry via https://www.toggl.com/app/timer, notice that plugin shows that some activity is being tracked (the button turns red), but the Pomodoro timer is not started.

### Additional details
It worked as described in "expected behavior" in the past (I'm not sure in what version it stopped working though) :smile:

**Comment by Stvad** [comment]
Ah, judging by discussions in #563, #639 and #638 it seems it's the intended behavior now. Justification kind of make sense, but can you make it as an option? 

I habitually start tracking things from the web application, so to make Pomodoro work, I need to start it in the webapp, stop it and then do "continue latest" from plugin, which is not the clearest workflow -_-.

**Comment by IndrekV** [comment]
This is indeed intended behaviour. I find starting timer from web and then using Toggl Button to be a strange workflow.

Currently only thing missing from Toggl Button is the autocomplete of time entries. It is already planned to be added. With the next big release we will add list of 5 latest unique entries that also allow continuing recent entries faster. PR #673 

I think we won't add a the suggested setting for this as with the planned updates there is no reason to start tracking from web when using Toggl Button.

**Comment by Stvad** [comment]
Well, I have some entries, that have already been configured in terms of Project/tags. I don't want to redo this, but I want to use Pomodoro functionality, so I find myself doing the thing I've described doing -_-.
5 last entries would indeed make things somewhat better, but will not ultimately fix the issue, as I habitually re-use less recent entries.

BTW, will those 5 entries be unique, or could they be duplicates (i.e if I've 5 identical records because I've tracked the same thing 5 times consecutively, will the plugin display it as 5 records or as 1)?

Not sure what've you meant by "autocomplete of time entries".

**Comment by IndrekV** [comment]
5 recent entries will be unique.

Autocomplete for time entries means that when typing in the description field autocomplete will suggest entries from recent matching description, project and probably even client. Similar to how web works currently.

**Comment by Stvad** [comment]
:+1: 
Autocomplete will help indeed.

**Comment by stinger112** [comment]
Can we add old behavior optionally? Using just Toggl Button for Pomodoro not so convenient in some cases.

**Comment by IndrekV** [comment]
I think the pomodoro should be connected to an app not an account to avoid confusing behavior. If you feel like not using Toggl Button all the time but need pomodoro, there is also pomodoro functionality in Toggl Desktop.
