### ISSUE TITLE
Trello broken

### ISSUE THREAD

**Issue by fernandoval** [toggl/toggl-button#713]
Start timer button not working in Trello.

### Environment details

* Operation system: Windows 10
* Extension version: 1.0.15

### Expected behavior

Start the task timer

### Actual behavior

Do not start the timer

### Steps to reproduce the behavior

Open a card in Trello and click on "Start timer" button

### Additional details

Fill the fields in pupup and then click in Done button.

**Comment by DonMat** [comment]
- Operation system: Windows 10
- Extension version: 1.0.15
- Google Chrome: 54.0.2840.99

New and old cards all work like a charm.

**Comment by fernandoval** [comment]
Not to me. Continue not working. I click in Start timer button but the timer is not fired.

The button still green until I change tab in Chrome (v54.0.2840.99 m). When I go back to Trello tab the button back to "Start timer". The Toggle track timer icon in top right corner still grayed.

![image](https://cloud.githubusercontent.com/assets/8930605/20462695/4577cf4e-af0b-11e6-9910-27eebe73e9e5.png)
![image](https://cloud.githubusercontent.com/assets/8930605/20462697/5a07cfe0-af0b-11e6-9d40-c821cbd19a76.png)
