### ISSUE TITLE
Cannot start new entries from Todoist

### ISSUE THREAD

**Issue by simonschllng** [toggl/toggl-button#714]
Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

### Environment details

* Operation system: Ubuntu 16.04 Google Chrome Version 54.0.2840.100 (64-bit)
* Extension version:  1.0.15

### Expected behavior

 1. Click on the button of a Todoist task in the list
 2. set details
 3. click start
 4. timer starts. 

### Actual behavior

 1. Click on the button of a Todoist task in the list
 2. set details
 3. click start
 4. timer does **not** starts but the button in the task row displays a green *Top timer* button.

### Additional details

 * Extension background page shows an error: `background.js:545 POST https://www.toggl.com/api/v9/workspaces/1023529/time_entries 400 (Bad Request)`
 * Response value is `Conflict with project/workspace: project needs to be in the same workspace as the time entry`
 * I can start tasks from the button in the browser bar as usual.

**Comment by IndrekV** [comment]
We are aware of this issue. We'll try to push out a release with the fix today.
