### ISSUE TITLE
Permission tab missing in Firefox

### ISSUE THREAD

**Issue by Samgarr** [toggl/toggl-button#718]
I'm not sure, if this bug but i could not find any related issue here. Permission tab in Firefox (50.0.2) is missing, therefore i can't configure Toggl button for custom domain.
![toggl_bt](https://cloud.githubusercontent.com/assets/1857575/21103477/edb97b34-c082-11e6-8926-c0c0f8816e94.png)

**Comment by IndrekV** [comment]
It's not a bug. Currently permissions managements is not supported in Firefox as in Firefox this API is not available. This will be added in the future.

**Comment by Samgarr** [comment]
I understand, it would be nice mention this somewhere in Readme or so. Thanks!

**Comment by brablc** [comment]
What about some quick hack that would allow us to write custom domains in about:config for instance? This is blocking issue for our team (we use Phabricator on our domain). We cannot force people to use Chrome.
