### ISSUE TITLE
Project selection will not be saved (Habitica)

### ISSUE THREAD

**Issue by therealmaxmoon** [toggl/toggl-button#720]
### Environment details

* Operation system: Linux
* Browser: Chromium
* Extension version: 1.0.18

### Expected behavior

On Habitica.com I should start with one click the timer without being ask about the project, because I've choosen the project before.

### Actual behavior

Every day I choose the same tasks (dailies) and I have to select every time the project.

### Steps to reproduce the behavior

Just click on the toggl button several times, it will reset the project field.

**Comment by IndrekV** [comment]
The specific functionality you are referring to is not present in Toggl Button.
In Toggl Button there is a project name matching functionality, but sadly this is not supported in Habitica integration. The selected project will not be saved to some local database when you start the timer.

To start timer with previously selected project you have a few choices:
__Set default project from settings__ - This project is automatically selected when timer is started and project is set.
__Continue time from the recent entries list__ - In the extension popup there is list of 5 recent unique entries. Continuing them will start entry with the same data.
