### ISSUE TITLE
Allow customization of fields used for generating time entry name

### ISSUE THREAD

**Issue by tupaschoal** [toggl/toggl-button#726]
### Expected behavior
Being able to customize what data from the webpage will be used as the time entry "tag"

### Actual behavior
Every website automatically pulls time entry identification

### Additional details
Some websites are configured to pull a key + description as the time entry name, but sometimes just the key is enough. It would be good to be able to customize them from the extension options, instead of having to modify the source code and produce an unpacked extension, as the former would allow the app to be kept up-to-date.

**Comment by tcrammond** [comment]
Closing in favour of https://github.com/toggl/toggl-button/issues/1187 (I noticed you commented on that too 👍 ).
