### ISSUE TITLE
Scrolling doesn't work in project dropdown in Trello

### ISSUE THREAD

**Issue by fonorobert** [toggl/toggl-button#728]
Chrome 55, Toggl Button 1.0.18

With the project selector dropdown open in Trello it can't be scrolled with the mouse scroller and there is no scrollbar and the dropdown is cut off at the bottom of the screen:

![screen shot 2016-12-20 at 15 54 50](https://cloud.githubusercontent.com/assets/6963710/21355295/bdb44648-c6cd-11e6-87e0-ff88150a9ca3.png)

**Comment by IndrekV** [comment]
This is because the height of the dropdown is bigger and goes out of the window height. I'll check the window size before opening autocomplete.
