### ISSUE TITLE
Settings get reset after browser restart

### ISSUE THREAD

**Issue by IndrekV** [toggl/toggl-button#730]
User reports:

>I've noticed that when I restart my computer, the setting for the Extension for "Remind me to track" turns back on. It will display a message about mid day, during my lunch, reminding me to track. When I click the "x" to close it, it starts the timer. I will 'untick' it and it will not become 'ticked' again until I restart my computer. Essentially, restarting my computer reverts these settings back to original, which has that option 'ticked.'

**Comment by kadrihvl** [comment]
If there's some news please share with case #400334

**Comment by tcrammond** [comment]
Should not be a problem anymore.
