### ISSUE TITLE
Add integration for Salesforce Lightning

### ISSUE THREAD

**Issue by fonorobert** [toggl/toggl-button#734]
Salesforce is coming out with a new UI: http://www.salesforce.com/campaigns/lightning/

**Comment by IndrekV** [comment]
Salesforce Lightning is actually supported. It was added a while ago with #504 
If there are UI changes that have broke the integration we need to test it out.

**Comment by tobiasbossin** [comment]
It seems that toggle doesn't work anymore with SF Lightning. Can you test it?

**Comment by vedr4n** [comment]
A user complained about this in the Chrome webstore. That was the second or third report in about a month. 

@dooart can you look into it?

**Comment by TheSoloJake** [comment]
A user in [this case](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2137598/conversations/19154323590) is also requesting that the Toggl Button work with the new Salesforce Lightning UI.

**Comment by vedr4n** [comment]
Are there any updates regarding this? I have another user asking about the integration. 

[Intercom](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2092037/conversations/20526407526).

**Comment by vedr4n** [comment]
@dooart @langri-sha Is adding support for Lightning on planned for the next quarter? Salesforce has made a big push towards Lightning and is slowly phasing out the Classic interface.

**Comment by tcrammond** [comment]
@vedr4n consider it on the hit list 👍

**Comment by Allawler** [comment]
An additional note on how the integration has broken:
Lightning adds three new alpha characters to every unique Salesforce Record ID. An example would be if the SFID in Classic is 12345678OOX91, the SFID in Lightning might be 12345678OOX91AAD. It appears Toggl can no longer link these to records in Salesforce.

Also, Salesforce recommends the use of the Console app structure when working in Lightning. Even in Classic, the Toggl integration only ever worked when you were in a non-console app. It would be great if, when re-evaluating the integration with this ticket, the Console page structure could be included, as most of my users will be in a console view now.

**Comment by tcrammond** [comment]
Thank you for the insights @Allawler. We have a minimum viable update ready for Lightning that will be released soon, but it does not include support for Console pages.

We'll keep this ticket open to consider supporting those next.

**Comment by Allawler** [comment]
Thanks @tcrammond ! I know the Console view is being pushed/recommended so most teams would like to use it and continue using Toggl as well.

Do you know if the update accounts for the different SFIDs from Classic to Lightning?

**Comment by tcrammond** [comment]
We've released update `1.21.0` that includes basic support for both Console views and the older "Sales" views within Salesforce Lightning 🎉 @Allawler there shouldn't be any issues with new SFIDs; the Toggl Button integration does not rely on them to function.

* Please note that `force.com` permission must be enabled in the extension settings. [Toggl Button settings](https://support.toggl.com/browser-extensions/toggl-button-for-chrome#toggl-button-settings)

* The Wiki page has been updated with some example screenshots in case the buttons are hard to find: [Where to find Salesforce Lightning buttons](https://github.com/toggl/toggl-button/wiki/Where-can-I-find-the-Button%3F#salesforce-lightning)

I'll close this issue now, please feel free to create new issues with any specific feedback or suggestions for the integration.
