### ISSUE TITLE
Trello cards opened with direct links aren't displaying the "Start timer" button

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggl-button#738]
When opening a Trello card outside of the app (i.e. from an email) the card that opens doesn't show the "Start timer" button. 

Issue originally reported on Twitter. I successfully reproduced it in Chrome
https://twitter.com/WreckReceiver/status/818417877720109056

**Comment by leafi** [comment]
"I have a user who says the Toggl Button is no longer appearing in his Trello checklists except after he closes and reopens a card. He says it only started a few days ago. I had him uninstall/reinstall the extension, reset the integration, clear his cache and make sure the permission tab was checked but none of that was succesful." Case (via Desk) 411483

**Comment by darinshepit** [comment]
I've been having a similar issue.

Direct links to cards seem to be the issue, even from inside Trello notifications. Sometimes, refreshing the page once or more will give me back the "Start timer" button. Opening cards from inside a Trello board, however, seems to work every time.

**Comment by matt-thorne** [comment]
I still see this issue upon opening any card that has checklist items. The button is not present on each item upon launch of the card, however closing and reopening the card displays the button
![no toggl button](https://cloud.githubusercontent.com/assets/25588468/22652666/ec749c0e-ec4c-11e6-9fce-55716066fb4d.png)
![with toggl button](https://cloud.githubusercontent.com/assets/25588468/22652665/ec749948-ec4c-11e6-801d-860f2d44eccb.png)

**Comment by tcrammond** [comment]
Hey @matt-thorne, can you check that you're on version 1.1.1 please?

We did an incremental roll out and you may have still been on the older version at the time.

**Comment by matt-thorne** [comment]
​It does appear to be working at this point, so I may have been on the
older version when I replied originally.

<https://about.me/matt_thorne?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel>
Matt Thorne
about.me/matt_thorne
<https://about.me/matt_thorne?promo=email_sig&utm_source=product&utm_medium=email_sig&utm_campaign=edit_panel>
