### ISSUE TITLE
Add codebasehq integration

### ISSUE THREAD

**Issue by ashsmith** [toggl/toggl-button#740]
Would be great to support codebase: https://www.codebasehq.com/

(I'd be interested in giving this ago myself)

**Comment by syko** [comment]
Thank you for the suggestion.

We are not currently actively developing new integrations ourselves but I've added your request to the most wanted list https://github.com/toggl/toggl-button/wiki/User-requested-buttons

Any help is much appreciated :+1:

**Comment by dooart** [comment]
integration already exists
