### ISSUE TITLE
Displaying times on page

### ISSUE THREAD

**Issue by topdown** [toggl/toggl-button#741]
I just tested the latest version of Toggl button on my eProject service and noticed that times no longer display next to the timer button.

This is what I use to have in some areas on the site. Eg. Task lists and single task showed the time.
![screen shot 2017-01-13 at 3 53 52 pm](https://cloud.githubusercontent.com/assets/195144/21947066/c759e5c0-d9a8-11e6-832d-f32f1e1362ed.png)

So my question is, was this removed or was it just changed in the way its handled and I need to update my code?

Edit: I see they were removed https://github.com/toggl/toggl-button/commits/master/src/scripts/content/eproject.me.js

Just don't know why?

**Comment by tcrammond** [comment]
I believe this feature was phased out due to flaws and it was not up to quality standard. Closing this issue in favour of https://github.com/toggl/toggl-button/issues/508.
