### ISSUE TITLE
Unable to log in with a google account.

### ISSUE THREAD

**Issue by seanbeaton** [toggl/toggl-button#747]
I use google to log into toggl, and that doesn't appear to be an option for the toggl button extension.

### Environment details

* Operation system: macOS 10.12.1, chrome 55.0.2883.95
* Extension version: 1.1.0

### Expected behavior

Supports login through google

### Actual behavior

Only has username/password login

### Steps to reproduce the behavior

1. Install extension
2. See that there's no option to login with google.

**Comment by kadrihvl** [comment]
Login with Google is actually indeed not available in Toggl Button. Sorry for the inconvenience!

This option may be added in the future. In the mean time you can either:
 - log in to toggl.com with Google > the button will be logged in as well
 - use password reset link (https://www.toggl.com/forgot-password) to get a Toggl password to use with the button
