### ISSUE TITLE
Select of projects does not open anymore on click

### ISSUE THREAD

**Issue by lorenaramonda** [toggl/toggl-button#754]
When starting the timer into the browser the projects select doesn't open anymore, while the tags' one works correctly.
Any idea?

**Comment by syko** [comment]
Is that from within another service or in the extension popup?

We had similar issues in Asana so could be related.

**Comment by lorenaramonda** [comment]
It's in chrome and it's not working neither in gmail nor in any other pages. I'm so sad :( it was useful!

Hope this comment helps.

**Comment by syko** [comment]
Hmm weird, we can't reproduce the problem. Can you try reinstalling the extension? Could also be conflict with another extension...

**Comment by lorenaramonda** [comment]
OK, it works!! The problem is that I was using a fork to use it with a redmin project, but now i see i can configure custom domain so now it works!! Great great! *__*
