### ISSUE TITLE
Use arrow keys to select project after filtering

### ISSUE THREAD

**Issue by jmgregory** [toggl/toggl-button#761]
### Environment details

* Operation system:  macOS Sierra, Google Chrome  (also produced on Windows 10)
* Extension version: 1.1.1

### Steps to reproduce the behavior

Click the Start Timer link (in my case, on a JIRA task).  Press tab to focus on the Add Project combo-box.  Begin typing the name of a project, until the project you're looking for is visible in the autocomplete list below the combo-box.

### Expected behavior

I should be able to press 'down' and highlight the desired project, then press Enter to select it.

### Actual behavior

'Up' and 'down' keys do nothing.  I have to use the mouse to select the project I want.

<img width="438" alt="screen shot 2017-02-15 at 9 44 08 am" src="https://cloud.githubusercontent.com/assets/5099258/22982267/4474241a-f364-11e6-925c-adb56f76fe6d.png">

**Comment by pablopaul** [comment]
+1

**Comment by kev4ev** [comment]
Completely agree. Little feature but makes a big UX difference.
