### ISSUE TITLE
Add integration for ReviewBoard

### ISSUE THREAD

**Issue by yolfer** [toggl/toggl-button#762]
ReviewBoard is a competitor to Crucible, Phabricator, etc.

See https://www.reviewboard.org/ for more info, or http://demo.reviewboard.org/r/212/ for an example of a page that the toggl button would show up on.

**Comment by syko** [comment]
Thank you for the suggestion.

We are not currently actively developing new integrations ourselves but I've added your request to the most wanted list https://github.com/toggl/toggl-button/wiki/User-requested-buttons

**Comment by yolfer** [comment]
Thanks for the reply. Can I submit a PR to have it added?

**Comment by syko** [comment]
Absolutely. PRs always welcome!

**Comment by dooart** [comment]
this integration already exists
