### ISSUE TITLE
Salesforce Lightning isn't working on custom domains

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggl-button#764]
The title pretty much says it all. "Start timer" button works/displays on the official Salesforce Lightning site, but not on custom domains. 

So far the issue has been reported by one user. Unfortunately, I don't have a way of reproducing the reported bug. 

---
Desk case: 426638

**Comment by nicktoggl** [comment]
It's very late here and I might edit these tomorrow if they are unrelated, but also 

case/429902

**Comment by vedr4n** [comment]
Another affected user in case 429866.
