### ISSUE TITLE
Set client from createTimerLink

### ISSUE THREAD

**Issue by avrudokvas** [toggl/toggl-button#765]
Is it possible to set the client from the createTimerLink? In my case I have two clients with same project name. So when createTimerLink executed it set first client with such project.

P.S. I understand that I can rename project in Toggl, but I don't want to :-)

**Comment by syko** [comment]
Hi,

Currently there is no support for that. Which tool are we talking about? If the tool has a similar concept to Toggl's clients then using that info when creating the Time Entry is something that we would consider implementing.
