### ISSUE TITLE
Data sync issues with the Breeze integration

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggl-button#767]
One user reported issues with the Breeze integration. Stopping the timer in Breeze failed to stop the timer in the web app. 

The opposite is also true; stopping the timer in the web app doesn't stop it in Breeze. 

Unfortunately, I don't have a way to reproduce the issue. 

---
Desk case: 429737

**Comment by Mikodzi** [comment]
Yes, indeed. Feels completely broken atm.

Issues I'm having: 
- Stopping the timer in toggl isn't doing that in the breeze and vice
versa: turning off the timer in breeze isn't turning it off in toggl;
- Doesn't fetch the project name automatically (toggl project === breeze
project name);
- Chrome plugin Project selector dropdown is bugged when you you starting
the timer on the card that is really close to the bottom of active view -
https://monosnap.com/file/nkIgRJ1XqT4j0caCJzoUPPXwKStSDh.png

**Comment by Phenome** [comment]
Hi.

This integration positions the Toggl Button to the left of Breeze's start/stop button.
![image](https://cloud.githubusercontent.com/assets/360894/24658879/6eafd0c0-1921-11e7-9ff2-7593d1a08dd5.png)
But there's a CSS rule **on Breeze** that overrides this position and put Toggl Button overlapping Breeze's start/stop button.
![image](https://cloud.githubusercontent.com/assets/360894/24658897/80df7fb6-1921-11e7-9c6a-63b6bc7575ca.png)
So we get this:
![image](https://cloud.githubusercontent.com/assets/360894/24658842/49b83c08-1921-11e7-959c-cf6e059c60db.png)
So you can't press one without also pressing the other.
That's probably fine if you only ever use the interface there. But if you have a running breeze timer, and a stopped Toggl timer, you're outta luck.

* As for automatically starting/stopping Breeze's timer when starting/stopping Toggl's, we don't currently have these hooks on the extension, so you'd have to click each button separately (if you could).
* I tested the 'project name matching' and apparently it's working. Can you please double check this? Remember that it's case sensitive.
* I fixed the dropdown height on this PR: #800 . After review we should be good to go.
