### ISSUE TITLE
Toggl Button Missing in Salesforce

### ISSUE THREAD

**Issue by crashgordon** [toggl/toggl-button#768]
Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

### Environment details

* Operation system: Mac OSX 10.10.5
* Extension version: 1.1.2

### Expected behavior

Should be a red Toggl button next to Salesforce "My tasks"

### Actual behavior

Button not found anywhere. Looks like Salesforce has updated their cloud environment, possibly that's what broke the integration.

### Additional details

* screenshots or screencapture
![screen shot 2017-02-26 at 10 54 36](https://cloud.githubusercontent.com/assets/10116139/23338377/05cac9e2-fc12-11e6-9d64-a7c83ea1befb.png)

**Comment by syko** [comment]
Note: it's possible you can switch between the old and new layout in salesforce's settings somewhere. I know they've done this with desk.
