### ISSUE TITLE
"Start timer" not showing on Remember The Milk

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggl-button#770]
The issue was originally submitted by a person on Twitter
https://twitter.com/DaylightGambler/status/836505957752520704

I ran a few tests with my own Remember The Milk account and can reproduce the problem. The "Start timer" button isn't showing where's it's supposed to. 
![screen shot 2017-02-28 at 10 39 31](https://cloud.githubusercontent.com/assets/19473351/23399890/3ecfefd8-fda2-11e6-897c-a461d226f732.png)

**Comment by lunaticare** [comment]
@vedr4n please vote for the fix to be merged upstream.

**Comment by leafi** [comment]
Fixed in PR #771 by @lunaticare <3

**Comment by leafi** [comment]
Reopening until we deploy master to the app/extension stores/whatever they're called.

**Comment by lunaticare** [comment]
The vendor updated the app, integration is broken again, the fix is ready.

**Comment by fonorobert** [comment]
@leafi do i understand correctly that this is just waiting for deploy to stores?

**Comment by syko** [comment]
I believe this has been fixed by the last PR.
