### ISSUE TITLE
Button missing on Remember The Milk (RTM)

### ISSUE THREAD

**Issue by xtoq** [toggl/toggl-button#774]
### Environment details

* Operation system: Windows 10 Pro
* Extension version: Version (1.1.2)

### Expected behavior

Button should show up on all RTM lists.

### Actual behavior

Button does not show up.

### Steps to reproduce the behavior

* Log into Remember the Milk (https://rememberthemilk.com)

### Additional details

* This started on Thursday, March 3 for me.
* I have tried with only Toggl extension running, same problem.
* I have not tried on a fresh profile.

**Comment by xtoq** [comment]
RTM is also enabled in the extension settings. Have tried disabling/reenabling there as well.

**Comment by leafi** [comment]
Yo - thanks for the detailed report, but issue #770 addressed this.

Fix has been merged to master and will go out with the next deploy of the extension (~few days?)

If you're willing to mess around a bit to get it sooner than that, you can `git clone` this repository, enable Developer mode in `chrome://extensions`, click 'Load unpacked extension', and point that bad boy at the src/ directory inside of the git clone.

Or wait some time. We'll deploy soon, promise :)

**Comment by xtoq** [comment]
Ah, thanks! I searched for open issues, not closed ones. Sweet, I'll do that, cause I can't be without my Toggl for very long. <3 Keep up the great work.
