### ISSUE TITLE
Can't set the "From" field under "Remind me to track"

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggl-button#777]
This is the field I'm referring to
![from-field](https://cloud.githubusercontent.com/assets/19473351/23600968/6f97fe48-0249-11e7-84df-e1562bf7760d.png)

Changes made to that field aren't saved. The "To" field appears to work correctly. 

I can reproduce this problem in both Firefox and Chrome.

**Comment by tcrammond** [comment]
Should be gone 🐛.
