### ISSUE TITLE
Clicking on the X button inside the Reminder notification starts the timer

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggl-button#778]
This issue is specific to Toggl Button for Firefox on Windows. On MacOS, the notification doesn't have an X button. 

When you click on the X (close) icon inside the notification the notification is closed and the timer starts. In other words, the behavior is the same as clicking anywhere else on the notification. 
![x icon](https://cloud.githubusercontent.com/assets/19473351/23602550/69fedeb8-0251-11e7-8bfa-deaa5e716f83.png)

---
Desk case: 430711

**Comment by nicktoggl** [comment]
additionally
 'I have noted
that this also occurs with other pop-ups. The Idle timer pop-up also
automatically discards my time and stops the current timer whether I click
it, dismiss it, or let it time out.'

case/430711

**Comment by zdericnina** [comment]
I've installed Toggl's Firefox extension and noticed a bug: when I am not tracking myself, from times to times the extension reminds me to start tracking. But when I click the X to close the notification, the extension starts the timer. It should not.

Case/448004

**Comment by RobDesideri** [comment]
Another: I also noted that it start also if I click **nothing**! The popup appears and the timer start.
Firefox 52.0.2 (32 bit),
Toggl button version (1.1.1)

**Comment by vedr4n** [comment]
Another user experiencing this Firefox issue. The timer starts even if they do nothing. 

See case 444371.

**Comment by patrickbolle** [comment]
Same experience here on Firefox Dev Edition. Incredibly annoying.

**Comment by khoallaby** [comment]
Firefox v59.0
Windows 10
Also experiencing this, and took a while for me to track down why i had random running timers. 

Even if you ignore the pop up, it will start a timer, which is incredibly annoying. So basically anything involved with this popup will trigger a new timer.

**Comment by oliverseal** [comment]
Firefox 60 64-bit
Win 10

This has screwed up my tracking several times. Extension is still useful, but this "feature" is aggravating.

**Comment by jdmachogg** [comment]
Another with this issue. Firefox 60

**Comment by maritoggl** [comment]
Similar issue reported in conversations/19438242364

**Comment by tcrammond** [comment]
Related to #1116, I'm looking into these now.
