### ISSUE TITLE
Button missing in wunderlist

### ISSUE THREAD

**Issue by syko** [toggl/toggl-button#784]
From a user:

> toggl with wunderlist not working. I just install Sierra on my mac and make all that I need to use this feature, but no "Start" button near ticket... What to do?

### Environment details

* User Agent: 5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.98 Safari/537.36
* Extension version: 1.1.3

**Comment by vedr4n** [comment]
Can't seem to reproduce this on Chrome/Sierra. 

I'm running 1.1.4. Maybe they just need to update the extension. 

Here's what it looks like for me
![screen shot 2017-03-15 at 09 17 39](https://cloud.githubusercontent.com/assets/19473351/23939323/6b81dd74-0960-11e7-9acd-4e6a5149c7b9.png)

**Comment by Phenome** [comment]
Working on 1.1.4.
Went back to tag 1.1.3. **Not working there**. Apparenly just needs to update.
