### ISSUE TITLE
Problems with Toodledoo

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggl-button#786]
Toodledoo implemented some design changes so that's what likely broke the integration. 

How it looked
![pasted image at 2017_03_14 07_39 pm](https://cloud.githubusercontent.com/assets/19473351/23939427/e87ce4fe-0960-11e7-82a2-4e79acb81cfb.png)

How it looks now
![pasted image at 2017_03_14 07_40 pm](https://cloud.githubusercontent.com/assets/19473351/23939437/ecf6ba96-0960-11e7-88a6-7d0c9cc634dd.png)

---
Desk case: 440983

**Comment by fonorobert** [comment]
case 443997

**Comment by Phenome** [comment]
Created an account; tested it.

It seems to be working. With it being a little offset to top, but apparently it's an old "issue".

![image](https://cloud.githubusercontent.com/assets/360894/26221499/20008d72-3bed-11e7-9489-7eaad5829519.png)

Can anyone confirm this is still a bug?

@syko just opened an issue about it ( #820 )... But I can't reproduce.

**Comment by neuraman** [comment]
It's still a bug @Phenome.

You have to switch to the new layout by looking for a exclamation point on the botton left of the screen to activate it. After this the Toggl button disappears.

![exclamation_point](https://cloud.githubusercontent.com/assets/1159876/26505653/fa626a34-421f-11e7-9fbf-41afd3697f2d.png)
![new_layout](https://cloud.githubusercontent.com/assets/1159876/26505654/fa687fbe-421f-11e7-8023-644cb2899738.png)
![switch](https://cloud.githubusercontent.com/assets/1159876/26505655/fa7b55bc-421f-11e7-90c5-8840301e1802.png)

**Comment by Phenome** [comment]
You're right. I got the dialog telling me about the new layout, and so I assumed I was already on it.

Proposed fix on PR #827
