### ISSUE TITLE
Feedly button is throwing a party

### ISSUE THREAD

**Issue by syko** [toggl/toggl-button#790]
### Environment details

* Operation system: macOS Sierra
* Extension version: 1.1.4

### Expected behavior

Not this :point_down:

### Actual behavior

Probably all the buttons for different articles are mistakenly attaching them to the first one.

![image](https://cloud.githubusercontent.com/assets/317674/24046052/d4b63112-0b29-11e7-8e25-1629f7d61bbb.png)

### Steps to reproduce the behavior

Open a feed in "Full Articles" mode

**Comment by Phenome** [comment]
Can't reproduce here. Tried master/local and chrome web store version

OS: Windows 10. Chrome. Extension 1.1.4.

![image](https://cloud.githubusercontent.com/assets/360894/24475910/e16086d8-14a7-11e7-8759-2d55ca8582f7.png)
.

Can you check again @syko ?

**Comment by syko** [comment]
Yes I can still reproduce it. Same version, macOS. I can take a crack at it myself at some point maybe.
