### ISSUE TITLE
Add a "Sign Up" option for Toggl Button extension

### ISSUE THREAD

**Issue by crashgordon** [toggl/toggl-button#792]
Currently new users only have the option to Log in when they install the Button.

The problem is that too many users don't bother with creating an account to start using Toggl. Last week we had 9000 new installs as Toggl became the #1 productivity tool in Chrome store, but this did not reflect in signups growth.

A Signup button could help there.

**Comment by crashgordon** [comment]
Screenshot of current "Log in" pop-up:
![screen shot 2017-04-10 at 13 49 57](https://cloud.githubusercontent.com/assets/10116139/24859103/d3ff1898-1df7-11e7-97b5-07e572064e06.png)

An simple fix to include a "Create account" option:
![toggl button sign up option](https://cloud.githubusercontent.com/assets/10116139/24859121/e587b598-1df7-11e7-8f68-21490450f537.jpg)

I realise this is not the best work of graphic design, but it's better to start simple and I hope this helps.

Current copy has "Create account" instead of "Sign up". I feel the former is a softer way of asking a new user to commit to something, whereas "sign up" sounds like they'll take on obligations.

**Comment by langri-sha** [comment]
There's a gap at the top. What do you think about this; maybe even the button styled in corp red?

![screenshot from 2017-04-10 13-21-30](https://cloud.githubusercontent.com/assets/77084/24859674/dd35390c-1df1-11e7-95ea-691a1f54b807.png)

**Comment by crashgordon** [comment]
Ok yes, that makes more sense!

I would keep it blue and with underline though, just to emphasise that it's a link that leads to account creation (to minimise risk that the user thinks the whole pop up is for creating an account).
