### ISSUE TITLE
Tags dropdown doesn't close easily, consider closing automatically after each tag is selected?

### ISSUE THREAD

**Issue by royfurr** [toggl/toggl-button#801]
Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

### Environment details

* Operation system: Windows 8
* Extension version: 1.1.4

### Expected behavior

Select a tag, tags dropdown closes, no little x button needed unless I choose not to select a tag.

### Actual behavior

Select a tag, tags dropdown stays open until I click x button.

### Steps to reproduce the behavior

Start timer, try adding tag.

### Additional details

* screenshots or screencapture

**Comment by pakamore** [comment]
![screenshot from 2018-08-15 19-00-46](https://user-images.githubusercontent.com/1393898/44158827-672c7f80-a0be-11e8-8801-3382934f590f.png)
![screenshot from 2018-08-15 19-01-34](https://user-images.githubusercontent.com/1393898/44158828-672c7f80-a0be-11e8-832f-5b7ff50f8894.png)

The expanded tag select box hides the button [Done]. This prevents many users from saving this form after selecting a tag. As explained by @royfurr , a user must know how to close this select box to get the submit button back and save the form. For those that know how this works, it is frustrating to make 2 unnecessary mouse clicks hundreds of times per day.

Possible solutions:
1. Avoid expanding tags list over the button [Done]. The select box may always be expanded into 2-3 lines – the same functionality, similar window size, eliminate 2 mouse clicks to open and close this select box.
2. Close the tag select box after selecting a tag. Originally suggested by @royfurr .
3. Save form data automatically after selecting a tag, clicking [Done] is not required.

**Comment by tcrammond** [comment]
The extension has received a revamp in 2019, so we'll close this issue and happily receive further feedback on the new version 🙇
