### ISSUE TITLE
Choosing tag in Todoist covers done button

### ISSUE THREAD

**Issue by Michelle112** [toggl/toggl-button#817]
A user DM'd on FB "when pressing toggle timer button in Todoist.com in Chrome on Mac OS 10.12. When I choose a tag for a task the popup mini window covers the done button."

Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

### Environment details

* Operation system: Mac OSX 10.12
* Extension version: TogglButton/1.1.5-todoist

### Additional details

* screenshots or screencapture 
![todoist](https://cloud.githubusercontent.com/assets/19910107/25494319/e68640be-2b3e-11e7-8a26-f11a5b10e25f.png)

**Comment by Phenome** [comment]
When selecting tags, the popdown stays open while you pick and choose any number of tags.
When you're done selecting, you should press the "x" button to the right, then the tasks popdown should close, revealing previously covered parts of the mini window.
> It's different from the projects popdown: Since you can only ever choose one project, then it auto closes when selecting one.

Tried it on todoist. Apparently seems to be working as expected. Closing the issue for now. If there is still an issue, please add a comment and I'll give it another look.
