### ISSUE TITLE
Broken in bitbucket

### ISSUE THREAD

**Issue by syko** [toggl/toggl-button#822]
Unconfirmed but apparently bitbucket has updated their design.

**Comment by Phenome** [comment]
Tried on the new "Beta" interface. Seems to be working.

Created a timer. Description matched issue description...

![image](https://cloud.githubusercontent.com/assets/360894/26220395/d569aee6-3be8-11e7-81a2-83c046004c21.png)

Should it also show somewhere else?

**Comment by syko** [comment]
Yeah seems to be working for me too. No other reports of this. Closing.
