### ISSUE TITLE
Check new chrome notifications compatibility

### ISSUE THREAD

**Issue by syko** [toggl/toggl-button#824]
Spot if there are any issues with this.

> Starting in Chrome 59, now available in Chrome Beta, notifications sent via 
chrome.notifications will be shown directly by the macOS notification 
system.

There is also supposed to be a migration guide somewhere

**Comment by LulzAugusto** [comment]
Migration guide https://developers.google.com/web/updates/2017/04/native-mac-os-notifications

**Comment by LulzAugusto** [comment]
Notifications are working fine. 👍
