### ISSUE TITLE
Project select box too small in Asana

### ISSUE THREAD

**Issue by vedr4n** [toggl/toggl-button#830]
The area within which you need to scroll and select a project is really tiny on Asana. Here's a GIF
![asana-tb](https://cloud.githubusercontent.com/assets/19473351/26621254/724a9426-45e6-11e7-85dd-0cbf1186ddb4.gif)

Other integrations don't have this problem. For example, here's the project box in Google Cal
![screen shot 2017-05-31 at 09 46 46](https://cloud.githubusercontent.com/assets/19473351/26621266/7d3cd696-45e6-11e7-9141-4675a6b65ec1.png)

---
Case: 477886

**Comment by tcrammond** [comment]
No longer seems to be an issue in the new UI (which we're up to date with now).
