### ISSUE TITLE
Error connecting to the server when clicking on Recent entries

### ISSUE THREAD

**Issue by zdericnina** [toggl/toggl-button#833]
When clicking on the Recent entries in Toggl Button popup, this error shows up.

* Operation system: macOS Sierra
* Extension version: Chrome (Version 58.0.3029.110 (64-bit)) - TogglButton 1.1.6.

### Expected behavior
Since Recent entries isn't clickable, I'd expect not to have any errors showing up when clicking on the field.
### Actual behavior
As soon as the field is clicked, the "Error connecting to the server" shows up.

### Steps to reproduce the behavior
Click on Recent entries in Toggl popup.

Screencast: https://drive.google.com/file/d/0B2woEdzhKYh9M3BPVExfbm9WRkk/view

Case: #470196

**Comment by fonorobert** [comment]
I can confirm this is indeed happening. Clicking the "recent entries" header produces the following error:
![screenshot from 2017-10-13 18-48-38](https://user-images.githubusercontent.com/6963710/31556938-3b7d5804-b047-11e7-9735-267718eefef9.png)
