### ISSUE TITLE
Promodoro not working 

### ISSUE THREAD

**Issue by mohessaid** [toggl/toggl-button#839]
### Environment details
* Operation system:
Edition      Windows 10 Pro (64-bit)
Version     1703
OS Build   15063.413
* Browser:
Name       Chrome
Version     59.0.3071.104 (Official Build) (64-bit)
* Extension version:
1.2.0
### Expected behavior
When I enable promodoro timer, it should start working.
### Actual behavior
When I enable promodoro timer, nothing happen?
### Steps to reproduce the behavior
Install the button and check it out.
### Additional details
The button was working in chrome when I first saw the promodoro feature, then the windows release windows 10 creator (April update) came out, Chrome started behaving weirdly and I switched to canary (my accounts are synchronized, so the extension was installed in canary, but the promodoro wasn't working). Now, after chrome last release I switched back to chrome and this feature still not working.

**Comment by tcrammond** [comment]
Thank you for reporting this, sorry it's been a while. We're quite a few versions ahead on the extension and browsers by now, please re-open the issue if you find it still exists.
