### ISSUE TITLE
Microsoft Team Foundation Server integration

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggl-button#850]
Users reporting that the start timer button won't appear with the new version of Microsoft Team Foundation Server 2017. More info case/502359

**Comment by vedr4n** [comment]
The user is reporting that the button does appear inside TFC on occasion, but displays an error. Open case 502359 to see the error/screenshot.

**Comment by LulzAugusto** [comment]
Can anybody else try to reproduce this problem? I can't even get my TFC account to look like the screenshots within the case. :(

**Comment by nicktoggl** [comment]
/case/694176

**Comment by VeljkoTN** [comment]
Another case, Intercom: 18310786953

**Comment by tcrammond** [comment]
We didn't have any luck finding the correct views and reproducing the problem (as is common with widely configurable tools like this one), closing for now until there's further feedback.
