### ISSUE TITLE
Add Toggl as first-class integration with Basecamp 3

### ISSUE THREAD

**Issue by davedenis** [toggl/toggl-button#859]
There are 10 other time tracking integrations but the best time tracker is missing:
https://basecamp.com/extras

There are some wonky workarounds but Toggl should have a first-class integration with Basecamp 3.

**Comment by rcstr** [comment]
same, BC3 should be a priority since is one of the most used project management tools, integration with version is very poor.

**Comment by tcrammond** [comment]
Basecamp 3 is now supported 🎉
