### ISSUE TITLE
Button is cropped in YouTrack

### ISSUE THREAD

**Issue by fonorobert** [toggl/toggl-button#863]
See screenshot below:

<img width="304" alt="screen shot 2017-08-10 at 15 59 34" src="https://user-images.githubusercontent.com/6963710/29173964-32118bd0-7de5-11e7-9f42-af182f7e8019.png">

**Comment by langri-sha** [comment]
https://github.com/toggl/toggl-button/pull/924 is now merged :confetti_ball:!
