### ISSUE TITLE
No URL permissions list showing and can't add custom url

### ISSUE THREAD

**Issue by Metismo** [toggl/toggl-button#864]
Just tried adding the extension to chrome on Windows 7 professional.
The URL permissions list is blank and on trying to add trello.com as a custom url, clicking the ADD button has no effect.
Extension does not run in trello as a result

**Comment by tcrammond** [comment]
The settings has moved on a long way since this issue was created, so I'll close it now. Please do let us know if there are new problems with it 🙇 .
