### ISSUE TITLE
Toggl button not appearing on GitLab new navigation settings

### ISSUE THREAD

**Issue by kukiron** [toggl/toggl-button#866]
When the new navigation (User Settings > Preference > New Navigation) option is selected from GitLab user settings, the toggl button is no longer visible - both in chrome & firefox (on Windows)

Here's a screen shot with regular settings --

![gitlab regular settings_screen shot](https://user-images.githubusercontent.com/17750543/29253610-70c37710-80a3-11e7-858e-61d110a149f0.jpg)

And here's one with "New Navigation" settings --

![gitlab new settings_screen shot](https://user-images.githubusercontent.com/17750543/29253613-8023fe96-80a3-11e7-8413-b285a12916c5.jpg)

**Comment by syko** [comment]
More reports on this.
Can confirm the button is not appearing.

**Comment by vedr4n** [comment]
I have another user who's reporting the same problem. Desk case 548549.

**Comment by kukiron** [comment]
Well, a [PR](https://github.com/toggl/toggl-button/pull/877) is waiting which fixes this issue. 

Now, up to the maintainers to merge it.
