### ISSUE TITLE
Project selector not showing Workspace Name

### ISSUE THREAD

**Issue by unmultimedio** [toggl/toggl-button#871]
### Environment details

* Operation system: macOS 10.12.6
* Extension version: 1.4.0

### Expected behavior

I click toggl button to start tracking an activity, and I can select a Project from any workspace, with a visual cue about what workspace each project belongs to.

### Actual behavior

I see only the names of 2 of my 3 workspaces. One of the workspaces is missing the title.

| WS OK | WS with errors |
|--|--|
| ![my_personal_tasks_-_report_bug_toggl_desktop_-_asana](https://user-images.githubusercontent.com/4431392/29595662-8ccea1be-877e-11e7-91c8-14fe37dd35e4.gif) | ![my_personal_tasks_-_report_bug_toggl_desktop_-_asana](https://user-images.githubusercontent.com/4431392/29595755-197dd1c0-877f-11e7-9ed6-4fc947ff7e19.gif) |

### Steps to reproduce the behavior

Open a toggl button with 3 workspaces, you may see only 2 workspaces titles and the other one projects' outside any workspace tag

### Additional details

![my_personal_tasks_-_report_bug_toggl_desktop_-_asana](https://user-images.githubusercontent.com/4431392/29597199-ab3f5046-8786-11e7-856b-9d06776ad030.gif)

And the tag missing is:

```
<ul class="ws-list" data-wid="XXXXX" title="Workspace name">
  <li class="ws-row" title="Workspace name">Workspace name</li>
  Here should be the "ul" elements with class "client-list"
</ul>
```

**Comment by tcrammond** [comment]
Thank you for reporting this, sorry it's been a while.

I couldn't reproduce this in the latest version of the extension, but please re-open if you still experience the problem.
