### ISSUE TITLE
Visualsutdio.com VSTS toggl Button disappeared 

### ISSUE THREAD

**Issue by stevan001** [toggl/toggl-button#876]
Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

### Chome Browser Version 60.0.3112.113 (Official Build) (64-bit)

* Operation system: macOS Sierra 
* Extension version:

### Steps to reproduce the behavior
just log into to visualstudio.com VSTS edit a backlog item or task 

### Additional details

* screenshots or screen capture
![screen shot 2017-09-07 at 4 49 28 pm](https://user-images.githubusercontent.com/2120208/30184595-994fd5f0-93ec-11e7-818c-564276e92edd.png)

**Comment by syko** [comment]
Fixed by #875
