### ISSUE TITLE
Chrome showing new timers starting at 12:00:00 am

### ISSUE THREAD

**Issue by ApocalypticFish** [toggl/toggl-button#879]
Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

Chrome using details from a user's OS locale/settings. Both occurrences appear to be on OSX but isn't happening for every user

* Operation system: OSX
* Extension version: 1.5.0

### Expected behavior
The timer should be starting at 00:00:00
### Actual behavior
The timer is starting at 
### Steps to reproduce the behavior
Unable to determine what is causing the issue consistently. Appears to be happening randomly to different users.
### Additional details

* screenshots or screencapture
![image](https://user-images.githubusercontent.com/18132080/30318399-28c4f898-97ec-11e7-9559-9b33e4ed9e73.png)
![image](https://user-images.githubusercontent.com/18132080/30318405-2dd7660e-97ec-11e7-9ef1-4f85acbbd135.png)

case/546968

**Comment by kukiron** [comment]
Can confirm the timer is starting at **12:00:00** AM (Start new option) on Chrome on Windows -

![toggl button chrome timer](https://user-images.githubusercontent.com/17750543/30780539-eaf1bae6-a12e-11e7-8dcd-391e781d1c5e.jpg)


But working as expected on FireFox - 

![toggl button firefox timer](https://user-images.githubusercontent.com/17750543/30780554-4779441e-a12f-11e7-97da-1ccff32e42c2.jpg)

**Comment by cori** [comment]
Can also confirm this still seems to be a problem in version 1.7.0 in chrome/os x, and I heard back from Toggl support via email that this is an acknowledged bug on 2017-09-22.

I note it's not labeled as a bug here; why is that?

**Comment by robrichter** [comment]
Same here. Chrome Version 60.0.3112.90 (Official Build) (64-bit)
OS Ubuntu 17.4

**Comment by steveswinsburg** [comment]
Same issue for me. Happens pretty much all the time in Chrome.

**Comment by fonorobert** [comment]
another user reporting this in 1.8.0 on Chromium on Linux

**Comment by ApocalypticFish** [comment]
Another user reporting this case/598879

**Comment by ricotheque** [comment]
Another user has encountered this as well case/626309

**Comment by maritoggl** [comment]
Another user reporting the same issue, case/636930
