### ISSUE TITLE
Button doesn't show up in GitLab's new design

### ISSUE THREAD

**Issue by fonorobert** [toggl/toggl-button#882]
User reports there was a UI change at GitLab and in the new design TB doesn't show up.

![image](https://user-images.githubusercontent.com/6963710/30429706-c6e7e0ae-9958-11e7-8c00-1d44dbd4538b.png)

case no 549325

**Comment by syko** [comment]
Has already been fixed. Will do a release shortly

**Comment by ezaki** [comment]
Yesterday,  gitlab.com was updated and that design little changed.

So button not appearing again.

![image](https://user-images.githubusercontent.com/13980441/30466747-da256138-9a1a-11e7-8503-f37092ce7e32.png)
