### ISSUE TITLE
Button disappeared from basecamp

### ISSUE THREAD

**Issue by syko** [toggl/toggl-button#887]
User reports button has disappeared from basecamp assignments.
Screenshot:
![image](https://user-images.githubusercontent.com/317674/30592469-88472c4c-9d4f-11e7-9d83-155bb834449c.png)

**Comment by fonorobert** [comment]
Have another report in case 553101

**Comment by ApocalypticFish** [comment]
case/569446

**Comment by LulzAugusto** [comment]
Fixed #941
