### ISSUE TITLE
Start Timer button missing from self-hosted GitLab

### ISSUE THREAD

**Issue by yassam** [toggl/toggl-button#889]
### Environment details

* Operation system: macOS Sierra 10.12.6
* Extension version: 1.7.0

### Expected behavior

I should see a Start Timer button when I view an issue in GitLab

### Actual behavior

The button is missing

### Steps to reproduce the behavior

This occurs on a private repo on a self-hosted GitLab, not on gitlab.com. Obviously I've added the site URL to custom domain permissions

### Additional details

Doesn't matter whether I use old or new navigation

GitLab version: gitlab-ce (9.5.5-ce.0)

<img width="471" alt="screen shot 2017-09-20 at 12 34 23 pm" src="https://user-images.githubusercontent.com/111379/30624383-79200fb6-9e00-11e7-80e1-5a64399f4cfe.png">

**Comment by MikeSorokin** [comment]
@yassam It is a well known issue - #886

**Comment by Symonen** [comment]
Still it is not visible.

**Comment by MikeSorokin** [comment]
@Symonen yes, although #886 was closed by author. Seems like GitLab update is the solution :)

**Comment by Symonen** [comment]
@MikeSorokin Yes that solves problem. Thanks :+1:

**Comment by dooart** [comment]
This was fixed already.
