### ISSUE TITLE
Login fail after password change

### ISSUE THREAD

**Issue by AndreyKravchina** [toggl/toggl-button#891]
After I had changed password firefox button does not let me log in. I receive error "wrong password or email". In same time I successfuly log in via desktop app and website with same password

**Comment by syko** [comment]
Hi,
Is this on chrome or firefox? I see several people having trouble on firefox but I can't reproduce the issue with neither.

**Comment by ohthehugemanatee** [comment]
maybe related to #716 ?

**Comment by tcrammond** [comment]
If anyone finding their way here experiences a similar problem, please see this comment for a possible resolution: https://github.com/toggl/toggl-button/issues/716#issuecomment-351197454.

Closing this issue as probably related to the above comment.
