### ISSUE TITLE
Stop timer automatically at the end of the day does not work

### ISSUE THREAD

**Issue by jankoweb** [toggl/toggl-button#893]
### Environment details
* Operation system: Linux Mint 17.1., Chrome Version 57.0.2987.110 (64-bit)
* Extension version: Toggl Button: Productivity & Time Tracker 1.7.0, Connection ADSL 100Mb/s

### Expected behavior
Stop timer automatically at the end of the day (I set 21:00)

### Actual behavior
It does not stop. Next day - timer duration 26 hours.

Notes: even Stop automatically checked, but does not work too (reported in https://github.com/toggl/toggl-button/issues/662).

**Comment by tcrammond** [comment]
We have made improvements to these areas and don't see any related problems now. If there are still problems in the latest versions of the extension, please feel free to open a new issue.
