### ISSUE TITLE
Add integration with Notion

### ISSUE THREAD

**Issue by brunohq** [toggl/toggl-button#896]
Feature request to add support for tracking time on [Notion](https://www.notion.so/).
Notion is a great Knowledge Base software. I'm starting to use it for documentation in most of my projects. And it's user base is growing rapidly.

**Comment by bartekhejnowicz** [comment]
Agree. Currently Notion is not offering any time tracker integrations:

> **Ashley From Notion <ashlee@makenotion.com>** on **24th May 2018** wrote:
> Hi Bartek! We don't currently integrate with any time tracker apps, but I'll add your vote for it

Toggl may be the first time tracker for Notion! 😉

**Comment by maritoggl** [comment]
Upvoting on behalf of user that reached out via case/723231 :)

**Comment by mkbehbehani** [comment]
+1

**Comment by Stvad** [comment]
@Jinivus any updates on your efforts? :)

**Comment by karlhorky** [comment]
@Stvad I tried out @Jinivus' branch and it didn't appear to be working, so I created a PR of my own (#1203).

**Comment by Stvad** [comment]
@karlhorky Awesome, thanks!

**Comment by tcrammond** [comment]
Which areas of notion would people like to see a timer integration in, specifically? The open PR from @karlhorky adds a button to Task items in database blocks, for example, which is one useful case.

**Comment by karlhorky** [comment]
Oh, did you want something else @tcrammond ? Didn't think about any other use cases.

I had a bug yesterday that was causing the other items to also get Toggl buttons on them, and I "fixed" that bug. But maybe that was what you wanted?

**Comment by lewcart** [comment]
Woo nicely done! Can I suggest switching to the greyscale logo and removing the text? That should work better for both style and dark/light mode switching.
![image](https://user-images.githubusercontent.com/3699424/49562759-a120da80-f968-11e8-9cb8-9106e923ea4e.png)
Other usecases I forsee are just basic todos, something like this (mockup): 
![notiontoggl](https://user-images.githubusercontent.com/3699424/49563371-5a80af80-f96b-11e8-802a-0e1640ad93e6.png)
And then within lists and tables? Not sure the best way to do this to make it discoverable, but I usually don't click into my tasks when I start them. 
![notiontoggl2](https://user-images.githubusercontent.com/3699424/49563419-88fe8a80-f96b-11e8-83c6-419c157a4a52.png)
![notiontoggl3](https://user-images.githubusercontent.com/3699424/49563422-9156c580-f96b-11e8-9eb1-cad12f24c537.png)
The later would mean looking a column called toggl so that it doesn't appear on EVERY table, but yeah just some ideas where i'd find them useful 👍

**Comment by karlhorky** [comment]
> switching to the greyscale logo and removing the text

I would be fine with the first one, but with the second I would like to keep the text (just in the modal view, in the other locations there's not enough space). I'll see what I can do to make the link text inherit the surrounding styles.

I'm new to Notion, so I didn't actually know there was a dark mode. I'll make sure that whatever changes I make work with that.

For lists, I'll base my implementation off of the Basecamp one:

https://github.com/toggl/toggl-button/blob/a5c7b8144098788e0bd99a7cae47baab54597159/src/scripts/content/basecamp.js#L74-L96

For the minimal buttons for the other views, I'll use the `buttonType: 'minimal'` option as in Asana:

https://github.com/toggl/toggl-button/blob/a5c7b8144098788e0bd99a7cae47baab54597159/src/scripts/content/asana.js#L187

I've found the table view, but can't seem to find the Daily Todos view that you have.

I've added these as todos in the pull request. Help welcome :)

**Comment by lewcart** [comment]
You can add multiple views to any table, in the top left next to the title of the table 😃. my daily todos is a "list".
![image](https://user-images.githubusercontent.com/3699424/49616064-3bc9f980-f9fb-11e8-8216-8c3d2a5c975e.png)

**Comment by karlhorky** [comment]
So the first PR for the task modal was merged in #1203. The remaining open tasks mentioned by @lewcart are (help welcome!):

- [ ] [Minimal button](https://github.com/toggl/toggl-button/blob/a5c7b8144098788e0bd99a7cae47baab54597159/src/scripts/content/asana.js#L187) for (unchecked) todos (like [Basecamp](https://github.com/toggl/toggl-button/blob/a5c7b8144098788e0bd99a7cae47baab54597159/src/scripts/content/basecamp.js#L74-L96))
- [ ] [Minimal button](https://github.com/toggl/toggl-button/blob/a5c7b8144098788e0bd99a7cae47baab54597159/src/scripts/content/asana.js#L187) for (incomplete) tasks in list view (like [Basecamp](https://github.com/toggl/toggl-button/blob/a5c7b8144098788e0bd99a7cae47baab54597159/src/scripts/content/basecamp.js#L74-L96))
- [ ] Add column [minimal button](https://github.com/toggl/toggl-button/blob/a5c7b8144098788e0bd99a7cae47baab54597159/src/scripts/content/asana.js#L187) for (incomplete) tasks in table view - how??
- [ ] Use the grayscale logo (may need to change [style.css](https://github.com/toggl/toggl-button/blob/3954ad26fe4ec948cbad9361aa1192afbe3d8ed2/src/styles/style.css) - [maybe difficult?](https://github.com/toggl/toggl-button/pull/1203#pullrequestreview-182349714))

**Comment by xmarkclx** [comment]
I enabed this and doesn't seem to work or add anything to Notion.

**Comment by karlhorky** [comment]
@xmarkclx Did you take a look at the screenshot in #1203? Does this not show up for you? Did you refresh?

**Comment by xmarkclx** [comment]
@karlhorky nope. i even quit(cmd q) and reloaded chrome and reopened notion with a hard refresh.

here's a screenshot.
<img width="385" alt="Screen Shot 2019-06-06 at 6 03 07 PM" src="https://user-images.githubusercontent.com/5523580/59024907-8848a180-8885-11e9-8402-fb884b4b3eab.png">

**Comment by karlhorky** [comment]
Can't remember whether I made it work on the full pages as well - try on a popup task. If you have further comments lets continue in the other closed PR: https://github.com/toggl/toggl-button/pull/1203.

**Comment by xmarkclx** [comment]
<img width="289" alt="Screen Shot 2019-06-06 at 6 58 08 PM" src="https://user-images.githubusercontent.com/5523580/59028008-0fe5de80-888d-11e9-8566-aaba096d948c.png">

Hi @karlhorky, is this a popup task? Because there is no button there as well.

**Comment by karlhorky** [comment]
As mentioned above, I'm continuing the discussion in the PR: #1203
