### ISSUE TITLE
Todoist - toggle-button doesn't input project name automatically

### ISSUE THREAD

**Issue by tadashi-aikawa** [toggl/toggl-button#897]
### Environment details

* Operation system: Microsoft Windows 10 Pro
* Extension version:  1.7.0

### Expected behavior

toggle-button input project name automatically when click button.

### Actual behavior

toggle-button doesn't input project name automatically when click button.

### Steps to reproduce the behavior

1. Move https://todoist.com/app
2. Click toggle-button

### Additional details

I investigated and found that class name had changed from `.pname` to `.project_item__name` on todoist web page.

![image](https://user-images.githubusercontent.com/9500018/31110581-f9f8f37c-a842-11e7-89c3-ead0e6c31cbe.png)

Maybe related code is below.

https://github.com/toggl/toggl-button/blob/e7b1d28d277dcc1bc2822e1347af2a24554209b0/src/scripts/content/todoist.js#L7

**Comment by vedr4n** [comment]
Another Toggl Button user complained about this.

See case 567912 for details.

**Comment by sarabsilveira** [comment]
I have the same issue.

This kind of makes the button not useful.

**Comment by vedr4n** [comment]
Another complaint. See Desk case 575965

**Comment by vedr4n** [comment]
Another user mentioned this problem. See case 580867

**Comment by vedr4n** [comment]
Aaaand another one. Case 584650

**Comment by maritoggl** [comment]
Another user came across the issue case/649981

**Comment by VeljkoTN** [comment]
Another user reporting the issue - case/654935

**Comment by maritoggl** [comment]
case/665225

**Comment by LulzAugusto** [comment]
Fixed by #973. Needs to be deployed, though.
