### ISSUE TITLE
Bitrix24 : Integration broken

### ISSUE THREAD

**Issue by jayvdb** [toggl/toggl-button#899]
Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

### Environment details

* Operation system: Linux / Chrome
* Extension version: 1.7.0

(Also tried on other OS/browser)

### Expected behavior

Starting a timer after loading a task from the task list should start the timer for that task.

### Actual behavior

No timer button appears, and
using the context menu "Start timer" creates a task named "My Tasks"

### Steps to reproduce the behavior

1. Go to tasks, list view
2. open a task, which loads a popup window
3. no timer button appears on the task
4. Right click, select "Start timer"
5. The timer starts with task name "My Tasks".

**Comment by jayvdb** [comment]
I've also tested going to the unique URL for the task, and the timer doesnt appear there either.

**Comment by jayvdb** [comment]
I believe they have changed things so that
- the UI region for the button is now class `task-view-buttonset` , 
- the title is `$('.pagetitle')`

Not changed:
- the optional project is class `task-group-field-label`

**Comment by maritoggl** [comment]
User reported the Russian version of the portal being broken (bitrix24.ru). 

[conversations/19689699578](https://app.intercom.io/a/apps/ayixs927/inbox/inbox/2100822/conversations/19689699578)
