### ISSUE TITLE
Todoist integration little bug

### ISSUE THREAD

**Issue by yrochon** [toggl/toggl-button#90]
When I click the Toggl button while I hover my task name in todoist, all information are transfered to Toggl, and when I say all information, I mean the title but also all tags I put.

**Comment by jeckojim** [comment]
Hi, I got the same bug since 3-4 weeks, uninstall reinstall didn't fix it, the extension is up to date v0.5.7.... Any idea to fix that or why this happens? My config: chrome last version on Mac OS 10.6.8 (SL)

Thank you for the extension, it's nice work.
