### ISSUE TITLE
Start timer button not appearing in Remember the Milk

### ISSUE THREAD

**Issue by seahorsecouncil** [toggl/toggl-button#901]
Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

### Environment details

* Operation system: macOS Sierra 10.12.6
* Extension version: 1.7.0

### Expected behavior

The "Start timer" button is appended to all tasks in Remember the Milk.

### Actual behavior

The "Start timer" button is not appended to all tasks in Remember the Milk. The button only appears on some tasks.

### Steps to reproduce the behavior

1. Create tasks in Remember the Milk.
2. Navigate to any task list.

### Additional details

<img width="1506" alt="image 2017-10-07 at 7 16 48 pm" src="https://user-images.githubusercontent.com/32603958/31312593-21be5fbe-ab95-11e7-8145-15bce808096c.png">

**Comment by xtoq** [comment]
This happens only on the built-in "Today" list for me, but does happen.

**Comment by aviskase** [comment]
Happens to me in different lists/searches, depending on what view was opened first. As far as I can tell it's because `.toggl` class isn't removed on switching.

![image](https://user-images.githubusercontent.com/3819473/34550532-babd4c22-f0df-11e7-86d5-b368e9e82c25.png)

**Comment by langri-sha** [comment]
Fix by @aviskase via #951.
