### ISSUE TITLE
Add integration with Outlook

### ISSUE THREAD

**Issue by grethelvandrik** [toggl/toggl-button#902]
Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

### Environment details

* Operation system:
* Extension version:

### Additional details

* screenshots or screencapture

**Comment by DarwinJS** [comment]
+1  Should support outlook.office.com for Office 365 accounts.

**Comment by DarwinJS** [comment]
Also outlook.live.com is for personal accounts.
Would like to see the tracking button on schedule items and emails.
trackingtime.co already supports this with their button - but I want to stick with toggl!!

**Comment by eyleron** [comment]
+1

**Comment by SamuelStevenson** [comment]
Tracking button on Outlook for Web yet?

**Comment by jthou** [comment]
Same issue (requirement). I'd like to track the real time by toggl for the scheduled tasks which on Outlook.com web.

BTW: It works fine on to-do.microsoft.com

**Comment by nidarasheed** [comment]
This integration already exists but is currently not working. An issue has been created to fix this [here](https://github.com/toggl/toggl-button/issues/1484)
Closing this issue as it is irrelevant given integration exists and just needs a fix :)
