### ISSUE TITLE
Support new Jira redesign

### ISSUE THREAD

**Issue by leonhh** [toggl/toggl-button#905]
### Environment details

* Operation system: Mac OS
* Extension version: 1.7.0

### Expected behavior
Show Toggl button

### Actual behavior
Toggl button isn't displayed anymore

### Steps to reproduce the behavior
Open issue

### Additional details
Due to the removed sidebar in the redsign of Jira the Toggl button isn't displayed anymore. This needs to be shown in the newly added popup when you click on an issue.

![jira](https://image.prntscr.com/image/mZ6GQcwLR8SBnqc5L4DUAw.png "Jira")

See [https://confluence.atlassian.com/jirasoftwarecloud/introducing-your-new-jira-experience-937886012.html](https://confluence.atlassian.com/jirasoftwarecloud/introducing-your-new-jira-experience-937886012.html)

**Comment by gerdriesselmann** [comment]
Second this. The new JIRA has been rolled out to all users in the meanwhile, and since then Toggle is nearly useless for us.

**Comment by Peeja** [comment]
The Toggl button does work on issue pages, so as a workaround you can still open the issue in a new tab and click it there. (But I hope it'll start working on boards again soon.)

**Comment by Peeja** [comment]
@dooart I'm on v1.9.0, but I still don't see the button on the board modal. (I do see the button on the individual issue page, as I did on v1.8.0.)

The fix appears to be looking for a `#ghx-detail-view`. There is a `div#ghx-detail-view` on the page, but it's `display: none`, even when a card's modal is on screen.

![banners and alerts](https://user-images.githubusercontent.com/2407/35108438-93de9594-fc41-11e7-82ab-9903248dfd99.png)

**Comment by dooart** [comment]
okay, i'll investigate

**Comment by iki** [comment]
@dooart confirming @Peeja 's observation with 1.9.0: 
- see it on issue detail page
- see it on backlog issue detail sidebar on right
- do **not** see it on kanban issue detail modal

**Comment by maritoggl** [comment]
Another toggler reported the button being missing on the board, case/637749

**Comment by dooart** [comment]
the integration for the board modal will be available in v1.10.0

**Comment by hhllcks** [comment]
We recently started using jira server on premise. 

It seems that the toggl button does not appear on the Kanban Board view. If I open an issue directly the timer appears.

We are using Jira version 7.6.2.
The sidebar that is mentioned above still exists in our version. There is no popup if I click on an issue.

I am using toggl-button version 1.9.0.

The following screenshot shows two useful positions for the button.

![image](https://user-images.githubusercontent.com/15328082/36151625-4ac7b066-10c8-11e8-81b0-002482f0b10b.png)

**Comment by dooart** [comment]
Hey, @hhllcks! We'll release v1.10.0 soon and it should include a fix for that.

**Comment by gerdriesselmann** [comment]
I'm on 1.10.1 and there's still no JIRA button on the modal dialog.

Judging from the HTML, JIRA has changed all it's class names to some weird shorten nonsense, like "hwwrsQ". Presumably this is done using some CSS preprocessors, so relying on classes may break frequently.

I'm not into it enough, but maybe a selector like [role=dialog] a[target=_blank]:first is more suitable to find the place to add the button next to and [role=dialog] h1:first to extract the title

**Comment by dooart** [comment]
Yeah, it seems to have stopped working again. The generated class names in JIRA's new design have made it hard for us to target DOM elements in a future-proof way, so the integration has become fragile. We'll take a look again soon.

**Comment by iki** [comment]
It worked for some time. Then it started to create multiple toggle buttons on the Jira issue detail modal. Now it doesn't show any again. Please reopen.

**Comment by ThatGuySam** [comment]
Having the same issue with version 1.10.5 in Chrome on macOS

It shows up on the issue page but not in the pop-up style view. 

##Issue page
<img width="1440" alt="screenshot 2018-05-04 11 51 45" src="https://user-images.githubusercontent.com/2830379/39641001-54a801ea-4f92-11e8-9534-c843e9b0e6c9.png">

##Modal/Pop-up view
<img width="1437" alt="screenshot 2018-05-04 11 50 43" src="https://user-images.githubusercontent.com/2830379/39640969-39c930ce-4f92-11e8-896b-b148cc5d7f65.png">
