### ISSUE TITLE
GUI is not intuitive

### ISSUE THREAD

**Issue by reneroth** [toggl/toggl-button#912]
Some small-ish caveats I noticed that prevent the extension from being perfect:

![screenshot 2017-10-19 at 10 31 19](https://user-images.githubusercontent.com/11065422/31761614-d42c37b2-b4b8-11e7-9b63-acf9bf61e8ce.png)

The GUI popping up when clicking on the Toggl button in, for example, Wunderlist:
- the "Stop Timer" button on the top left is not perceived as a button, but as the headline for the modal
- the Toggl logo is part of the "Stop timer" button
- The "Done" button, especially in combination with the not-a-headline button, make it seem like clicking it would stop the tracking

![screenshot 2017-10-19 at 10 32 00](https://user-images.githubusercontent.com/11065422/31761745-47b4683a-b4b9-11e7-92cd-756cfac6aff2.png)

The modal when clicking on the extension button:
- the Toggl logo in the top left acts differently from the one in the previous modal, opening the website. even more confusing because the logo is essentially a power button and I'd expect it to stop the tracking
- the button on the top right seems like it'd open the website, but instead logs the user out without asking for confirmation

I would've put in a pull request to fix these issues, but they require some more extensive adjustments to the design, so I'll rather ask for community/developer feedback.

**Comment by tcrammond** [comment]
The extension has received some large revamps in recent times, so I'll close this issue now. Please feel free to submit your feedback on the new version of the extension 🙇, there's always more to be done.
