### ISSUE TITLE
Feature request: Add Brave browser support

### ISSUE THREAD

**Issue by eightyfive** [toggl/toggl-button#915]
Not a bug, a feature request, not sure I am supposed to post it here, but I didn't find anywhere else to do so.

Can we foresee Toggl button Brave support in a near future?

Brave
https://brave.com/

**Comment by SuperGeekJake** [comment]
https://community.brave.com/t/toggl-button-productivity-time-tracker/7596

Anyone interested in seeing our extension available inside Brave should upvote this thread (it's the heart/like button).

**Comment by eightyfive** [comment]
Ok thanks.

**Comment by gbpoole** [comment]
Where did this end-up?  I'm keen to use Toggl Button in Brave.  I notice that it's not offered through their extension service though.
