### ISSUE TITLE
Injection in new Google Calendar is not supported

### ISSUE THREAD

**Issue by oliveratgithub** [toggl/toggl-button#919]
Google just launched a reworked Calendar under: https://calendar.google.com/calendar/r/week
(could be that this is currently for Google Business users only available).

See also: https://support.google.com/calendar/answer/7541906?hl=en

The Toggl Button injection in the new GCalendar is not yet working.
Hope you can add this asap :) Thanks

**Comment by dr-BEat** [comment]
I would love to see this as well.
The new calendar can already be enabled for normal users.

**Comment by pvdhurk** [comment]
Please release this!

**Comment by oliveratgithub** [comment]
@pvdhurk it is released! I see the Toggl button in the new Google Calendar via the Toggl Google Chrome Extension.

**Comment by pvdhurk** [comment]
Hi Oliver, and thanks for responding!

I see that my toggle extension in chrome is 1.9.0, I also restarted my browser just in case, but to no avail. I'll let the team know here at least that it should be available and hope it is just an issue with my system.

**Comment by Phenome** [comment]
Hi @pvdhurk. This was added in november by PR #923. It's present on our current build `1.9.0`.
I just tried it and it appears to be working properly:
![image](https://user-images.githubusercontent.com/360894/35291518-a48112a2-0054-11e8-8b27-3961dc446196.png)
Have you enabled `calendar.google.com` integration in the options?

**Comment by pvdhurk** [comment]
This is what is setup and happening for me

<img width="451" alt="screen shot 2018-01-24 at 09 57 16" src="https://user-images.githubusercontent.com/9461902/35325934-16ff12e6-00ed-11e8-9278-c49dd20521fd.png">

<img width="402" alt="screen shot 2018-01-24 at 09 57 06" src="https://user-images.githubusercontent.com/9461902/35325932-14d78430-00ed-11e8-91c4-fa580a54401b.png">
<img width="731" alt="screen shot 2018-01-24 at 09 56 31" src="https://user-images.githubusercontent.com/9461902/35325930-1278f14c-00ed-11e8-98c3-25d93e019c9e.png">

**Comment by pvdhurk** [comment]
I fixed it by uninstalling the plugin and reinstalling it. I do not know since what version I had the plugin, but this would suggest that one of the updates did not remove the former cache properly.

I'll leave that with you

**Comment by Phenome** [comment]
Thank you for taking the time to go through what you did. We'll look into it 👍

**Comment by pvdhurk** [comment]
Happy to help :)
