### ISSUE TITLE
Unable to Login to Toggl - Firefox Android

### ISSUE THREAD

**Issue by colinstgeorge** [toggl/toggl-button#922]
### Environment details
* Operation system: Android 7.0
* Extension version: 1.7.0
* Browser(s): 
    - Firefox 56.0
    - Firefox Beta 57.0b13
    - Firefox Nightly 58.0a1
* Device(s): LG v20 & LG GPad x8.0

### Expected behavior
Toggl button to appear (and function) in Taiga (or anything) next to things like in Firefox on ChromeOS.

### Actual behavior
- Firefox 56.0:
    Settings does not render properly, cannot set permissions.
- Firefox Beta 57.0b13:
    Settings renders properly, and can set permissions... But when click 'Toggl Time Tracker' in menu, it opens the login tab for moz-extension://long-uuid-tell-me-if-you-need-it/html/popup.html with a login form (like on 'desktop' browsers)... But when the 'LOG IN' button is clicked, nothing happens... 
- Firefox Nightly 58.0a1:
    Same as Beta

### Steps to reproduce the behavior
Install any Firefox for Android, install toggl-button 1.7.0 add-on, attempt to login (or configure permissions if not on dev version)...

### Additional details
*unsure if Firefox on Android is supported, but it's almost there... I'd love to see this work, just unsure where to try to start hacking if there is an issue to be worked or potential for this to work.

**Comment by ohthehugemanatee** [comment]
Maybe related to #716 ?

**Comment by shantanuraj** [comment]
We've disabled the extension for mobile browsers at the moment.
