### ISSUE TITLE
Suggestion : return timer value in custom field

### ISSUE THREAD

**Issue by GostkaDesign** [toggl/toggl-button#927]
Hello,
i use toggl in taiga.io, and here we can create some custom fields.
When i launch toggl timer from a task (ex : #24 something to do) togll saves my timer and stack it in toggl that's cool ! BUT, it would be very interesting that we can assign a field in settings and toggl put the timer value in our custom field on our service (taiga.io for me).  With the selection between separetly 01:20 | 04:22 | 00:43 or combined 06:25
Do you think its possible? Of course the page shouldn't closed. 

Or simply display total timer under task name or toggl task icon :D

**Comment by tcrammond** [comment]
Hi, it's been a while but thanks for your suggestion. We don't really have plans to implement something like this at the moment, we're trying to keep the extension simple. I'd recommend forking the latest version of the extension to create the custom functionality you need!
