### ISSUE TITLE
Support new Google Calendar layout

### ISSUE THREAD

**Issue by wardweistra** [toggl/toggl-button#938]
Google has introduced a new layout for Google Calendar: https://blog.google/products/g-suite/time-refresh-introducing-new-look-and-features-google-calendar-web/

Please update the button to work on this!
Thanks in advance, love the button.

**Comment by pvdhurk** [comment]
Fixed in #919 (Pull #923)

**Comment by pvdhurk** [comment]
Last release was on 2017-11-14 (22 days ago), release is due?

**Comment by ricotheque** [comment]
Bumping this, as I've received another related case.

**Comment by oliveratgithub** [comment]
Toggl Button version 1.9.0 for Google Chrome supports it!

**Comment by wardweistra** [comment]
Awesome, confirmed. I'll close this now.
