### ISSUE TITLE
The option "Pomodoro time interval in minutes" isn't saving on Firefox.

### ISSUE THREAD

**Issue by iagobozza** [toggl/toggl-button#942]
### Environment details

* Operation system: Ubuntu 17.04 / Firefox Quantum 57.0.1 (64-bit)
* Extension version: 1.8.0

### Expected behavior

The option "Pomodoro time interval in minutes" should save on exit.

### Actual behavior

The option "Pomodoro time interval in minutes" isn't saving on exit.

### Steps to reproduce the behavior

Enter the preference screen, change the time and exit the preferences screen.

### Additional details

[Screencast 2017-12-14 18:40:00.mp4.zip](https://github.com/toggl/toggl-button/files/1561131/Screencast.2017-12-14.18.40.00.mp4.zip)

**Comment by tcrammond** [comment]
This has since been resolved. Please re-open if you experience the problem in the latest version.
