### ISSUE TITLE
toggl-button placement on gitlab.com makes me close issues on extension version 1.8.0

### ISSUE THREAD

**Issue by GabLeRoux** [toggl/toggl-button#944]
Hi,  
On gitlab.com, whenever the Start timer appears, I'm about to edit an issue and bam, I mark it as closed. The button should be aligned to the left.

### Environment details

* Operation system: MacOS
* Extension version: 1.8.0

### Expected behavior

The button should appear without moving buttons

### Actual behavior

When the button appears, buttons from issue bar are moved to the left, faster users may click on the wrong button.

### Steps to reproduce the behavior

Visit an issue you have rights to do actions on at [gitlab.com](gitlab.com) and feel the annoying problem ;)

1. Create a project on gitlab
2. Create an issue
3. Refresh the page of the issue
4. Click on edit, you will probably hit the close button when the button appears
5. Flip a table (╯°□°）╯︵ ┻━┻ and reopen issue

### Additional details

<img width="969" alt="image" src="https://user-images.githubusercontent.com/1264761/34111634-4dc64330-e3d8-11e7-8263-62944bcf6647.png">

Start button should appear at the left of the buttons, not right of them. Maybe something changed recently as I usually edit issues quickly and started to have this behaviour of closing issues by mistake only today.

**Comment by glensc** [comment]
TOTALLY HATE THIS. WAS ABOUT TO REPORT THE SAME.

closed already two merge requests by the buttons jumper!

i suggest to move the toggl button before the "edit", "close", "new issue" buttons

**Comment by glensc** [comment]
until no fix from toggl-button team, workaround is to disable gitlab integration:

![image](https://user-images.githubusercontent.com/199095/34180038-dfb43f0c-e515-11e7-8fe5-01b9d3742c88.png)

**Comment by GabLeRoux** [comment]
This is not even possible in Firefox, I disabled the plugin. @IndrekV would it be possible to get a fix for this or at least a way to remove gitlab permissions in firefox plugin settings?

**Comment by GabLeRoux** [comment]
Thanks @dooart <3

**Comment by dooart** [comment]
we'll release a new version with the fix soon :)
