### ISSUE TITLE
Button missing on Remember the Milk (RTM)

### ISSUE THREAD

**Issue by xtoq** [toggl/toggl-button#946]
### Environment details

* Operation system: Windows 10 Pro
* Extension version: Version (1.8.0)

### Expected behavior

Button should show up on all RTM tasks. (We-ll, most. Built-in Today list always has a problem, see #901 )

### Actual behavior

Button does not show up.

### Steps to reproduce the behavior

* Log into Remember the Milk (https://rememberthemilk.com)

### Additional details

* This started on Tuesday, December 19 for me after an update to the Remember the Milk web app.
* I have tried with only Toggl extension running, same problem.
* I have tried on two other (not fresh) profiles.

**Comment by xtoq** [comment]
I also searched closed issues this time, and didn't see anyone else reporting this or a fix yet. ;)

**Comment by ka4426** [comment]
I have been experiencing this since December 19th as well

**Comment by ricotheque** [comment]
Bumping, as another user has noticed as well: https://twitter.com/DaylightGambler/status/948128576452415488

**Comment by langri-sha** [comment]
Thanks @aviskase, closing this.
