### ISSUE TITLE
Integrate with Assembla

### ISSUE THREAD

**Issue by rodrigomaia17** [toggl/toggl-button#95]

**Comment by IndrekV** [comment]
Added with version 0.7.0 release today. #308

**Comment by zainengineer** [comment]
It no longer works. It looks like assembla html has changed.

**Comment by BrizzleRocker** [comment]
Any updates on this please?

**Comment by IndrekV** [comment]
I will investigate this tomorrow. Thank you for the heads up and sorry for the delay.

**Comment by zainengineer** [comment]
@IndrekV 
It has started working again. So we can close this for now
