### ISSUE TITLE
Bitrix24 support

### ISSUE THREAD

**Issue by nicktoggl** [toggl/toggl-button#950]
User reporting that Bitrix24 for Toggl Button isn't working for them, even when using custom domains.

"Hello! The Chrome toggle button doesn&#39;t work in bitrix24.com
I&#39;ve connected our bitrix24.ru account - ttn.bitrix24.ru, but the button doesn&#39;t appear.
Please check out your connection with tasks in bitrix24.com.
Thanks!"

case/618132

**Comment by VeljkoTN** [comment]
case/690644

**Comment by thirschbuechler** [comment]
adding the domain (eg. https://mycompany.bitrix24.de) to the whitelist doesn't help either

**Comment by bryanph** [comment]
Duplicate of #899
