### ISSUE TITLE
Extension no longer on Chrome Web Store

### ISSUE THREAD

**Issue by deviousgeek** [toggl/toggl-button#957]
### Environment details

* Operation system: Debian Buster, Chrome 63.0 (Stable)
* Extension version: 1.9.0

### Expected behavior
Being able to download the extension from the Chrome Web Store ( via URL https://chrome.google.com/webstore/detail/toggl-button/oejgccbfbmkkpaidnkphaiaecficdnfn )

### Actual behavior
The Chrome Web Store returns a 404 error.

### Steps to reproduce the behavior
Visit https://toggl.github.io/toggl-button/ and click 'Download Extension', or Google 'toggl button' and click on the first result (assuming it's the chrome web store).

### Additional details

Seems like the extension no longer exists on the store? :cry: 

![screenshot 2018-01-15 16 46 49](https://user-images.githubusercontent.com/4342988/34928763-b4af810a-fa13-11e7-8eb4-d285ea8cb451.png)

**Comment by gerdriesselmann** [comment]
I encountered this issue on Friday, 12th January, already, but assumed it was of only temporary nature.

**Comment by psmyda** [comment]
Yes. Google pulled of APPS from Chrome Webstore. Is it possible to get instructions - or even better - package that can be manually installed into Chrome? I'm not very fond of switching to FF.

**Comment by lucallero** [comment]
Same problem here, extension url return 404. Any tips on how to build/pack the extension from source code?

**Comment by adherejames** [comment]
We're also experiencing problems due to this

**Comment by dooart** [comment]
Hey, guys! We've been in contact with Google to bring Toggl Button back to the Chrome Webstore.

Meanwhile, here's how you build it from the source code (ping @lucallero):
1. Clone the toggl-button repo
2. Open this url in Chrome: `chrome://extensions`
3. Enable developer mode:
![image](https://user-images.githubusercontent.com/371426/34955125-34aead86-fa0a-11e7-8dc0-a449d80acaec.png)

4. Click on "Load unpacked extension":
![image](https://user-images.githubusercontent.com/371426/34955104-22ee2e5a-fa0a-11e7-9303-725cd127b533.png)

5. Point it to `toggl-button/src`

**Comment by dooart** [comment]
Hey guys! The extension is back on the Chrome Webstore but it's still one version behind the latest. We'll now try again to get the latest version live, if everything goes well it should be up later today or tomorrow.

Thank you for your patience!

**Comment by deviousgeek** [comment]
Thanks!

**Comment by ihoru** [comment]
Is it happening again?
