### ISSUE TITLE
Button missing on active sprint for new Jira Styles

### ISSUE THREAD

**Issue by charly-palencia** [toggl/toggl-button#958]
Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

### Environment details

* Operation system: Mac Os 10.13.2 
* Extension version: 1.8.0

### Expected behavior
When i go to jira project
And click the `active sprint` sidebar option
And click one of the issue for this sprint
then page should show a modal with the selected issue and the toggl button
 
### Actual behavior
The old markup used for jira was working.but, since the jira application was updated the markup change and now the button only appears when you click the id link and go to the isse detail page.

### Additional details

* screenshots or screencapture
Sprint page
![screen shot 2018-01-15 at 8 36 50 am](https://user-images.githubusercontent.com/645526/34945032-d51600de-f9cf-11e7-9fc6-7c1bebff56bb.png)

Show page 
![screen shot 2018-01-15 at 8 36 58 am](https://user-images.githubusercontent.com/645526/34945039-d98fa3f4-f9cf-11e7-9994-ff3614cff9df.png)

**Comment by dooart** [comment]
Hey there! We fixed this already. The fix will be available in the next release of Toggl Button (1.9.0), which should be released later this week.

**Comment by charly-palencia** [comment]
@dooart  thanks! 🎉

**Comment by cbertozzi** [comment]
@dooart in 1.9.0 version button appears only in the "Backlog" section of the new JIRA but not in the "Active sprints" one.
This issue should not be closed for now

**Comment by dooart** [comment]
You're right, @cbertozzi. But we have a fix for it already and it'll be released in v1.10.0.
