### ISSUE TITLE
Option to disable keyboard shortcuts

### ISSUE THREAD

**Issue by fonorobert** [toggl/toggl-button#966]
From the user in case/637747:

> when working in Google Chrome on macOS, I use the keyboard shortcut cmd + shift + e for a function of a web app in Chrome.
> However, the toggl add-on is "stealing" this shortcut and start/stopping the current timer! How can I avoid that?
> Can I either disable this shortcut for toggl or disable all keyboard shortcuts for toggl in Chrome?

**Comment by LulzAugusto** [comment]
@fonorobert chrome users can manage extensions' shortcuts (including Toggl) at chrome://extensions/shortcuts (this a URL).
