### ISSUE TITLE
Support Google Login for Firefox

### ISSUE THREAD

**Issue by rhelms** [toggl/toggl-button#967]
Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

### Environment details

* Operation system: Ubuntu 17.10
* Extension version: 1.9.0

### Expected behavior

When clicking the Toggl button for the first time, the login screen will have a Login with Google, as is seen for the Chrome extension.

### Actual behavior

There is no Login with Google or Google option. Since I created my Toggl account with a Google login, I have no way of signing in with the Firefox extension.

### Steps to reproduce the behavior

N/A

### Additional details

N/A

**Comment by dooart** [comment]
Duplicates https://github.com/toggl/toggl-button/issues/347
