### ISSUE TITLE
Starting timer using todoist extension, ending with desktop app issue

### ISSUE THREAD

**Issue by johnmatthewtennant** [toggl/toggl-button#968]
### Environment details

* Operation system: OSX
* Extension version: 1.9.0

### Expected behavior
Stopping timer using desktop app should remove "stop timer" button from todoist

### Actual behavior
"Stop timer" button persists in todoist after tracking stopped using desktop app.
Pressing "stop timer" button in todoist overwrites the end time of the entry with the current time.

### Steps to reproduce the behavior
Start a timer using the todoist extension, stop the timer using the desktop app
Note the end time of the entry. 
Notice the todoist "stop timer" button is still present
Wait 60 seconds or more.
Press todoist "stop timer button"
The previous end time for the entry will be overwritten with the current time

### Additional details
In the screenshot, notice the timer is stopped, but the todoist button persists
* screenshots or screencapture
![screen shot 2018-02-02 at 2 52 18 pm](https://user-images.githubusercontent.com/15180577/35752104-b3efe598-0828-11e8-88e0-c5033882c9e4.jpg)

**Comment by dooart** [comment]
duplicated of https://github.com/toggl/toggl-button/issues/300
