### ISSUE TITLE
Request for button integration - Microsoft Planner

### ISSUE THREAD

**Issue by reyo** [toggl/toggl-button#975]
Users requesting a button integration for Microsoft Planner (can probably use a lot of Trello code, maybe)

https://tasks.office.com/

**Comment by clptrsn** [comment]
I have added this integration, and submitted a pull request for it. It has not been merged into the main branch yet, but if you want to take a look at it, here is the pull request. #964

**Comment by reyo** [comment]
Superb! Thanks. How can we **stimulate** them to merge?

**Comment by clptrsn** [comment]
There is one small error in the README for the pull request. I didn't catch it until now. I also commented on the pull request about this. #964

**Comment by maxwellt** [comment]
Any comments on why this issue has been closed and not integrated?

**Comment by shantanuraj** [comment]
This _was_ integrated in #964 

https://github.com/toggl/toggl-button/wiki/Where-can-I-find-the-Button%3F#microsoft-planner

**Comment by maxwellt** [comment]
D'oh, I forgot I had to enable it in the settings which is why I thought this was never integrated. Thanks for the link :-).
