### ISSUE TITLE
Default project randomly changes or is set to "no project"

### ISSUE THREAD

**Issue by jcronk** [toggl/toggl-button#981]
### Environment details

* Operation system: MacOS High Sierra
* Extension version: 1.10.1

### Expected behavior

Default project doesn't change.  When remembering projects by URI, starting a timer from the exact URI uses the previously used project.

### Actual behavior

Default project changes apparently at random, and when reset to its correct value, persists for a few days at most.  Starting a timer from the exact URI when remembering projects by URI results in a random project, the random (incorrect) default project, or the most recently used project (irrespective or URI) being selected.  

### Steps to reproduce the behavior

Use the plugin with a default project set for longer than a week.

**Comment by tcrammond** [comment]
We think this should no longer be a problem in the new version of settings, closing the issue. Please let us know if anything else happens.
