### ISSUE TITLE
Connection failure when Chrome has been on for a long time

### ISSUE THREAD

**Issue by dooart** [toggl/toggl-button#983]
From chrome webstore reviews:

> Retry connecting every once in a while?
>
> Fails to connect the first time when Chrome has been on for a long time (like on for a few days). I have to click off the window and reclick toggl to start a timer every time it fails.

### Environment details

* Operation system: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.140 Safari/537.36
* Extension version: 1.9.0

**Comment by tcrammond** [comment]
Hmm, unconfirmed and there have been some changes to websocket for example in the year since. Might be a case of #805. Closing this one for now.
