### ISSUE TITLE
Idle warning appearing when time is not being tracked

### ISSUE THREAD

**Issue by dooart** [toggl/toggl-button#985]
From Chrome Webstore reviews:

> even when I stop the timer on the website, when I come back to my computer later, the extension will tell me I've been idle for "X" amount of time. When I check the website (and the app on my phone), it shows that the timer is NOT running, but the extension will continue to warn me of idle hours when I'm away. 

### Environment details

* Operation system: 5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.186 Safari/537.36
* Extension version: 1.10.1

**Comment by tcrammond** [comment]
This was re-worked since, closing this one for now.
