### ISSUE TITLE
Visual redesign

### ISSUE THREAD

**Issue by dooart** [toggl/toggl-button#986]
More info will be added to this issue after we discuss this internally.

For now I'll just leave here some recent user feedback about the design:
- Too small details, need to make it bigger, so we can see more details. For example, if you select tag, Done button go down and only half of it visible
- Task/project names are cut off because the popup is so narrow. Please make it wider. The project search is very hard to use because you cannot view more than 2 results at a time. Please make it easier to see more. Everything is way too cramped. Please please please, make it larger!
- Also, the interface looks so bad compared to the iphone app or even desktop dashboard. I just don't get it. It is one day of work to restyle it in CSS.

Related issue (with some interesting feedback): https://github.com/toggl/toggl-button/issues/912

**Comment by tcrammond** [comment]
First revamp is complete, closing this one 🎉.
