### ISSUE TITLE
Button Showing Several Times On Same Page

### ISSUE THREAD

**Issue by VeljkoTN** [toggl/toggl-button#992]
Please follow this guide when creating a new issue. This speeds up the process of replicating the issue and finding a solution.

### Environment details

* Operation system: Windows
* Extension version: 1.10.3

### Actual behavior: 
![image](https://user-images.githubusercontent.com/36152180/37709480-a87369e0-2d0a-11e8-82ae-d3c800ce9622.png)

### Steps to reproduce the behaviour: 
- Browse around in Jida, reopen a task and there will be 3 buttons present, browse some more and re-open the same task and there will be 7 time tracking buttons for the same issue.

CASE #661226

Let me know if you need anything else.

**Comment by charly-palencia** [comment]
I saw the issue.
When you open a jira issue if the issue contains in the description some h1 then it will create a new button for each of h1 into the description.

**Comment by VeljkoTN** [comment]
Another user reported the same issue in Jira (case/675368)

![image](https://user-images.githubusercontent.com/36152180/38617362-1a654158-3d97-11e8-8fd6-f1740a56ed49.png)

**Comment by charly-palencia** [comment]
any updates for this isue?

**Comment by ricotheque** [comment]
Hey guys, following up on this please.

**Comment by VeljkoTN** [comment]
case/691717

new case, anything new we can share here?
